### ISSUE TITLE
localhost:3000 shows 2017 theme

### ISSUE THREAD

**Issue by andrewcodes404** [olefredrik/FoundationPress#1001]
Hi, I have a fresh install of wordpress then cloned the repository and install with npm, gone into the wp-admin using MAMP PRO as a host and changed the theme to FoundationPress. 

ok no style so  I use 'npm install'
When I visit the site from here I get the FoundationPress theme, great

I want to use the browser sync so changed the url in gulpfile.js to 'localhost' and 'npm run watch' but when the localhost:3000 window pops up I get the 2017 theme?

So I trashed the 2017 theme thinking this will force it to show FoundationTheme, but now it's still showing the 2017 theme which is kind of weird

Any ideas?
Thanks
Andrew

Sierra 10.12.5
node v6.10.3
foundation-sites#6.3.1

**Comment by linuxbastard** [comment]
You may have a vhost or another process running on port 3000 which is serving a WP install.

Have you tried changing ports?

**Comment by andrewcodes404** [comment]
where can I change ports in gulpfile.js

**Comment by linuxbastard** [comment]
Around line 103 of `gulpfile.js`

`    // port: PORT`

**Comment by andrewcodes404** [comment]
Ah great thanks, tried that and it changes the port number but still no joy. It's not that it fails to load, it starts trying to load but ends up spinning

**Comment by linuxbastard** [comment]
localhost right? Apache? so when you go to localhost it gives you the default apache info page?

**Comment by andrewcodes404** [comment]
![screen shot 2017-06-13 at 10 10 40](https://user-images.githubusercontent.com/22410771/27075036-b81c4ece-5020-11e7-8177-f18a4fddbf1e.png)
I mean this is working fine and you can see there I've changed the port to 8080. But when I try to view localhost:8080 it doesn't load

**Comment by andrewcodes404** [comment]
_'vhosts files to run an apache server on a specific folder?'_ I haven't done anything like this, just following the instructions in the docs

**Comment by linuxbastard** [comment]
The only thing I can think of is to make sure FoundationPress is installed under the "wp-content/themes" folder of the working WP install. When you go to wp-admin FoundationPress is available under themes, right? and you can activate it? Other than that, I can't see why you're setup is not working

**Comment by andrewcodes404** [comment]
yeah thats all in place but had to change themes using MAMP PRO because obviously I couldn't login in using BrowserSync, thanks anyway

**Comment by linuxbastard** [comment]
You really don't go to WP dashboard using browsersync, that's only supposed to give you a preview of your sites front-end. You login to the wp dashboard of the virtual host you set up using MAMP Pro. You can create any number of virtual hosts in mamp pro, so how did you set up the one that servers your WP?

**Comment by andrewcodes404** [comment]
Just the same as any host in MAMP Pro. Create a new host pointing to the wp directory and create a database with it, open up the host and in the browser finish the installation of wordpress

**Comment by linuxbastard** [comment]
This is what I get when I run
`npm run watch`

```[BS] Proxying: http://themesite.dev
[BS] Access URLs:
--------------------------------------
Local: http://localhost:3000
External: http://192.168.1.100:3000
--------------------------------------
UI: http://localhost:3001
UI External: http://192.168.1.100:3001
--------------------------------------
[BS] Watching files..

I just visit `http://192.168.1.100:3000` and I get my wp install with FoundationPress loaded.
If I want to change my theme or edit content, I visit http://themesite.dev/wp-admin and log in

**Comment by linuxbastard** [comment]
This is my gulpfile.js entry at line 17
```
// Enter URL of your local server here 
// Example: 'http://localwebsite.dev'
var URL = 'http://themesite.dev';`

**Comment by andrewcodes404** [comment]
ok yeah it loads when i use the  http://192.168.1.75:8080 but it still using 2017theme which is not even in the theme directory. The only theme in the theme directory  is FoundationPress


![screen shot 2017-06-13 at 12 35 55](https://user-images.githubusercontent.com/22410771/27080677-e7b5748a-5034-11e7-973f-b0d2921dbf9c.png)

![screen shot 2017-06-13 at 12 36 04](https://user-images.githubusercontent.com/22410771/27080690-f2c59c24-5034-11e7-9543-00bd458a706c.png)

**Comment by linuxbastard** [comment]
ahh, but your vhost is pointing to localhost. if clean2 is the directory, you should have a vhost in MAMP pro pointing to it, and you need to add in a new domain. Right now, localhost is just serving up the default mamp vhost, that's why you're not seeing the changes.

**Comment by andrewcodes404** [comment]
Success. Of course... it's pointing to local host because I told it to, which set up on MAMP PRO is just a fresh install of wp with 2017 theme... So i just change the gulpfile.js to point to 'clean2' . and it works. Got there in the end thanks for your help @linuxbastard.

**Comment by colin-marshall** [comment]
Closing this. Nice help @linuxbastard! (sweet username too!)
