### ISSUE TITLE
fail NPM install because Node-sass repo doesn't exist

### ISSUE THREAD

**Issue by idpokute** [olefredrik/FoundationPress#1002]
**How can this bug be reproduced?**

1. clone FoundationPress repo on your local
2. run : npm install

**What did you expect to happen?**
npm should install the modules and set this theme up.

**What happened instead?**
I think node-sass repo doesn't exist. When I access the provided url, it shows 404 error.
Download failed with following messages;

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-57_binding.node":

**Please List the Following:**
* OS & version: win-7 32bit
* Node version (node -v) [Node v4+ is required] :  node 8
* Foundation version (bower list) : the latest repo. June 17th

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by colin-marshall** [comment]
@idpokute try going into `package.json` and changing `"gulp-sass": "^2.1.0"` to `"gulp-sass": "^3.1.0"`. Then delete your `node_modules` folder and run `npm install` again and tell me if that works.

**Comment by olefredrik** [comment]
I see you're using the bleeding edge version of node (v8) which is not supported by FoundationPress. Node version 4.x - 6.x will work. 

After switching between node versions, it's a good idea to run a ``npm rebuild node-sass``. Anyway, gulp-sass is now updated. https://github.com/olefredrik/FoundationPress/pull/1014 and should be working just fine.
