### ISSUE TITLE
Float used in spite of flex grid

### ISSUE THREAD

**Issue by MarineLB** [olefredrik/FoundationPress#1005]
Hello, 
I am using FoundationPress on a new project. 
I commented `@include foundation-grid;` and decommented `@include foundation-flex-grid;` to use the new flex grid, as I always do.
However, in a single page, article.main-content and .sidebar have the css float property. 
Therefore, the footer is broken and appears in the middle of the page.
By adding float:none; to both of them, the issue is resolved. 
Is this standard behavior ? Because it doesn't seem logical to still use float when we're using flex grid.

Thanks :)

**Comment by dantahoua** [comment]
What I do when using Flex (always for 6 month now) is commenting `@include foundation-grid;` AND `@include foundation-float-classes;`
I uncomment `@include foundation-flex-classes;` AND `@include foundation-flex-grid;`
Never add problem after (maybe with he Offcanvas menu if I recall well, but not sure...)

**Comment by MarineLB** [comment]
Oh wow thank you @dantahoua I had totally missed this foundation-float-classes line in the docs !
