### ISSUE TITLE
Local to Live Pulling all Changes

### ISSUE THREAD

**Issue by lcarlhart** [olefredrik/FoundationPress#1012]
**How can this bug be reproduced?**
Hi, I am having a lot of trouble 1) getting browser-sync to stay up and running while in development and 2) pushing the local theme to our staging server without much of the changes missing.
1. Edit the site on our local computer (after running npm run watch)
2. Browser-sync stops working every so often and we have to rerun it.
3. I run npm run package
4. Upload it to our staging WP
5.  Many of the styles are missing or the latest changes are not reflected.

**What did you expect to happen?**
I expected the site to look the exact same as it does on my local computer.
**What happened instead?**
A partially broken/unstyled site.
**Please List the Following:**
* OS & version: MacOS 10.12.5
* Node version (node -v) [Node v4+ is required] :Node V6.10.2
* Foundation version (bower list) : 7?

Thank you for your help! We are building a woocommerce site for a great client. Hope this can be fixed :|

Thanks again,
Luke

Here is my error log from terminal:
`npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "phpcs"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.9.0 phpcs: `gulp phpcs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.9.0 phpcs script 'gulp phpcs'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp phpcs
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.`

And for the debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'phpcs' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prephpcs', 'phpcs', 'postphpcs' ]
5 info lifecycle foundationpress@2.9.0~prephpcs: foundationpress@2.9.0
6 silly lifecycle foundationpress@2.9.0~prephpcs: no script for prephpcs, continuing
7 info lifecycle foundationpress@2.9.0~phpcs: foundationpress@2.9.0
8 verbose lifecycle foundationpress@2.9.0~phpcs: unsafe-perm in lifecycle true
9 verbose lifecycle foundationpress@2.9.0~phpcs: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/lukecarlhartman/Documents/Sites/foundation/wp-content/themes/FoundationPress/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/DevDesktop/drush
10 verbose lifecycle foundationpress@2.9.0~phpcs: CWD: /Users/lukecarlhartman/Documents/Sites/foundation/wp-content/themes/FoundationPress
11 silly lifecycle foundationpress@2.9.0~phpcs: Args: [ '-c', 'gulp phpcs' ]
12 silly lifecycle foundationpress@2.9.0~phpcs: Returned: code: 1  signal: null
13 info lifecycle foundationpress@2.9.0~phpcs: Failed to exec phpcs script
14 verbose stack Error: foundationpress@2.9.0 phpcs: `gulp phpcs`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid foundationpress@2.9.0
16 verbose cwd /Users/lukecarlhartman/Documents/Sites/foundation/wp-content/themes/FoundationPress
17 error Darwin 16.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "phpcs"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error foundationpress@2.9.0 phpcs: `gulp phpcs`
22 error Exit status 1
23 error Failed at the foundationpress@2.9.0 phpcs script 'gulp phpcs'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the foundationpress package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp phpcs
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs foundationpress
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls foundationpress
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by lcarlhart** [comment]
Update:
When I run <pre>npm run watch</pre> I get this screen:

<img width="1440" alt="screen shot 2017-07-13 at 7 03 30 am" src="https://user-images.githubusercontent.com/5340924/28170222-99bd01f4-6799-11e7-9e70-1752b48dccfa.png">

I saw this [article](http://foundation.zurb.com/forum/posts/43223-npm-run-build-error) on the difference between npm run watch and npm run build. Not sure if that has something to do with the output of my css via sass/scss.

As you can tell, I am a bit confused. Any advice would be super super appreciated.

Thanks,
Luke

**Comment by olefredrik** [comment]
@lcarlhart Do you run a local webserver (e.g MAMP)? Did you put your localhost URL in your [Gulpfile.js](https://github.com/olefredrik/FoundationPress/blob/master/gulpfile.js#L17)?

**Comment by lcarlhart** [comment]
You are correct, it was the localhost URL, I was able to fix it. 

Thank you! 
Love using your starter theme. Thanks for the excellent development :)

**Comment by olefredrik** [comment]
Good stuff 👍  I'm glad you fixed it :)
