### ISSUE TITLE
Page builder to use with FoundationPress

### ISSUE THREAD

**Issue by pablopaul** [olefredrik/FoundationPress#1015]
@olefredrik can you recommend a page builder which works with FoundationPress and outputs Zurb Foundation markup?

**Comment by olefredrik** [comment]
I haven't used any page builders for a while. But I have good experience with [ACF](https://www.advancedcustomfields.com), which works great along with Foundation because you get full control of your markup.

**Comment by pablopaul** [comment]
@olefredrik so basically you frame all contents into ACF fields?

**Comment by olefredrik** [comment]
Yup. I checked out a few page builders a while ago, but all those I tried added a lot of bloat to my markup while not giving me full control of the layout. That said, my experiences around page builders are not up to date with the latest and greatest in the market. Please keep me updated if you find a solution that is better than ACF.

**Comment by pablopaul** [comment]
@olefredrik thanks for the insights. Right now I am running Site Origins Page Builder with customizations for Zurb Foundation markup and experience the same thing as you described

> added a lot of bloat to my markup while not giving me full control of the layout

The "bloat" is tolerable but the full control thing is it.

Will keep you updated.
