### ISSUE TITLE
npm ERR! A complete log of this run can be found in:

### ISSUE THREAD

**Issue by Naveed-anwar123** [olefredrik/FoundationPress#1016]

**Comment by olefredrik** [comment]
Can you please provide a description of your issue? Please use the [issues template](https://github.com/olefredrik/FoundationPress/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by olefredrik** [comment]
Closing this issue due to lack of description. Feel free to provide a description and reopen.

**Comment by krishna5668** [comment]
$ npm start
npm ERR! path D:\codekul\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'D:\codekul\package.json                                                                                                                '
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2017-09-23T12_07_34_6                                                                                                                08Z-debug.log

**Comment by krishna5668** [comment]
How can i solve this issue ??

**Comment by Umartahir93** [comment]
Hey you have made a syntax mistake somewhere in your html css code. Some thing just happened to me I was putting double hash with a color like ##u0008. After removing a hash my problem was solved. Look for a mistake something like your issue will be resolved.

**Comment by Fasih1** [comment]
> @ development E:\xampp\htdocs\inventory_vue
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

The system cannot find the path specified.
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\webpack\bin\webpack.js ENOENT
    at notFoundError (E:\xampp\htdocs\inventory_vue\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (E:\xampp\htdocs\inventory_vue\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (E:\xampp\htdocs\inventory_vue\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fasih\AppData\Roaming\npm-cache\_logs\2018-06-05T07_50_28_732Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fasih\AppData\Roaming\npm-cache\_logs\2018-06-05T07_50_28_764Z-debug.log

**Comment by Fasih1** [comment]
please help me!

**Comment by niranjanreddy891** [comment]
I am facing the same issue when I run `npm start` from terminal. I got this error
```

npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/niranjan/.npm/_logs/2018-08-24T07_36_58_171Z-debug.log
```
I am using Ubuntu-16.04

**Comment by Fasih1** [comment]
https://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start

**Comment by isd94** [comment]
Need help!

npm ERR! path C:\Users\Ibro_Joe_DIABATE\Documents\EDACY\My Courses\Programmation\Angular\Mes TPs\firstProject\NodeJS\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Ibro_Joe_DIABATE\Documents\EDACY\My Courses\Programmation\Angular\Mes TPs\firstProject\NodeJS\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ibro_Joe_DIABATE\AppData\Roaming\npm-cache\_logs\2018-12-05T18_44_53_692Z-debug.log

**Comment by adamdavis99** [comment]
Pls help
I am also finding an npm error after typing npm install saying
"A complete log of this file can be found in" with some memory address completely different from the place I am using this command in cmd. Pls see this

**Comment by JbFragoso** [comment]
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-07T11_38_35_380Z-debug.log
root@fragoso-H61M-S2-B3:/home/fragoso/salao# node --version


Estou com esse problema aqui, alguém pode me ajudar a resolver?

**Comment by charlie77k** [comment]
try this
"scripts": {
  "test": "make test",
  "start": "node index.js"
}

**Comment by gsrikanth007** [comment]
remove a package-lock.json file and run npm install it Will work

//Windows
> del package-lock.json
>npm install

**Comment by Ebrayan** [comment]
I was getting the same error  and   I  got it 
 cause  wasn't positioned in the correct folder.

 make sure   you're positioned in the project folder

**Comment by Love9056** [comment]
> @niranjanreddy891 remove a package-lock.json file and run npm install it Will work
> 
> //Windows
> 
> > del package-lock.json
> > npm install

not work still having same error

**Comment by GrabielDeLaNieve** [comment]
PS C:\Users\Grabiel\Desktop\node\07-restserver> npm i jsonwebtoken --save
npm ERR! Unexpected end of JSON input while parsing near '...onal-changelog":"~1.1'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Grabiel\AppData\Roaming\npm-cache\_logs\2019-05-12T16_11_24_556Z-debug.log
PS C:\Users\Grabiel\Desktop\node\07-restserver>
![Error jsonwebtoken](https://user-images.githubusercontent.com/43450822/57584932-2af04900-74af-11e9-9ba1-481227b40525.PNG)

Hi guys, I have this error and I would like to know why when installing this dependency this error jumps me.

**Comment by omar-bakhsh** [comment]
`
$ npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Amoory.SO\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Amoory.SO\package.json'
npm WARN Amoory.SO No description
npm WARN Amoory.SO No repository field.
npm WARN Amoory.SO No README data
npm WARN Amoory.SO No license field.

audited 1553 packages in 2.12s
found 0 vulnerabilities`

**Comment by mabelcole** [comment]
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mabel.cole\AppData\Roaming\npm-cache\_logs\2019-06-07T19_35_29_33
4Z-debug.log

**Comment by mabelcole** [comment]
plz help

**Comment by Shireensiddiqui** [comment]
> I am facing the same issue when I run `npm start` from terminal. I got this error
> 
> ```
> 
> npm ERR! missing script: start
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/niranjan/.npm/_logs/2018-08-24T07_36_58_171Z-debug.log
> ```
> 
> I am using Ubuntu-16.04



> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\mabel.cole\AppData\Roaming\npm-cache_logs\2019-06-07T19_35_29_33
> 4Z-debug.log

i am also facing same problem!plz provide proper solution if nyone knws

**Comment by Krishna2107** [comment]
am also face same issue am use npm to yarn it,s working now.

**Comment by Chamaxonline** [comment]
I am trying to update **angular2-toaster** from 3.0 to 8.0. it gives following issue when I run 
**npm install angular2-toaster@latest --save**

**Comment by Bansi23** [comment]
follow this command
1.install yarn.
2.npm start

**Comment by basyusuf** [comment]
You should delete this package-lock.json. `sudo rm -rf package-lock.json`
Cant see package-lock.json? Try this `sudo ls -la`.
Next steps;
1-`npm update`
2-`npm install`
3- install your package example: `nodejs node_modules/node-sass/scripts/install.js`
4- rebuild your package example: `npm rebuild node-sass`
