### ISSUE TITLE
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required

### ISSUE THREAD

**Issue by Naveed-anwar123** [olefredrik/FoundationPress#1019]
I am using laravel 5.4 and tried to send  Mails with Mailables and then this error occured.

**Comment by olefredrik** [comment]
Do you consider this to be a FoundationPress issue? It seems to me more likely that this is related to Maravel or Mailables?

**Comment by Naveed-anwar123** [comment]
Thnaks , I am actually new to github so it was my mistake.

**Comment by olefredrik** [comment]
No problem. It's totally okay to open new issues for all things related to the project. But as far as I'm concerned, the response codes you're getting has nothing to do with FoundationPress. Please correct me if I'm wrong.
