### ISSUE TITLE
Smooth Scroll not added.

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1027]
I noticed that the foundation Smooth Scroll plugin wasn't added. Was there a reason for this? Or just that it is easy to do in other ways...

**Comment by linuxbastard** [comment]
It is. Check `src/assets/js/lib/foundation-explicit-pieces.js` line 28.

And to test, create a page with the kitchen sink template and see if the sidebar navigation smooth scrolls to the sections of the page.

**Comment by JPOak** [comment]
@linuxbastard indeed kitchen sink did smoothscroll. What is strange is that before I asked here I did a search on the repo and saw that reference. However, for the life of me I can't find that path in my project. I was thinking that it was in the components section under the plugins. So, strange. It's driving me nuts. Thanks.

**Comment by JPOak** [comment]
Ah, this is a 2.9.2 version project I am working with. I don't think it was referenced the same...

**Comment by linuxbastard** [comment]
If this is clear, can we close this issue? Thanks!

**Comment by JPOak** [comment]
Indeed. And Thank you.
