### ISSUE TITLE
Missing script: watch

### ISSUE THREAD

**Issue by viktoras** [olefredrik/FoundationPress#1028]
I've been having some jQuery issues - that I still haven't resolved - and I did a re-install only to get the "npm missing script: watch" message.

I found an older issue that had been marked closed referencing to package.json and I realize that there is no watch script entry in it anymore. What gives?

Doing a bit of search I see the entry got removed in commit f6cb1d6ece55d86b2321898a1f83b179a7917ad8

**Comment by linuxbastard** [comment]
The new workflow uses the command 'npm start' to run gulp and start watching files for changes. The readme file should have the updated instructions. How exactly did you do the 're-install'?

**Comment by viktoras** [comment]
I see that now in the readme, I was stuck following the original procedure. Thanks!
