### ISSUE TITLE
How to import 3rd party css?

### ISSUE THREAD

**Issue by huytrq** [olefredrik/FoundationPress#1034]
I want to add fancybox (https://github.com/fancyapps/fancybox) in my dist stylesheet. I tried doing this by:

1. `bower install --save fancybox`
2. In the gulfile.js, update the value of PATHS.sass to:
sass: [
  ```
    'assets/components/foundation-sites/scss',
    'assets/components/fontawesome/scss',
    'assets/components/fancybox/dist/jquery.fancybox.min.css'
```
 ],
3. Running `npm run watch`

However, its contents are not included in \assets\stylesheet\app.css.

Could you tell me how I'm meant to import 3rd-party css from the bower components folder into my production code?

**Comment by olefredrik** [comment]
What version of FoundationPress are you on?

**Comment by huytrq** [comment]
I'm using version 2.9.2

**Comment by olefredrik** [comment]
Instead of modifying the gulpfile, you could just include the stylesheet in your [foundation.scss](https://github.com/olefredrik/FoundationPress/blob/v2.9.2/assets/scss/foundation.scss) file.
