### ISSUE TITLE
 Manage packaging

### ISSUE THREAD

**Issue by LGT4** [olefredrik/FoundationPress#1039]
Please include some readme notes on how to manage packaging.

**Comment by olefredrik** [comment]
Please use the issues template so I can know how to respond to this issue.

**Comment by LGT4** [comment]
npm run package 

results in

npm ERR! missing script: package

**Comment by linuxbastard** [comment]
Hi @LGT4,

We need specifics to address your issue. Reply with the following template:



**How can this bug be reproduced?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**

**What happened instead?**

**Please List the Following:**
* OS & version:
* Node version (node -v) [Node v4+ is required] :
* FoundationPress version (see line 3 in package.json):
* Foundation version (see dependencies in package.json) :

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)
