### ISSUE TITLE
Keeping customizer settings when packaging / deploying the theme

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#1044]
Sorry if this isn't unique to FoundationPress, feel free to close. But I'm finding that whenever I package a theme and upload it, most of the customiser settings don't carry through, such as active widgets (sometimes works) Mobile menu always reverts to top menu and any custom customiser settings that I make such as phone numbers/ addresses are lost
**How can this bug be reproduced?**

1. package theme
2. upload zip
3. navigate to customiser

**What did you expect to happen?**
Hoped that all previously configured settings would be retained

**Please List the Following:**
* OS & version: macOS Sierra
* Node version (node -v) [Node v4+ is required] : 8.2.1
* FoundationPress version (see line 3 in package.json): 2.9.2 / 2.10..2
* Foundation version (see dependencies in package.json) : 6.3 / 6.4.2

**Comment by olefredrik** [comment]
Without being 100% sure, I assume you will experience the same thing with other themes too? From my point of view, it's logical that custom settings are stored in the database (on the server) and not in the theme files. Please correct me if I am wrong.

**Comment by nitrokevin** [comment]
I'm sure you are right :) its fine that the settings are stored in the database, but there doesn't seem to be any way (that I know of) to re-apply them, even when the same theme is activated .. I often find myself wondering why the off canvas has stopped working only to realise it has defaulted back to top menu

**Comment by olefredrik** [comment]
If you dump a copy of your localhost database to your remote server, along with your theme files of course, I'm sure you will get both your custom settings, content and design. As I said, I think the way it's working now is by design. But if you experience different behaviour for other themes, I'm willing to look into it.

**Comment by badcat** [comment]
@nitrokevin This happens to me all the time :)  Especially when starting with a base theme and then realizing I forgot to switch to a Child theme version of the Parent. 
Take a look at Customizer Export/Import: 
https://wordpress.org/plugins/customizer-export-import/
