### ISSUE TITLE
npm run command not working after running npm build

### ISSUE THREAD

**Issue by billymo** [olefredrik/FoundationPress#1046]
As the description says, I am not exactly certain what happened. I ran npm run build for the first time, it ran fine. I then attempted to run npm run package and it wouldn't work. I checked all the other npm commands and no luck. 

```
npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "package"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! missing script: package
```
The debug log says: 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'package' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose stack Error: missing script: package
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd /home/bill/vagrant-local/www/webale/htdocs/wp-content/themes/FoundationPress
6 error Linux 4.10.0-32-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "package"
8 error node v6.11.2
9 error npm  v3.10.10
10 error missing script: package
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```
Sorry if I'm missing something obvious. I just thought this was very strange.

**Comment by olefredrik** [comment]
Are you using the latest version of FoundationPress?  As youncan see in the README, the package script is gone.

**Comment by billymo** [comment]
I checked my package.json file and it was identical. The thing that was strange was I already running watch for browser sync. It has been up and running for days. I only backed out of it to run the build command and it worked just fine, but after, nothing worked any more. I will investigate more tomorrow.

**Comment by nitrokevin** [comment]
The build command is still there, but package doesn't exist anymore. Or are you saying the build command has stopped working now?

**Comment by billymo** [comment]
Yes, actually, the build command is still there, however it says both "watch" and "package" are missing scripts. I cloned the repository on the 14th, so it would appear that I have the latest version. I have been developing on it ever since with no issues until this.

**Comment by olefredrik** [comment]
@billymo As I said, the package script has been removed since [FoundationPress v2.10.0](https://github.com/olefredrik/FoundationPress/releases/tag/v2.10.0). 

To run the watch command, type `npm start`. 
To build your assets, type `npm run build`

Please see the [readme](https://github.com/olefredrik/FoundationPress#2-get-started) for more details.
