### ISSUE TITLE
Tracking in git?

### ISSUE THREAD

**Issue by roborracle** [olefredrik/FoundationPress#1047]
My question is really a simple one today, and I'm drawing a blank. I'm doing my development work locally via MAMP, and we've got repository set up for our whole WP project on Bitbucket. Due to the needs we have we usually track everything we have in wp-content including themes, etc. I'm trying to add in my changes on a new project I just started up, but I keep getting a notification that the theme has been modified, but it is untracked, and I can't get it to track. I recall you made some changes that the ultimate output is now in the src file, but i'd like to get a little more info/recommendation from you on how to effectively manage our build within the FoundationPress theme package as you've got it set up now.

**Comment by olefredrik** [comment]
I'm not sure I understand what you're asking. But to me this seems more like a general question around using Git, than an issue with FoundationPress.  I guess you will be able to get help on this at Stackoverflow.

**Comment by roborracle** [comment]
No worries - really more of a question about approach for how you'd recommend managing via git so that I wouldn't need to delete your git files in order to track my own for update/upgrade reasons.
