### ISSUE TITLE
$offcanvas-size is deprecated

### ISSUE THREAD

**Issue by bej-soan** [olefredrik/FoundationPress#1048]
With a fresh install (local) I get the following warnings in the terminal with `npm start`: 

> 
> **WARNING: `$offcanvas-size` is deprecated and not used anymore! Please update your settings and use the map `$offcanvas-sizes` instead**
> Backtrace:
> 	node_modules/foundation-sites/scss/components/_off-canvas.scss:78, in mixin `off-canvas-basics`
> 	node_modules/foundation-sites/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
> 	src/assets/scss/app.scss:33
> 
> **WARNING: `$offcanvas-vertical-size` is deprecated and not used anymore! Please update your settings and use the map `$offcanvas-vertical-sizes` instead**
> Backtrace:
> 	node_modules/foundation-sites/scss/components/_off-canvas.scss:82, in mixin `off-canvas-basics`
> 	node_modules/foundation-sites/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
> 	src/assets/scss/app.scss:33
> 

Is this an old definition in foundationpress or do I have to update something in my node_modules?

**Comment by olefredrik** [comment]
Thanks for reporting in. Seems like there has been a breaking change in Foundation 6.4.2 or 6.4.3 that produces this deprecation warning. I have now made a change in package.json that points directly to version 6.4.1. https://github.com/olefredrik/FoundationPress/pull/1049

If you clone a fresh version of the repo and do a `npm install` and `npm start` now, you shouldn't get any deprecation warnings.

**Comment by navjeetsingh** [comment]
I am using Zeeks Starters theme, Heisenberg with Foundation and I have tried to update foundation, and now i get the following error.

WARNING: $offcanvas-size is deprecated and not used anymore! Please update your settings and use the map $offcanvas-sizes instead
Backtrace:
	node_modules/foundation-sites/scss/components/_off-canvas.scss:78, in mixin `off-canvas-basics`
	node_modules/foundation-sites/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
	assets/sass/vendors/_foundation.scss:29

WARNING: $offcanvas-vertical-size is deprecated and not used anymore! Please update your settings and use the map $offcanvas-vertical-sizes instead
Backtrace:
	node_modules/foundation-sites/scss/components/_off-canvas.scss:82, in mixin `off-canvas-basics`
	node_modules/foundation-sites/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
	assets/sass/vendors/_foundation.scss:29


I have downloaded the latest foundation from github and replaced the only the file which is that folder. Any guidance where i have gone wrong?


Thank you.

**Comment by apsolut** [comment]
Yap. confirming warning: $offcanvas-size is deprecated  (clean download from getting-started and run npm etc...)
