### ISSUE TITLE
What version of FoundationPress  & Foundation am I running?

### ISSUE THREAD

**Issue by hawbsl** [olefredrik/FoundationPress#1050]
Sometimes feels like FoundationPress and Foundation move too fast for me. Every time there's a big jump lots of new things to figure out.

Often it's crucial to figure out what version of FoundationPress and Foundation I am running.

I guess my version of **FP comes from CHANGELOG.md**. I just check the latest version number at the top?

As for Foundation I used to check **foundation.js** where the Foundation version number was easily findable. But I don't think with the latest version of FoundationPress I have the foundation.js file any more. How to be sure which version of Foundation my project is currently on?

**Comment by olefredrik** [comment]
You can find the version numbers for FoundationPress and Foundation a number of places. In addition to checking the latest version number at the top of your changelog, the version number for FoundationPress can also be found here:

https://github.com/olefredrik/FoundationPress/blob/master/style.css#L6
https://github.com/olefredrik/FoundationPress/blob/master/package.json#L4
https://github.com/olefredrik/FoundationPress/blob/master/library/enqueue-scripts.php#L16
https://github.com/olefredrik/FoundationPress/blob/master/library/enqueue-scripts.php#L25

And the version number for Foundation can be found here:
https://github.com/olefredrik/FoundationPress/blob/master/package.json#L27

:-)

**Comment by hawbsl** [comment]
Many thanks!
