### ISSUE TITLE
Console error: Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by aibrean** [olefredrik/FoundationPress#1051]
I have the compiled js file from the latest FoundationPress running and I get Uncaught SyntaxError: Unexpected token import. This is referencing the following line:
`import $ from 'jquery';`

**Comment by olefredrik** [comment]
Did this happen on a fresh install, or after you downgraded the jQuery version (ref https://github.com/olefredrik/FoundationPress/issues/1052)?

**Comment by olefredrik** [comment]
I will assume that this issue is due to issue https://github.com/olefredrik/FoundationPress/issues/1052 . I will therefore close this. Feel free to reopen if you think the problem is not related to the other issue.

**Comment by aibrean** [comment]
This was a fresh install
