### ISSUE TITLE
Issues with running jQuery 3.x

### ISSUE THREAD

**Issue by aibrean** [olefredrik/FoundationPress#1052]
I've noticed the latest FoundationPress uses `3.2.1`. I've been encountering compatibility issues with plugins, specifically Gravity Forms. I downgraded to use a 2.2x version and it works fine. It might be something to take into consideration (as far as compatibility goes) to enqueue a more universally accepted version of jQuery.

**Comment by olefredrik** [comment]
HI @aibrean 

jQuery 3.2.1 is the current version and version 1.x and 2.x does no longer receive patches (which can potentially introduce security issues). In a WordPress context, it is very challenging to support all types of plugins 100%. This is not in scope for FoundationPress, I'm afraid. I've added the jQuery version that Zurb uses for the Foundation, as I consider it important that all the components of the Foundation work as expected. 

Of course, you are free to downgrade jQuery yourself to which version you need, to fix compatibility with third party plugins. But if I were to guarantee compatibility with all possible plugins out there, I could quit my day job to support issues in this project. I have no plans for that :)
