### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by egad1868** [olefredrik/FoundationPress#1055]
[2017-08-27T20_45_26_005Z-debug.docx](https://github.com/olefredrik/FoundationPress/files/1254726/2017-08-27T20_45_26_005Z-debug.docx)

**How can this bug be reproduced?**

1. Step one- Followed instructions on https://foundationpress.olefredrik.com/posts/tutorials/foundationpress-for-beginners
2. Step two - got to npm install
3. Step three got these errors 
C:\Users\amyld>cd C:\vhosts\storks\FoundationPress-master

C:\vhosts\storks\FoundationPress-master>npm install
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated

> node-sass@3.13.1 install C:\vhosts\storks\FoundationPress-master\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\vhosts\storks\FoundationPress-master\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\vhosts\storks\FoundationPress-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:13:12)\n    at F (C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:68:19)\n    at E (C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:80:29)\n    at C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:89:16\n    at C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\isexe\\index.js:42:5\n    at C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\vhosts\storks\FoundationPress-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:13:12)\n    at F (C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:68:19)\n    at E (C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:80:29)\n    at C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\which\\which.js:89:16\n    at C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\isexe\\index.js:42:5\n    at C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\vhosts\storks\FoundationPress-master\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\vhosts\storks\FoundationPress-master\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\vhosts\storks\FoundationPress-master\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\vhosts\\storks\\FoundationPress-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\vhosts\storks\FoundationPress-master\node_modules\node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amyld\AppData\Roaming\npm-cache\_logs\2017-08-27T20_45_26_005Z-debug.log

C:\vhosts\storks\FoundationPress-master>

**What did you expect to happen?**
foundation press to install

**What happened instead?**
got above errors

**Please List the Following:**
* OS & version:  Windows 10 home no version number listed
* Node version (node -v) [Node v4+ is required] : 8.4.0
* FoundationPress version (see line 3 in package.json):2.10.2
* Foundation version (see dependencies in package.json) :6.4.1

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by olefredrik** [comment]
> This project requires Node.js v4.x.x to v6.11.x to be installed on your machine. Please be aware that you might encounter problems with the installation if you are using the most current Node version (bleeding edge) with all the latest features.

See: https://github.com/olefredrik/FoundationPress#requirements
