### ISSUE TITLE
WooCommerce Sidebar issues

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#1057]
**How can this bug be reproduced?**

1. Install WooCommerce
2. Add some products or [dummy data](https://docs.woocommerce.com/document/importing-woocommerce-dummy-data/)
3. Go to main "Shop" or single "Product" page

**What did you expect to happen?**
Siderbar appears to the side

**What happened instead?**
Sidebar appears below all other content. In `woocommerce.php` the sidebar is outside of the `.main-wrap` container. Moving it inside there does not fix the problem. See attached image.

![woocommerce](https://user-images.githubusercontent.com/4453733/29789913-ed6f1de4-8bf4-11e7-8ee7-34ccb8069572.png)

**Comment by colin-marshall** [comment]
@olefredrik here are my suggestions for a solution, what do you think?

1. Wrap WooCommerce loop in `<section class="main-content"></section>` and register a new, WooCommerce specific sidebar to be displayed only on shop pages. Having the regular sidebar on the shop isn't very flexible and in most cases I don't see people using the same widgets in their shop as they do on their blog.
2. Abandon the sidebar altogether for WooCommerce pages.

**Comment by olefredrik** [comment]
@colin-marshall Will solution 1 allow the user to choose whether or not a sidebar should be used in the store? If yes, I think this would be a decent solution. 

Disclaimer: I have limited (close to zero) experience with WooCommerce. Never used this plugin in a real project. I've only installed it and played around with it for an hour or so (over a year ago). 

Which of the solutions will work best in your opinion?

**Comment by colin-marshall** [comment]
@olefredrik there is no option for displaying the sidebar in WooCommerce that I know of, I believe it's strictly theme dependent.

One thing we could do, in addition to solution 1, is add a conditional that checks if there are any widgets present in the WooCommerce sidebar. If there aren't any then it would add the `.full-width` class to `<section class="main-content"></section>`.  If there are widgets present then it would add the sidebar.

This would turn the sidebar off and on automatically when widgets are added/removed, and adjust the grid layout accordingly. 

@linuxbastard @Aetles or anybody else have any thoughts?

**Comment by JPOak** [comment]
I prefer the secondary method that woocommerce suggests, which is more flexible. Delete the woocommerce.php in the root. Then delete the stuff at the bottom of the cleanup.php (I'm not sure why this is there). Then put something like the below in the functions. This will add basic functionality with a sidebar. Let the developer decided whether to remove the sidebar or add a different sidebar via code or a plugin sidebar manager.

remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10);
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10);

add_action('woocommerce_before_main_content', 'fp_theme_wrapper_start', 10);
add_action('woocommerce_after_main_content', 'fp_theme_wrapper_end', 10);

function fp_theme_wrapper_start() {
  echo '<div class="main-wrap" role="main">
			<article class="main-content">';
}

function fp_theme_wrapper_end() {
	?>
	</article>
		<?php get_sidebar(); ?>
	</div>;
	<?php
}

**Comment by JPOak** [comment]
@colin-marshall What are you thoughts on using the below for basic woo support. It's pretty stripped down. The sidebar should position correctly although devs will need to style products for devices. Woo has it's own hooks for putting stuff in front and behind content.

```
<?php
/**
 * Basic WooCommerce support
 *
 * @package FoundationPress
 * @since FoundationPress 1.0.0
 */

get_header(); ?>

	<div class="main-wrap" role="main">
		<article <?php post_class('main-content') ?> id="post-<?php the_ID(); ?>">
			<header>
				<h1 class="entry-title"><?php the_title(); ?></h1>
			</header>
			<div class="entry-content">
				<?php woocommerce_content(); ?>
			</div>
		</article>
	<?php get_sidebar(); ?>
	</div>
<?php get_footer();
```

**Comment by colin-marshall** [comment]
@JPOak I just tested this and the sidebar functionality works good. There are a couple issues I see, which are due to the existing code, not anything you did.

1. There are duplicate `<h1>` elements because the `woocommerce_content()` function already includes the title. See images below. On the main shop page it actually shows the title of the first product in the listing (Flying Ninja) instead of the page title (Shop). If we just get rid of the `<header>` element and the `<h1>` inside of it, everything looks much better. 

![screen shot 2017-09-22 at 9 50 34 pm](https://user-images.githubusercontent.com/4453733/30769951-dd8ddd6a-9fe1-11e7-8cf8-cd530962b2df.png)
![screen shot 2017-09-22 at 9 55 12 pm](https://user-images.githubusercontent.com/4453733/30769952-dd8fc29c-9fe1-11e7-90f5-40798fa57fd3.png)

2. The article element seems semantically correct for a single product page, but on the main shop page listing many products, I think section would be the semantically correct element to use. I'm not sure how to accomplish this if we're using `woocommerce.php` since the [Third party / custom / non-WC theme compatibility](https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/) docs state:
> Note: When creating woocommerce.php in your theme’s folder, you will not be able to override the woocommerce/archive-product.php custom template as woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

So are hooks the only way to accomplish wrapping the shop listing and the single product page in different elements? If so, I should have listened to your advice about using the hooks instead of `woocommerce.php` (sorry!) I didn't realize it would prevent us from doing stuff like this.

**Comment by colin-marshall** [comment]
I just looked at some official WooCommerce themes and it looks like they use the `<main>` element instead of section or article so that makes it easier on us.

There's more duplication happening that I noticed in the classes markup too. I will revisit this tomorrow, it should be a couple easy adjustments and we won't need to switch to hooks like I previously thought if we are using `main` for both shop listing and single product pages.

**Comment by JPOak** [comment]
@colin-marshall Yeah, sorry about the title h1 elements. Woo injects a lot of stuff by itself. I suggest just keeping it to basic integration and leave a note to look at the docs for deeper templating. Woo templating can get pretty complex and I don't think you want to support it.

Although, I wouldn't be against including a woocommerce-integration.php file and putting all that has to do with Woo in there. Much like Underscores does. They also keep the wrapper super simple and leave it to the dev to decide what way they want to go.

**Comment by colin-marshall** [comment]
@JPOak no need to apologize, the h1 duplicates were already in there. Let me know you think this looks:

```php
<?php
/**
 * Basic WooCommerce support
 *
 * @package FoundationPress
 * @since FoundationPress 1.0.0
 */

get_header(); ?>

	<div class="main-wrap">
		<main class="main-content" role="main">
			<?php woocommerce_content(); ?>
		</main>
	<?php get_sidebar(); ?>
	</div>
<?php get_footer();
```

Also, I agree that we should have a WooCommerce file in the `library` directory for all WooCommerce related functions and actions/filters.

**Comment by JPOak** [comment]
@colin-marshall That works well. On a side note, if you go by the same logic for changing out the "article" element for the shop page, which is basically an archive page, wouldn't it then be also wrong for things like blog archives, category archives etc. which is how it is currently implemented in the theme?

**Comment by colin-marshall** [comment]
@JPOak I agree those are also implemented incorrectly if they are using the article element. Underscores and Twenty Seventeen both use the main element, even for single.php.

**Comment by JPOak** [comment]
@colin-marshall I'm no semantic wiz, but I contemplate it a lot! I have actually seen the article element used before on archive pages in other themes. Basically, all woocommerce is is it's own CPT. In my thinking, if you need to change the wrapper for it, then you need to change the wrapper across the theme because it won't be semantic for the standard post type or when devs add their own CPT. So, anyways, when you said that you were going to change the wrapper especially for Woo, It sort of was like a "canary in the coal mine" type of thing.

**Comment by colin-marshall** [comment]
@JPOak the way I understand it is that semantically the article element is fine to use on an archive page as long as it is wrapping each individual post rather than wrapping the entire list of posts. So there should be multiple article elements on any page that lists posts. I'll have to go through the templates in FP and see what all needs modifying.

**Comment by colin-marshall** [comment]
I believe this is completed.
