### ISSUE TITLE
template-specific sass styles

### ISSUE THREAD

**Issue by evangrim** [olefredrik/FoundationPress#1062]
Question:

Kitchen sink styles seem to apply to other pages as well (since they're @import ed in app.scss), and I don't want that. Of course I can just remove the @import lines from app.scss. But supposing I want to retain styles for those templates, do I need to separate css output for kitchen sink & front? If so, how is that best done?

**Comment by colin-marshall** [comment]
If you are talking about the `.grid-x` styles in `_kitchen-sink.scss`, it looks like I messed that up when I updated them the other day and they're applying to `.grid-x` elements anywhere. I will fix that shortly here. Thanks for opening the issue!
