### ISSUE TITLE
Npm start not watching css modifications

### ISSUE THREAD

**Issue by MarineLB** [olefredrik/FoundationPress#1064]
Hi, 
Now that FoundationPress files are compiled via `npm start` instead of `npm run watch`, my `app.css` file is not being compiled automatically, I need to run `npm start` everytime I make a modification.

Is this normal ?

**Comment by olefredrik** [comment]
@MarineLB Sorry I'm not sure if I understand your question? `npm start` does the same as `npm run watch` used to do. When it's running as a background task, your `app.css` should be compiled every time you make a change. The `npm start` command will run as a background task until you kill it manually. What am I misunderstanding here?

**Comment by MarineLB** [comment]
My bad, I was changing files insite node_modules/foundation-sites. 
It does work like `npm run watch` for `app.css` !
