### ISSUE TITLE
Rename & fix path file

### ISSUE THREAD

**Issue by Makar** [olefredrik/FoundationPress#1067]
FoundationPress/library/theme-support.php

line 46
add_editor_style( 'assets/stylesheets/foundation.css' );

**Comment by Eccola** [comment]
@makar, what FP version you are using? There is no /assets/stylesheets/foundation.css anymore in the latest version.

**Comment by Makar** [comment]
now fp compiles css to app.css file
and places it in a folder /dist/assets/stylesheets/

and the code indicates the connection of a file with the old name

line 46
add_editor_style( 'assets/stylesheets/foundation.css' );
fix 
line 46
add_editor_style( 'dist/assets/stylesheets/app.css' );

?

**Comment by Eccola** [comment]
@Makar, now I got it.. You're right. Make a PR!

**Comment by Makar** [comment]
@Eccola that's good
