### ISSUE TITLE
Dropdown Links Not Working - Tablet

### ISSUE THREAD

**Issue by moseke** [olefredrik/FoundationPress#1072]
OS: Mac 10.12.6
Node: 7.9.0
FP: 2.9.0
Site: https://blog.uhaul.com/

We are using the dropdown menu as a subnav which is displayed with icons in the hero. On tablet (landscape) the links are not working. 

Tapping a top level link will open the dropdown, but when you click on one of the category links, the dropdown closes and doesn't change the page.

This is a problem that appeared a bit on Foundation issue boards, however I don't see a way to incorporate the fix. What would you suggest?

**Comment by colin-marshall** [comment]
@moseke what version of Foundation are you using and can you please link to the fix you describe?

**Comment by moseke** [comment]
Not sure what version of Foundation is being used on this. 
[https://github.com/zurb/foundation-sites/issues/9484](https://github.com/zurb/foundation-sites/issues/9484)

**Comment by colin-marshall** [comment]
@moseke I need to know what version of Foundation you are using in your FoundationPress install. Please go into `/assets/components/foundation-sites/bower.json` and tell me what the version # is. Thanks!

**Comment by moseke** [comment]
6.3.0

**Comment by colin-marshall** [comment]
@moseke updating foundation-sites to 6.3.1 appears to fix the issue. Run `bower update foundation-sites` and it should update to 6.3.1, since 6.3.1 is the latest version in the 6.3.x minor release series.

**Comment by giantleif** [comment]
I have updated to the latest version of foundation and am still having this problem. Dropdown menu does not work on ipad.

visitcookcounty.com

**Comment by colin-marshall** [comment]
@giantleif your `foundation.js` file shows you are also on version 6.3.0. Please update to at least version 6.3.1.

**Comment by moseke** [comment]
Thank you @colin-marshall. This update appears to have solved our issue!

**Comment by giantleif** [comment]
@colin-marshall please see our test site:

http://vcc.giantvoices.com/

It should be using version 6.3.1 now but this still seems to be a problem.

**Comment by colin-marshall** [comment]
@giantleif I see that you have updated but I also see that you are not using FoundationPress. You are using JointsWP so you will have to go to that repo for support.
