### ISSUE TITLE
Stop combine admin enqueue JavaScript into one file or add ignore options

### ISSUE THREAD

**Issue by MrAndreius** [olefredrik/FoundationPress#1073]
/gulpfile.babel.js
// Combine JavaScript into one file

The Wordpress can enqueue separate JavaScript files for the administrative panel

action **wp_enqueue_scripts** & action **admin_enqueue_scripts**  ( or customizer enqueue )

If I add such a file to src\assets\js\  folder, then it merges with the app.js
It is not necessary

See example in 
twentyseventeen/functions.php 
twentyseventeen/inc/customizer.php
https://developer.wordpress.org/reference/hooks/admin_enqueue_scripts/

**Comment by colin-marshall** [comment]
@Makar I believe the latest version of FoundationPress combines js using webpack imports in `/src/assets/js/app.js`. It shouldn't be combining every file placed in `/src/assets/js/`, although it did in prior versions. 

You can exclude or include files using the PATHS variable in `config.yml`.

**Comment by colin-marshall** [comment]
@Makar my apologies, I misunderstood what you were saying at first. I thought you were talking about all JavaScript files. I see you mean the admin only js. Feel free to make a pull request regarding this.

**Comment by MrAndreius** [comment]
I placed these files in a separate folder and registered the path to them

![87](https://user-images.githubusercontent.com/1025948/30621387-7d6ce762-9db3-11e7-9ad5-72909644d51a.png)

**Comment by colin-marshall** [comment]
@MrAndreius I just did a test and this is not necessary to use separate folders. You can use the `/src/assets/js/*` folder and it will not automatically combine anything unless you import it in `app.js`.

It does, however, run the gulp tasks for javascript whenever you add or change a file in that directory, so maybe that is why you thought it was combining them. As you know, FP doesn't copy js files without tweaking. We could possibly set up a special `admin` directory inside of `src/assets/js/` and modify the gulpfile to make it easier to add and enqueue admin scripts out of the box.

**Comment by MrAndreius** [comment]
Yes, but!
individual files are not included in the import
this folder is ignored when copying

and the 
.pipe(gulp.**dest**(PATHS.dist + '/assets/css'))
.pipe(gulp.**dest**(PATHS.dist + '/assets/js'));
.pipe(gulp.**dest**(PATHS.dist + '/assets/img'));
 erases the **dist** folder and overwrites it

and it turns out that the files disappear if they are not put as described above

**Comment by JPOak** [comment]
@MrAndreius @colin-marshall I'm not sure this is exactly what you mean, but I can see that there is no way without moving things around to enqueue scripts individually in the "src" folder as that during the build process the distribution folder is overwritten each time. So, I guess you would have to deploy the src folder and enqueue from there....?

**Comment by colin-marshall** [comment]
After looking further into this, the best way to do it is to use Webpack. I'm new to Webpack so I can't give you specific instructions yet, but it basically goes like this:
- Create an additional entry point file (like `src/assets/js/admin.js`)
- Add the new entry point file to the webpack config file so it knows to process it.
- Create your custom admin js as a module, for example `src/assets/js/lib/my-admin-module.js`
- Import the module in the newly created entry point file
- Enqueue the script

Then you should end up with an `app.js` and an `admin.js` in your `dist` folder and you don't need to modify the build system at all.

**Comment by MrAndreius** [comment]
Unfortunately, I know even less about js

**Comment by colin-marshall** [comment]
@MrAndreius I have looked into it now, and it's actually very easy to do:

1. Create new `admin.js` file in `src/assets/js` directory and add your code to it. If you're going to use jquery, make sure to add `import $ from 'jquery';` at the top of the file.
2. In `config.yml` add `src/assets/js/admin.js` to `PATHS.entries`.
3. Enqueue the script in `library/enqueue-scripts.php`.
4. Run `gulp`

That's it. It gets more complicated if you want to break it out into separate modules for different js functionalities where you then import them through the `src/assets/js/admin.js` file, It's not mandatory to do that though, and it doesn't sound like you will be doing anything like that anyway.

**Comment by colin-marshall** [comment]
@MrAndreius I'm closing this issue. If you still have trouble, feel free to reopen it.
