### ISSUE TITLE
How to get the breakpoint variable value from _settings.scss

### ISSUE THREAD

**Issue by anthonyabraira** [olefredrik/FoundationPress#1077]
Pardon but this is not an issue as much as a technical question.

I am trying to incorporate the values of the set breakpoints in the _settings.scss file. Meaning, I would like to get the pixels I have set here:
```
$breakpoints: (
  small: 0,
  small-medium: 600px,
  medium: 960px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
```

Is there a way to use something like `@include breakpoint(small-medium)` but only nab the 600px value?

Again sorry for using this forum for what might be a newbie question. I couldn't find anything in the documentation. If there is a better place for this question, please advise.

**Comment by colin-marshall** [comment]
`map-get($breakpoints, small)`

**Comment by anthonyabraira** [comment]
Thank you so much. That did it.
