### ISSUE TITLE
app.js file in "dist" folder not compiling correctly

### ISSUE THREAD

**Issue by tangmediauk** [olefredrik/FoundationPress#1080]
Hi, I have a problem where my app.js file in my "dist" folder looks the same as the app.js in the "src" folder after the watch or build processes have finished and both processes run without error messages. So i'm not getting the full app.js file with the minified code (or unminified if watching) from the "import" files in my "dist" folder app.js, instead it shows the "import $ from 'jquery';" lines of code which should be replaced by the actual code.

I'm using all of the latest versions of FoundationPress, node and webpack so:

Windows 10
Foundationpress 2.10.3
node 6.11.3
webpack version 2.7.0

I've attached the "built" version of my app.js file (as a TXT file) from the "dist" folder for reference here:
[app.js.txt](https://github.com/olefredrik/FoundationPress/files/1310622/app.js.txt)

Any ideas as to why this might be happening?

Thanks

Ben

**Comment by colin-marshall** [comment]
@tangmediauk have you tried this on a completely fresh clone and npm install of the repo and you get the same result?

**Comment by tangmediauk** [comment]
Hi, yes i tried a fresh build this morning with the same result. Previous builds have been fine as well.

Let me know if you need any more info.

Thanks

Ben

**Comment by colin-marshall** [comment]
@tangmediauk thanks for the further info. Can you please copy/paste the entire console output, not just the javascript part? What you put looks normal to me. I also get 406kb and 0 chunks when I run it. It appears the js is getting built but the file it outputs is incorrect for some reason.

One thing you could try is to switch to a fresh install of a different node version and see if you get the same result. I would recommend installing [nvm-windows](https://github.com/creationix/nvm) which allows you to have multiple versions of node installed that you can easily switch between.

**Comment by tangmediauk** [comment]
Hi, apologies for the radio silence. I'm working on this project in my spare time. I've attached the full output (i've redacted the path to the gulp babel file but it's looking in the correct place):

[npm-output.txt](https://github.com/olefredrik/FoundationPress/files/1346295/npm-output.txt)

I already use nvm windows to switch between the following versions and i've tried all three:

* 6.11.3 (Currently using 64-bit executable)
    6.9.2
    0.10.33

Thanks for your help.

Best regards

Ben

**Comment by colin-marshall** [comment]
@tangmediauk please run `npm ls -g --depth 0` and paste us the output here. I am curious to see what global packages are installed. Also, do a fresh clone of the repo and instead of running `npm install` run `npm install 2>&1 | tee log.txt` and provide the log.txt file it creates.

I really don't have much more to suggest besides trying more versions. Definitely don't go below version 4. I would say try the following versions:
- 8.4.0
- 7.10.1 
- 5.12.0
- 4.8.4

**Comment by tangmediauk** [comment]
I don't usually install anything globally as i've built up different versions of foundation over the years so i guess that the output of `npm ls -g --depth 0` reflects that:

C:\Users\Ben\AppData\Roaming\npm
`-- (empty)

I'll go through the other versions and do some digging on dependencies in case i'm missing a correct version of a module or something.

Thanks

Ben

**Comment by colin-marshall** [comment]
@tangmediauk you may need gulp installed globally. Next time you switch to a new version of Node do the following:
- run `npm install gulp-cli -g`
- clone FoundationPress
- enter FoundationPress directory
- run `npm install 2>&1 | tee log.txt`

Then please provide the log.txt file it creates.

**Comment by tangmediauk** [comment]
Ok thanks for the advice, i'll update this thread if i find a solution.

Best regards

Ben

**Comment by colin-marshall** [comment]
@tangmediauk even if you don't find a solution, please provide the log.txt because I may be able to find something that went awry during npm install. Thanks!

**Comment by derweili** [comment]
I think this can be closed since the last activity was in 2017
