### ISSUE TITLE
Remove woocommerce hooks in cleanup.php..

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1082]
With the way Woocommerce is currently used in the FoundationPress (woocommerce.php in the root), I don't think the hooks are needed in the cleanup.php . 

I think it creates confusion when someone decides to use the more flexible hook method to integrate woocommerce it creates an error being there. In fact, technically with the way you currently have woo implemented you dont need to declare add_theme_support( 'woocommerce' ); .

Thoughts on removing this?

**Comment by colin-marshall** [comment]
@JPOak weren't you suggesting in #1057 to keep the hooks and drop `woocommerce.php`?

**Comment by JPOak** [comment]
@colin-marshall Yes. But it is really one or the other. I prefer using the hooks, but if you want to go the woocommerce.php way in my opinion we should remove what is there in cleanup as it is not needed. If you want to go the woocommerce.php way I think that could just be changed around a bit to make the sidebar work as default and let the dev decide how they want to implement the sidebar or not.

**Comment by colin-marshall** [comment]
@JPOak thanks for clarifying. I personally would prefer to keep `woocommerce.php` because I'm not a big fan of writing markup inside of php functions, but that's just me.

**Comment by JPOak** [comment]
@colin-marshall Ok. No worries. I still am not sure why there is the woocommerce reference in the cleanup, but as long as I know it is there I can remove as needed. I'll close this.

**Comment by colin-marshall** [comment]
@JPOak sorry for not being clearer in my response. I am in favor of removing the unnecessary WooCommerce hooks in `cleanup.php`, and keeping `woocommerce.php`.

**Comment by JPOak** [comment]
@colin-marshall ok. will send pull request.

**Comment by colin-marshall** [comment]
@JPOak thanks for the PR! So we can also remove the `add_theme_support` for WooCommerce if we're using `woocommerce.php`, correct?

**Comment by JPOak** [comment]
@colin-marshall - yeah. I'll do a pr for that as well. What did you think of the refactored woocommerce.php here #1057 .
