### ISSUE TITLE
Update configuration process

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#1083]
@olefredrik and others, I have found it to be a pain that entering in the proxy URL for browsersync shows up in git as changes, so I have to remember to remove it whenever I make changes to the gulpfile to push upstream. I noticed you have had to undo some commits for the same reason in your PR's.

I propose the following:
- Add `config-default.yml` file to the repo (just a duplicate of `config.yml`)
- Add `config.yml` to `.gitignore` and remove it from tracking in repo
- In the gulpfile, if `config.yml` exists, load the configuration from `config.yml`. If `config.yml` does not exist, load configuration from `config-default.yml`.
- Move the browsersync proxy URL from the gulpfile to the config file.

This way users can create their own `config.yml` file by copying `config-default.yml` and have the theme configured differently for different environments and not deal with git headaches (like the proxy URL change showing up in git).

What do you guys think?

**Comment by olefredrik** [comment]
Good stuff, @colin-marshall ! Let's to this 👍
