### ISSUE TITLE
Pagination showing same content

### ISSUE THREAD

**Issue by kayzoe** [olefredrik/FoundationPress#1087]
**How can this bug be reproduced?**
When on the archive page, 
1. When on the archive page, click on the "2" for next page after the initial 10 posts
2. Same 10 posts appear again

**What did you expect to happen?**
It should click through to the next 10 posts

**What happened instead?**
The same 10 posts appeared

**Please List the Following:**
* OS & version: OS X Version 10.11.6
* Node version (node -v) [Node v4+ is required] : 7.10.0
* FoundationPress version (see line 3 in package.json):  2.9.3
* Foundation version (see dependencies in package.json) : 2.9.3

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by colin-marshall** [comment]
@kayzoe since you closed this, is it safe to assume there is no bug here?

**Comment by kayzoe** [comment]
@colin-marshall That's correct. Thank you for the follow up.
