### ISSUE TITLE
Npm start error 

### ISSUE THREAD

**Issue by icaromelog** [olefredrik/FoundationPress#1089]
I am having this **error** when I try to run npm start

```
$ npm start

> foundationpress@2.10.3 start C:\wamp64\www\******\wp-content\themes\*****
> gulp

[00:29:59] Requiring external module babel-register
[00:30:00] Loading config file...
[00:30:00] config.yml exists, loading config.yml
[00:30:00] Using gulpfile C:\wamp64\www\unium\wp-content\themes\uniumfinal\gulpfile.babel.js
[00:30:00] Starting 'default'...
[00:30:00] Starting 'build'...
[00:30:00] Starting 'clean'...
[00:30:00] 'clean' errored after 104 ms
[00:30:00] Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\unium\wp-content\themes\uniumfinal\dist'
    at Error (native)
[00:30:00] 'build' errored after 105 ms
[00:30:00] 'default' errored after 106 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundationpress@2.10.3 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundationpress@2.10.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pichau\AppData\Roaming\npm-cache\_logs\2017-09-24T03_30_00_162Z-debug.log
```

I did the installation correctly and I activated browsersync, and for some reason after some time this error started to appear, I downgraded from node js version, from v6.11.3 to v4 .8.4. How can I proceed? Thanks!

Here's my log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Pichau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v4.8.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundationpress@2.10.3~prestart: foundationpress@2.10.3
6 info lifecycle foundationpress@2.10.3~start: foundationpress@2.10.3
7 verbose lifecycle foundationpress@2.10.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle foundationpress@2.10.3~start: PATH: C:\Users\Pichau\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\wamp64\www\unium\wp-content\themes\uniumfinal\node_modules\.bin;C:\Users\Pichau\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Pichau\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Ruby24-x64\bin;C:\Users\Pichau\AppData\Local\Microsoft\WindowsApps;C:\Users\Pichau\AppData\Local\atom\bin;C:\Users\Pichau\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle foundationpress@2.10.3~start: CWD: C:\wamp64\www\unium\wp-content\themes\uniumfinal
10 silly lifecycle foundationpress@2.10.3~start: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle foundationpress@2.10.3~start: Returned: code: 1  signal: null
12 info lifecycle foundationpress@2.10.3~start: Failed to exec start script
13 verbose stack Error: foundationpress@2.10.3 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Pichau\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at EventEmitter.emit (events.js:172:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Pichau\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:862:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
14 verbose pkgid foundationpress@2.10.3
15 verbose cwd C:\wamp64\www\unium\wp-content\themes\uniumfinal
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pichau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v4.8.4
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error foundationpress@2.10.3 start: `gulp`
22 error Exit status 1
23 error Failed at the foundationpress@2.10.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by colin-marshall** [comment]
It's a permissions issue. I don't use Windows so I can't help you much. Are you running as administrator?

**Comment by icaromelog** [comment]
Maybe is that, i will try running as admin, thanks you! =)
