### ISSUE TITLE
Semantically incorrect use of article elements

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#1091]
I have noticed a lot of use of the article element as a wrapper in FoundationPress. Here are some examples where I believe it used incorrectly:

https://github.com/olefredrik/FoundationPress/blob/master/archive.php#L21
https://github.com/olefredrik/FoundationPress/blob/master/woocommerce.php#L17
https://github.com/olefredrik/FoundationPress/blob/master/search.php#L15

The `<main>` element seems more semantically appropriate to me in these instances.

**Comment by JPOak** [comment]
@colin-marshall  I would add the index.php to this as well possibly.
