### ISSUE TITLE
Error While npm install -g gulp

### ISSUE THREAD

**Issue by bkovuru** [olefredrik/FoundationPress#1092]
C:\Users\bkovuru080717\Downloads\sgwt-app>npm install -g gulp
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect
npm ERR! Error: connect ECONNREFUSED 176.6.35.40:80
npm ERR!     at Object.exports._errnoException (util.js:1018:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1041:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
npm ERR!  { Error: connect ECONNREFUSED 176.6.35.40:80
npm ERR!     at Object.exports._errnoException (util.js:1018:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1041:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '176.6.35.40',
npm ERR!   port: 80 }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

**Comment by colin-marshall** [comment]
Please see here:

https://stackoverflow.com/questions/42371380/npm-err-error-connect-econnrefused

**Comment by colin-marshall** [comment]
@bkovuru I'm going to close this as this is not an issue with FoundationPress. If you feel I've done so in error or you need more help, feel free to reopen.
