### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by evangrim** [olefredrik/FoundationPress#1093]
Unsure whether this is an FP error or environmental. But I've tried every fix I can find or think of, and any help would be appreciated.

**How can this bug be reproduced?**

1. Working install
2. Restart computer
3. Run NPM start and see error

**What happened instead?**

C:\xampplite\htdocs\mysite.dev\wp-content\themes\FoundationPress>npm start

> foundationpress@2.10.3 start C:\xampplite\htdocs\mysite.dev\wp-content\themes\FoundationPress
> gulp

[13:34:57] Requiring external module babel-register
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'C:\Users\Evan\.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1348:33)
    at save (C:\xampplite\htdocs\mysite.dev\wp-content\themes\FoundationPress\node_modules\babel-register\lib\cache.js:48:16)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.10.3 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundationpress@2.10.3 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampplite\htdocs\mysite.dev\wp-content\themes\FoundationPress\npm-debug.log

C:\xampplite\htdocs\mysite.dev\wp-content\themes\FoundationPress>node -v
v6.11.3

**Please List the Following:**
* Windows 10 Pro 15603.608
* Node 6.11.3
* FoundationPress 2.10.3
    foundation-sites: "6.4.1"
* DesktopServer (rather than xampp)

**Comment by colin-marshall** [comment]
Sounds like this problem arises from your user folder being read-only or if the file is marked hidden. See:
https://github.com/facebook/react-native/issues/8678

**Comment by evangrim** [comment]
.babel.json was in fact hidden. Thank you.
