### ISSUE TITLE
Content in Single.php

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#1094]
Underscores and other themes control the content for both single pages and archive pages in `template-parts/content.php` using conditionals (like if `is_single()`). 

In my opinion we should move the content out of single.php so we have one file controlling the content in both situations.

**Comment by JPOak** [comment]
@colin-marshall I'm looking at trying to help out with a few things (cleanup etc). Should I just do a PR and you guys can review and reject as you see fit.

**Comment by colin-marshall** [comment]
@JPOak That would be great! Just make sure to separate the PR's out by bugfix or whatever topic they cover. Thanks!
