### ISSUE TITLE
check-if-sidebar-exist.php  Is this used anymore?

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1103]
check-if-sidebar-exist.php  

Is this used anymore?

**Comment by colin-marshall** [comment]
I don't see it being used anywhere. It uses the stock Foundation grid classes which haven't been used in FP for awhile. Currently we have the page templates for left/right sidebar and full-width and I think the idea is to let the developer use those instead of conditionally adding the sidebar.
