### ISSUE TITLE
Old "NPM run build" method.....

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1107]
I'm wondering if anyone else misses the old "npm run build" script. The are various scenarios that I actually like using it. The most basic is for right after the initial clone. Now, I use start, and then I need to escape the browser sync. There are also other times I would use the unminified files and sourcemaps when iterating with a client.

I know it is a little thing, but I think it would be easy to add back into package.json . I guess if I am the only one, I can just add it in manually on my own when I start a new project.

**Comment by colin-marshall** [comment]
Is there an issue that discusses the removal? For now you should be able to run `gulp build` which is the same thing.

**Comment by JPOak** [comment]
@colin-marshall Actually simply typing gulp build doesnt work. Before the big update it did, but now there are errors I think related to how we do the paths now.

Anyways, i'm going to close this. I think I will push my branch that has automatic static asset revisioning via hashing for cache busting to see what you guys think. This would include a new npm run dev  .
