### ISSUE TITLE
What's the better way to update?

### ISSUE THREAD

**Issue by ymgomes** [olefredrik/FoundationPress#111]
How can I update FoundationPress to get new functionality without break my site? What folders should I upgrade?

**Comment by ChrisAynesworth** [comment]
How do I update from say, Foundation 6.1.2 to Foundation 6.2? Typing in 'foundation update' just shows lines of bower cached and bower validate items:

bower cached        git://github.com/zurb/foundation-sites.git#6.1.2
bower validate      6.1.2 against git://github.com/zurb/foundation-sites.git#~6.1.0
bower cached        git://github.com/FortAwesome/Font-Awesome.git#4.4.0
bower validate      4.4.0 against git://github.com/FortAwesome/Font-Awesome.git#~4.4.0
bower cached        git://github.com/zurb/motion-ui.git#1.1.1
bower validate      1.1.1 against git://github.com/zurb/motion-ui.git#~1.1.0
bower cached        git://github.com/kenwheeler/slick.git#1.5.9
bower validate      1.5.9 against git://github.com/kenwheeler/slick.git#~1.5.9
bower cached        git://github.com/jquery/jquery-dist.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery-dist.git#~2.1.4
bower cached        git://github.com/jquery/jquery-dist.git#2.2.1
bower validate      2.2.1 against git://github.com/jquery/jquery-dist.git#>=1.7
bower cached        git://github.com/ten1seven/what-input.git#1.1.4
bower validate      1.1.4 against git://github.com/ten1seven/what-input.git#~1.1.2

I'm running FoundationPress 2.3

**Comment by olefredrik** [comment]
Hi @ChrisAynesworth , 

We have an open [pull request](https://github.com/olefredrik/FoundationPress/pull/740) for the latest Foundation update. Just need to fix a few issues before it's merged into the master branch. If you plan on upgrading yourself, you should follow this [upgrade guide](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2).

Cheers,
Ole Fredrik

**Comment by ChrisAynesworth** [comment]
Thanks Ole, and for your theme!

I'll be looking for those latest changes. I guess my question was also on the scope of why running `foundation udpate` doesn't do anything?
