### ISSUE TITLE
Basic grid not working?

### ISSUE THREAD

**Issue by Pixelsmith** [olefredrik/FoundationPress#1117]
I'm sure I missed an update on this and I'll need to enable it somehow, but I can't get basic row/column grids to work in the latest version of FP.

**How can this bug be reproduced?**

1. Create a div with the class "row"
2. Inside that div, create another div with classes "medium-6 columns"
3. Create a second div inside "row" with classes "medium-6 columns"

**What did you expect to happen?**
I expected that the medium-6 divs would be in the same row

**What happened instead?**
The medium 6 divs are on separate rows

**Please List the Following:**
* OS & version: Windows 10
* Node version (node -v) [Node v4+ is required] : 6.10.2
* FoundationPress version (see line 3 in package.json): 2.10.3
* Foundation version (see dependencies in package.json) : 6.4.1

**Include Test Case** (if applicable):  
I checked the Foundationpress kitchen sink page (https://foundationpress.olefredrik.com/kitchen-sink). The Abide section has rows and columns that are also not behaving correctly.

Any codepen with just Foundation works as I would expect it to.

**Comment by colin-marshall** [comment]
@Pixelsmith the XY-Grid is the default now. You can switch between the regular grid, flex grid, and the XY grid in the `app.scss` file.

**Comment by Pixelsmith** [comment]
Thanks! I knew I was missing something.
