### ISSUE TITLE
Unable to load app.css

### ISSUE THREAD

**Issue by 87pancakes** [olefredrik/FoundationPress#1118]
I found a bug within the WP Editor, there was an error on the screen that said;

Unable to load ".../dist/assets/css/app.css".

I fixed this by changing the following;

```
	// Add foundation.css as editor style https://codex.wordpress.org/Editor_Style
	add_editor_style( 'dist/assets/css/app.css' );
```

to

```
	// Add foundation.css as editor style https://codex.wordpress.org/Editor_Style
	add_editor_style( 'foundationpress', get_template_directory() . 'dist/assets/css/app.css' );
```

**Comment by colin-marshall** [comment]
@87pancakes thanks for the report. What is the `'foundationpress'` argument doing? We don't have a stylesheet named that.

Also, the `add_editor_style( $stylesheet )` docs say this:
> **$stylesheet**
> (array|string) (Optional) Stylesheet name or array thereof, **relative to theme root**. Defaults to 'editor-style.css'
Default value: 'editor-style.css'

The arguments are already relative to the theme root, so why do we need to add `get_template_directory()`? Only reason I can think of that `'dist/assets/css/app.css'` by itself would not be working is because the build process hasn't been run yet.

**Comment by JPOak** [comment]
@colin-marshall I just tested this to see if had to do with my cacheing. It worked for me without adding the get_template_directory. That being said I need to make the hashing function accessible so we can use it on this as well for when turned on.

**Comment by colin-marshall** [comment]
@JPOak good call and thanks for testing.

On a related note, I just updated the README to add some information on outputting separate JavaScript files. We probably need to add some information for how to handle this when versioning is turned on.

**Comment by JPOak** [comment]
@colin-marshall truthfully, I just throw everything into that one file to be cache busted. If I want to selectively load a JS file into a page I just require it via PHP for that page. That being said, I have been thinking of bringing up to you guys having a custom.js in the directory by default and using a Dom Based Routing (The Paul Irish thing) setup in that file. Maybe down the road.

**Comment by 87pancakes** [comment]
@colin-marshall If i'm honest, I just copied the function arguments from the top of theme-support.php that adds the language support and it fixed the issue in the editor, that's as far as I've taken it.

I did run the build process and the error just wouldn't go away, once I'd ruled our plugins, it must be foundation, however the file was loading in my browser perfectly fine which lead me to believe it's something to do with relative paths.

Removing the `'foundationpress'` argument will probably still work.

**Comment by colin-marshall** [comment]
@JPOak my point is that if somebody adds another js file to the `PATHS.entries` as described in the readme AND they have revisioning turned on, they will have to enqueue the script using the `js_asset_path()` function. I'm thinking this is worth mentioning in the README.

**Comment by colin-marshall** [comment]
@87pancakes something else must going wrong here, because the argument is already relative to your theme's path as I quoted in the docs.

**Comment by colin-marshall** [comment]
@87pancakes I am closing this issue. If you still need help resolving the problem, feel free to reopen.
