### ISSUE TITLE
Responsive $grid-margin-gutters only work when XY-cell is included with a breakpoint

### ISSUE THREAD

**Issue by studiobovenkamer** [olefredrik/FoundationPress#1121]
I'm working with the XY-grid. I tried to get different gutters for medium (30px) and small (15px), but I discovered that this only works when the xy-cells are nested in a breakpoint media query, like this:

```
.example-section{

@include xy-grid-container;
@include xy-grid;
  
.text {
    @include xy-cell(4);//the gutter will be small-sized for small screens
    
@include breakpoint(medium) {
      @include xy-cell(4);//now the gutter will be medium-sized, for medium screens and up
    }

  }
  .icon {
    @include xy-cell(3);//but this one always uses the small gutter size, also on medium screens. 
  }

}
```

I don't know if this is a bug or a feature, but I expected that in this example .icon would have responsive gutters too (just like it does with $grid-column-gutter) without nesting the cell in media queries. Currently this leads to extra coding, for example this could be simpler:

```
//To use the grid-margin-gutter map for small and medium, I need to write:
.responsive-something {
    @include xy-cell();
    @include breakpoint(medium) {
      @include xy-cell();
    }
}

//While it might be nicer to just write this 
.responsive-something {
    @include xy-cell();
}
```

**Comment by colin-marshall** [comment]
@studiobovenkamer that's a valid concern, but it is a Foundation issue, not a FoundationPress issue so you will need to raise the issue at https://github.com/zurb/foundation-sites.

**Comment by studiobovenkamer** [comment]
Created a issue at foundation-sites:
https://github.com/zurb/foundation-sites/issues/10743
