### ISSUE TITLE
Complete Noob at installing this...

### ISSUE THREAD

**Issue by FifthCloud** [olefredrik/FoundationPress#1124]
Tried following your steps on installing FoundationPress. Made sure that node.js is at the correct version. I chose 6.11.4 Hopefully, that's cool. As I am using GoDaddy as my host I has taken me a while to figure out how to install lot of this stuff. 

I came across this error message when I type in the command npm start or npm run build. Am I supposed to this at the server level? Or was this all supposed to be build on my local machine? 

Anyways here is the error message I am receiving...
0 info it worked if it ends with ok
1 verbose cli [ '/home/diamondsbysc/.nvm/versions/node/v6.11.4/bin/node',
1 verbose cli   '/home/diamondsbysc/.nvm/versions/node/v6.11.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundationpress@2.10.3~prebuild: foundationpress@2.10.3
6 silly lifecycle foundationpress@2.10.3~prebuild: no script for prebuild, continuing
7 info lifecycle foundationpress@2.10.3~build: foundationpress@2.10.3
8 verbose lifecycle foundationpress@2.10.3~build: unsafe-perm in lifecycle true
9 verbose lifecycle foundationpress@2.10.3~build: PATH: /home/diamondsbysc/.nvm/versions/node/v6.11.4/lib/node_modules/npm/bin/node-gyp-bin:/home/diamondsbysc/public_html/wp-content/themes/FoundationPress/node_modules/.bin:/home/diamondsbysc/.nvm/versions/node/v6.11.4/bin:/usr/local/jdk/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/cpanel/composer/bin:/opt/puppetlabs/bin:/opt/dell/srvadmin/bin:/usr/local/bin:/usr/X11R6/bin:/home/diamondsbysc/.local/bin:/home/diamondsbysc/bin
10 verbose lifecycle foundationpress@2.10.3~build: CWD: /home/diamondsbysc/public_html/wp-content/themes/FoundationPress
11 silly lifecycle foundationpress@2.10.3~build: Args: [ '-c', 'gulp build --production' ]
12 info lifecycle foundationpress@2.10.3~build: Failed to exec build script
13 verbose stack Error: foundationpress@2.10.3 build: `gulp build --production`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/home/diamondsbysc/.nvm/versions/node/v6.11.4/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid foundationpress@2.10.3
15 verbose cwd /home/diamondsbysc/public_html/wp-content/themes/FoundationPress
16 error Linux 2.6.32-673.26.1.lve1.4.30.el6.x86_64
17 error argv "/home/diamondsbysc/.nvm/versions/node/v6.11.4/bin/node" "/home/diamondsbysc/.nvm/versions/node/v6.11.4/bin/npm" "run" "build"
18 error node v6.11.4
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error foundationpress@2.10.3 build: `gulp build --production`
24 error spawn ENOENT
25 error Failed at the foundationpress@2.10.3 build script 'gulp build --production'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the foundationpress package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     gulp build --production
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs foundationpress
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls foundationpress
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

Hopefully, this makes sense to you. Sorry I am a complete newby at this.

**Comment by colin-marshall** [comment]
You should be doing development locally, through a virtual machine or using MAMP, and then you should copy the files to the server.  Did this error come from running it on the server?

**Comment by FifthCloud** [comment]
Yes this did show up on the server. I guess I should be doing like you described. Everything locally then move files.

**Comment by colin-marshall** [comment]
@FifthCloud everything will be way faster when you develop locally and you should also experience less setup headaches.

**Comment by FifthCloud** [comment]
Thanks for the advice! I will do that.
