### ISSUE TITLE
Bring back WordPress Coding Standards and Codesniffer

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#1127]
I understand why Travis was removed, but I think it would be beneficial to keep the WordPress coding standards and codesniffer in the project for us to run locally and push corrections to the repo. The codesniffer helped keep the code consistent.

**Comment by olefredrik** [comment]
I agree that the idea and intention behind Travis CI and WordPress Coding Standards are good. Very good, actually. But in practice it was a big pain in the ass that the standards changed from week to week without notice. As a result we got build errors on files that had not been modified in pull requests. Why would anyone spend hours manually fixing sniffing errors in files they did not change?

If we could get to a local build agent that could sniff for WP coding standard violations and fix automatically, that would be great. This was previously part of the repo, but unfortunately it never worked out so well. At least not for me. Did you get it to work? Anyway, as a result, it became a lot of work to include new features and bug fixes. 

If there is a good solution for detecting and fixing WP coding standard errors locally, I would gladly consider bringing Travis CI back into the project. If we can't get this to work, it's not worth it, in my opinion.

**Comment by colin-marshall** [comment]
@olefredrik to clarify, I was asking that we forget about Travis (for now at least) but keep the Codesniffer and coding standards in the repo to pick out syntax errors and stuff like that locally. If I remember correctly, we could run PHPCS locally and it would show us errors which we could then fix manually. That way we have the benefit of being able to check for errors and fix them, without being held back by Travis.
