### ISSUE TITLE
Error notice referencing enqueue-scripts.php

### ISSUE THREAD

**Issue by AmyGail** [olefredrik/FoundationPress#1128]
Hello All.
I just installed the latest version and received the following notice on activation.

"( ! ) Notice: Only variables should be passed by reference in /.../enqueue-scripts.php on line 18".

Here's a screenshot in case it's helpful.
Thanks for all your hard work.

![screen shot 2017-10-12 at 4 00 07 pm](https://user-images.githubusercontent.com/1883213/31516425-82d490b4-af66-11e7-8719-2d11c2738d11.png)

**Comment by JPOak** [comment]
@AmyGail What version of PHP are you running on Mamp. I am guessing it is old.

**Comment by AmyGail** [comment]
I'm on 7.1.1

**Comment by JPOak** [comment]
@AmyGail I just tested on 6.4 and 7 and have no error. However, I did test on an older version of PHP and I get the error. @colin-marshall any comment here? i think it has to do with the usage asset_path function and line 18. Maybe we should tweak...

**Comment by colin-marshall** [comment]
@JPOak I guess we should have tested that before merging. The solution is to store the result of explode in a variable and then run the end function on that variable. Source:
https://stackoverflow.com/a/4636183/2755888

**Comment by JPOak** [comment]
@colin-marshall I was looking at that exact stack!

**Comment by JPOak** [comment]
@AmyGail On line 18 replace that with the below and see if that works.

	$tmp = explode('.', $filename);
	$dir = end($tmp);

**Comment by AmyGail** [comment]
Looks like it works!

**Comment by JPOak** [comment]
@AmyGail Sorry about that. We added a new asset hashing feature and still working out the kinks. I will do a PR now for that fix.

**Comment by AmyGail** [comment]
No worries! I appreciate the quick fix.
Thanks.
