### ISSUE TITLE
Newbie, figured out needed to install babel, PLEASE interpret error log

### ISSUE THREAD

**Issue by G-Blackwell** [olefredrik/FoundationPress#1135]
> foundationpress@2.10.4 start /Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress
> gulp

[14:16:02] Failed to load external module babel-register
[14:16:02] Requiring external module babel-core/register
/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "es2015" relative to directory "/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress"
    at /Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundationpress@2.10.4 start script 'gulp'.
npm ERR! This is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress/npm-debug.log

**Comment by colin-marshall** [comment]
@G-Blackwell were there any errors when you ran `npm install`? I think running `npm install babel-register --save-dev` should fix this, but normally you shouldn't have to do that.

**Comment by G-Blackwell** [comment]
Apologies if I'm misunderstanding what you're asking. If your referring to my Node installation, there were not any errors. I recall I installed Node/npm to be used from any directory. Don't know if this is significant but gulp, gulp-babel, and babel-core installed into seperate directories within the node_modules directory (see image). I am a newbie, but I'm thinking I need to correct this by doing a complete reinstall BUT not sure exactly what files to edit (gulpfile.js?) first before running gulp again. the following is the actual output from the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart foundationpress@2.10.4
6 info start foundationpress@2.10.4
7 verbose unsafe-perm in lifecycle true
8 info foundationpress@2.10.4 Failed to exec start script
9 verbose stack Error: foundationpress@2.10.4 start: `gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid foundationpress@2.10.4
11 verbose cwd /Users/gmcdaniels/Dev/wordpress/wp-content/themes/foundationpress
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error foundationpress@2.10.4 start: `gulp`
17 error Exit status 1
18 error Failed at the foundationpress@2.10.4 start script 'gulp'.
18 error This is most likely a problem with the foundationpress package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs foundationpress
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls foundationpress
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Any guidance is greatly appreciated. I guess I can always use grunt if need be (since I've never had issues), but more folks are using gulp these days so I figured it was time to start using it.
![foundpress_gulp-babel_install-dir](https://user-images.githubusercontent.com/1680366/31889139-57f2c364-b7c4-11e7-9edb-397ab9b54184.jpg)

**Comment by FlatspinZA** [comment]
I think what @colin-marshall is referring to is did you run `npm install` from within your theme folder after cloning the FoundationPress repository, and if there were any errors displayed therein?

**Comment by colin-marshall** [comment]
@FlatspinZA is correct, that's exactly what I was asking. Your `node_modules` directory is missing a bunch of dependencies which means that the ones in there were installed manually/individually and `npm install` was never ran or there was an error during `npm install`.

**Comment by G-Blackwell** [comment]
Thanks to both of you. Everything is hunky dory now. This morning I deleted the theme folder, walked through it again step by step and all the dependencies working.
