### ISSUE TITLE
Sticky menu

### ISSUE THREAD

**Issue by massprogressive** [olefredrik/FoundationPress#1136]
I'm trying to create a sticky menu - added helper classes and it works, but not as expected. 

My menu toggles to left side above the site title name instead of expected position on the right side.

**Comment by colin-marshall** [comment]
@massprogressive please fill out the issue template and provide us with a codepen example so we can help you.

**Comment by colin-marshall** [comment]
@massprogressive did you get it figured out?

**Comment by massprogressive** [comment]
@colin-marshall, sorry for delay, 
yes, I've replaced it with my own custom menu and now all works fine for me.
