### ISSUE TITLE
Front Page displays in Reading Settings

### ISSUE THREAD

**Issue by idpokute** [olefredrik/FoundationPress#1140]
Hi guys,
The reading settings page doesn't have Front page displays section. 
I thought it's kind of standard feature.
What do you think?
Thanks.

**Comment by JPOak** [comment]
@idpokute That would indeed be weird. Can you send a screenshot of what you mean. It is indeed a standard feature.

**Comment by idpokute** [comment]
@JPOak Sorry, it was my mistake. I didn't have any page when I tested it.
