### ISSUE TITLE
Show notice of sass gulp task running

### ISSUE THREAD

**Issue by Aetles** [olefredrik/FoundationPress#1144]
This is not a bug, just a question. 

On older FoundationPress projects whenever the watch gulp task found changes in .scss files there was a notice on the command line. But on my latest project the sass task runs fine but does not produce any notice, unless there is an error. Is there anything I can change in `gulpfile.babel.js` to make it always show output again?

**How can this bug be reproduced?**
1. Run `npm start`
2. Make a change to a .scss file.

**What did you expect to happen?**
A notice on the command line telling me that the sass task ran, like:
```
[15:12:34] Starting 'sass'...
[15:12:36] Finished 'sass' after 1.86 s
```

**What happened instead?**
Nothing. (The sass task _do_ run, it's just not telling me about it.)

**Please List the Following:**
* OS & version: Linux 3.10.0-614.10.2.lve1.4.55.el7.x86_64
* Node version (node -v) [Node v4+ is required] : v8.9.0
* FoundationPress version (see line 3 in package.json): 2.10.4 (but modified)
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.1

**Comment by colin-marshall** [comment]
@Aetles looks like some of the gulpfile code I wrote in the previous version didn't get ported over in the Foundation 6.4 update for FP. Gulp was updated to v4 and the watch method is different now. I'll get this sorted out soon.

**Comment by tiborp** [comment]
May I add to this that it would be nice to get noticed if errors appear during the process? I am not proficient enough to add this myself, but I have been using a gulp file that had this function that took care of that:

```
/**
 * Handle errors and alert the user.
 */
function handleErrors() {
	const args = Array.prototype.slice.call( arguments );

	notify.onError( {
		'title': 'Task Failed [<%= error.message %>',
		'message': 'See console.',
		'sound': 'Sosumi' // See: https://github.com/mikaelbr/node-notifier#all-notification-options-with-their-defaults
	} ).apply( this, args );

	gutil.beep(); // Beep 'sosumi' again.

	// Prevent the 'watch' task from stopping.
	this.emit( 'end' );
}
```

Comes in very handy if you are watching your browser and nothing is happening ;-)

**Comment by Aetles** [comment]
I was using an older FoundationPress project (back in the _grunt_ days!) and it had this nice progress and report for every SASS change, like this:

```
>> File "scss/site/_global.scss" changed.

Running "sass:dist" (sass) task

Done, without errors.


Execution Time (2018-01-16 16:52:13 UTC+1)
loading tasks  415ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 64%
sass:dist      229ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 36%
Total 645ms

Completed in 1.018s at Tue Jan 16 2018 16:52:14 GMT+0100 (CET) - Waiting...
```

I've yet to figure out how to make the latest workflow present this kind of information (or any at all) when re-compiling sass.

**Comment by Aetles** [comment]
https://github.com/olefredrik/FoundationPress/pull/1210 solves this issue, thank you!
