### ISSUE TITLE
Topbar vs Offcanvas..

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1147]
I'm not sure if this is a bug or by design. However, when using Topbar menu it looks like inline style to hide and show are being injected by js. I'm not sure where this is coming from and it makes it harder to change breakpoints. Is this something leftover from the past?

However, Offcanvas isn't doing this and very easy to change breakpoints via the nav scss.

**Comment by JPOak** [comment]
Ok. Maybe a weird question!

**Comment by colin-marshall** [comment]
@JPOak I just haven't had time to investigate this. Feel free to reopen.

**Comment by JPOak** [comment]
@colin-marshall No worries. I think it is more of a Foundation thing. From the Foundation forums there are other people that also feel that it uses more JS for the navigation than necessary. Another example is for the dropdowns. Instead of using CSS it uses JS I believe. It makes it more difficult to add smoother transitions on it. I guess it's not really a bug.
