### ISSUE TITLE
Upgrade gulp-sass to 3.1.0?

### ISSUE THREAD

**Issue by Aetles** [olefredrik/FoundationPress#1148]
Right now in `package.json` the version of gulp-sass is 2.1.0. 

I was using node v8.9.1 and npm 5.5.1 and ran into an issue where `npm install` would not work because gulp-sass 2.x requires node-sass@3.13.1 which doesn't have a pre-built binaries for node > 4.x. according to [this issue](https://github.com/sass/node-sass/issues/2017) and [this change](https://github.com/farrago/angular-foundation-6/commit/3775388aedb0d5b4e501e9d990b60b0f48da7a2c). 

Part of my error message looked like this (pasting it if others search for this):

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 

HTTP error 404 Not Found
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
```

My solution was to update `package.json` at line 54
`    "gulp-sass": "^2.1.0",`
to
`    "gulp-sass": "^3.1.0",`

Then `npm install` ran successfully. 

I have not tested this with other versions of node, but if there are no know downsides for other versions of node, then I would suggest we increase the required version of gulp-sass like I did.

**Comment by colin-marshall** [comment]
@Aetles I see that they say there are no pre-built binaries for Node > 4.x, but that's odd because it works fine for me on Node 8.4.0 and I checked the node-sass package and it is 3.13.1.

Going to have to do some testing to verify which versions of Node we can support if we update that package.

**Comment by Aetles** [comment]
I did an installation on another, similar server just a couple of days ago without issues, so I was a little surprised to run into this, to be honest. But it solved my issue today.

**Comment by JPOak** [comment]
I did a full update of node and npm the other day. I had to run `npm rebuild node-sass` .

**Comment by Aetles** [comment]
Yeah, `npm rebuild node-sass` has been a lifesaver many times but not this time though (I did try it).

**Comment by colin-marshall** [comment]
@Aetles @JPOak I would appreciate your input on something confusing I came across.

> The v3.13.1 release of node-sass, required by gulp-sass 2.x, does not contain binaries for **node 5 (module version 57)**, which is why you get a 404.
Try upgrading your gulp-sass to version 3 or above.

Source: https://github.com/sass/node-sass/issues/2017

When he says "Node 5" is he really meaning Node 8/npm 5? Because according to [previous node releases](https://nodejs.org/en/download/releases/), module number 57 is Node 8.x and npm 5.x.

Then there's also this comment:
> Yes you can downgrade to **Node 4** to use gulp-sass@2. It's worth noting there
are no breaking changes between gulp-sass 2 and 3 so upgrade should be
painless.

So if I'm correct about the Node 8/npm 5 thing, then in the comment above he really means downgrade to npm 4.x (Node 7.4.x -> 7.10.x), right?

**Comment by JPOak** [comment]
@colin-marshall I think that is right, but confusing. All I know is that if you update to the latest version on Node and NPM (which I did two days ago) that you will most likely need to rebuild node-sass/update it on all your installs, which is what I have been having to do. As I was getting this error which I think is connected to your thread: https://github.com/sass/node-sass/issues/1764

**Comment by Aetles** [comment]
@colin-marshall Hmm, maybe you're right. I didn't look into that part, I was mostly focused on the fact that gulp-sass 2.x was the cause behind the failed node-sass 3.13.1 download, and that upgrading to gulp-sass 3.x solved my issue (and also the reassuring that there were no breaking changes, so it seemed safe). 

If no-one else is having my issue there's no hurry to change `package.json`, we can just keep this in mind if it comes up again.

Also, I am using Node 8.x and the FoundationPress readme clearly says v4.x.x to v6.11.x:

> This project requires Node.js v4.x.x to v6.11.x to be installed on your machine.

**Comment by colin-marshall** [comment]
Thanks for the responses.

@Aetles the upper limit of the required Node version for FP is kind of ambiguous and doesn't get updated as regularly as it could. Right now I see no reason it couldn't be 7.10.x seeing as how the only known issue with any newer versions of Node is the very issue we are discussing here which relates to 8.x.

It might be best to wait until 10.x is released until we bump up `package.json` and force everybody to use at least 8.x of Node. If they keep the development pace at the rate it's going now, that would be in about 6 months.

**Comment by DanielRuf** [comment]
Generally `node-gyp` should rebuild it. Did you try `npm rebuild node-sass --force`?

**Comment by Aetles** [comment]
No, I did not try it with `--force`. 

(But I'm not sure that would have help, the error seemed to depend on my version of node and the fact that gulp-sass 2.x requires node-sass@3.13.1 which doesn't have a pre-built binaries for node > 4.x.)

**Comment by DanielRuf** [comment]
It should have. If not node-gyp will (re)compile the sourcecode to a binary.

**Comment by DanielRuf** [comment]
Without `--force` there might not happen anything.

**Comment by Aetles** [comment]
Ah, didn't know that! Well, if I stumble upon it again I might try that then. Changing to gulp-sass 3.1.0 worked well for me this time.
