### ISSUE TITLE
Container and grid-x on the same element by purpose?

### ISSUE THREAD

**Issue by Aetles** [olefredrik/FoundationPress#1151]
Personally, I don't use the mixins for grid, I prefer inline classes ([tachyons style](http://tachyons.io)), but I noticed that currently in [_content.scss](https://github.com/olefredrik/FoundationPress/blob/master/src/assets/scss/modules/_content.scss) the code looks like this:

```sass
.main-wrap {
  @include xy-grid-container;
  @include xy-grid();
```

Both the `xy-grid-container` and `xy-grid` are used on the same element. Is that supposed to be like that? 

(Also, is there a reason for the parentheses on `@include xy-grid();`? Otherwise I think they can be removed, just like they are not present on the mixin above.)

When I checked the [docs for the XY Grid](https://foundation.zurb.com/sites/docs/xy-grid.html) all the examples places the container element outside the grid-x element. 

```html
<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell small-4">cell</div>
    <div class="cell small-4">cell</div>
    <div class="cell small-4">cell</div>
  </div>
</div>
```

And for the mixins they do like this:

```sass
.container {
  @include xy-grid-container;
}

.my-grid {
  @include xy-grid;
}
```

**Comment by colin-marshall** [comment]
@Aetles thanks for bringing this up. I noticed it while working on a site but forgot to raise the issue here.

My question is, do we want to wrap `.main-wrap` in `div.grid-container` or use a mixin like:

```scss
.container {
  @include xy-grid-container;
}
```

I can appreciate that you prefer to build grids with the stock Foundation classes, however for consistency in FoundationPress it might be best to keep everything built semantically with mixins. What do you think?

**Comment by Aetles** [comment]
Yeah, I'm not suggestion any change of that, having clean templates with semantic SASS mixins is how it's done here, and probably how most prefer it, that part is just a matter of personal workflow. (I just wanted to say that I wasn't using it myself, so I didn't know if it actually was a problem or not, that they used the same element.)

For consistency I think another mixin probably the best solution.

**Comment by JPOak** [comment]
@colin-marshall I noticed that too in my last project and thought it odd. I'm all for separating it out as you did in your example with a mixin.

**Comment by colin-marshall** [comment]
Since "container" and "wrap" are close to each other in meaning, I think it makes sense to name the classes like so:

```html
<div class="main-container">
  <div class="main-grid">
    <main class="main-content">
      ...
    </main>
  </div>
</div>
``` 
Thoughts?

**Comment by JPOak** [comment]
@colin-marshall That totally makes sense to me. I just launched a site on on the old FP V2.9 (yes, it took a long time!) . I realized I think the current iteration of FP has much cleaner code. It sort of makes me sad for my clients project so I am thinking of going through it all and making some of the changes we did for the current version.
