### ISSUE TITLE
Update to Foundation 6.4.3?

### ISSUE THREAD

**Issue by Aetles** [olefredrik/FoundationPress#1152]
Have anyone tried to use FoundationPress with Foundation for Sites 6.4.3?

Looking at the [release notes for Foundation for Sites](https://github.com/zurb/foundation-sites/releases/) it seems like a lot of fixes and a big XY Grid improvement that went into the 6.4.2 release (the 6.4.3 release was just a quick patch of errors introduced in 6.4.2). 

FoundationPress is currently locked at Foundation for Sites 6.4.1 because of https://github.com/olefredrik/FoundationPress/issues/1048. I'm curious if anyone tried to fix this, and if there are _other_ breaking changes or issues with 6.4.3?

The diff for `_settings.scss` should the same as [the one for Zurb Foundation Template](https://github.com/zurb/foundation-zurb-template/commit/e78b9421b0eeb3c7315f2a7402654480969e25db) right?

**Comment by Aetles** [comment]
I updated my `_settings.scss` accordingly and changed to 6.4.3 in `package.json`, removed my `node_modules` folder an re-ran `npm install` and `npm start` and so far it seems to work fine.

**Comment by Aetles** [comment]
Also, Ole called it "a breaking change" in https://github.com/olefredrik/FoundationPress/issues/1048 but I'm not so sure it was breaking anything. I just produced a warning. In https://github.com/zurb/foundation-sites/issues/10556 the response was:

> @isapir there haven't been introduced any non backwards compatible changes.
> What you see on gulping is a **warning** not an **error**.
> 
> I've added this to prompt the user to update his settings at an early stage instead of waiting until it has been removed and cause an actual error.
> Right now the deprecated `$offcanvas-size` is still working and gets internally converted into the new `$offcanvas-sizes`.
> 
> I think it's not a backwards compatibility issue if you get only a warning. 

So I wonder if the lock on 6.4.1 really is necessary?

**Comment by colin-marshall** [comment]
@Aetles I would love a PR for this if you have time. I agree that the warning was nothing to worry about and it would be removed simply by updating the settings file. Thanks!
