### ISSUE TITLE
Do you use this theme as starter theme or parent theme?

### ISSUE THREAD

**Issue by idpokute** [olefredrik/FoundationPress#1153]
Hello folk.
I am curious how people handle this theme.
Do you guys use this theme as starter theme, so you modified the source code directly?
Or do you use this theme as parent theme, so you keep the original code and pull the latest code from the git repo?

If i write this question on the wrong place, l'm sorry. Let me know if FoundationPress has a forum.
Thanks.

**Comment by colin-marshall** [comment]
@idpokute it's more than fine to ask questions here. FoundationPress is a starter theme and is meant to be "hacked" however you like. It's not meant to be used as a parent/child theme.

**Comment by idpokute** [comment]
@colin-marshall when the FP is updated, how do you do version up your hacked theme to catch the latest FP? This is what I want to know from the folk.

**Comment by olefredrik** [comment]
@idpokute It depends. You could check the repo and manually catch the latest changes if you like. Or you could simply ignore the updates to FP and carry on with your project. As @colin-marshall said, it's meant to be a starter theme. As I see it, it's purpose is to give you a head start into new projects. Hopefully that is what you'll get if you clone the latest release when you start a new project :)
