### ISSUE TITLE
correctness and json_decode

### ISSUE THREAD

**Issue by jshwlkr** [olefredrik/FoundationPress#1156]
I'm going to unhelpfully nitpick a bit here and note that `json_decode` is somewhat notorious in its potentially unhelpful error reporting. In order to be robust you'd have to use `json_last_error`https://secure.php.net/manual/en/function.json-last-error.php. I'm not entirely sure FoundationPress could find itself in a situation where json_decode fails in a silent and inexplicable way, but I thought I'd note it.

**Comment by colin-marshall** [comment]
@jshwlkr thanks for pointing this out. I guess it could fail if the manifest file got messed up during the build process. I would think this would be noticeable even if it failed silently because then your JS and CSS assets would likely not load. I guess we could test it by purposely messing up the manifest file.

**Comment by colin-marshall** [comment]
@JPOak can you help out with this issue since you introduced this code?

**Comment by JPOak** [comment]
@colin-marshall I was caught on the "silent and inexplicable" and then your follow-up. If it failed it would be pretty evident. Our usage of it is pretty simple/straightforward.

**Comment by colin-marshall** [comment]
@JPOak I guess I'll just close this out and we can revisit it down the line if people have trouble. Thanks!

**Comment by JPOak** [comment]
@colin-marshall Also, json_decode is only used when a person is using the cache busting. I used the cache busting feature recently with a client where I was iterating quickly on a live production server. It worked well for me. But yeah, lets revisit if there are issues.
