### ISSUE TITLE
Theme updates through wordpress interface

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#1163]
Is it possible to add functionality to FoundationPress so that themes that we produce can be updated via the wordpress interface, so users will be alerted that an update is available and they can action the update, instead of having to upload a new zip file. 

I have to admit I don't know anything about this process and it may not be relevant to FoundationPress at all, so apologies if it isn't.

**How can this bug be reproduced?**

Not a bug, just a question

**Comment by dantahoua** [comment]
I don't think so as the purpose of FoundationPress is to be a skeleton theme, that you customise every time you make a new website...
I have used this theme more than 20 times and each time the theme ends up very different from website to website...
This theme allow you to be very picky performance wise, so updating through "regular" wordpress theme would remove this possibility...
That's my point of view... :)

**Comment by nitrokevin** [comment]
Thanks but I was thinking more in terms of after you have customised it and you are making later updates to the same site, not rolling out to other websites. Packaging, logging onto the site, navigating to themes, uploading zip, activating new theme... it can be a bit of a ball ache.
Just didn’t know if part of the packaging process could handle uploading or making it available for updating somehow

**Comment by colin-marshall** [comment]
I agree with @dantahoua, this is not the type of theme where you would update through the WordPress interface. Besides the fact that FP is not a parent/child theme setup, it doesn't make sense.

@nitrokevin your workflow for updating is kind of inefficient. Why don't you just overwrite/merge the theme folder from your local copy to the remote server via FTP? That way you don't have to package anything, and you don't even have to touch the dashboard. You can set your FTP software to ignore the `node_modules` directory which will make everything fast.

I personally have never even used the package task, besides testing it when I wrote it lol. It's useful for some situations, like passing theme off to another person, but there's better ways to update.

Another fast way to update is through git. Remove the line from `.gitignore` that ignores the `dist` directory. Then commit the `dist` directory to the repo. Add your hosting server as a remote on your local repo, and then push local changes after you commit. Make sure you build as production before pushing.

**Comment by nitrokevin** [comment]
Great thanks, I knew there must be a better way. Thanks again
