### ISSUE TITLE
npm ERR! Unexpected token } in JSON at position 32554

### ISSUE THREAD

**Issue by SamboVisal** [olefredrik/FoundationPress#1181]
### I have tried to install it but it throws me some errors like this:
`npm ERR! Unexpected token } in JSON at position 32554

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sambo visal\AppData\Roaming\npm-cache\_logs\2017-12-08T17_11_35_886Z-debug.log`

**Comment by colin-marshall** [comment]
@SamboVisal are you using FoundationPress?

**Comment by colin-marshall** [comment]
@SamboVisal I'm closing this issue because I don't believe it has anything to do with FoundationPress. If I have done so in error, feel free to reopen the issue at anytime.

**Comment by emilyJQ** [comment]
@SamboVisal  Dear.i have same problem in my project.Can you tell me how you solved this problem?
