### ISSUE TITLE
Can Not Find Module hooks.json

### ISSUE THREAD

**Issue by niks-230688** [olefredrik/FoundationPress#1185]
Hello Guys.

 I am getting below errors during install framework7.

Can you please help me out for this.

**How can this bug be reproduced?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**

**What happened instead?**

**Please List the Following:**
* OS & version:
* Node version (node -v) [Node v4+ is required] :
* FoundationPress version (see line 3 in package.json):
* Foundation version (found in `node_modules/foundation-sites/package.json`) :

**Include Test Case** (if applicable):  

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by colin-marshall** [comment]
@niks-230688 what is framework7? Are you using FoundationPress?
