### ISSUE TITLE
Font-Awesome auto-complete

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#1190]
Not really an issue but as now Font-Awesome is added in the enqueue-Scripts.php, we lost (when using PhpStorm like me) the auto-complete feature which is very usefull with icon library... What I do now is just dropping the font-awesome.css in the scss folder, not even using it but as PhpStorm see it, it can auto-complete after...
But maybe there is a better way for doing this? Maybe adding the possibility to queue it from CDN or from local directory as before?
Just looking for some suggestion to be more effective in my dev settings! :)

**Comment by colin-marshall** [comment]
If the file is not contained locally in the repo, I see no reason to add the option to enqueue it locally, even if it's commented out. It's just going to confuse people if they uncomment it and they get console errors from the file not being there.

If it's too much of a hassle to add the file in manually and enqueue after cloning, you can always maintain your own fork of FP with the CSS file added into your repo and enqueued locally. If you do it that way you have to consider that you have to take some extra steps in pulling upstream changes from the main FP repo to keep your fork up-to-date.

It might be faster to just do it all manually and forget about the fork if those are the only changes you would make in your fork.

**Comment by dantahoua** [comment]
Yes you are totally right! It was just a kind of thinking out loud! :)
Thanks Colin.
