### ISSUE TITLE
FoundationPress & Style Sherpa

### ISSUE THREAD

**Issue by jastnet** [olefredrik/FoundationPress#1191]
Is it possible to generate a Style Guide with FP & Style Sherpa?

**Comment by colin-marshall** [comment]
@jastnet I have no experience specifically with Style Sherpa, but one thing you could do is clone the Foundation Zurb Template and overwrite the `_settings.scss` with the one from your FoundationPress project. The Foundation Zurb Template creates a `styleguide.html` when you build, which I'm assuming is similar to Style Sherpa.
