### ISSUE TITLE
Someone have a set of install instructions for Ubuntu?

### ISSUE THREAD

**Issue by wcataldo** [olefredrik/FoundationPress#1195]
It has been 8 months or so since I used FoundationPress with VVV. I cannot get it to run anymore. I would like to point to just one error I am having but my issues are all over. I am using nvm and have tried bunch of different node versions, I have tried two different libsass solutions, one ppa and a build script.  Every time I feel like I took a step forward I get kicked in the balls.

Most of the errors are "The following tasks did not complete: sass" or failed at gulp. But it always bitches about babel and I have tried whatever I could find on installing babel with npm. I apologize for not filling out the form. I will gladly install a fresh elementary os or whatever it takes. I have searched through numerous threads and tried dozens of deleting modules folder. You have to chuckle at the amount of moving parts involved with getting a modern dev environment up and running.

I am throwing this out with the hopes of some hero showing me a gist script that can reinstall or fix this nightmare.

best regards

**Comment by colin-marshall** [comment]
@wcataldo I also use VVV. Are you trying to run FoundationPress from inside of VVV (vagrant ssh) or are you running from your host machine? In theory it should work either way, but I always run/build it from the host machine.

What versions of Node have you tried? If you're using v8+, you should check out #1148 which may be related to your sass error(s).

Finally, can you provide some of the babel errors?

**Comment by colin-marshall** [comment]
@wcataldo I just pulled in a fix from @alexbohariuc in #1192 that is most likely will resolve some of your problems. Please pull the updates or do a clean clone of FoundationPress and let me know how that turns out.
