### ISSUE TITLE
https://api.github.com/repos/olefredrik/ in app.js imapcts YSlow

### ISSUE THREAD

**Issue by forex4noobs** [olefredrik/FoundationPress#1203]
**How can this bug be reproduced?**
1. Look in app.js and you will see the url 
https://api.github.com/repos/olefredrik/foundationpress?callback=foundationpressGithub&access_token=ed6229228dbc763038dbf1e68d0d8a4a0935b38a&callback=jQuery32105592909205515957_1515614253048&_=1515614253049
2. Visit this GTmetrix URL, click YSlow and you can see the issue
https://gtmetrix.com/reports/foundationpress.olefredrik.com/36fyvomx

**What did you expect to happen?**
I didn't really expect it to be there, I don't understand why it is.

**What happened instead?**
It was there and it impacts speed score with several page speed testers like GTmetrix... which makes clients unhappy.

**Please List the Following:**
* OS & version:
N/A
* Node version (node -v) [Node v4+ is required] :
N/A
* FoundationPress version (see line 3 in package.json):
Latest
* Foundation version (found in `node_modules/foundation-sites/package.json`) :
Latest

**Comment by JPOak** [comment]
@forex4noobs That was removed last month I believe. #1188 . You can remove it it is just for the demo examples and to pull in the stargazers count I believe.

**Comment by colin-marshall** [comment]
@JPOak is correct. Closing this out. Thanks!
