### ISSUE TITLE
Jquery code included to app.js

### ISSUE THREAD

**Issue by touled** [olefredrik/FoundationPress#1206]
Hi!
I have noticed that when your run **npm start** Jquery code is included to app.js.

**How can this bug be reproduced?**

1. npm start
2. app.js contains jquery code

**What did you expect to happen?**

no jquery code in app.js

**What happened instead?**

app.js contains jquery code.
However if you run **npm run build** or **npm run dev** jquery is not included to app.js

* Windows 7 64-bit
* Node v.6.11.5
* FoundationPress version 2.10.4:
* Foundation version 6.4.3

**Comment by conorbarclay** [comment]
Can you try out the ammended gulpfile I put together for #1205 and report back here?

**Comment by touled** [comment]
Yes, ammended gulpfile worked! Thanks! However webpack do not compile js using babel-loader. For me I commented this line in gulpfile.babel.js
// exclude: /node_modules(?!\/foundation-sites)/,

**Comment by dioogbento** [comment]
@conorbarclay I was having the same kind of issues, including jquery in the app.js file and wrong compiling order, and your fix solved it! Thank you!
