### ISSUE TITLE
foundationpress_responsive_video_oembed_html Errors with Instagram oEmbed

### ISSUE THREAD

**Issue by drivenfaroff** [olefredrik/FoundationPress#1208]
Running into errors when using oEmbed on an Instagram photo.

1. oEmbed an Instagram photo on a post. Example "https://www.instagram.com/p/9zkHAeyDD9/"

2. The oEmbed's will work, however the _foundationpress_responsive_video_oembed_html_ function that tries to make it 100% width is throwing errors.

> Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in /wp-content/themes/CVB/library/foundation.php on line 140
> 
> Notice: Undefined variable: width in /wp-content/themes/CVB/library/foundation.php on line 153
> 
> Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in /wp-content/themes/CVB/library/foundation.php on line 140
> 
> Notice: Undefined variable: width in /wp-content/themes/CVB/library/foundation.php on line 153

Is this possibly because Instagram could be a photo or video? Instagram isn't in the $video_sites whitelist so I would think it would be ignored by the _foundationpress_responsive_video_oembed_html_ function. 

Disabling this function for now on this site. Anybody know a possible fix/workaround?

Would still like the Instagram oEmbed's to be 100% width even if just a photo but could target those iframes with CSS if needed.

**WordPress:** 4.9.1
**FoundationPress:** 2.10.4

**Comment by colin-marshall** [comment]
@drivenfaroff I have debug turned on in my `wp-config.php` and I'm not getting the warnings that you are when I embed that exact Instagram post? It doesn't go to full width though.

**Comment by drivenfaroff** [comment]
@colin-marshall Tried this on another site with no issue. So not sure what was going on with the errors. Closing this. Thanks.

**Comment by jordan314** [comment]
Hi, this is all over our logs too.
You can suppress them with `libxml_use_internal_errors(true);` on line 135 of foundation.php.
`[Mon Feb 26 23:23:05.001841 2018] [:error] [pid 12862] PHP Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:23:05.003078 2018] [:error] [pid 12862] PHP Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:23:05.004404 2018] [:error] [pid 12862] PHP Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:23:05.005676 2018] [:error] [pid 12862] PHP Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:23:05.006908 2018] [:error] [pid 12862] PHP Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:23:05.008165 2018] [:error] [pid 12862] PHP Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:27:30.689968 2018] [:error] [pid 8321] PHP Warning: DOMDocument::loadHTML(): Tag time invalid in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:30:55.004946 2018] [:error] [pid 30344] [client 207.46.13.42:26571] PHP Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:31:03.152896 2018] [:error] [pid 30411] PHP Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 in [path]library/foundation.php on line 136
[Mon Feb 26 23:31:43.776123 2018] [:error] [pid 32092] PHP Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 in [path]library/foundation.php on line 136`
