### ISSUE TITLE
Font Awesome JS Enqueue

### ISSUE THREAD

**Issue by wishe** [olefredrik/FoundationPress#1209]
The way Font Awesome is included in this theme is not efficient at all. I am having to go back to sites I have made with it and changing the way Font Awesome is included because it caused a number of issues.

**How can this bug be reproduced?**
1. Run the theme in a production environment

**What did you expect to happen?**
Expected fontawesome to load quickly and with no delays

**What happened instead?**
Font awesome loads incredibly slow. The CDN that is used responds slowly.

**Suggested fix**
It is better to include the CSS version of the font, it loads alot smoother.

**Please List the Following:**
* OS & version: Ubuntu 16.04
* Node version (node -v) [Node v4+ is required] : 6.10.1
* FoundationPress version (see line 3 in package.json): 2.10.4

**Comment by conorbarclay** [comment]
IMHO, Font Awesome should be removed from this repo all together in favour of SVG icons + accompanying SVG sprite build task. If you need FA, enqueue it and implement it yourself. It's just too heavy to include when often most devs are only going to use a few of the icons from it.

The 2017 Theme has a neat implementation: https://2017.wordpress.net (view source, and scroll all the way to the bottom...inline SVG calls to a sprite that's embedded in the footer, with only the icons you need)

Sorry that this wasn't helpful at all, haha.

**Comment by JPOak** [comment]
@conorbarclay That was helpful. You gave another option and opinion. Much better than just saying "No" and not saying why or alternatives.

**Comment by tiborp** [comment]
Sort of off-topic, but apart from the FA discussion, SVG sprites like @conorbarclay suggests was  a potential pull request of mine. So we can call out icons this way:

https://github.com/WebDevStudios/wd_s/blob/6448e2da38f019a0df63e3fa16da0bc5caa9e7a1/inc/template-tags.php#L90

**Comment by JPOak** [comment]
I've been playing with the below webpack loader for sprites on a local branch of FP. Seems to work alright. Anybody have any thoughts on it/tried it?

https://github.com/kisenka/svg-sprite-loader

**Comment by conorbarclay** [comment]
@JPOak I've tried that as well and it does work fine...however, I would probably just keep it simple and run a Gulp task for it, rather than fussing around with Webpack and adding entries and loaders. Something like `gulp-svg-sprite` would do fine:

`
....
import { dest, src, task } from 'gulp';
import plugins from 'gulp-load-plugins';
import config from '../config';

const $ = plugins();
const { paths } = config;

task('icons', () => (
  src(paths.icons)
    .pipe($.filter(file => file.stat && file.stat.size))
    .pipe($.svgSprite({
      mode: {
        symbol: {
          inline: true,
          dest: '.',
          sprite: 'svg-sprite.svg',
        },
      },
      shape: {
        id: {
          generator: 'fp-icon-',
        },
      },
      svg: {
        xmlDeclaration: false,
        doctypeDeclaration: false,
      },
    }))
    .pipe(dest(`${paths.dist}/icons`))
));`

**Comment by JPOak** [comment]
@conorbarclay I'll try that as well. I didn't think the webpack method was too difficult once you setup config. I wouldn't mind having some sort of go to icon solution. Clients like icons : ) .

Let's see if anybody else has any thoughts.

**Comment by JPOak** [comment]
Ok. I tested out https://github.com/jkphl/gulp-svg-sprite that @conorbarclay suggested. I kind of half way implemented it (simple task runner). I feel the Webpack version is easier to implement into FP, but the pure Gulp method might be easier for people to use with its classes. However, I do worry about some of the current errors on their mb .

Anyways, be interested in other peoples opinion as one or the other solution would useful I think. @colin-marshall ?

**Comment by JPOak** [comment]
Ok. Last thing I will say on this. This is may be another option: https://github.com/shakyShane/gulp-svg-sprites .

Just from the docs I like this because it looks like it will allow you to set the relative path of the svg in the stylesheet if you decide to do custom paths for the svg stylesheet (use as scss) and the svg files. This could make things a lot easier and cleaner in the build and structure.

**Comment by colin-marshall** [comment]
@JPOak I would be interested in seeing something implemented with the new Font Awesome 5 and if it bundles only the icons you use so it's resource friendly.

**Comment by JPOak** [comment]
@colin-marshall that’s funny I was just looking at FA 5 and their new svg and js implemenation. Looks tiny and better .

**Comment by colin-marshall** [comment]
@JPOak feel free to put together a PR we can test out and possibly implement.

**Comment by JPOak** [comment]
@colin-marshall I played around a bit with FA 5 SVG and JS . It's sort of cool and I may start using it in projects. However, I am not sure it will make sense to add it as a permanent part of FP.

If you/or anybody else want to give it a go I tested with the following:

Install FA 5 and the library you want
```
npm i --save @fortawesome/fontawesome
npm i --save @fortawesome/fontawesome-free-brands
```

Import it in app.js and make the icon you want accessible. Import a single Facebook icon.
```
import fontawesome from '@fortawesome/fontawesome';
import faFacebook from '@fortawesome/fontawesome-free-brands/faFacebook';
fontawesome.library.add(faFacebook);
```

Add to your html
`<i class="fab fa-facebook"></i>`

**Comment by dantahoua** [comment]
I was going to switch to ForkAwesome but this method of selecting just what you need pick up my interest! I'll try it. Thanks!

**Comment by jsaxestaral** [comment]
Hi All,
I've been struggling for the better part of a couple hours now to get FontAwesome implemented.  There doesn't seem to be any documentation really (unless I'm missing it).  

so far I've
`npm install @fortawesome/fontawesome-svg-core`
`npm install @fortawesome/free-solid-svg-icons`

then in app.js I added
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faAddressBook } from '@fortawesome/free-solid-svg-icons';

library.add(faAddressBook);
```
finally in my template file
`<i class="fas address-book"></i>`

I can see the js files being included via webpack in the developer console, but I'm not seeing the icon. My understanding is that the <i> tag is should be converted to an svg and display?  Has anyone gotten this going recently?  Is there a documentation somewhere that I'm missing?  Any help is much appreciated.

**Comment by JPOak** [comment]
They changed some thing from the post I wrote above. I used the below for a more recent project a couple months ago after sorting through their documentation that seems to change a bit. Of course swap in the icon you want.


```
//Add Fontawesome
import { library, dom } from '@fortawesome/fontawesome-svg-core';

import { faSignInAlt } from "@fortawesome/free-solid-svg-icons";

library.add( faSignInAlt );

dom.watch();
```

**Comment by jsaxestaral** [comment]
Worked like a charm @JPOak!  Thanks fort the quick reply.
