### ISSUE TITLE
Error: It's not clear which file to import for '@import "foundation"'.

### ISSUE THREAD

**Issue by adambundy** [olefredrik/FoundationPress#1215]
1. Copied my FoundationPress folder into the local instance of a site for some dev work
2. npm start
3. Getting an error in the terminal...

After this theme folder dup, I was getting some errors, so I deleted node modules and re-ran npm install and npm run build. 

Then, after trying to 'npm start', Im getting the following:

Error: It's not clear which file to import for '@import "foundation"'.
       Candidates:
         foundation.scss
         foundation.css
       Please delete or rename all but one of these files.
        on line 5 of src/assets/scss/app.scss
>> @import 'foundation';

Any idea how to solve this and why it would have sudenly cropped up on this duped instance? Thanks for any help in advance!

-Adam

**Comment by colin-marshall** [comment]
@adambundy you have to run `rm -rf node_modules` and then `npm install` again since you switched environments.

**Comment by adambundy** [comment]
@colin-marshall thank you!! Project running again. What exactly does the first command do with the node_modules?

**Comment by adambundy** [comment]
@colin-marshall never mind. I see that it just removed the node_modules folder. Thanks again for the help!

**Comment by colin-marshall** [comment]
It deletes the folder. Every time you switch machines, or even just switch node versions/installs on the same machine, you should delete the folder and run `npm install` again. When you move your project around, I would just ignore the `node_modules` folder altogether to save time and disk space when copying. Or better yet, just use git and clone from a remote repo. `node_modules` is ignored by default in the `.gitignore` file.

**Comment by adambundy** [comment]
@colin-marshall disregard. Dont ask me how, but I think I got this ironed out. Thanks!
