### ISSUE TITLE
build process choking on SVG images?

### ISSUE THREAD

**Issue by adambundy** [olefredrik/FoundationPress#1216]
I have some SVG images in /assets/images/, and running the build process generates the following error:

[11:52:52] Starting 'images'...
[11:52:53] 'images' errored after 458 ms
[11:52:53] CssSyntaxError in plugin 'gulp-imagemin:'
Message:
    Colon is expected
Details:
    parseError: [object Object]
    fileName: [...]/wp-content/themes/FoundationPress/src/assets/images/arc-lines-top-r2.svg
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[11:52:53] 'build' errored after 6.09 s

If I remove 'images' from the gulp build task, it runs fine. Is there perhaps an issue with optimizing SVGs?

**Comment by colin-marshall** [comment]
@adambundy in `package.json` try changing `"gulp-imagemin": "^2.2.1",` to `"gulp-imagemin": "^4.1.0",` and run `rm -rf node_modules` and `npm install` again. Looks like we are using an older version of gulp-imagemin.

**Comment by colin-marshall** [comment]
https://github.com/sindresorhus/gulp-imagemin/issues/229

**Comment by adambundy** [comment]
@colin-marshall I upped the version on imagemin, and re-enabled images in the build task, but still getting an error on that step:

[13:06:39] TypeError in plugin "gulp-imagemin"
Message:
    Cannot read property '0' of undefined
Details:
    fileName: [...]/wp-content/themes/FoundationPress/src/assets/images/arc-lines-top-r2.svg
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

**Comment by colin-marshall** [comment]
Try downloading a SVG from somewhere else and see if it still chokes on that. It might be that the svg you are using is faulty.

**Comment by colin-marshall** [comment]
@adambundy I'm closing this out. If you have more information or if you want to share the SVG's that were causing it to choke, feel free to reopen.
