### ISSUE TITLE
Best practice for loading libraries ?

### ISSUE THREAD

**Issue by BBackerry** [olefredrik/FoundationPress#1218]
Hi,

So with Foundation 6 featuring webpack I've had to spend some time figuring out how to add external libraries. It seems easy and practical to load modules but I can't figure out how to add libraries that aren't packaged as modules or jQuery plugins.

Taking fancybox (installed from npm, but not packaged as a module and distributing css, not scss) as an example, I've had to add
```javascript
window.jQuery = $;
require('@fancyapps/fancybox/dist/jquery.fancybox');
```
to independant files using it (I don't really use app.js as I prefer to divide my code into multiple files and require them via `is_page`or `is_singular`...) which is okay, but then I've also had to add
```php
wp_enqueue_style( 'fancyboxcss', get_template_directory_uri() . '/dist/assets/static/css/jquery.fancybox.min.css', array() );
```

Is there a better way to do this (it would be better to load both css and js in the same place) ? I'm asking for jQuery plugins and more generally non-modules libraries

**Comment by BBackerry** [comment]
Sorry about the "bump" but it's weird to see no reply to such a simple question ? Is it not the place to ask something like this ? If it is, anyone who has built something with FoundationPress should be able to respond.

**Comment by colin-marshall** [comment]
@BBackerry the easiest way I can think of that you could do it is just include them via CDN in the `is_page` conditional. Then you don't have to mess around with the build system.

```php
if ( is_page ) {
wp_enqueue_style( 'fancyboxcss', 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css', array() );
}

**Comment by derweili** [comment]
wp_enqueue_script() is the best solution
https://developer.wordpress.org/reference/functions/wp_enqueue_script/
