### ISSUE TITLE
Breakpoints not working in scss

### ISSUE THREAD

**Issue by q4impact** [olefredrik/FoundationPress#1231]
When I add the scss it will not add the breakpoint, When I refresh and resize the page nothing happens. It looks like this breakpoint call is being ignored. Anyone know why this would happen?

 .left {
      @include grid-column(8);
      padding:0 32px;
      position: relative;
      background-size: cover;
      background: $light-grey;
      @include breakpoint(small) {
          @include grid-column(12);
      }
}

I am using the latest version of FoundationFress which uses Foundation 6.
I have the latest version of node installed.
npm is running.

**Comment by nitrokevin** [comment]
is it because you have declared the small breakpoint at 12, but you have already set small (by default) to 8, to see something happen, you need to change 
@include breakpoint(small) {

to 

@include breakpoint(medium) {

**Comment by q4impact** [comment]
I have tried changing @include breakpoint(medium) { 
and nothing happened. 
When I add in the the breakpoint in like below it works. Not sure why.
.left {
      @include grid-column(8);
      padding:0 32px;
      position: relative;
      background-size: cover;
      background: $light-grey;
      @include breakpoint(767px) {
          @include grid-column(12);
      }
}

**Comment by q4impact** [comment]
I have fixed this issue. Thanks for the help.
