### ISSUE TITLE
Motion ui is not working

### ISSUE THREAD

**Issue by q4impact** [olefredrik/FoundationPress#1235]
I am using the latest version of FoundationPress everything is up and running, but when i try to get a simple animation to work on a 

 <h1 class="animate">Title Of Product</h1>
the scss i am using to call in the mixin is below
 @include mui-fade(in, $duration, 5s);
I have also tried
  @include mui-fade(in);
and nothing happens. 

I also tried just adding the class into the h1 but that did noting.

Any help would be great. I really need to get this working. Thanks ahead of time.

**Comment by AmyGail** [comment]
I found this helpful (scroll down to ‘working with animations’
[https://www.creativebloq.com/web-design/create-custom-animations-motion-ui-21619210](url)

Also check the docs for tha parameters that each animation accepts. Fade only accepts 2 numbers, and for most cases, you probably don’t even need to use them as it fades from zero to full opacity by default.

from (Number) - Opacity to start at. (Default: 0)
to (Number) - Opacity to end at. (Default: 1)

[https://github.com/zurb/motion-ui/blob/master/docs/animations.md](url)

I hope this helps, you might want to visit the forum over at Foundation if you’re still stuck.

**Comment by q4impact** [comment]
I am working on using wow.js I have gone through the steps of npm install wow.js, I an not sure where to go from here. I have tried to using this  i

var wow = new WOW({
  boxClass: 'wow',
  animateClass: 'is-animating'
});

wow.init();

n the app.js file but I get WOW is not defined any help would be great.
