### ISSUE TITLE
Utility Classes MISSING

### ISSUE THREAD

**Issue by pcross1986** [olefredrik/FoundationPress#1238]
text-center works fine, but if I were to use "small-text-center" or "medium-text-center", it does not work.

Foundation mentions importing this....

@include foundation-prototype-text-utilities;

**Comment by pcross1986** [comment]
I apologize. And really the answer I was looking for, is the fact that Foundation had changed a while back.

What I was suppose to do is just use text-left for small screens, and medium-text-right for medium and up screens. Sorry again.

**Comment by colin-marshall** [comment]
@pcross1986 no worries! Thanks for editing your post. Closing this out.
