### ISSUE TITLE
Update jQuery Migrate to 3.x version to be compatible with jQuery

### ISSUE THREAD

**Issue by farlandlee** [olefredrik/FoundationPress#1243]
FoundationPress uses 1.x version of jQuery Migrate and it needs to be updated to 3.x version in order to be compatible with the version of jQuery enqueued with FoundationPress.

**Comment by colin-marshall** [comment]
Your PR _adds_ jQuery migrate, it doesn't update it. FoundationPress currently doesn't use jQuery migrate and I'm not sure why we would need it in there since there is nothing to migrate in a new FP project. If you need it otherwise,

**Comment by farlandlee** [comment]
Actually it does update it.  Since Wordpress 3.6 jQuery migrate is included by default in core.  That's why I deregister the default version and register the new version that is compatible with jQuery 3 as used in Foundation.  I could just enqueue the script and not list it as a dependency for foundation.js.

**Comment by JPOak** [comment]
When we initially wp_deregister jquery on line 43 it removes wp migrate as well I believe. I think that is what @colin-marshall may mean. FP doesn't use it.

**Comment by farlandlee** [comment]
@JPOak actually it doesn't.  I just created a clean wordpress install and added foundationpress and made it the active theme.  It has jQuery Migrate registered as version 1.4.1 which is not compatible with  jQuery 3.2.1 used in FoundationPress.  So any plugin that depends on jquery-migrate is going to throw errors when run in conjunction with foundationPress.  I think maybe what @colin-marshall was taking exception to is I made jquery-migrate a dependency of foundation.js which is does not actually need to be.  So I have changed my PR to simply deregister the old version of jquery-migrate and register, but not enqueue the correct version to use with jQuery 3.2.1.  That work?

**Comment by colin-marshall** [comment]
@farlandlee I just tested and deregistering jQuery also deregisters jQuery migrate. If I comment out the lines in FP which deregister jQuery and enqueue from the CDN, only then do I see jQuery migrate in the `<head>`.

**Comment by farlandlee** [comment]
You dequeued it, but didn’t deregister it. If you add
wp_enqueue_script(‘jquery-migrate’) to the theme you will see the old
version,1.4.1, gets added so if you want it to work, it will need to be
updated as I have done in the PR.

**Comment by colin-marshall** [comment]
@farlandlee ahh that's right, my bad. I don't do much with registering/enqueueing because I concatenate all my JS and CSS.

How about you change your PR to look like this:

```php
// Deregister the jquery version bundled with WordPress.
wp_deregister_script( 'jquery' );

// CDN hosted jQuery placed in the header, as some plugins require that jQuery is loaded in the header.
wp_enqueue_script( 'jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js', array(), '3.2.1', false );

// CDN hosted jQuery migrate for compatibility with jQuery 3.x
wp_register_script( 'jquery-migrate', '//code.jquery.com/jquery-migrate-3.0.1.min.js', array('jquery'), '3.0.1', false );

// Enqueue jQuery migrate. Uncomment the line below to enable.
// wp_enqueue_script( 'jquery-migrate' );

// Enqueue Foundation scripts
wp_enqueue_script( 'foundation', get_template_directory_uri() . '/dist/assets/js/' . foundationpress_asset_path( 'app.js' ), array( 'jquery' ), '2.10.4', true );
```

This way it's easier for the user to enable if they need it.

**Comment by farlandlee** [comment]
@colin-marshall done.

**Comment by colin-marshall** [comment]
@farlandlee thank you! Merged.
