### ISSUE TITLE
page.php while loop cleanup

### ISSUE THREAD

**Issue by dgobnto** [olefredrik/FoundationPress#1246]
A while ago there were a couple code cleanups concerning indentation and other inconsistencies.
#1178 #1173 

Despite everyone's best efforts, I believe the page.php _while_ loop still lacks a bit cleanup, for consistency with other files.

**Comment by esarantanen** [comment]
@dgobnto , just a note..
A while ago, Automattic  _s theme went thru a major cleanup: https://github.com/Automattic/_s/commit/b26b6ebfa4a92d82a69576e69aefe44192350635

**Comment by dgobnto** [comment]
@esarantanen Then apparently it's all the other files that need cleanup! ;)

**Comment by colin-marshall** [comment]
Feel free to submit a PR.

**Comment by dgobnto** [comment]
I would, but now I'm confused! 😆

Which markup should we follow?

I did a very quick research and [Wordpress PHP Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/) refers to this kind of markup/syntax:
```
<?php if ( have_posts() ) : ?>
    <?php while ( have_posts() ) : the_post(); ?>
        <!-- ... -->
    <?php endwhile; ?>
<?php endif; ?>
```

While Automattic's _s theme recent cleanup went towards:
```
<?php if ( have_posts() ) : ?>
	<?php
	/* Start the Loop */
	while ( have_posts() ) :
		the_post();
		get_template_part( 'template-parts/content', get_post_format() );
	endwhile;
endif;
?>
```
I prefer the former, though…

**Comment by pyrodie18** [comment]
I agree, the former is much easier to read.

**Comment by tiborp** [comment]
+1
