### ISSUE TITLE
Dropdown Menus not showing up on Internet Explorer

### ISSUE THREAD

**Issue by johnfrancisli** [olefredrik/FoundationPress#1247]
Experiencing this issue on a fresh install. I'm guessing something with the gulpfile.babel.js but just can't seem to find the issue.

**Reproduction:**
1. Fresh install of Foundation Press
2. Setup a menu system with a drop down
3. Test on Internet Explorer (11, not working but no error in console)
4. Set emulation on IE to 10, an error 
SCRIPT1014: Invalid character
app.js (106,105)

`  return Math.round((Math.pow(36, length + 1) - Math.random() * Math.pow(36, length))).toString(36).slice(1) + (namespace ? `-${namespace}` : '');
`
**OS & version:**
* Node version (node -v) [Node v4+ is required] : 6.9.5
* FoundationPress version (see line 3 in package.json):  2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.3

**Comment by aibrean** [comment]
I'm having the same issue.

**Comment by conorbarclay** [comment]
Just tested this on Windows 10, on IE11 and IE10 emulation and it worked as intended on both, no console errors. You're sure you're using the latest install of FP? There were some changes to the gulpfile in a recent PR.

**Comment by aibrean** [comment]
@conorbarclay that's likely the issue

**Comment by johnfrancisli** [comment]
I'll test out latest release and see if that issue still occurs.
