### ISSUE TITLE
jQuery error with Internet Explorer

### ISSUE THREAD

**Issue by GarySwift** [olefredrik/FoundationPress#1248]
**How can this bug be reproduced?**

1. Clean install (npm install and npm run build)
2. View on Internet Explorer 11

**What did you expect to happen?**
*app.js* to  be parsed without an error.

**What happened instead?**
Console log error 'jQuery is not defined'

**Please List the Following:**
* Windows 7 Home Edition
* Internet Explorer 11

**Summary**
I usually don't usually check IE anymore  as I don't even use Windows anymore. However this was pointed out to me and I believe there is an issue related to webpack and how it builds app.js.

This issue is only related to IE as far as I can tell. All other browsers are behaving as normal.

**Comment by GarySwift** [comment]
If anybody else is unfortunate enough to to be using **IE 11**, would you mind checking if a clean install of FoundationPress is parsing _app.js_ correctly.

I haven't expected all features to be on IE for a long time but breaking JavaScript on a clean install is a real problem for me. 

Thanks in advance.

**Comment by JPOak** [comment]
@GarySwift Yeah. I don't think the current version of FP works on Windows. You will want to try and make the changes discussed here: #1219 . Also, see my comment at the end about the interchange images on IE linked in another discussion.

**Comment by GarySwift** [comment]
Thank you @JPOak. I will try your suggestion.

**Comment by GarySwift** [comment]
I had to leave this issue for a while but I got back to it this morning. I spent a few hours trying to resolve this issue using various suggestions from other comment threads. 

Specifically I tried conorbarclay's forked `gulpfile.babel.js` from here https://github.com/olefredrik/FoundationPress/issues/1219#issuecomment-361328292 using the fix mentioned here https://github.com/olefredrik/FoundationPress/issues/1219#issuecomment-361344578. 

I was unable to resolve this issue. As far as I can tell, webpack is compiling the `app.js` in a way that is incompatible for widows.

I'm not talking about building on Windows. My dev environment is in OSX and I'm uploading a packaged version of a clean install onto a server. I then load the site on IE 11. All JavaScript is broken because of the this error.

This is a major issue for me and i am sad to say I may have to abandon using FoundationPress for the moment. I could live with features such Interchange but having JavaScript completely broken is a dealbreaker for me.

**Comment by dantahoua** [comment]
Just tested an install of FoundationPress compiled on MacOsX on IE 11... No problem there... Note that is a december 2017 version but it use webpack... I use all the package (sometime I remove stuff I do not use to minimize the size of js and css)...

**Comment by GarySwift** [comment]
Thanks @dantahoua 

I actually now think the issue was the crap version IE/WIndows I was using. I found some friends with IE and I did not have the issue. Sorry about that and thanks for everybody's help.
