### ISSUE TITLE
Footer Widgets xy grid stacking medium/small

### ISSUE THREAD

**Issue by squidzink** [olefredrik/FoundationPress#1251]
Even though there were changes made to how footer widgets should respond on medium and small breakpoints, I'm still not seeing the solution to the issue that was presented in #1180 and seemingly resolved in #1189. 

What am I missing? Foot widgets still do not expand as expected at medium and small breakpoints  even when classes are manually put into widget-areas.php

**Comment by JPOak** [comment]
@squidzink The footer works as expected I believe. It's pretty basic and left to the developer to do what they want with it. I never use it as is and normally add in different widget areas.

However, if you just want to add in different breakpoints etc. You can try the below and tweak what you want in _footer.scss

```
  section {
    @include xy-cell();

    @include breakpoint(large) {
      @include xy-cell(6); //or however you want them to look on large screens
    }

```

**Comment by JPOak** [comment]
@colin-marshall I wonder if we should add a default breakpoint to help clear up confusion with footer widgets on mobile.

Maybe something like:

```
  section {
    @include xy-cell();
    @include breakpoint(large) {
      @include xy-cell(auto);
    }
```

**Comment by squidzink** [comment]
@JPOak Thanks for the clarification. I'm still catching up on the xy grid. I'm good to go.

**Comment by colin-marshall** [comment]
@JPOak ya we forgot about that.

**Comment by squidzink** [comment]
Should I go ahead and close this one?
