### ISSUE TITLE
Error during running the app

### ISSUE THREAD

**Issue by PavanBisaralli** [olefredrik/FoundationPress#1252]
error code ELIFECYCLE
21 error errno 2
22 error angular_app@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
22 error Exit status 2
23 error Failed at the angular_app@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by colin-marshall** [comment]
I'm closing this as I don't believe this anything to do with FoundationPress.
