### ISSUE TITLE
sudo npm start hangs on service start

### ISSUE THREAD

**Issue by RohanKurane** [olefredrik/FoundationPress#1254]
I am running 'sudo npm start' on Ubuntu 16.04LTS and it hangs when it should start the web server.
From npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle CM-UI@0.1.0~prestart: CM-UI@0.1.0
6 silly lifecycle CM-UI@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle CM-UI@0.1.0~start: CM-UI@0.1.0
8 verbose lifecycle CM-UI@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle CM-UI@0.1.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/gui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle CM-UI@0.1.0~start: CWD: /home/ubuntu/gui
**11 silly lifecycle CM-UI@0.1.0~start: Args: [ '-c', 'node scripts/server.js' ]
12 silly lifecycle CM-UI@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle CM-UI@0.1.0~start: Failed to exec start script**
14 verbose stack Error: CM-UI@0.1.0 start: `node scripts/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid CM-UI@0.1.0
16 verbose cwd /home/ubuntu/gui
17 error Linux 4.4.0-1049-aws
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error CM-UI@0.1.0 start: `node scripts/server.js`
22 error Exit status 1
23 error Failed at the CM-UI@0.1.0 start script 'node scripts/server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the CM-UI package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node scripts/server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs CM-UI
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls CM-UI
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

How can I fix this ?  

I am connecting the server to port 8000.

**Comment by colin-marshall** [comment]
Closing this out, feel free to reopen if you feel I have done so in error, or you still need help.
