### ISSUE TITLE
PHP error when posting

### ISSUE THREAD

**Issue by sky1tech** [olefredrik/FoundationPress#1264]
When updating a post I received the following PHP error:

Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 in /srv/users/serverpilot/apps/xxxxxxx/public/wp-content/themes/xxxxxxx_2018-04-22_15-15/library/foundation.php on line 136

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/xxxxxxx/public/wp-content/themes/xxxxxxx_2018-04-22_15-15/library/foundation.php:136) in /srv/users/serverpilot/apps/xxxxxxx/public/wp-admin/post.php on line 198

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/xxxxxxx/public/wp-content/themes/xxxxxxx_2018-04-22_15-15/library/foundation.php:136) in /srv/users/serverpilot/apps/xxxxxxx/public/wp-includes/pluggable.php on line 1216

* macOS Sierra Version 10.12.6 (16G29)
* Node 6.9.5
* FoundationPress version 2.10.4

This occurred on the production server. The post updated correctly but still receive this error on each update. Did not do this before.

**Comment by colin-marshall** [comment]
@sky1tech is your `library/foundation.php` untouched? If so, line 136 is `$doc->loadHTML( $html );`. This is a part of a responsive video embed function. Does your post have a video embedded in it? 

Also, what version of WP are you on?

**Comment by pdfcorner1** [comment]
Hey, I had the same problem while installing a new plugin on my website http://pdfcorner.com. I tried many things, even I was unable to change my theme. Then I logged in to my serverpilot account and then downgraded the PHP version of my website. Again I have upgraded to my previous PHP version. Then Everything is now okay.

**Comment by colin-marshall** [comment]
Thanks for the input @pdfcorner1. I'm going to close this out since it appears to be inactive and most likely unrelated to FoundationPress. Feel free to reopen if you feel I have done so in error.
