### ISSUE TITLE
I can't find the Magellan navigation

### ISSUE THREAD

**Issue by mmoser-markl** [olefredrik/FoundationPress#1265]
I would like to use the [Magellan](https://foundation.zurb.com/sites/docs/magellan.html) navigation but I it seems to not be added in the latest version of FoundationPress. Has this intentionally left out?

Thanks.

**Comment by colin-marshall** [comment]
@mmoser-markl all JS components in Foundation are included by default in FoundationPress. Please fill out the issue template to show us what code you are using that is not working. Also, you have to add your own styles to the Magellan `.is-active` class to make the menu item appear differently.

**Comment by mmoser-markl** [comment]
@colin-marshall  - Thanks for the tip. You're right, I haven't included the css to the is-active class that's why I can't find the difference. I also, I thought Magellan should be included to the app,scss to be able to use it.

**Comment by colin-marshall** [comment]
@mmoser-markl it's not included in regular Foundation's SCSS either. I think the reasoning is because the `.is-active` class can be used in a lot of different ways, not just changing a background color, for example.
