### ISSUE TITLE
use FoundationPress without git

### ISSUE THREAD

**Issue by wgruenberger** [olefredrik/FoundationPress#1267]
Hi,

my Wordpress-Installation is living in a restricted environment where i'm not root.
I also plan to update Foundation manually because we will deploy via svn and i don't want to mess with 2 different version controls

So i uploaded FoundationPress via FTP changed to the folder, ran 
`npm install` 
and got:
`npm ERR! code ENOGIT`
`npm ERR! No git binary found in $PATH`
`npm ERR! `
`npm ERR! Failed using git.`
`npm ERR! Please check if you have git installed and in your PATH.`

Do i have to ask our root to install git or is there a way around it?

**Comment by wgruenberger** [comment]
@colin-marshall Yes, that's what i'm going to do, thx!

**Comment by colin-marshall** [comment]
Closing this out.
