### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by aswathykrishna18** [olefredrik/FoundationPress#1268]
I tried to install mean by running "npm install && npm start"
But I got this error

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aswathy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v8.11.1
npm ERR! npm  v4.2.0
npm ERR! file C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm ERR! path C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

npm ERR! node-sass@4.9.0 install: `node scripts/install.js`
npm ERR! spawn C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

[2018-04-30T08_01_01_824Z-debug.log](https://github.com/olefredrik/FoundationPress/files/1959863/2018-04-30T08_01_01_824Z-debug.log)

**Comment by nbeers22** [comment]
the readme states: This project requires Node.js v4.x.x to v6.11.x to be installed on your machine

your error clearly states you are using v8.11.1

You should read the requirements of the project before posting this like it's an issue with the project

**Comment by colin-marshall** [comment]
@nbeers22 the Readme is outdated.

@aswathykrishna18 please run `npm install` and `npm start` separately. Let us know which command gives you the error and copy the output of your terminal instead of providing the log. Thanks.

**Comment by pixelbrad** [comment]
@aswathykrishna18 I've run into the same issue personally. My solution? Run your command line/powershell as an administrator and then run `npm install`.

**Comment by colin-marshall** [comment]
Closing this. Feel free to reopen if you still need help.
