### ISSUE TITLE
Question from a complete noob

### ISSUE THREAD

**Issue by m-id** [olefredrik/FoundationPress#1271]
Hello,

I hope someone will be able to help. 

I'm looking to get foundationpress 6 starter theme with unminified foundation.css 

Templates which I downloaded come with scss file, I need a simple fondation.css which I will be able to modify. 

I tried using NPM commands but I'm getting errors.

If someone has a theme with unminified foundation.css  that could send me I would be grateful.

Cheers

**Comment by colin-marshall** [comment]
@m-id what commands did you try and what were the errors?

**Comment by m-id** [comment]
I ve managed to get around the problem by reinstalling all components on another laptop and it seemed to work,

Thanks for your help.
