### ISSUE TITLE
Missing elements?

### ISSUE THREAD

**Issue by chrisyoong-golin** [olefredrik/FoundationPress#1273]
**How can this bug be reproduced?**

1. Step one

Trying to use 

```
$(document).foundation();
$('.title-bar').on('sticky.zf.stuckto:top', function(){
  $(this).addClass('shrink');
}).on('sticky.zf.unstuckfrom:top', function(){
  $(this).removeClass('shrink');
})

```
Doesn't work.  It appears so many elements from Foundation are missing.  How can I ensure everything from 6.4.3 are included?

2. Step two
3. Step three

**What did you expect to happen?**

I expect to use Foundation 6 out of the box but just integrated into Wordpress

**What happened instead?**

It's like only part of Foundation are in place, i'm confused to what is present and what is not.

**Please List the Following:**
* OS & version: macOS
* Node version (node -v) [Node v4+ is required] :  v8.11.2
* FoundationPress version (see line 3 in package.json):   "version": "2.10.4"
* Foundation version (found in `node_modules/foundation-sites/package.json`) :

**Comment by chrisyoong-golin** [comment]
i also tired to use
` rem-calc `
and this was missing

**Comment by colin-marshall** [comment]
@chrisyoong-golin where and how are you using `rem-calc`? It's included in Foundation by default so something is not right.

Also, are there any errors in the console related to your Sticky event handlers?

**Comment by chrisyoong-golin** [comment]
@colin-marshall I discovered that FoundationPress seemed to omit some for core functions / mixins when compared to the latest Foundation 6.4.3 Build (either that or they're located / enabled somewhere else?)

I've found myself manually adding these files gradually as and when I need them to the `node_modules/foundation-sites/scss/` folder.
e.g. I've added 
`util, xy-grid' to that folder

I'm just a little confused.  I assumed FoundationPress had everything 6.4.3 had just within a WordPress setup but I don't this this assumption is right?

**Comment by colin-marshall** [comment]
@chrisyoong-golin that assumption is 100% right. Something is wrong with your install. `node_modules/foundation-sites/` will ALWAYS have everything in it already as that is the Foundation Sites package. If it's missing stuff you should do a `rm -rf node_modules` and run `npm install` again.

**Comment by colin-marshall** [comment]
Closing this. Feel free to reopen if you still need help.
