### ISSUE TITLE
help me fix

### ISSUE THREAD

**Issue by israelkingz** [olefredrik/FoundationPress#1276]
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Dell\AppData\Roaming\npm-cache_logs\2017-09-23T12_07_34_6 08Z-debug.log

**Comment by colin-marshall** [comment]
Please edit your issue with the required information from the issue template. This tells us nothing.

**Comment by colin-marshall** [comment]
Closing this out, feel free to reopen if you feel I have done so in error, or you still need help.
