### ISSUE TITLE
Watch task for changes on SVG not working

### ISSUE THREAD

**Issue by derweili** [olefredrik/FoundationPress#1280]
**How can this bug be reproduced?**

1. Start the gulp watch task
2. When the watch task ist running, place a new or edit an existing svg file inside the images folder

**What did you expect to happen?**
I expected the svg to be copied to the assets folder and the browser should reload after successful copy process.

**What happened instead?**
The watch task does not watch for changes on svg files. They are only copied once when starting the watch task by the copy task but when a new svg file ist added later while the watch task is already running they are not copied anymore.

**Please List the Following:**
* OS & version: macOS 10.13.3
* Node version (node -v) [Node v4+ is required] : v8.10.0 but also testet with v6.13.0
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.3

**Comment by derweili** [comment]
This may not be the most sexy solution but it works well. 
Maybe there is a gulp expert who can solve this issue in a cleaner way.

**Comment by olefredrik** [comment]
Fixed in https://github.com/olefredrik/FoundationPress/pull/1281
