### ISSUE TITLE
Don't use my license Badge

### ISSUE THREAD

**Issue by meodai** [olefredrik/FoundationPress#1283]
What about generating you own badge.?

There are tons of forks out there that use the license of my color-list. Would love to change my license to a closed one just to fuck with you and all your forks :P

https://img.shields.io/npm/l/color-name-list.svg?colorB=ff77b4

Just get the one you want here: https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba

**Comment by colin-marshall** [comment]
Thanks for updating @derweili
