### ISSUE TITLE
how to include a new js library

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#1284]
@colin-marshall 

Hey Colin, been away a while and I'm not following the gulp procedure (didn't this used to be grunt?)

I have included a library as a dependency in package.json, so the package exists in node_modules
```
  "dependencies": {
     ... 
    "intl-tel-input": "^12.3.0",
     ... 
```

How do I get it included or compiled into app.js so that I will be able to call on it later.
```
<script>
  $("#phone").intlTelInput();
</script>
```

**Comment by ChristofLee** [comment]
Hey @jimlongo56 

Try adding `import intlTelInput from 'intl-tel-input';` to your app.js.

This should find the script if it's installed by npm.

I've tried and it works for me. 
In regards to paths, Webpack does most of the work for you.

Hope this helps and if you need more information, let me know.

**Comment by jimlongo56** [comment]
Thanks @ChristofLee that did compile it into app.js, but I think the fact it's in the footer caused the error ".intlTelInput() is not a function", but importing from cdnjs in enqueue-scripts worked.

`wp_enqueue_script( 'form-validation-intl-tel', '//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.3.0/js/intlTelInput.min.js', array( 'jquery' ), '12.3.0', false );`

Are you using this library?

**Comment by ChristofLee** [comment]
My steps to get it working were:
- `npm install intl-tel-input --save-dev`
- Add `import intlTelInput from 'intl-tel-input';` to app.js
- Add `$('#phone').intlTelInput();` at the bottom of app.js

This was running on html copied from the examples on the NPM package page.

I didn't need to use a CDN, or enqueue any scripts. This was all done on a fresh install.

**Comment by jimlongo56** [comment]
And did you get validation working?

**Comment by pixelbrad** [comment]
I ran into a similar issue, with a different JS library. I don't understand enough about installing libraries from npm and using them in my own projects. My solution may not be elegant, but here's what I did:

1. Download the library in question using your browser.
2. Move the JS library to `src/assets/js/vendor/`
3. Near the top of `app.js`, write `import ./vendor/library-name.js`

That may work for some libraries and may not work for others, I don't know the differences well enough. This is what I had to do with Slick.js (awesome slider library if you've never heard of it). While Slick has an NPM package, I could not, for the life of me, get it working any other way. /shrug

**Comment by jimlongo56** [comment]
Yes I have used Slick, it's awesome.  I suspect web pack is messing up some javascript if you try to append it to app.js.

In the end I loaded the main library from a cdn 
		`wp_enqueue_script( 'form-validation-intl-tel', '//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.3.0/js/intlTelInput.min.js', array( 'jquery' ), '12.3.0', false );`

and loaded the utils.js from a cdn, using the javascript `utils option`.

```
telInput.intlTelInput({
            utilsScript: "//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.3.0/js/utils.js",
})
```
