### ISSUE TITLE
svg files not working in safari browser 

### ISSUE THREAD

**Issue by DikshaTagra** [olefredrik/FoundationPress#1288]
in my site svg files not working in safari browser. svg file load properly but something is wrong with svg image layers. http://prntscr.com/k0cl24
here is my site link http://varsitycart.presentation.site/index.php?route=design/patch
thanks.

**Comment by derweili** [comment]
Can't see a difference. Probably that's not an issue with FoundationPress itself but an issue with svg browser support in Safari.

**Comment by colin-marshall** [comment]
Ya I don't believe this is a FoundationPress problem. Closing, feel free to reopen if you feel I have closed in error.
