### ISSUE TITLE
Adding function checks to make FoundationPress more Child Template friendly.

### ISSUE THREAD

**Issue by dotmagic** [olefredrik/FoundationPress#129]
I would welcome if the library functions add some checks for previous defined function. This allows Child Theme developers to easy overwrite functions without deregister in child theme or uncomment in parent theme. It's just a suggestion.

Example for: /library/widget-areas.php
```PHP
if ( ! function_exists( 'foundationpress_sidebar_widgets' ) ):
  function foundationpress_sidebar_widgets() {
    // Code
  }
endif;
```

**Comment by shoaibik** [comment]
+1

**Comment by iamseangrant** [comment]
+1

**Comment by themestechnology** [comment]
I have done a pull request to sort this.

**Comment by olefredrik** [comment]
Merged https://github.com/olefredrik/FoundationPress/pull/198
