### ISSUE TITLE
What's the recommended workflow from local to dev?

### ISSUE THREAD

**Issue by roborracle** [olefredrik/FoundationPress#1290]
I love FoundationPress and have been using it for a while, but it seems, unless I'm wrong, that the preferred method of working with this theme from a development perspective has evolved over time and I'm struggling to figure out the best way to work with it. I've got no issues working with Sass, or any of the template files. My issue is how to work with it between local and development servers, which in my case, are two separate places. 

How do you recommend setting up FP within a larger WordPress repository? We keep more than just the wp-content folder in our repositories, so how would you recommend that we set things up so that we can track our overall site? I've had to remove your .git directory more often than not in order to get it to track the way we want, but that obviously breaks connectivity with the main FP repo, so I'd love to hear how you think we should set this up.

This question is similar, but slightly different: How do recommend moving things between local and dev? It looks like at this time the preferred method is to package it up, log in to the WP dashboard then install the theme, but that's very cumbersome in my experience. We do our development on multiple different MAMP server installs on local machines, then we push to the repository, then pull to the dev server from our repository. This doesn't seem very efficient, so I'd love to hear how you good people are handlign your workflow. What do you recommend?

**Comment by nitrokevin** [comment]
Personally I package the first build, but further changes after that are just pushed out via ftp

**Comment by JPOak** [comment]
@roborracle I don't keep tracking the FP repo in my projects. I just delete and init a new repo.

As for deployment, just because it is easy, I can manage things beyond WP on it, and I can give access levels to other people as needed, I like services like DeployHQ. I create a development branch to deploy to staging and a master branch that deploys to production. You can even setup pre deployment processes if you want such as building sass on their servers if you don't want to keep binary stuff in your repo. However, I do.

**Comment by roborracle** [comment]
@JPOak yea, that's what I've been doing, but figured that there would be a better/recommended way to do this. By removing that git repo do you not eliminate the ability to update it?

**Comment by JPOak** [comment]
@roborracle unless you are in a parent/child theme setup i'm not sure why you would need to update. In this discussion #1097, we discussed whether FP was a starter or parent theme. There were also people that probably weren't happy that it went away from it being more of a parent theme.

**Comment by roborracle** [comment]
We don't do the complete build at one time. We create and develop in stages, review, etc. that's why we do it the way we do, but I get your point about updating. I guess it doesn't entirely make sense if you've got versions from 5 > 6, but I like to keep up to date in the instance that there are updates we'd like to have in place within a 6.x, etc. type release.
