### ISSUE TITLE
Feature request: remove comments.php template

### ISSUE THREAD

**Issue by derweili** [olefredrik/FoundationPress#1291]
The FoundationPress theme comes with a custom comment form template ([comments.php](https://github.com/olefredrik/FoundationPress/blob/master/comments.php)) that overwrites the wordpress default comment form with harcoded input fields.
Since is does not include any Foundation specific adjustments/functions  I'm wondering if the custom template is really necassary.

The custom template has no advantages, but instead some disadvantages:
- The Comment form does not automatically get updated when WordPress itself makes changes on the default comment form
- Plugins that modify the Comment Form (adding, modifying or removing fields) don't work with this custom template.
- As mentioned in #1289 most of the users in the EU use several plugins that modify the Comments Forms to comply with the [GDPR](https://www.wpgdprc.com/faq/). These Plugins do not work with the custom comments.php template

For these reasons I would recommend to remove the comments.php from FoundationPress.

**Comment by dantahoua** [comment]
Are you sure there is nothing involved between comments and Foundation? Because there is the 'library/class-foundationpress-comments.php' file... But when I look at it, seems there is no reference to any Foundation class...
So I second that also, let's keeps the comment to wordpress or to the user who want to customize them...

**Comment by dantahoua** [comment]
Just encounter a problem with comments.php... For the first time I use it! And there is a pluguin who is supposed to add a ReCaptcha on the comment form on the website. Without comments.php it works, but if I use the FoundationPress comments.php, it do not works... It seems we need to use the special comment filter and function to be sure everything works ok...

**Comment by derweili** [comment]
@dantahoua I think the best way ist to keep the `comments.php` but to replace the hardcoded comment form with the `comment_form();` template tag

This template tag includes all necessary hooks to support third party plugins.

**Comment by derweili** [comment]
resolved by #1296
