### ISSUE TITLE
Comments pagination missing

### ISSUE THREAD

**Issue by derweili** [olefredrik/FoundationPress#1295]
In the discussion settings of WordPress you can specify how many Comments should be visible per page.
To support this, the comments pagination must be included into the comments.php template file.
This template tag is missing in FoundaitonPress.

**How can this bug be reproduced?**

1. Add two comments to a single post/page
2. Go to WP Discussion settings and set the top level comments per page to `1`
3. Look at the post in the fronend. Only one comment is visible

**What did you expect to happen?**
There sould be a pagination 

**What happened instead?**
No pagination shown. Only the first page is visible.

**Please List the Following:**
* FoundationPress version "2.10.4":

**Comment by colin-marshall** [comment]
I would prefer if we could style comment pagination with Foundation pagination styles. What are our options here? Do we have to use a custom function to do this?

**Comment by derweili** [comment]
solved by #1296
