### ISSUE TITLE
Problem in offcanvas foundation press menu

### ISSUE THREAD

**Issue by di3gof3rn4ndes** [olefredrik/FoundationPress#130]
Hello!
I'm having problem in offcanvas foundation press menu, does not work when you click the menu item, not going anywhere and could not find the error
site:http://www.maispiscinas.com.br
![offcanvas](https://cloud.githubusercontent.com/assets/9196553/4613572/3a3db9be-52d7-11e4-9392-1152649baa5c.jpg)

Thanks!!!

**Comment by robjekt** [comment]
I found a solution to this today after reading through the Foundation docs for Off-Canvas. You need to reflow after document load:

$(document).foundation('offcanvas', 'reflow');
http://foundation.zurb.com/docs/components/offcanvas.html

Must be something to do with how the menus are built into the page? Anyway, happy days now its fixed :dancer:
