### ISSUE TITLE
Promise in IE not defined

### ISSUE THREAD

**Issue by maciekgrzybek** [olefredrik/FoundationPress#1300]
**How can this bug be reproduced?**

1. Install Axios
`import axios from 'axios';`
2. Fetch some data
`    axios
      .get(urlRequest)
      .then((response) => {
        let temp = parseInt(response.data.main.temp);
        let weather = response.data.weather[0].id;
        showWeather(temp, weather, el);
      })
      .catch((error) => {
        console.log(error);
      });`

**What did you expect to happen?**
Should return correct data from API

**What happened instead?**
Promise is not defined in IE11

**Please List the Following:**
* OS & version:  macOS 10.13.3 - tested on BrowserStack and Windows 10
* Node version  : 8.9.4
* FoundationPress version : 2.10.4
* Foundation version  : 6.4.3

**Comment by colin-marshall** [comment]
You need to add the polyfill according to the [Axios repo](https://github.com/axios/axios).

> axios depends on a native ES6 Promise implementation to be supported. If your environment doesn't support ES6 Promises, you can [polyfill](https://github.com/jakearchibald/es6-promise).

**Source:** https://github.com/axios/axios#promises
