### ISSUE TITLE
New and old build getting unexpected token 'import' error

### ISSUE THREAD

**Issue by linuxbastard** [olefredrik/FoundationPress#1302]
I just cloned an old (less than 1 month) project and tried to do an `npm run build` and got the unexpected token 'import' error. I did a new clone and got the same thing.

I was just on this project on the same computer yesterday.

**How can this bug be reproduced?**

1. Step one
clone foundationpress and run npm install. then try to run npm ruin build

**What did you expect to happen?**
will get an initial build of theme

**What happened instead?**
got an error
`$ npm run build`

`> foundationpress@2.10.4 build /home/linuxbastard/projects/FoundationPress`
`> gulp build --production`

`[07:11:40] Failed to load external module @babel/register`
`[07:11:40] Failed to load external module babel-register`
`[07:11:40] Failed to load external module babel-core/register`
`[07:11:40] Failed to load external module babel/register`
`/home/linuxbastard/projects/FoundationPress/gulpfile.babel.js:3`
`import plugins       from 'gulp-load-plugins';`
`^^^^^^`

`SyntaxError: Unexpected token import`
    `at createScript (vm.js:56:10)`
   ` at Object.runInThisContext (vm.js:97:10)`
   ` at Module._compile (module.js:549:28)`
   ` at Object.Module._extensions..js (module.js:586:10)`
    `at Module.load (module.js:494:32)`
    `at tryModuleLoad (module.js:453:12)`
   ` at Function.Module._load (module.js:445:3)`
    `at Module.require (module.js:504:17)`
   ` at require (internal/module.js:20:19)`
    `at execute (/home/linuxbastard/.nvm/versions/node/v6.14.3/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:36:18)`

`npm ERR! Linux 4.15.0-32-generic`
`npm ERR! argv "/home/linuxbastard/.nvm/versions/node/v6.14.3/bin/node" "/home/linuxbastard/.nvm/versions/node/v6.14.3/bin/npm" "run" "build"`
`npm ERR! node v6.14.3`
`npm ERR! npm  v3.10.10`
`npm ERR! code ELIFECYCLE`
`npm ERR! foundationpress@2.10.4 build: `gulp build --production`
`npm ERR! Exit status 1
`

**Please List the Following:**
* OS & version: Ubuntu 18.04
* Node version (node -v) [Node v4+ is required] : Node 6.14.3 and 8.11.4 (tried both)
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.3

**Comment by linuxbastard** [comment]
Still getting the same issue after the steps above.

I've also uninstalled gulp globally and reinstalled into the project only. The only difference now is that I see only 3 failed babel register attempts instead of 4.

https://gist.github.com/linuxbastard/804722860869437b0e683a39008db6cb

**Comment by conorbarclay** [comment]
This may seem like a silly question, but is there a `.babelrc` file in the project root, or was it modified in any way from what comes default in the repo?

**Comment by linuxbastard** [comment]
@conorbarclay .babelrc is present on a new clone, and also present on my old themes.
Here is the package.json after I do an npm install. https://gist.github.com/linuxbastard/05179fd4f34bb6e6956b0a2d99314a85

My errors have gone away after I removed all versions of node, removed and reinstalled nvm, installed only node 8.11.4/npm 6.4.0 and did a fresh clone. Then I did `npm install` and `npm start` on the new clone and when that succeeded, I copied over the node_modules and package.json to the old themes I was working on, after I did the steps from @colin-marshall  above.

I have no idea why that worked, but I'm happy that it did. I tried just copying the node_modules folder on their own, but I was getting errors, probably because my old package.json wasn't the same as what packages were in my node_modules folder.

I did not need to install gulp separately after the re-install, so it looks like having different node versions, specifically 6.14.3 and 8.11.4, seems to have messed gulp up. (I'm only guessing).

Anyway, I am marking this one as solved, and is probably only applicable to my setup.

**Comment by colin-marshall** [comment]
> I tried just copying the node_modules folder on their own

Never do this. Whenever you move a project to a new environment or switch node versions you must delete and reinstall the `node_modules` directory. It's only safe to move the `node_modules` directory when you're just moving it to a different directory on the same environment.

Anyways, glad you're back up and running!
