### ISSUE TITLE
Uglify error

### ISSUE THREAD

**Issue by dmcgrew** [olefredrik/FoundationPress#1303]
Not sure why I'm getting this error.. **SyntaxError: Unexpected token: name (SwapAnimation)'** 

I've read that it might have something to do with Webpack or Babel not compiling to es2015, but es2015 is set in my babelrc file. I haven't touched any of the default FP stuff. 

I'm getting the error when I run "npm run build."

Here's the full output..

https://pastebin.com/6dwDBVUi

**Comment by colin-marshall** [comment]
I replied in the other thread first, but let’s continue this conversation here.

Does this happen on a clean/fresh install and what version of Node are you on?

**Comment by dmcgrew** [comment]
It does not happen on a fresh/clean install. It seems to get tripped up on something with the Shopify Draggable library (https://github.com/Shopify/draggable).  As soon as I import this in my app.js the uglify doesn't like it. I know this might be an issue with Shopify Draggable but if you can point me in the direction of what might be wrong or how to fix it, that would be awesome!

**Comment by conorbarclay** [comment]
Try importing from their pre-transpiled ES5 lib:

`import Draggable from '@shopify/draggable/lib/es5/draggable';`

Worked fine for me on a fresh install of FP, on Node 6.14.3.

**Comment by dmcgrew** [comment]
Thanks! I had to do this since I'm using some of their other plugins..

`import {Draggable, Sortable, Plugins, SwapAnimation} from '@shopify/draggable/lib/es5/draggable.bundle';`

**Comment by colin-marshall** [comment]
Thanks @conorbarclay! Closing this out now.
