### ISSUE TITLE
How do I finalize the theme for upload in WP Dashboard?

### ISSUE THREAD

**Issue by AngelaStucky** [olefredrik/FoundationPress#1305]
I ran my first footer.scss edit - just a quick background color change - to see if I can affect the theme and upload it. Command line is watching when I make edits, but when I typed npm run build and npm run package, nothing happened. Perhaps I've missed something. I'm very new to all of this.

* OS & version: High Sierra 10.13.6
* Node version (node -v) [Node v4+ is required] : Node 8.12.0
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.3

**Comment by AngelaStucky** [comment]
So, update - I installed MAMP, so I can see that even though I'm not seeing a result from npm run build and npm run package, the css file is being changed by the scss because i am running npm start. I am still a little confused though, about how the final theme package will look. I'm assuming that I won't need everything that's in my FoundationPress folder that I cloned from github. Is that correct? Thank you so much to whoever can help me!

**Comment by matt-antone** [comment]
I've used this and it works great. Just upload the resulting zip file via the "Add Theme" button on the themes page on your production or staging WordPress installation.

From the readme:

To create a .zip file of your theme, run:

npm run package

Running this command will build and minify the theme's assets and place a .zip archive of the theme in the packaged directory. This excludes the developer files/directories from your theme like /node_modules, /src, etc. to keep the theme lightweight for transferring the theme to a staging or production server.

**Comment by AngelaStucky** [comment]
Hi Matt, thank you! I am now having two problems - one is that when I'm writing the SASS with "npm start" running, it says in my terminal that it's changing the css file, but it's not in fact actually changing it. I'm not sure what I'm doing wrong here. Also, when I run npm run package, nothing happens. No zip file is created.

**Comment by matt-antone** [comment]
ah. I see what your missing. You need to incorporate your all the commands into your workflow.

`npm start` compiles the scss and injects the styles into you browser via BrowserSync

you need to run `npm build` in order to see the updates on your dev server without BrowserSync.

when your ready to publish your theme you can `npm run package`

**Comment by AngelaStucky** [comment]
Do I run `npm `build` or `np run build`?

**Comment by matt-antone** [comment]
I've gotten the same results either way.

**Comment by AngelaStucky** [comment]
Yes, I'm still seeing that even though my terminal says
`[10:49:14]` File src/assets/scss/modules/_footer.scss changed.
[10:49:14] Starting 'sass'...
[Browsersync] 1 file changed (app.css)
[10:49:15] Finished 'sass' after 852 ms
[10:49:42] Starting 'copy'...
[10:49:42] Finished 'copy' after 12 ms`
It's still not compiling the sass into the css, even though I did run `npm run build`

**Comment by AngelaStucky** [comment]
At least, I'm not seeing it in my browser, and the file in finder does not have a timestamp to say that it's changed.

**Comment by matt-antone** [comment]
OK. I just fired up my dev server. Ran `npm build`. I show the file has not been updated in the Finder, and couln't see the changes. Cleared my browser cache and viola. Does clearing browser cache help?
I think because the date isn't changing in the finder, you're being served a cached file.

**Comment by AngelaStucky** [comment]
Oh my gosh you're right! I'm doing it! *winning at liiiiiiife*
THANK YOU!

**Comment by conorbarclay** [comment]
@AngelaStucky What browser are you using? In Chrome's dev tools, there is an option in the settings to disable the browser cache while you have the inspector window open. Super handy!

**Comment by matt-antone** [comment]
yeah. but then I always seem to forget to turn that off, so the rest of the interwebs are so slow.

you may want to look into using Vagrants instead of MAMP. I've found that it's much easier to replicate your production server.

I use this exclusively for the last 3 years: https://varyingvagrantvagrants.org

**Comment by conorbarclay** [comment]
> yeah. but then I always seem to forget to turn that off, so the rest of the interwebs are so slow.

AFAIK, that setting is only in effect while your dev tools are open. Surely you're not doing your normal browsing with them open ALL the time.

**Comment by AngelaStucky** [comment]
I am using Chrome. Thank you, that's helpful! I set it to disable cache when Dev Tools is open, and it's working great. I will also check out Vagrants.
