### ISSUE TITLE
Error during second installation Git checkout fail

### ISSUE THREAD

**Issue by RonEarl** [olefredrik/FoundationPress#1315]
Hi,

I've used the FP 5 in the past, and recently upgraded a personal site to FP 6. Installed an iteration of it on my work computer and was happy with the progress that I wanted to utilize FP 6 for a work project.

So I went through the steps again.

$ cd my-wordpress-folder/wp-content/themes/
$ git clone https://github.com/olefredrik/FoundationPress.git
$ cd FoundationPress
$ npm install

Instead of successfully installing like the previous project it errored out, producing the following log errors:

15 verbose stack Error: Command failed: C:\Program Files\Git\cmd\git.EXE checkout 4.0
15 verbose stack error: pathspec '4.0' did not match any file(s) known to git.
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at ChildProcess.emit (events.js:214:7)
15 verbose stack     at maybeClose (internal/child_process.js:925:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
16 verbose cwd C:\websites\hdmedia\wp-content\themes\FP-HDMedia
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
19 verbose node v8.11.1
20 verbose npm  v5.6.0
21 error code 1
22 error Command failed: C:\Program Files\Git\cmd\git.EXE checkout 4.0
22 error error: pathspec '4.0' did not match any file(s) known to git.

I'm running:

* OS & version: Windows 7 Ultimate/NT
* Node version (node -v) [Node v4+ is required] : 5.6.0
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : Install did not complete.
* Git version: 2.19.1.windows.1

I can't understand why there is an issue now. The previous installation was smooth.

Any insight is appreciated.

Thank you.

-Ron

**Comment by mark1187** [comment]
This should fix that issue: https://github.com/olefredrik/FoundationPress/issues/1316#issuecomment-432320509
