### ISSUE TITLE
Foundation 6.5 Release..

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1318]
I was checking into FoundationPress for an upcoming project and was having some deprecation notices related to Foundation. This made me go look into possibly updating Foundation, which made me see that a major version is about to be released. Thoughts on updating? I can help test etc. 

Just wondering if there is interest or hold off for a bit. Anybody already merge it?

https://github.com/zurb/foundation-sites/pull/11551

**Comment by DanielRuf** [comment]
Hi @JPOak, there are already some using the latest RC release.
You can generally checkout the branch and test a fresh build.

I suggest waiting until it is released as we'll likely add some more commits.

**Comment by JPOak** [comment]
@DanielRuf Yeah, I will probably just give it a whirl. Thanks.

**Comment by dgobnto** [comment]
Now that Foundation 6.5.0 has been released are there any plans on updating FoundationPress?
