### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by mark1187** [olefredrik/FoundationPress#1320]
Hey,

I installed a fresh version of FoundationPress and when I tried to install npm I was presented with many errors. Currently these are the errors I am seeing:

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:200:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:862:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
npm WARN addRemoteGit  gulpjs/gulp#4.0 resetting remote /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801 because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm ERR! git clone --template=/Users/mark/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: Cloning into bare repository '/Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801'...
npm ERR! git clone --template=/Users/mark/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: git@github.com: Permission denied (publickey).
npm ERR! git clone --template=/Users/mark/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/mark/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: 
npm ERR! git clone --template=/Users/mark/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/mark/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: and the repository exists.
npm ERR! code 128
npm ERR! Command failed: git clone --template=/Users/mark/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801
npm ERR! Cloning into bare repository '/Users/mark/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801'...
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mark/.npm/_logs/2018-10-25T23_03_16_426Z-debug.log

Does anyone know what is going on?

**Comment by mark1187** [comment]
After reading through a few other issues that were posted I have found the solution:

in package.json changing line 42 from "gulp": "gulpjs/gulp#4.0", to "gulp": "4.0" fixed it.

**Comment by cdriscoll66** [comment]
Problem for me too... Thanks for the solve.

**Comment by samirwin** [comment]
@mark1187 thanks for posting this. You my friend are a legend.

**Comment by samirwin** [comment]
@mark1187 you are a legend. Thanks for posting this.

**Comment by redietGirma** [comment]
Yeap. Works for me too. Thanks😊
