### ISSUE TITLE
can't run npm install on Cent OS 7 - node v.6.14.4

### ISSUE THREAD

**Issue by valerymihaylov** [olefredrik/FoundationPress#1323]
Hello, please help me.

when run npm install i get this error

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: Permission denied (publickey).
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: fatal: Could not read from remote repository.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: Please make sure you have the correct access rights
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801: and the repository exists.
npm ERR! Linux 3.10.0-862.9.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-7c06e801
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/wp-content/themes/FoundationPress/npm-debug.log

WHAT TO DO?

OS: CentOS 7

**Comment by Mathster0598** [comment]
What's the status of this issue? I'm having similar problems

**Comment by derweili** [comment]
@valerymihaylov @Mathster0598 This is an error with gulp
See here: #1353

You have to change the gulp version in your package.json to `"^4.0"`
https://github.com/olefredrik/FoundationPress/blob/1f701d98ce0a7539317e63b24dce0f199c0602f5/package.json#L42
