### ISSUE TITLE
Kitchen Sink Components issues

### ISSUE THREAD

**Issue by youriwims** [olefredrik/FoundationPress#1324]
Hi everyone,
I know it's probably a silly question but, I can't seem to include the kitchen sink components properly. I've used Foundation quite a few times, but this is my first time working with FoundationPress. I've registered my nav and created it in the wp-admin. I'm trying to accomplish a drop down menu at desktop and off-canvas on mobile. How exactly would I accomplish this?
Thanks in advance!

**Comment by mattbag** [comment]
You need to assign the nav as primary I think. You will see those 2 navs have the 2 different and separated markup. There might be an extra setting in the customise panel to have of no the off canvas.

**Comment by derweili** [comment]
You have to create a new Menu in the WordPress Dashboard unter Appearance > Menus
Then assign the menu to the position "TopBar Right"

Now you should see you menu on desktop.
 
To enable the off-canvas menu:
1. Go To *Appearence > Customize > Mobile Menu Settings > Mobile navigation layout.*
2. Then select *Offcanvas*
3. Publish Changes
