### ISSUE TITLE
Page rendering problems

### ISSUE THREAD

**Issue by massprogressive** [olefredrik/FoundationPress#1326]
I've got a problem when I'm opening website on a mobile devices, sometimes its ok, sometimes not.

If I switch WP to default theme all works fine. What can cause this issue?

![img_2391](https://user-images.githubusercontent.com/18536583/47768630-91670400-dce1-11e8-8fb3-1d98441d93a0.PNG)
![img_2392](https://user-images.githubusercontent.com/18536583/47768631-91670400-dce1-11e8-99e3-aee0aa0b89e9.PNG)

**Comment by mattbag** [comment]
Really hard to understand what you're doing, is it a slider? Might be an issue with the font in that alphabet on that device (safari?)
