### ISSUE TITLE
npm start not working, tried many solves :|

### ISSUE THREAD

**Issue by luukee** [olefredrik/FoundationPress#1328]
**How can this bug be reproduced?**

1. renamed the foundationpress theme folder
2. ran into multiple issues.
3. copy and pasted `package.json` and `package-lock.json` from this repo to my theme's, respective, files as a fix.
4. Deleted the `node_modules` folder
5. run `npm install` on the theme folder

**What did you expect to happen?**
I expected npm to install so I could boot up and run the site in the localhost:8888 window

**What happened instead?**
Atom (the editor) freezes, as well as terminal and I get this error in terminal:

```
Unhandled rejection Error: Command failed: /usr/local/bin/git checkout 4.0
error: pathspec '4.0' did not match any file(s) known to git

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)

⸨            ░░░░░░⸩ ⠦ extract:fsevents: sill extract is-accessor-descriptor@1.
```

**Please List the Following:**
* OS & version: Mojave 10.14
* Node version (node -v) [Node v4+ is required] : v10.11.0
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : no file named `foundation-sites`??

Please help, this is driving me wild. Haha.

Thanks!
Luke

**Comment by DeiCha** [comment]
Just read  fixes: https://github.com/olefredrik/FoundationPress/issues/1312  https://github.com/olefredrik/FoundationPress/issues/1316

Sadly can't help with atom (using sublime) but it could happen if you don't exclude node_modules folder when importing project.

**Comment by luukee** [comment]
@DeiCha Thank you! 

Your reply [here](https://github.com/olefredrik/FoundationPress/issues/1316#issuecomment-432634229) fixed it for me. 

Also, I'm using [nvm](https://github.com/creationix/nvm) to downgrade to node version 6.11.5.

After installing nvm I ran this to check which version I was on:

`node -v`

Then I ran 

`nvm use 6`

. . . then I started at your [second bullet point](https://github.com/olefredrik/FoundationPress/issues/1316#issuecomment-432634229):

- npm rm -rf node_modules (to delete packages if some of them installed)
- delete: package-lock.json
- try npm init and npm install again

Everything works! 

**although I still have these "deprecated" warnings:

`
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! `
`
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`
`
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.`
`
npm WARN deprecated wreck@6.3.0: This version is no longer maintained. Please upgrade to the latest version.`
`
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.`
`
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.`
`
npm WARN prefer global node-gyp@3.8.0 should be installed with -g
`

And on `npm start` I see this failed to load:

`[09:40:24] Failed to load external module @babel/register`

But it FINALLY works!

Thanks again @DeiCha!

**Comment by FlatspinZA** [comment]
Try running `npm audit fix`, which will still leave you with some warnings which can be fixed with `npm audit fix --force`

There is one last issue that needs to be manually fixed. `--force`  won't fix it, but if you run `npm audit fix` again, it will allow you to scroll & update the package manually. 

Nothing broke for me as far as I can tell.

**Comment by luukee** [comment]
Thanks! I’ll give it a try.

**Comment by derweili** [comment]
This was an error with the gulp dependency. It is already fixed

To solve this problem in your project follow these steps: 

1. Delete the node_modules folder.
2. Open the package.json
3. Search for` "gulp": "gulpjs/gulp#4.0",` and replace it with `"gulp": "^4.0",`
4. Make sure you have node version 6.11.xx installed
5. Run `npm install`
