### ISSUE TITLE
Closing off-canvas menu via keyboard

### ISSUE THREAD

**Issue by djmtype** [olefredrik/FoundationPress#1329]
How can this bug be reproduced?
Use the Tab key to open off-canvas menu, then try pressing ESC to close the menu.

What did you expect to happen?
The off-canvas area should closed and move focus to the content area.

What happened instead?
Nothing at all.

OS & version: Mac 10.14.1 / Chrome Version 70.0.3538.77
Example: 
https://foundationpress.olefredrik.com/

Suggestions?
Maybe add a close button to the off-canvas menu, although, that may seem redundant.

**Comment by mattbag** [comment]
This seems more a question for the actual foundation-sites github. It might not be implemented since off-canvas it's mostly for mobile, but for your use case your suggestion seems the most proper

**Comment by derweili** [comment]
@mattbag I searched for the mentioned functionality in the official Foundation Docs and it works well there. 

So I think there is an error in the Off-Canvas implementation of FoundationPress.
This should be fixed.

**Comment by djmtype** [comment]
@derweili Just wanted to say "thanks!"
