### ISSUE TITLE
Woocommerce Shop navigation not working corretctly

### ISSUE THREAD

**Issue by Johannes-Hartmann** [olefredrik/FoundationPress#1335]
I am using a pretty old compiled Version of FoundationPress, its all Float Grid and has been working so far so good. Now I have the odd phenomena that it doesn't work with woocommerce properly anymore. When entering the Shop the Add to Cart Button is missing and when I try to navigate it jumps to Page 1 (now the Add to Car button is there), when going to another Site it works fine until I refresh it jumps back to Page 1. 

I disabled every Plugin (except Woocommerce) and still the error persisted, I changed to twenty-seventeen and no Problems anymore.
So I've gone ahead and compiled a new FoundationPress Version with Node 6.15.0 and used it as the main theme, still the problem persistet. 
Anyone else having this Problem or any Idea how to solve it? WP_Debug showed nothing out of the ordinary and no console errors.

OS & version: Ubuntu 14.04 LTS
FoundationPress 5 and 6 (v. 2.1.4)

**Comment by derweili** [comment]
I'm running 4 WooCommerce shops with Foundation.
Never had a problem.
Your description certainly sounds more like caching problems.

**Comment by Johannes-Hartmann** [comment]
> I'm running 4 WooCommerce shops with FoundationPress.
> Never had a problem.
> Your description certainly sounds more like caching problems.

That was my first thought aswell, but after switching Themes it worked and there is no cache active (not even server side since it's a development enviroment)

**Comment by Johannes-Hartmann** [comment]
The problem coincided with a cookie set by a GDPR Plugin which was pretty persistent and was set upon reload with disabled cache. The plugin got an Update which solved the Issue permanently.
