### ISSUE TITLE
npm install/npm start failing.

### ISSUE THREAD

**Issue by roborracle** [olefredrik/FoundationPress#1340]
I've got an older project that I need to update but `npm install` > `npm start` is failing. 

to be clear - I've already removed the `node_modules` directory and tried to re-run. 

I also tried updating the package.json file to the most recent version so all packages are up to date, but  it continues to fail. 

I just updated to the latest stable version of node.js 11.6.0 and the previous version where I first found this error was from around version ~10.8

Here is the output from npm install which seems remarkably thin judging based on previous instances of use:

```
> fsevents@1.2.4 install /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> node-sass@4.11.0 install /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/SMG_Rob/.npm/node-sass/4.11.0/darwin-x64-67_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.11.0 postinstall /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/node-sass
> node scripts/build.js

Binary found at /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/node-sass/vendor/darwin-x64-67/binding.node
Testing binary
Binary is fine

> gifsicle@4.0.1 postinstall /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@4.0.0 postinstall /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@5.1.0 postinstall /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
added 1271 packages from 987 contributors and audited 25417 packages in 35.791s
found 0 vulnerabilities
```

Here is the error output:

```

> foundationpress@2.10.4 start /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme
> gulp

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'run-sequence'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/gulpfile.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundationpress@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.10.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Not sure what I need to do here to get sass running compiling again and would love any help I could get.

**Comment by dgobnto** [comment]
From the readme file:
> This project requires Node.js v4.x.x to v6.11.x to be installed on your machine. Please be aware that you might encounter problems with the installation if you are using the most current Node version (bleeding edge) with all the latest features.

You might wanna downgrade to nodejs v6.11.5 (with nvm) or try the fix mentioned [here](https://github.com/olefredrik/FoundationPress/issues/1316#issuecomment-432747381), [here](https://github.com/olefredrik/FoundationPress/issues/1312#issue-372302113) and [here](https://github.com/olefredrik/FoundationPress/issues/1320#issuecomment-433241546).

**Comment by roborracle** [comment]
@dgobnto - thanks for the response here. I didn't realize it wouldn't perform correctly on newer versions of Node.js, so I tried rolling back to 6.11.1. No luck.

I checked the package.json for the links you mentioned, no luck there either. 

 `npm install` still fails, as does `npm start`

```
> foundationpress@2.10.4 start /Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme
> gulp

module.js:471
    throw err;
    ^

Error: Cannot find module 'run-sequence'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/my-project/wp-content/themes/my-theme/gulpfile.js:9:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/SMG_Rob/.nvm/versions/node/v6.11.1/bin/node" "/Users/SMG_Rob/.nvm/versions/node/v6.11.1/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.10.4 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.
```

Looks like the same error output as before. 

FWIW - this is an older project - probably around ~2 years old. I tried exchanging the old package.json with the newest version so that all the node_modules would be pulling in the latest.

**Comment by dgobnto** [comment]
Which version of Foundation do you have in the node_modules folder? Look for the package.json file in node_modules > foundation-sites.

**Comment by dgobnto** [comment]
I believe it's your gulpfile that is outdated.
If you need to update Foundation / FoundationPress maybe it would be easier to make a fresh install and import your old site into the new installation. If you don't need to update, just stick to your old release of FoundationPress and pay attention to the required nodejs version (you can navigate the file tree for your FoundationPress release and check for nodejs requirements in the readme file).

**Comment by GuillaumeComadequat** [comment]
in the readme.md :
"**This project requires [Node.js](http://nodejs.org) v4.x.x to v6.11.x to be installed on your machine.** Please be aware that you might encounter problems with the installation if you are using the most current Node version (bleeding edge) with all the latest features."

grrrrr it is never simple ! 
So i am going to try to downgrade nodejs. thank you !

**Comment by roborracle** [comment]
> Which version of Foundation do you have in the node_modules folder? Look for the package.json file in node_modules > foundation-sites.
> Did you clean cache and delete node_modules folder before npm install?
> In the meanwhile, make a fresh install to see if you run into the same problems.

node_modules/foundation-sites/package.json = "foundation-sites@6.4.3",

I did delete node_modules (a couple times) before. 

Not sure what cache you're referring to?

**Comment by dgobnto** [comment]
@roborracle I mean npm cache, with `npm cache clean --force`.

**Comment by roborracle** [comment]
> I believe it's your gulpfile that is outdated (you should have a `gulpfile.babel.js` file rather than `gulpfile.js`).
> If you need to update Foundation / FoundationPress maybe it would be easier to make a fresh install and import your old site into the new installation. If you don't need to update, just stick to your old release of FoundationPress and pay attention to the required nodejs version (you can navigate the file tree for your FoundationPress release and check for nodejs requirements in the readme file).

yea, I can't get it working. How would you recommend upgrading to the latest version of FP? Seems that would be preferrable at this point, but I don't know of an easy way to separate out my theme from what a new instance of FP would install and/or how to integrate it. If you have advice there, I'd be most grateful.

**Comment by dgobnto** [comment]
@roborracle It depends on the FoundationPress release you started the project with, how much modification you have done and whether you're using git. It could be a more or less easy task or it could be a very tedious one. I think it's always better to keep things steady while working on a project, hence my previous suggestion of sticking with your current FoundationPress release. But if you really need to update, I believe you could try a fresh install of FoundationPress in a new folder and replace the src folder, templates and php files, etc with your current ones.

Have you replaced your gulpfile with the latest one in the meanwhile?

**Comment by FlatspinZA** [comment]
`gulp-cli` needs to be installed globally, from what I can see regarding your error.

I was having that same problem and found the recommendation to install `gulp-cli` on another thread regarding other software. Spent many hours tearing my hair out.

Fixed my problems with `npm start`

**Comment by derweili** [comment]
I think the problem is a a new, updated version of the package.json with updated versions of the dependencies on the one hand and an old version of the build process (gulpfile).

Because the build-process (gulpfile.js / gulpfile.babel.js) make use of the dependencies defined in the package.json both files must be compatible.

So I think there are two ways to solve this:
1. Switch back the the original package.json
If to do this, you may have to use an older node version (6.11)

2. Switch to the latest package.json and gulpfile.babel.json
If you do this, there could be additional problems depending on else has changed since your original version.

Personally I would prefere the first option.

**Comment by derweili** [comment]
> `gulp-cli` needs to be installed globally, from what I can see regarding your error.

No, `gulp-cli`does not have to be installed globally.

**Comment by derweili** [comment]
@GuillaumeComadequat 
> "**This project requires [Node.js](http://nodejs.org) v4.x.x to v6.11.x to be installed on your machine.** Please be aware that you might encounter problems with the installation if you are using the most current Node version (bleeding edge) with all the latest features."

The latest version is compatible with node v10 and node v11

I just testet those versions and had not problem.

Older versions of FoundationPress had issues with node versions newer than 6.11.xx
Because @roborracle uses an older version of FoundationPress he has those problems.

**Comment by roborracle** [comment]
So to give an update here - basically, I had to clean up my old version and use nvm to switch back to 6.11.5. That combined with the the correct command to watch and compile - note in the older versions the command was `npm run watch` not `npm start`. Once I got those lined up with the cleaned up package.json I was able to get it all running again properly.

**Comment by derweili** [comment]
@roborracle 

Back in August 2017 there was an breaking change in FoundationPress.

Webpack replaced the previous JavaScript Build Process, the assets management changed (separate src and dist folders).

This was the time when the name of the script was changed. Not sure why it was changed.

Because of this reasons it is not possible to use the new build process with the old structure. (without major changes to you project) This old build process does not support newer versions of node.

I think this issues is solved. If you have further questions, feel free to re-open the issue.

**Comment by FlatspinZA** [comment]
> 
> 
> > `gulp-cli` needs to be installed globally, from what I can see regarding your error.
> 
> No, `gulp-cli`does not have to be installed globally.

Strange, because I have never had the problem with `npm install/start` & the only solution I could find was to install `gulp-cli` globally from another git repository where they were having issues.
