### ISSUE TITLE
Update "main" parameter of package.json

### ISSUE THREAD

**Issue by dgobnto** [olefredrik/FoundationPress#1341]
The `main` parameter in `package.json` points to `gulpfile.js`, which has been updated to `gulpfile.babel.js` a few releases ago, with the introduction of Foundation 6.4.1.
Should it be updated?

**Comment by derweili** [comment]
@dgobnto yes

**Comment by dgobnto** [comment]
Although it doesn't seem to be making any trouble…

**Comment by derweili** [comment]
It does not make any trouble it is not used anywhere.
But because a main script is required for a valid package.json it should be set to the right file.
