### ISSUE TITLE
Breadcrumbs demo

### ISSUE THREAD

**Issue by jmbarlow** [olefredrik/FoundationPress#135]
Something I add to FoundationPress - usually at the end of [header.php](header.php) - is a quick bit of code for breadcrumbs (internal links):

```php
<div class="row">
<?php if ( function_exists('yoast_breadcrumb') && !is_front_page() ) {
              yoast_breadcrumb('<p id="breadcrumbs" class="breadcrumbs">','</p>');
        } ?>
</div>
```

This adds a grid row, and prints the breadcrumbs applying the relevant classes [the div can also be within the `if` statement, just an example here to show which bit does what].

 On the one hand, this is a [plugin dependency](https://yoast.com/wordpress/plugins/seo/) [albeit with a check], but on the other hand it's a great way to use/demo the Foundation breadcrumbs classes in a Wordpress site.

I can make a pull request if you think it's worth including in the core theme.

**Comment by vimes1984** [comment]
Did this ever get committed?

**Comment by themestechnology** [comment]
Im on the move at the moment so I have not yet tested the code but this is basically what you need, I will do a commit in a few hours... https://github.com/themestechnology/FoundationPress-comments/blob/master/parts/breadcrumb-mettadata.php

simply use get_template_part('parts/breadcrumb-mettadata'); in your footer

**Comment by vimes1984** [comment]
I prefer to add the function into a custom-functions.php file in library 
then add a page part called breadcrumbs..

**Comment by themestechnology** [comment]
https://github.com/themestechnology/FoundationPress-comments/blob/master/library/foundation.php

Just use a do_action('FoundationPress_do_bredcrum'); to place it where you want

**Comment by themestechnology** [comment]
There is now a pull request for that @olefredrik however I will leave it up to you do remove another breadcrumbs in the theme
