### ISSUE TITLE
Build Issue with v2.10.4 Cannot find module 'gulp-sass-glob'

### ISSUE THREAD

**Issue by liquidonthedrums** [olefredrik/FoundationPress#1351]
I'm running the "npm start" command and getting an error "Cannot find module 'gulp-sass-glob'".

**How can this bug be reproduced?**

1. Clone the theme
2. Update package.json dependency to "gulp": "4.0"
3. Run npm install
4. Run npm start

**What did you expect to happen?**
Build without issues

**What happened instead?**

Error: Cannot find module 'gulp-sass-glob'

**Please List the Following:**
* OS & version: Ubuntu 16.04
* Node version (node -v) [Node v4+ is required] : 6.11.5
* FoundationPress version (see line 3 in package.json):  2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.3

Below is the error log

0 info it worked if it ends with ok
1 verbose cli [ '/home/matt/.nvm/versions/node/v6.11.5/bin/node',
1 verbose cli   '/home/matt/.nvm/versions/node/v6.11.5/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundationpress@2.10.4~prestart: foundationpress@2.10.4
6 silly lifecycle foundationpress@2.10.4~prestart: no script for prestart, continuing
7 info lifecycle foundationpress@2.10.4~start: foundationpress@2.10.4
8 verbose lifecycle foundationpress@2.10.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle foundationpress@2.10.4~start: PATH: /home/matt/.nvm/versions/node/v6.11.5/lib/node_modules/npm/bin/node-gyp-bin:/home/matt/projects/abc/wp-content/themes/abc1/node_modules/.bin:/home/matt/.sdkman/candidates/gradle/current/bin:/home/matt/.nvm/versions/node/v6.11.5/bin:/home/matt/bin:/home/matt/.local/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/matt/Android/Sdk/tools:/home/matt/Android/Sdk/platform-tools:/home/matt/java/jdk1.8.0_171/bin
10 verbose lifecycle foundationpress@2.10.4~start: CWD: /home/matt/projects/abc/wp-content/themes/abc
11 silly lifecycle foundationpress@2.10.4~start: Args: [ '-c', 'gulp' ]
12 silly lifecycle foundationpress@2.10.4~start: Returned: code: 1  signal: null
13 info lifecycle foundationpress@2.10.4~start: Failed to exec start script
14 verbose stack Error: foundationpress@2.10.4 start: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/matt/.nvm/versions/node/v6.11.5/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/matt/.nvm/versions/node/v6.11.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid foundationpress@2.10.4
16 verbose cwd /home/matt/projects/abc/wp-content/themes/abc-alt1
17 error Linux 4.15.0-43-generic
18 error argv "/home/matt/.nvm/versions/node/v6.11.5/bin/node" "/home/matt/.nvm/versions/node/v6.11.5/bin/npm" "start"
19 error node v6.11.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error foundationpress@2.10.4 start: `gulp`
22 error Exit status 1
23 error Failed at the foundationpress@2.10.4 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the foundationpress package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs foundationpress
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls foundationpress
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

I have tried deleting the node_modules folder and re-running "npm install", and also tried deleting the package-lock.json file, removing node_modules and re-installing.

**Comment by derweili** [comment]
> I'm running the "npm start" command and getting an error "Cannot find module 'gulp-sass-glob'".

The referenced package `gulp-sass-glob` is not an [FoundationPress dependency](https://github.com/olefredrik/FoundationPress/blob/master/package.json). 
So I wonder why npm tries to install it. 

Did you add `gulp-sass-glob` manually to your package.json?

Please provide us your package.json.
 
> Update package.json dependency to "gulp": "4.0"

Why did you change this? 
`"gulp": "^4.0",` should work fine.
