### ISSUE TITLE
is gulp-cli required?

### ISSUE THREAD

**Issue by derweili** [olefredrik/FoundationPress#1352]
`gulp-cli` is a devDependency in the package.json but I can't find out where it is used. Do we still need it?

**Comment by kLOsk** [comment]
I did some research and correct me if I'm wrong, but I believe gulp-cli allows for gulp workflow execution of different versions when gulp is globally installed on the system. So if a users uses gulp 3 globally, but our project requires gulp 4, he is still able to run our tasks without having to upgrade his system. More info here: https://stackoverflow.com/questions/35571679/what-does-gulp-cli-stands-for

**Comment by FlatspinZA** [comment]
I think it is, because I had some issues getting `npm start` to run on a fresh system install & ended up having to install `gulp-cli` globally to resolve my issues.

**Comment by kLOsk** [comment]
I close this for now as I think we need it.
