### ISSUE TITLE
Question: where is the markup for a standard, non-gallery, single image with a caption?

### ISSUE THREAD

**Issue by adambundy** [olefredrik/FoundationPress#1355]
I just wanted to remove the inline hard-coded width in the <figure> element. Thanks!

**Comment by derweili** [comment]
There are some modifications to Standard Images in the responsive-images.php file.

https://github.com/olefredrik/FoundationPress/blob/master/library/responsive-images.php

Or do you mean something else.

**Comment by adambundy** [comment]
No I was referring to an image with a caption applied in the edit image modal. Is this being modified by Foundation, or is this core WP somewhere?? The opening figure tag ends up looking like:

`<figure id="attachment_XX" style="width: 1024px" class="wp-caption alignnone">`

**Comment by derweili** [comment]
This is a WordPress "Feature".

Under the following link you will find solutions to solve the problem.

https://stackoverflow.com/questions/23812072/wordpress-3-9-x-remove-inline-width-from-figure-element

**Comment by adambundy** [comment]
Oh wow, how dumb. :)  Thanks @derweili!
