### ISSUE TITLE
Failed at the theme@2.10.4 start script.

### ISSUE THREAD

**Issue by WordpressNick** [olefredrik/FoundationPress#1373]
**How can this bug be reproduced?**

I am revisiting a project from last year and when I run NPM start I get the following error...
[11:29:07] 'build' errored after 72 ms
[11:29:07] 'default' errored after 75 ms
[11:29:07] The following tasks did not complete: webpack:build, images, copy
[11:29:07] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! theme@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the theme@2.10.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**What did you expect to happen?**

Compile the code

**What happened instead?**

Errors...

[11:29:07] 'build' errored after 72 ms
[11:29:07] 'default' errored after 75 ms
[11:29:07] The following tasks did not complete: webpack:build, images, copy
[11:29:07] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! theme@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the theme@2.10.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Please List the Following:**
* OS & version: Sierra 10.12.6 
* Node version (node -v) [Node v6+ is required] : v10.15.3
* FoundationPress version (see line 3 in package.json): 2.10.4
* Foundation version (found in `node_modules/foundation-sites/package.json`) : 6.4.3

**Comment by derweili** [comment]
@WordpressNick please try using node v 6.11.5.

The FoundationPress Version 2.10.4 (from last year) does not support Node Version 10.15.3

Try following steps

- switch to node version 6.11.5 ([I recommend using nvm Node Version manager](http://dev.topheman.com/install-nvm-with-homebrew-to-use-multiple-versions-of-node-and-iojs-easily/))
- delete your `node_modules` folder
- run `npm install`


If this does not work, please provide the whole content of your `package.json`

**Comment by WordpressNick** [comment]
Thanks that worked!
