### ISSUE TITLE
Accessibility Issue - How to edit the HTML of foundationpress_pagination output

### ISSUE THREAD

**Issue by WordpressNick** [olefredrik/FoundationPress#1382]
Accessibility Issue - How to edit the HTML of foundationpress_pagination output?

Working with an AT Tester I need to move the aria-label and role outside the UL and replace the caret icon with "Next".

How do i edit the output of HTML of the foundationpress_pagination output?

**Comment by FlatspinZA** [comment]
`foundation.php` found in `/themes/your-theme-name/library/foundation.php`
