### ISSUE TITLE
JS code being revised 

### ISSUE THREAD

**Issue by adambundy** [olefredrik/FoundationPress#1383]
Does the JS processing in the build routine sometimes revise JS code? I have the following in a custom JS file:
`almComplete = function(alm){
	console.log("ALM load is complete");
};`

and it ends up in app.js as:
`almComplete = function almComplete(alm) {
	console.log("ALM load is complete");
};`
<img width="1076" alt="Screen Shot 2019-05-02 at 3 19 21 PM" src="https://user-images.githubusercontent.com/664533/57108336-9daf3680-6cef-11e9-9042-e861b871f149.png">

**Comment by kLOsk** [comment]
Yes, FP is using babel to transpile into old school JS.
