### ISSUE TITLE
White Text in TinyMCE visual editor

### ISSUE THREAD

**Issue by FrankLauda** [olefredrik/FoundationPress#1385]
Hi,

I'm not sure if anyone else has encountered this problem. I've done a fresh install of foundationPress with npm. Everything is fine until I start doing some work on the theme, or even just add some content in the WordPress admin. 

The WordPress visual editor TinyMCE, you can't see any text. It's there, but it's white, and you can view in text editor mode. But obviously, this is no good to me when I hand this off to a client. All the buttons e.g. kitchen sink are still displaying.

I've taken all these common steps to try and resolve the issue. see https://mythemeshop.com/blog/fix-white-text-and-missing-buttons-error/,  but no luck.
I'm using a local environment setup on my Mac with MAMP.

The only resolution I found is to do a fresh install of FoundationPress, but the same result, do some more work then the same issue.

So does anyone have any thoughts on this? Any help would be much appreciated.

Regards
Frank

**Comment by kLOsk** [comment]
Hi Frank,
in _editor-style.scss can you try add color: $black; or color: black; to the tinymce selector?

**Comment by FrankLauda** [comment]
Hi Daniel,

Yes, that work! I can't believe I didn't think of this. The editor is
mimicking the front-end, which the p tag was white. Thanks for your help.

**Comment by kLOsk** [comment]
Glad it helped. Yes Foundationpress isn't really ready for a dark mode yet unfortunately. Would be nice if this can be added more easily in the future.
