### ISSUE TITLE
Mobile Navigation Not Working in Mobile

### ISSUE THREAD

**Issue by akshi007** [olefredrik/FoundationPress#1386]
Hi Friends

I am using septera theme for my website ([https://www.digitalrajeev.com]), when I tried my site on mobile devices and click on Menu Icon then menu’s not working means not open any menu

please help if any body have idea

Thanks in Advance

**Comment by kLOsk** [comment]
I believe this is so wrong here? This is the FoundationPress github support. Septera seems to be here: https://www.cryoutcreations.eu/forum
