### ISSUE TITLE
Doesn't work in China

### ISSUE THREAD

**Issue by cjyabraham** [olefredrik/FoundationPress#1392]
Is there a reason jQuery is being included from ajax.googleapis.com?  This url doesn't work in China so all sites using this won't work.  Why not just use the jQuery included in WP?  Does this theme use features not available in that version?

**Comment by kLOsk** [comment]
You can pull it locally too. Some of the JS components of Foundation require jQuery 3 but if you want to use jQuery 2 it will work too, except of these components. I don't have a list which components that are unfortunately.
