### ISSUE TITLE
Hooks overview

### ISSUE THREAD

**Issue by violacase** [olefredrik/FoundationPress#140]
I commented on a closed issue. Not so clever perhaps, have to create a new issue.

I'd like to see a webpage with an overview of the actual WP hooks implemented in FP. I'm scanning php files now to get an idea. 
I'd like to contribute by perhaps setting up a WP hooks schema like Genesis does. Well, users have to find all the bits and pieces after implementation I suppose.

**Comment by chrismacho** [comment]
I found [this] (http://virtualblend.com/2015/03/foundation-press-hook-list/)
