### ISSUE TITLE
ENOTFOUND Package  not found when trying to install from bower

### ISSUE THREAD

**Issue by GregRR** [olefredrik/FoundationPress#151]
I'm using bower to pull this in to a project. It's listed in my bower.json dependencies:
"FoundationPress": "https://github.com/olefredrik/FoundationPress.git",

But on 'bower install' I get:
bower FoundationPress#\*     not-cached https://github.com/olefredrik/FoundationPress.git#*
bower FoundationPress#\*        resolve https://github.com/olefredrik/FoundationPress.git#*
bower FoundationPress#\*       checkout master
bower FoundationPress#\*   invalid-meta foundation-libsass-template is missing "main" entry in bower.json
bower FoundationPress#\*   invalid-meta foundation-libsass-template is missing "ignore" entry in bower.json
bower FoundationPress#\*       resolved https://github.com/olefredrik/FoundationPress.git#2540603ac0
bower foundation#\*           ENOTFOUND Package  not found

If I remove the FoundationPress line from my bower.json then all works as expected.

Any ideas?

**Comment by SanjanaTailor** [comment]
I am still facing the same issue - bower install Jqm-editable-listview
bower                        ENOTFOUND Package Jqm-editable-listview not found

**Comment by brutalcrozt** [comment]
sure i still face this issue

**Comment by iamShashi** [comment]
@SanjanaTailor  try using full path of the git project it could be that URL it is trying its not actually in the home directory but under some other directory. Just resolved such an issue.
