### ISSUE TITLE
Problem with sticky  Class in wordpress

### ISSUE THREAD

**Issue by rabendeviaregia** [olefredrik/FoundationPress#155]
Hello,
i try to use the sticky top-bar and it works fine but...
in wordpress the class sticky it's used to the sticky post... 
in the foundation site say: "Top bar supports data-options configuration."
i try to add this
data-options="sticky_class:'mystickyclass'"
but dosnt work
any idea?

**Comment by Anydog** [comment]
Yeah -- I need solution for this, too ... anyone ?
