### ISSUE TITLE
[Clearing gallery] Applying Foundation's Fix#3410 "the image shift" 

### ISSUE THREAD

**Issue by versedi** [olefredrik/FoundationPress#186]
Good evening,

I'm currently trying to apply Foundation's fix for image shifting:
https://github.com/zurb/foundation/issues/3410

I'm having troubles with building app.js based on customized foundation.clearing.js. All the time it's rewritten with foundation's default file and then build into app.js

Could you assist me in applying that fix?
Have a nice evening,
versedi

**Comment by olefredrik** [comment]
I'll apply the fix as soon as a new foundation version gets shipped.
