### ISSUE TITLE
Can't disable buttons component

### ISSUE THREAD

**Issue by josh1324** [olefredrik/FoundationPress#188]
I can disable every component by deleting or setting them in comment in scss/foundation.scss, except for buttons. How can i fix this?

**Comment by olefredrik** [comment]
That's probably because there is a property in _base.scss which depends on a $ medium-up declaration is in _buttons.scss. Comment out line 71-76 in _base.scss and you should be good to go.

**Comment by josh1324** [comment]
Thanks for the quick response. I tried it on clean install but it didn't work.
