### ISSUE TITLE
Strict Standards: Declaration of FoundationPress_comments::start_el() should be compatible with Walker_Comment::start_el()

### ISSUE THREAD

**Issue by DamianS1987** [olefredrik/FoundationPress#194]
Hi, fyi, I had this error message when I installed the theme with the steps you've provided in the documentation.

Strict Standards: Declaration of FoundationPress_comments::start_el() should be compatible with Walker_Comment::start_el(&$output, $comment, $depth = 0, $args = Array, $id = 0) in /Applications/MAMP/htdocs/websites/wordpress_test/my_project/wp-content/themes/my_test_theme/library/foundation.php on line 173

I quickly found this help:
http://wordpress.stackexchange.com/questions/111557/strict-standards-error-bootstrap-navwalker

and fixes to arguments helped to solve the issue:
line 113 (wp-content/themes/my_test_theme/library/foundation.php)

    function start_el( &$output, $comment, $depth = 0, $args = array(), $id = 0 ) {}

Thanks,
Damian

**Comment by olefredrik** [comment]
https://github.com/olefredrik/FoundationPress/pull/195
