### ISSUE TITLE
Changing border-radius of input border not working

### ISSUE THREAD

**Issue by joedaniels** [olefredrik/FoundationPress#197]
When I try to change the border-radius of input elements nothing happens. No matter what I enter the the css stays like so:

```css
-webkit-appearance: none;
-webkit-border-radius: 0px;
```

**Comment by jmbarlow** [comment]
1. Uncomment line 634 in [_settings.scss](https://github.com/olefredrik/FoundationPress/blob/master/scss/config/_settings.scss)
2. Set the value you wish to use.
3. Run `grunt build`

**Comment by joedaniels** [comment]
Doesn't work. That is why I made the post...

**Comment by jmbarlow** [comment]
The output CSS using this variable is:

`input[type="text"].radius, input[type="password"].radius, input[type="date"].radius, input[type="datetime"].radius, input[type="datetime-local"].radius, input[type="month"].radius, input[type="week"].radius, input[type="email"].radius, input[type="number"].radius, input[type="search"].radius, input[type="tel"].radius, input[type="time"].radius, input[type="url"].radius, input[type="color"].radius, textarea.radius {
    border-radius: $input-border-radius; }`

Having set a radius value (or use the default), you need to add the `radius` class to the input element.
