### ISSUE TITLE
Sidebar Menu support?

### ISSUE THREAD

**Issue by HansUXdev** [olefredrik/FoundationPress#200]
Cool stuff. 
I found this awesome sidebar on the forums. How would I go about adding it? 
I'm still new to WordPress.

http://foundation.zurb.com/forum/posts/21166-check-out-this-sidebar-off-canvas-icon-menu

**Comment by themestechnology** [comment]
You could add a page template to your theme and copy the code into it, you would then have to add the standard word press get post PHP or you could follow one of many wordpress theme tutorials and add the sidebar code into the standard wordpress sidebar.php page

**Comment by olefredrik** [comment]
Hi. I agree that this is a neat concept. But I have no plans to take this into the project to date.

**Comment by HansUXdev** [comment]
Hey thank for the tips and feedback. I just started testing out foundation in wordpress.
