### ISSUE TITLE
FoundationPress_comments function not found?

### ISSUE THREAD

**Issue by chadamski** [olefredrik/FoundationPress#202]
Heya. Thanks to olefredrik for such a wonderful theme. I'm new to both custom themes and Foundation, but this is an awesome project that you maintain.

I'm not sure if I'm asking this question in the right place, so sorry in advance if I should post it elsewhere, but here's the rub.

I've got a local install of WP and no active plugins whatsoever. Just trying to build a clean theme with FoundationPress. Everything was going fine and dandy until I clicked on an article and noticed that it looks like there are two sections to display comments, one that works fine and one that creates the following issue:

Warning: call_user_func() expects parameter 1 to be a valid callback, function 'FoundationPress_comments' not found or invalid function name in C:\Program Files\wamp\www\collegedrive\wp-includes\comment-template.php on line 1796

When I switch to a default theme, I don't encounter this problem. I'm probably just doing something really dumb or wrong, but I'm having a heck of a time trying to figure this out. Thanks very much for your time.

**Comment by olefredrik** [comment]
Hi Chelsea,

Thank you for testing and playing with FoundationPress. You're absolutely right about the error with FoundationPress_comments. I was able to reproduce the same error on my dev environment. There are a few contributors who have done some work on the comments section the last few weeks. Which is nice, of course. All FoundationPress contributors are awesome. But unfortunately I have been too busy to do a proper code review and test all new functionality before this was merged into the project. 

Anyway, I've managed to trim the code that caused the error message (https://github.com/olefredrik/FoundationPress/commit/caa5bebac2bc19d3414480ac1c2d010e4cec16e9)

When I get time, I'll look into whether there is a better permanent solution. Something tells me comments.php and associated files need a proper overhaul.

(cc: @themestechnology @Pourcentage )

**Comment by chadamski** [comment]
You're awesome! Thanks for such a fast response and for all the work you and other contributors do to make this project real.

**Comment by robertrhu** [comment]
Hi! I'm having a similar issue. I updated the code from the caa5beb link but there was no change. I am getting the following error...

Warning: call_user_func() expects parameter 1 to be a valid callback, function 'FoundationPress_comments' not found or invalid function name in /Users/robertrhu/Documents/Websites/locavore/wp-includes/comment-template.php on line 1796

Any thoughts?

Thanks for this amazing project and for your help!
