### ISSUE TITLE
Warning: call_user_func(); comment-template.php on line 1796

### ISSUE THREAD

**Issue by indus** [olefredrik/FoundationPress#205]
i get the following error:
```Warning: call_user_func() expects parameter 1 to be a valid callback, function 'FoundationPress_comments' not found or invalid function name in C:<path>\wp-includes\comment-template.php on line 1796```

**Comment by olefredrik** [comment]
I pushed a fix to this error yesterday. https://github.com/olefredrik/FoundationPress/pull/203
