### ISSUE TITLE
Recommended SASS customizations?

### ISSUE THREAD

**Issue by adaptifyDesigns** [olefredrik/FoundationPress#207]
Are you recommending that we add our custom styles to `_base.scss`? Or that we start new `.scss` files and add them to the `foundation.scss` sheet as imports?

In the same line of thought, is there a recommendation for updating the core theme when you push updates? 

Just trying to make sure I future proof this theme before I start building. Thanks for any help/suggestions. And thanks a lot for this theme!

**Comment by joshsmith01** [comment]
+1

**Comment by olefredrik** [comment]
I prefer personally to divide up styling in relation to various components, and include these in foundation.scss.

For example:
```import "site/base";```
```import "site/sidebars";```
```import "site/Badges";```

... And so on. In this way I get a better overview and structure. It gives me greater flexibility than if I'd had all the styling in the same file. Grunt ensures that the output is just one minified file, so you don't have to worry about many http requests and slow loading times. 

To answer your second question, this can be solved by doing a ```git pull origin master```. Note that you may need to handle merge conflicts that must be resolved if the same files are modified both locally and remote. Merge conflicts is however a common part of Git, and can be easily solved with a variety of free tools.

Having said this, there is no definitive answer your questions. I recommend that you play around and find the way that best suits your workflow.

Good luck and have fun :)

**Comment by themestechnology** [comment]
+1
