### ISSUE TITLE
Error when run 'npm install && bower install && grunt build' instruction

### ISSUE THREAD

**Issue by Vivaria** [olefredrik/FoundationPress#208]
Hi, when I run 'npm install && bower install && grunt build' instruction from my WP theme directory, I get this error:

C:\Users\LuciaA\Documents\Progetti\Vivaria\website\FoundationPress-master>npm in
stall && bower install && grunt build
/
> node-sass@1.2.3 install C:\Users\LuciaA\Documents\Progetti\Vivaria\website\Fou
ndationPress-master\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\LuciaA\Documents\Progetti\Vivaria\we
bsite\FoundationPress-master\node_modules\node-sass\vendor\win32-x64\binding.nod
e

> node-sass@1.2.3 postinstall C:\Users\LuciaA\Documents\Progetti\Vivaria\website
\FoundationPress-master\node_modules\node-sass
> node scripts/build.js

`win32-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: no errorC:\Users\LuciaA\Documents\Progetti\Vivaria\website\FoundationPres
s-master\node_modules\node-sass\vendor\win32-x64\binding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\LuciaA\Documents\Progetti\Vivaria\website\Fo
undationPress-master\node_modules\node-sass\lib\index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js
'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\LuciaA\Documents\Progetti\Vivaria\website\FoundationPress-
master\npm-debug.log

What is the problem?
Thanks a lot for your support

**Comment by themestechnology** [comment]
Windows

**Comment by themestechnology** [comment]
lol sorry try --force or npm i 

also make sure you are running the CMD window as Admin (right click)

**Comment by Vivaria** [comment]
Thank you for your answer! Yes, I'm Admin,I've forced but but it doesn't work... when I modify scss files I get errors:

>> File "scss\config\_settings.scss" changed.

Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.

**Comment by Vivaria** [comment]
I've solved installing nodejs version 0.10.33 (Stable) 2014.10.20 and git. Launching 'npm install && bower install && grunt build' from git now it works.
