### ISSUE TITLE
Off canvas or top-bar

### ISSUE THREAD

**Issue by jw86** [olefredrik/FoundationPress#210]
I think it would be great to have the option to select either off canvas or top-bar for smaller devices as I use both of these depending on the project requirements.

**Comment by olefredrik** [comment]
I agree. It is in the pipeline for development, but I am currently very busy with other tasks. If anyone wants to look at it, I will gladly go through a pull request and consider taking it into the project.

**Comment by olefredrik** [comment]
The same topic is also discussed here https://github.com/olefredrik/FoundationPress/pull/206

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/releases/tag/v1.1.0
