### ISSUE TITLE
Functions Conflict in Child theme

### ISSUE THREAD

**Issue by theodorocaliari** [olefredrik/FoundationPress#211]
Hi @olefredrik, I found a little problem when developing my child theme of FoundationPress. When I try to customize the pagination with the same function name of parent theme, I recieve the error of "redeclare function"... Searching for a solucion on the web I found this link ( http://wordpress.stackexchange.com/questions/95799/is-it-possible-to-disable-a-function-of-a-parent-theme ). I make a test on local theme, make change on parent theme and works. If in parent theme every the function it was declared with ` if(!function_exists(" ")){} ` this will make the child theme able to replace the parent function with same name. 
Example:
```php
if(!function_exists("FoundationPress_pagination"){
FoundationPress_pagination(){
//parent theme pagination code
}
}
```
Please take a look on that.... 
Thanks...

**Comment by themestechnology** [comment]
Are you using the latest version this was patched?

**Comment by theodorocaliari** [comment]
Hi Phill, I really don't know... :(
Em 12/02/2015 11:26, "Phill" <notifications@github.com> escreveu:

**Comment by theodorocaliari** [comment]
Well, I think my version is out dated... 
Why my wordpress no highlight is a new version available?

**Comment by themestechnology** [comment]
Well I guess this is not a plugin on the WP repository and the theme does not have any API that checks with github for the latest version, so no I would not expect the theme to announce a change in WP

**Comment by theodorocaliari** [comment]
Thanks Phill...
