### ISSUE TITLE
Cannot install npm in foundationpress dir

### ISSUE THREAD

**Issue by ianxdev3** [olefredrik/FoundationPress#212]
Hi, recieving this error in the command prompt:

15456 error Windows_NT 6.1.7601
15457 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
15458 error node v0.12.0
15459 error npm  v2.5.1
15460 error code ELIFECYCLE
15461 error node-sass@1.2.3 postinstall: `node scripts/build.js`
15461 error Exit status 1
15462 error Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
15462 error This is most likely a problem with the node-sass package,
15462 error not with npm itself.
15462 error Tell the author that this fails on your system:
15462 error     node scripts/build.js
15462 error You can get their info via:
15462 error     npm owner ls node-sass
15462 error There is likely additional logging output above.

Thanks for any help

Ian

**Comment by themestechnology** [comment]
https://github.com/olefredrik/FoundationPress/issues/209#issuecomment-74096068

**Comment by ianxdev3** [comment]
Thanks for the quick response, but after following the above link and instructions the problem remains.
I get the same error after npm install. i followed the instructions on the foundationpress github page:
cd my-wordpress-folder/wp-content/themes/
git clone git@github.com:olefredrik/FoundationPress.git
mv FoundationPress your-theme-name
cd your-theme-name
npm install && bower install && grunt build

**Comment by themestechnology** [comment]
I would follow that post as it was only opend yesterday, did you try the uninsall bit?

Personaly I am using Ubuntu with the latest node and foundation and have no problem.

**Comment by ianxdev3** [comment]
Much appreciated but no joy. I'll follow the other post.

**Comment by FlatspinZA** [comment]
Just have to love the people that espouse the Linux as the solution to everything, instead of helping to fix the actual Windows problem.
