### ISSUE TITLE
Foundation press and plugins "revolution slider"

### ISSUE THREAD

**Issue by pixel-up** [olefredrik/FoundationPress#213]
hello,
I use foundationpress. I buy the plugin "revolution slider" and when I instaled I have an error message:
------
Warning: An unexpected error has occurred. Something seems to not work with WordPress.org or configuration of the server. If you continue to have problems, please try the support forums. (WordPress does not establish a secure connection to WordPress.org. Please contact your server administrator.) In /home/www/wordpress/public_html/wp-includes/update.php on line 295
-------

I wished to know if revolution slider was consistent with "foundationPress."

thank you for your answer

**Comment by olefredrik** [comment]
Hello. First of all. Please do not use header-styling when describing your problem. It makes it harder to read. Secondly, I do not offer support for third party plugins. This is a starter-theme for web developers who want a good starting point for new sites. The internet is packed with sites where you can download polished themes that are packed with plugins and whanot.

I don't mean to be harsh, but if a gallery plugin is the biggest problem, it might not be a good idea going ahead with node, grunt, sass etc.

**Comment by themestechnology** [comment]
http://foundation.zurb.com/docs/components/orbit.html

https://wordpress.org/plugins/wp-orbit-slider/

**Comment by AdamChlan** [comment]
I've also found that using the capabilities of Foundation's Orbit in conjunction with something like the Advanced Custom Fields plugin allows for very customizable sliders, which much less chance for conflicts from a dedicated slider plugin.

**Comment by Aetles** [comment]
Before diving into Orbit, be aware that it [has been deprecated](http://foundation.zurb.com/forum/posts/14504-moving-on-from-developing-orbit) and the development and support stopped as of May last year.

**Comment by themestechnology** [comment]
Humm really... Its hard to keep a track of eveything would recommend this one I have use a few times http://owlgraphic.com/owlcarousel/

**Comment by pixel-up** [comment]
thank you for your answer ...
I will use the plugin "Orbit".
@ +

**Comment by FlatspinZA** [comment]
I think this slider is more than capable - it works well. https://wordpress.org/plugins/fluid-responsive-slideshow/
