### ISSUE TITLE
Where is app.scss in foundationpress

### ISSUE THREAD

**Issue by ianxdev3** [olefredrik/FoundationPress#216]
Sorry, proberbally a stupid question but I need to add custom styles and was told to put them in app.scss. Also, whats the difference between app.scss and base.scss for this purpose?

any advice would be appreciated

Ian

**Comment by FlatspinZA** [comment]
Hi. See here: https://github.com/olefredrik/FoundationPress/issues/172

**Comment by themestechnology** [comment]
Zurb changed app.css to foundation.css

also app.js became foundation.js

**Comment by ianxdev3** [comment]
Thanks, so if I make changes in foundation.scss and base.scss these will be compiled into foundation.CSS? Also, what files are overwritten during an update and what files should I make copies of?

**Comment by themestechnology** [comment]
Yes and pretty much anything in CSS and bower folders that have default file names

**Comment by ianxdev3** [comment]
Thankyou for your time that has cleared things up for me, cheers
