### ISSUE TITLE
Examples of FoundationPress sites

### ISSUE THREAD

**Issue by jmbarlow** [olefredrik/FoundationPress#219]
Hiya,

There isn't really a category for "praise" so I'll stick this in issues. A quick shout out to @olefredrik for this great repo. Looking back at the last few months, me and my guys have built quite a few sites on FoundationPress:

http://www.sokolovelaw.com/
http://www.asbestos.net/
http://www.xenanetworks.com/
http://www.learningtheory.org/
http://www.learningtheory.org/colt2015/
http://www.pandorachildrensparties.co.uk/

(I still can't persuade clients to ditch the sliders, though).

**Comment by olefredrik** [comment]
Sweet! Well done @jmbarlow :+1: 

I added a few of them to the [Examples of sites built using FoundationPress](https://github.com/olefredrik/FoundationPress#examples-of-sites-built-using-foundationpress) section in the readme. Hope you don't mind :)

**Comment by FlatspinZA** [comment]
Some very nice sites, with awesome menu customisations - makes me realise how lazy I have been. 

http://tech-boy.net/

I am redesigning a native Foundation site with FoundationPress - I hope to show more innovation.

**Comment by FlatspinZA** [comment]
BTW, Ole, I wanted to ask you if I could take the time to design a proper logo for your platform? I feel that your work deserves its own icon/logo - something we could link to using an icon, like I have on my homepage? 

If anyone else feels like contributing to this effort, with Ole's approval, we could make it a competition of sorts?

**Comment by themestechnology** [comment]
why not just do the Foundation with a + then WP logo
