### ISSUE TITLE
How to customize woocommerce templates?

### ISSUE THREAD

**Issue by ianxdev3** [olefredrik/FoundationPress#220]
Hi, 

If I wanted to to for example change the layout, appearence of the product catagory template, how would I go about this in my foundationpress theme?

Thanks

**Comment by themestechnology** [comment]
There are some example templates here http://foundation.zurb.com/templates.html

You would need a working knowledge of HTML, CSS, PHP and WordPress (and possibly SCSS)

So you can identity files in FoundationPress such as sidebar-left.php footer.php etc and make the appropriate changes
