### ISSUE TITLE
customize woo commerce cat and single prod pages

### ISSUE THREAD

**Issue by ianxdev3** [olefredrik/FoundationPress#223]
Cannot find category and single product template files in in woo commerce plugin to duplicate in a woo commerce folder in foundationpress, so that I can override these original templates.

In single product the is image left, price and add to cart right and description , review tabs below. I need to change this default layout.
Appreciate any help. Thanks

**Comment by ianxdev3** [comment]
I know how to do this HTML, scss etc.. I just can't find the php template files that need to be overridden

**Comment by themestechnology** [comment]
Well the checkout pages would be using the page.php and the products would be using the single.php file and the category page would be using the index.php page (i think if not the archive.php page)

*Dont forget that woo may be using its own templates inside the wp post loop

I start by creating a child theme using FoundationPress as its parent and add your own single.php template there

http://codex.wordpress.org/Child_Themes

These tags may help ie. # if( is_product() ){ //do something }

http://docs.woothemes.com/document/conditional-tags/

**Comment by ianxdev3** [comment]
Ok , ill give that a go. Thanks for the advice

**Comment by ianxdev3** [comment]
I Thought i could override the woo templates, if I made duplicates, created a folder called woo commerce inside foundation press and placed them in side this folder. What would the template files be called in woo commerce plugin that handle cat and single product pages?

**Comment by themestechnology** [comment]
I think this page is what you are looking for but these question are generic about woo not FoundationPress you would face the same situation with any template so perhaps the woo forum may be better to ask on 

http://docs.woothemes.com/document/template-structure/

**Comment by ianxdev3** [comment]
Thanks, problem solved
