### ISSUE TITLE
Bower error

### ISSUE THREAD

**Issue by Eccola** [olefredrik/FoundationPress#226]
npm installs fine, but bower fails at this point:

bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/FortAwesome/Font-Awesome.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection timed out

So I have node_modules but no bower_components

**Comment by olefredrik** [comment]
Hmm. I just cloned the repository and I'm unable to reproduce the error.
```npm install && bower install && grunt build``` resulted in  ```Done, without errors.```

![screen shot 2015-02-17 at 14 02 14](https://cloud.githubusercontent.com/assets/1080017/6228563/af3d286e-b6ad-11e4-9577-c6e48ee04c1a.png)

**Comment by Eccola** [comment]
I just ran bower install && grunt build again, and everything ok!

Thank you!

**Comment by olefredrik** [comment]
Your error message suggests that you might have lost your network connection for a second?
> fatal: unable to connect to github.com 
> github.com[0: 192.30.252.131]: errno=Connection timed out

Anyway. Nice that it works now :)

**Comment by Eccola** [comment]
I'm starting a portfolio theme development project at http://demo.eccola.fi/sa/
Graphic designer will join next week.
It would make a great community tutorial, what do you think?

**Comment by olefredrik** [comment]
Would be cool if you could post some of your experiences as the project progresses. Always fun and inspiring to see what others are doing. :)

**Comment by themestechnology** [comment]
Try...

gems clean
bower init
bower install

also have you tried grunt instead of bower?

**Comment by olefredrik** [comment]
@themestechnology Grunt instead of Bower? Do you have any idea what you're talking about?

**Comment by themestechnology** [comment]
sorry though this was about scss compiling

**Comment by Eccola** [comment]
The photography portfolio/blog site was made public a couple of weeks ago at: http://stormarts.fi

Everything went smooth, thank you. ;)

I wrote down some notions over development, but they're still at very fragmented format, so..
