### ISSUE TITLE
FoundationPress folder structure

### ISSUE THREAD

**Issue by smonksi** [olefredrik/FoundationPress#228]
Is there any reason why 'source' files/folders  e.g.  bower_components, node_modules, scss etc  can't go in their own folder, to separate 'source' from 'target' files?

I created an install of FP today with a sub folder containing these files and folders, and it works fine so far. I had to edit Gruntfile.js to reflect the new folder relationships to make it work.

**Comment by olefredrik** [comment]
Sorry, I I'm not sure if I understand what you are asking? Do you want to move bower_components, node_modules and the SCSS folders to a separate 'source' folder? Clearly, this can be done. And if it gives a better overview of the contents in the project, it should perhaps be done. Have simply not thought much about it.

**Comment by smonksi** [comment]
Thanks yes, that is is what I meant. I am working on windows and it suits my workflow better, but I wondered if it might cause any issues. It doesn't seem to. It just creates some separation and is less cluttered, plus a bit easier to see what needs to be on the server side and what can remain locally in the IDE. 

On the other hand, I can see for pure simplicity of installation, having everything in one folder can be a bit easier for some.

So I am not sure if this approach is good generally or just for me.
