### ISSUE TITLE
Change class on widget_search  

### ISSUE THREAD

**Issue by baaboum** [olefredrik/FoundationPress#232]
Hello I want to change the class of input on widget-search but I don't find the html in the library of foundationPress.

Can you please help me to find this ?

**Comment by themestechnology** [comment]
The widget search is a widet/plugin that comes with wordpress not the theme

**Comment by baaboum** [comment]
ok thanks :)

2015-02-18 13:58 GMT+01:00 Phill <notifications@github.com>:

> The widget search is a widet/plugin that comes with wordpress not the theme
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olefredrik/FoundationPress/issues/232#issuecomment-74859695>
> .
>



-- 
Xavier Frayssignes

*Webdesigner - intégrateur*
Portefolio : http://xavier-frayssignes.fr/
Mail : xav.fray@gmail.com
