### ISSUE TITLE
Hard code text in page-home.php or via admin-pages-Home?

### ISSUE THREAD

**Issue by MrsColombo** [olefredrik/FoundationPress#234]
Hallo, greetings from Sweden!
I am making a website for a client based on FoundationPress. On the home page we want to publish some columns based on the grid. What is your suggestion on how to do it the right way?
I can hard code the information in the page-home.php but it doesn't feel right. If I'll place all my html in the admin - pages - Home - text editor, section Text I am afraid that my client might unwillingly brake some of it. You know yourself, delete one tag by accident and your whole page is broken. 
So what is a client-proof solution in this case?
I do appriciate your comments! Thank you for your time!

Julia

**Comment by olefredrik** [comment]
Hi Julia,

This sounds familiar. I've also had the same challenge on several occasions. There are a few solutions with different approaches in terms of how much flexibility you want to give your client.

You should nonetheless never go for a solution where you put HTML in the WYSIWYG editor in wp-admin. I've been using a brilliant (actually priceless) free plugin called Advanced Custom Fields (ACF). With this plugin you can define the page layout and grid structure in your template files and create custom meta boxes in wp-admin where the actual content to be submitted.

An example where I have used this is my own mini-site, [olefredrik.com](http://www.olefredrik.com). On the front page I display a grid with a list of various cases. I need every case to have a name, short description, picture and link to a case description page. In this case, I've used ACF with repeater fields.

![acf](https://cloud.githubusercontent.com/assets/1080017/6263285/4c95fc5e-b815-11e4-9f06-23e2e2a71511.png)

There are many more options for how to resolve your challenge, but if you want a straightforward solution that is easy to get started with, I would recommend going with ACF.

You can check out ACF here:
http://www.advancedcustomfields.com/
http://www.advancedcustomfields.com/add-ons/repeater-field/

Cheers,
Ole Fredrik
