### ISSUE TITLE
Foundation Equalizer not working

### ISSUE THREAD

**Issue by tconroy** [olefredrik/FoundationPress#237]
Hello!

I'm trying to make an Equalizer component as per the [Foundation docs](http://foundation.zurb.com/docs/components/equalizer.html), however it doesn't seem to be working with FoundationPress. 

Below is my markup and a screenshot of what it produces. 

      <div class="section-content row" data-equalizer>

        <div class="small-12 medium-4 columns">
          <div class="panel" data-equalizer-watch>
            test
          </div>
        </div>

        <div class="small-12 medium-4 columns">
          <div class="panel" data-equalizer-watch>
            test
          </div>
        </div>

        <div class="small-12 medium-4 columns">
          <div class="panel" data-equalizer-watch>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>

        <div class="small-12 medium-4 columns">
          <div class="panel" data-equalizer-watch>
            test
          </div>
        </div>

        <div class="small-12 medium-4 columns">
          <div class="panel" data-equalizer-watch>
            test
          </div>
        </div>

        <div class="small-12 medium-4 columns">
          <div class="panel" data-equalizer-watch>
            test
          </div>
        </div>

      </div> 

![screenshot 2015-02-20 10 49 35](https://cloud.githubusercontent.com/assets/1609336/6289487/7e4a4a5a-b8ee-11e4-9ebe-bb6e2fdef83d.png)

**Comment by FlatspinZA** [comment]
Separate the columns you want 'equalized' by rows.

i.e. Create a separate 'row' DIV for your 1st three panels, and another for your 2nd three panels. 

![capture_001_21022015_051542](https://cloud.githubusercontent.com/assets/6318620/6312944/bb3e9d9a-b988-11e4-8fd9-f7b312cac4db.jpg)
