### ISSUE TITLE
Topbar data-options Configuration Not Applying

### ISSUE THREAD

**Issue by indadam** [olefredrik/FoundationPress#238]
Hello-

I'm building a custom theme based on FoundationPress, but I'm running into a weird issue. It seems to be ignoring the JavaScript data-options I'm implimenting (re: http://foundation.zurb.com/docs/components/topbar.html in the "Using the Javascript" section near the bottom of the page). I've added the following code to the init-foundation.js file:

    $(document).foundation({
    	topbar : {
    		custom_back_text: false,
    		back_text: '&larrhk;'
    	}
    });

I've enqueued the script correctly in the library function page, I have have other scripts working correctly, and I can see the link in the page source as well. I've copy and pasted the above code from a non-Press Foundations version of the site, so I know it should work in theory. I enqueued the script directly after the foundations script, before my other scripts.

Any ideas?

**Comment by digitalhydra** [comment]
I think that's a bug on the foundation script itself, because I try runing the script directly on the foundation site and it didn't change the back button either.
also based on the docs if you want to change the text you need to set the property custom_back_text to true.
```
$(document).foundation({
    topbar : {
        custom_back_text: true,
        back_text: '&larrhk;'
    }
});
```
