### ISSUE TITLE
Help understanding enqueue-scripts.php

### ISSUE THREAD

**Issue by ianxdev3** [olefredrik/FoundationPress#239]
I recently included an orbit slider on my site and everything works perfectly without uncommenting the orbit register script and enqueue script  in the enqueue-scripts.php. So how is foundation.orbit.js being included? 

Also the path  /js/foundation/js/foundation/foundation.orbit.js doesnt exist in foundationpress theme foundation.orbit.js is located /bower_components/foundation/js/foundation/foundation.orbit.js. This has left me a bit confused, can anyone explain this?

Help would be much apprecited, thanks

**Comment by olefredrik** [comment]
I understand very well that this was confusing. A pull request that should not have been approved, has unfortunately been merged into the project a while ago. I just did a cleanup to make things more clear. Hopefully it is a bit more understandable now. Please find all details in this link https://github.com/olefredrik/FoundationPress/pull/240

**Comment by ianxdev3** [comment]
It makes sense now, so I could just comment out the components I dont need in the grunt.j file

**Comment by olefredrik** [comment]
Yup. Comment out the components you don't need in Gruntfile.js. Save and do a ```grunt build```. That's it. :)
