### ISSUE TITLE
Enqueue jQuery before </head> ?

### ISSUE THREAD

**Issue by iamseangrant** [olefredrik/FoundationPress#243]
I recently came across an issue with loading jQuery in the footer and some plugins expecting jQuery to load in the header.

I saw that this was addressed in Issue #24 but then in the latest cleanup ( PR #240 )  it got switched back to the footer. 

Was there a reason for this switch back?

I've changed my copy, but want to know if I'll need to keep an eye on it, or make a filter to switch it automagically.

Thanks!

**Comment by olefredrik** [comment]
You know what? You're right. My initial thought was to load jQuery in footer to reduce load and optimize performance. But as you say, there are several plugins that for some strange reason requires jQuery to be loaded in the header. So I have reintroduced the jQuery in header thing (loaded via Google CDN). See further details in this pull request https://github.com/olefredrik/FoundationPress/pull/244

Thanks for your feedback! :+1:
