### ISSUE TITLE
Image Cleanup with Captions - Markup Output Issue

### ISSUE THREAD

**Issue by sky1tech** [olefredrik/FoundationPress#245]
Having trouble with the output on images and captions in posts. 

I noticed the issue when: inserting an image into the post, the paragraph tags and paragraph text is showing up between the <figure tags where caption is supposed to be. The </figure wraps around all the paragraphs in the post.  

See screenshots: 

Step 1 -  I used Add Media and wrote in the Caption, then clicked Insert into Post as shown:
https://www.evernote.com/shard/s34/sh/a49332e0-8d90-4b13-8fd4-c9c6e8931a8c/f1bcfd44b69d09ace654a31ad745f086/deep/0/Screenshot-2-24-15,-1-11-PM.png

Step 2 - Upon Updating the post I view page to check the markup and see the paragraph text is showing up where the caption should be? : 
https://www.evernote.com/shard/s34/sh/20419e43-051d-4681-b9f5-bf5969be77bf/50bb7c03410b8240eb450105d31e5ad7/deep/0/Screenshot-2-24-15,-1-00-PM.png

Step 3 - Go back to Edit the post, then click to edit the already inserted image to find my caption missing:
3a: https://www.evernote.com/shard/s34/sh/a49332e0-8d90-4b13-8fd4-c9c6e8931a8c/f1bcfd44b69d09ace654a31ad745f086/deep/0/Screenshot-2-24-15,-1-11-PM.png 
3b: https://www.evernote.com/shard/s34/sh/a0c448a6-ca49-4505-b39b-cfcd00adbc41/da24a4c2b5f8b8f1bcc7a2bb182a52d4/deep/0/Screenshot-2-24-15,-1-12-PM.png

Step 4 - I Update the caption while editing the already inserted image. Then update the Page and go to check my markup to see this: 
https://www.evernote.com/shard/s34/sh/09f31bdc-119e-4ee5-9c44-8f0455dc834e/d675f9e8ab1caff5f110b2d17ef294aa/deep/0/Screenshot-2-24-15,-1-05-PM.png

I will eventually have to hack away at the cleanup.php but I thought I would share what I'm seeing on my end. I probably would not have noticed this if the font weights were not changing on the View Page (due to the <figure> tags surrounding my body text). 

Love the theme BTW. Great work.

**Comment by olefredrik** [comment]
Hi, 

Your issue seems to be related to this https://github.com/olefredrik/FoundationPress/issues/110 . 

I'm aware of the problem, but have so far failed to fix it. It's still on the list of open issues, and will be fixed when I get time. If you have the time and opportunity to contribute, I would be more than happy to look at pull requests related to this issue.

**Comment by sky1tech** [comment]
I thought so too but the alignment is working okay for me. Or, at least the correct classes are appearing so I can control that.
