### ISSUE TITLE
where to put my own scss?

### ISSUE THREAD

**Issue by MrsColombo** [olefredrik/FoundationPress#252]
Hi,
There is no _base.scss file anymore in this version of FoundationPress. I'm putting my custom styles in _hero.scss but I have to use !important way to often to make them have effect. Is there a better way? Thank you for your reply!

**Comment by Aetles** [comment]
You could also create your own `scss/site/_custom.scss` and then add `@import "site/custom";` to `scss/foundation.scss` instead of editing the other files. (That does not change the override problem, though.)

**Comment by Pautomagi** [comment]
The order of @import in scss/foundation.scss does matter to what you will be overriding. If you place custom at the bottom it will ovveride all above if you use a selector that is previously used.
