### ISSUE TITLE
Display child pages in a block grid

### ISSUE THREAD

**Issue by MrsColombo** [olefredrik/FoundationPress#255]
Hi, 
I would like to display child pages in a four column grid in one of the sections on my front page. Somehow it's not working. I have a feeling that I'm not closing my div's properly. I've tried like a hundred time to close my div's but still no result. All four children pages are displayed in the first column of the four intended. I really appriciate your help on this!
http://pastebin.com/YvYZi38h
Julia

**Comment by jmbarlow** [comment]
Is the goal to have 4 child posts as 3 unit width columns in a row on a large display? In which case, the column should all be defined inside the while block?
```
  while ( $services_query->have_posts() ) {
    echo '<div class="small-6 large-3 columns">';
    // Render stuff [using Wordpress the_post or similar
    the_post(); 
    echo '</div>';
  }
```
Assumes you have only 4 services defined.

**Comment by MrsColombo** [comment]
James, you are a geniuos! Thank you so much! It was not about where I close the dive, but where I open it. Cool!
How about if I want to display only 4 out of many? Thank you!

**Comment by jmbarlow** [comment]
Have a look at "Show x Posts per page" in the "[Interacting with WP_Query](http://codex.wordpress.org/Class_Reference/WP_Query#Interacting_with_WP_Query)" documentation.
```
$args = array(
  'post_type' => 'page',
  'post_parent' => $services_id,
  'posts_per_page' => 4
);
$services_query = new WP_Query( $args );
```

**Comment by MrsColombo** [comment]
Thank you!
