### ISSUE TITLE
Interchange stopped working

### ISSUE THREAD

**Issue by Tralapo** [olefredrik/FoundationPress#258]
Today I pulled a fresh verion of FoundationPress here from GitHub to give my Wordpress-theme a refreshment.

There's one issue: Interchange seems to have stopped working in this latest version (talking about the one with .html parts). It just shows the default one, all the time.

**Comment by olefredrik** [comment]
Strange. Can not see why this should happen. Can you test if interchange works with Foundation 5.5.1 without WordPress? It is possible that there is an error in the component itself, and not in FoundationPress.

**Comment by Tralapo** [comment]
>Strange. Can not see why this should happen. Can you test if interchange works with Foundation 5.5.1 without WordPress? It is possible that there is an error in the component itself, and not in FoundationPress.

Good call Ole, I didn't even try to start at that end. I'm sorry. Turn's out I can't get it to work in the basic Foundation to.

To be more specific, it seems like the full queries can't be used anymore? See [http://foundation.zurb.com/docs/components/interchange.html#named-queries](Named Queries). When I use the small/medium/large name, it works. When I try to use the full querie with a custom min-width, it stops working.

I don't know if I missed that support for doing it like that stopped, but I wil inform Zurb.

**Comment by Tralapo** [comment]
@olefredrik I can now confirm that this is a bug in Foundation itself. See [the issue over there](https://github.com/zurb/foundation/issues/6368). You can close this issue ;)
