### ISSUE TITLE
Javascript ignored by grunt process

### ISSUE THREAD

**Issue by tomislavboric** [olefredrik/FoundationPress#271]
I've just installed theme and added custom scripts inside of /js/custom/ but grunt watch doesn't see any changes. I've tryed to change content in every js file but still no action in command promp. Unlike css which is being processed normally. Do you have the same issue?

**Comment by olefredrik** [comment]
See the config in Gruntfile.js. You'll need to do a grunt build. Or modify the grunt watch task to your needs. It's quite flexible, so you can basically make tell grunt to do whatever you like.

**Comment by tomislavboric** [comment]
Grunt build did the job. Tnx for your kind support. Cheers!

**Comment by olefredrik** [comment]
My pleasure :) have a great weekend. Cheers!
