### ISSUE TITLE
Nested Side Nav?

### ISSUE THREAD

**Issue by sashareds** [olefredrik/FoundationPress#273]
Hi there,
Great starter framework.. Helps a lot.
I'm new to this framework and may miss something, but so far I haven't found nested side menu feature out of the box.
Is there any plans to add this feature? Or perhaps you have already workarounds or suggestions how to do that?
Thank you

**Comment by FlatspinZA** [comment]
https://github.com/zurb/foundation/issues/5829

**Comment by olefredrik** [comment]
Hello. As of now there is only support for top-bar menu and off-canvas mobile menu out of the box. I plan to add support for top-bar with dropdown for mobile, as an alternative to off-canvas. https://github.com/olefredrik/FoundationPress/issues/283

I have no plans to add nested page nav, but I'm always open to look at any pull requests, if you or someone else will give it a try.

Cheers,
Ole Fredrik
