### ISSUE TITLE
Dropping global dependencies for bower & grunt

### ISSUE THREAD

**Issue by stefanjudis** [olefredrik/FoundationPress#274]
Hey I'll just giving foundation press a shot.

The one thing I don't like so far is, that in current state there is a need for global grunt & bower installation.

Are you open for a PR that solves this, by using npm only?

Bower and grunt could then be declared as "normal" deps and could be run via npm to avoid forcing global installations?

This would mean that command like `npm run build`, `npm run grunt` and `npm run bower` would be available.

Also this `npm install && bower install && grunt build` could be improved to simply be post install hooks right after npm install. :)

Thanks,
Stefan

**Comment by LukePettway** [comment]
Wow that sounds really interesting. I'd be interested in seeing how this progresses.

**Comment by stefanjudis** [comment]
@LukePettway 

Cool - hopefully I'll make it to propose a PR tomorrow then.
Shouldn't take long. :)

**Comment by stefanjudis** [comment]
And PR is there.
I'm excited what you think of it. :bowtie:

**Comment by olefredrik** [comment]
https://github.com/olefredrik/FoundationPress/pull/334
