### ISSUE TITLE
How to add a Blog feed to a certain part of a page?

### ISSUE THREAD

**Issue by dfill** [olefredrik/FoundationPress#275]
Hey all,

I'd like to set up a specific row in my front-page.php file to simply contain a blog feed. So when a client posts, the blog feed will show up (I'd say probably 2-3 posts).

Is there a certain PHP snippet that I need to integrate in order to make this happen?

Any help would be appreciated!

**Comment by FlatspinZA** [comment]
Set up a new WP_Query. You can look at the solution I provided here for an idea on how to do this: https://github.com/olefredrik/FoundationPress/issues/265. 

OFC, WP provides documentation: http://codex.wordpress.org/Class_Reference/WP_Query

**Comment by dfill** [comment]
I will look into this. Thank you @FlatspinZA !
