### ISSUE TITLE
add_filter('get_image_tag', 'FoundationPress_image_editor', 0, 4) is removing the caption of the image

### ISSUE THREAD

**Issue by jesstura** [olefredrik/FoundationPress#276]
I tried it with a clean install of FoundationPress, and it is still hiding/removing the caption for inserted the images into the post. Whenever i uncomment that filter, the caption is displaying.

Is it only me? But thanks for the help.

**Comment by Aetles** [comment]
Maybe it's related to https://github.com/olefredrik/FoundationPress/issues/245
