### ISSUE TITLE
Top Bar Mobile Drop Downs

### ISSUE THREAD

**Issue by joewellmade** [olefredrik/FoundationPress#283]
Hi, i'm trying to implement the top bar like I have it at this URL: http://wellmadestudio.com/showandtell/index.html

When you view it on mobile the menu appears to the right and still has the drop downs.

When i'm trying to build this using FoundationPress, the menu on mobile screens disappears, this is with 'offcanvas' commented out in foundation.scss:

//@import "../bower_components/foundation/scss/foundation/components/offcanvas";

If I uncomment it then I get the offcanvas menu on mobile resolution. 

I just want to implement the drop down as in the first URL. Does anyone know how to do this, any help would be appreciated.

Thanks in advance,
Joe

**Comment by olefredrik** [comment]
Hi,

I think it would be a good idea to add a 'top-bar with dropdown' as a new menu option for mobile (in theme locations in apperance - Menus in wp-admin).

![menu](https://cloud.githubusercontent.com/assets/1080017/6768970/9092cf7a-d086-11e4-8193-46bd7c974571.png)


Possibilities of menus would then be
- Left top bar
- Right top bar
- Mobile off-canvas
- Mobile topbar dropdown

This would be a nice-to-have feature that I want to put in place as part of the theme. Will look into this when I get the time.

**Comment by joewellmade** [comment]
Hi Ole, that would be great. I've signed the functionality off with the client already suing the mock up so i'll have to find another way for now, however it'd be amazing if you could add the functionality. The theme is brilliant and I've really enjoyed using it. Thanks for getting back to me so quickly.

**Comment by olefredrik** [comment]
Thanks for the kind words. It means a lot. I'll leave this issue open until the new functionality is in place. Thanks for your input and good luck with your project :+1:

**Comment by olefredrik** [comment]
Hi. Here is a working quick fix for your issue. 

Open parts/topbar.php and paste this
```
<div class="top-bar-container contain-to-grid show-for-small-up">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h1><a href="<?php echo home_url(); ?>"><?php bloginfo('name'); ?></a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href=""><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
            <?php foundationPress_top_bar_l(); ?>
            <?php foundationPress_top_bar_r(); ?>
        </section>
    </nav>
</div>
```

In header.php, remove the markup in line 42-53:
```
<nav class="tab-bar show-for-small-only">
		<section class="left-small">
			<a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
		</section>
		<section class="middle tab-bar-section">
			
			<h1 class="title"><?php bloginfo( 'name' ); ?></h1>

		</section>
	</nav>

	<?php get_template_part('parts/off-canvas-menu'); ?>
```

Save and reload. Voila!

Not the most sophisticated solution to the problem, but it does the trick for now.

**Comment by joewellmade** [comment]
Awesome, that's amazing, you've really saved my bacon. Thanks!

**Comment by webnugget** [comment]
I was struggling with the same issue thanks for the fix

**Comment by LukePettway** [comment]
This was awesome, just used it on a project and saved me a lot of time!

**Comment by AdamChlan** [comment]
In my latest project I used the theme customizer to give the option of having the mobile menu be off-canvas or the Topbar style dropdown. This thread references giving that option in the Menu admin area, but if there is interest in having it as a standalone customizer option, I can submit for review once I do some more testing.

**Comment by olefredrik** [comment]
@AdamChlan : That would be great!

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/releases/tag/v1.1.0
