### ISSUE TITLE
Difficulties making Grunt work

### ISSUE THREAD

**Issue by JCoK** [olefredrik/FoundationPress#284]
Hello everybody

I'm new to Grunt and I have the following problem: whenever I follow the instructions given in FoundationPress Quickstart I get the following: "Warning: Unable to write "js/vendor/fastclick.js" file (Error code: EACCES). Use --force to continue.

Aborted due to warnings."

Any suggestions how to solve this problem would be greatly appreciated

**Comment by olefredrik** [comment]
Hi. What is it specifically you do that trigger this error message? Did you run ```npm install && bower install && grunt build``` after cloning the repository?

**Comment by JCoK** [comment]
Hi and thanks for answering. 
The theme runs flawlessly now. Just renamed it and went through the installation procedure once again. That did the trick. 
Thanks for the effort you put into this theme.

**Comment by olefredrik** [comment]
Glad to hear that :)
