### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by joewellmade** [olefredrik/FoundationPress#286]
Hi Ole, sorry to hassle you again, however, I can't seem to get the pagination working on normal pages where I have custom posts displayed. It is working on one page: category-highlights.php which is a category custom post page. My other page: page-events.php. Can you help at all?

http://pastebin.com/4q7dVuPf

**Comment by quadriclops** [comment]
Hi joewellmade, I had this same problem with custom post types and I found [this post](https://wordpress.org/support/topic/wp_query-amp-pagination-not-working#post-1431801) which indicated that `next_posts_link` & `previous_posts_link` expect the query object to be called `$wp_query`. Like you I had been using a custom variable name `$custom_query` and I spent several hours trying to figure out why pagination wouldn't work. I've found no mention of this on the Wordpress Codex which makes it especially frustrating.

So in your case you would replace:
`$the_query = new WP_Query( $args );`
with `$wp_query = new WP_Query( $args );`

I hope this works for you as well as it did for me.

**Comment by olefredrik** [comment]
@joewellmade : have you tried @quadriclops 's suggestion? If this works for you, it would be good if you could close the issue. If not, please let us know what did not work (the errors you get) and we'll keep the ticket open. Cheers

**Comment by joewellmade** [comment]
Hi guys, thanks for this, really appreciate it, I have everything working now!
