### ISSUE TITLE
Uncaught TypeError: Cannot read property 'topbar' of undefined

### ISSUE THREAD

**Issue by thomas529** [olefredrik/FoundationPress#289]
Hey there,

with a fresh install of foundation press I get the following error in the chrome console:

Uncaught TypeError: Cannot read property 'topbar' of undefined

Topbar is working though.

Any ideas?

**Comment by olefredrik** [comment]
Hi Thomas,

I'm unable to reproduce your error message. I'm using the latest vesion of Chrome in OSX Yosemite. Do you get any errors in your terminal after running ```grunt build```? Do you get the same error when browsing the [demo site](http://foundationpress.olefredrik.com)?

Cheers,
Ole Fredrik

**Comment by thomas529** [comment]
Hi Ole,

I've reinstalled all the tools (ruby, node, etc. ) and set up a few sites to test it. It seems to be working now. The first install still produces a couple of strange errors but none of them reappeared after the reinstall.

I guess it's solved for now.

Still, thanks for replying.

cheers,
Thomas Jones

**Comment by olefredrik** [comment]
:+1:
