### ISSUE TITLE
How to use full-width rows properly?

### ISSUE THREAD

**Issue by jdfweb** [olefredrik/FoundationPress#293]
Hey all,

I'm working on a client's site and it's going great so far. I have one minor problem, though. On most of the pages I want to use full-width rows. So what I did was this: 

- In header.php, I took out the div class="row" to disable this container on my whole site. This allows me to do full-width designs on any page (see below).

![1](https://cloud.githubusercontent.com/assets/11800545/6998221/18a70838-dba7-11e4-851d-d6d3c7b7b5e7.png)

- Then I would place that row I deleted (the div class="row") on page where I did want a container, and the full-width effect was gone because that page had a container (see below).

![2](https://cloud.githubusercontent.com/assets/11800545/6998223/327acad8-dba7-11e4-8bf6-40d92f8daad2.png)

- So that works great. However, I noticed my blog page was all wonky now. I thought to myself, "okay, lets just put in the div class="row" in the content.php page, which will put the blog right back into a container and it will solve the problem! Nope, it didn't. My blog page still looks like this:

![3](https://cloud.githubusercontent.com/assets/11800545/6998228/5968d234-dba7-11e4-980d-d96660a57f99.png)

Any idea how to fix this? This is the only problem left on my site and it's driving me nuts! Any help would be appreciated.

**Comment by FlatspinZA** [comment]
That's odd because I don't have the 'row' div for my install of FoundationPress in my header.php.

Anyway, check your index.php and insert your 'row' div there, which should fix your blog page. 

On my install, index.php already has a 'row' div, so I don't know what is going on with your install.

**Comment by jdfweb** [comment]
I added the 'row' div into my index.php page, and it came out like so:

![5](https://cloud.githubusercontent.com/assets/11800545/6998525/2c4eee44-dbb3-11e4-9e39-b5f0e7ff6139.png)

So I took it out and it's back to being all wonky. What I did do was add the div class of 'row' that I originally took out (to enable full width), back into the header.php file where it was originally. The blog does work now, however my other full width pages look like this:

![4](https://cloud.githubusercontent.com/assets/11800545/6998537/69d4f600-dbb3-11e4-8858-1b2c2bd0bcb7.png)

So now that the blog page works fine, my question is - how do I make these rows full-width instead of them being inside a container?

**Comment by jdfweb** [comment]
FIgured it out!

Added this code..

    <div class="container" role="document">
	    <div class="row">

To the following pages:

single.php, index.php - JUST BELOW the php get header tag.

Hope that helps anyone that may get stuck with this in the future!
