### ISSUE TITLE
WooThemes Sensei Support

### ISSUE THREAD

**Issue by dwainm** [olefredrik/FoundationPress#296]
Hi Ole, 

We've created an integration guide should any of your users need the theme to play nicely with Sensei ( the LMS plugin from WooThemes ) . 

https://support.woothemes.com/hc/en-us/articles/204125559-FoundationPress

All the best to you.

**Comment by olefredrik** [comment]
Hi, 

Thank you so much! I've added a link to your integration guide from the docs https://github.com/olefredrik/FoundationPress/pull/307. Sorry for getting back to you so late, I've been busy traveling lately. 

Thanks again for your contribution. Wish you a brilliant weekend!

Cheers,
Ole Fredrik
