### ISSUE TITLE
comments.php error

### ISSUE THREAD

**Issue by badcat** [olefredrik/FoundationPress#297]
I'm getting this error:

`Fatal error: Can't use function return value in write context in .../comments.php on line 39`

any ideas?

**Comment by t-fulton** [comment]
Also getting this error with a fresh install

**Comment by badcat** [comment]
Same here - I also tried this with Josh's fork https://github.com/josh-rathke/FoundationPress
For now, I've commented out lines 39 and 40.  

I wanted to try to use FP as a parent theme, but it looks like it's really better to approach this like using UnderscoreS - and just start adding / removing what I need directly, instead of building a Child theme.

**Comment by theodorocaliari** [comment]
Same here...
```html
Fatal error: Can't use function return value in write context in C:\EasyPHP14\data\localweb\projects\w4\wp-content\themes\foundationpress\comments.php on line 39
```

**Comment by LukePettway** [comment]
Assigning to a variable and then checking if the variable is empty seems to work.

```php
$file_name_to_check = sanitize_file_name( $_SERVER['SCRIPT_FILENAME'] );
if ( ! empty( $file_name_to_check) && 'comments.php' == basename( sanitize_file_name( $_SERVER['SCRIPT_FILENAME'] ) ) ) {
		die (__( 'Please do not load this page directly. Thanks!', 'FoundationPress' )); }
```

**Comment by chrisleach** [comment]
That helped me @LukePettway, thanks.

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/309 . Shoutout to @josh-rathke for saving the day!
