### ISSUE TITLE
Menu Icon not showing on mobile menu

### ISSUE THREAD

**Issue by mikevisions** [olefredrik/FoundationPress#300]
On a Samsung Galaxy S2 the menu icon is not showing. The word "menu" is present. The area where the icon should be is clickable and the menu is working. Problem is on a site I am working on and the FoundationPress demo site. Would welcome any suggestions on how to resolve.
Mike.

**Comment by olefredrik** [comment]
Hmm. Strange. Unfortunately I have no Samsung Galaxy S2 test device. I've tested on Samsung Galaxy S4 and Google Nexus tablet with Chrome. No errors. Are you using a special type of browser? Have you tried deleting your cache and resetting all browser settings? I can not find a logical explanation as to why it fails on a S2. Someone else who has a Galaxy S2 which can assist with testing?

**Comment by mikevisions** [comment]
Yes really strange. I have done a complete reset on the phone and all updates. Works fine on a S3 and many other Android based phones.

**Comment by olefredrik** [comment]
Can you check http://foundation.zurb.com/ on your S2 device and see if the menu icon is showing there?

**Comment by mikevisions** [comment]
Yes  same problem on the demo site.

**Comment by olefredrik** [comment]
Hm. If the problem is also present on the official Zurb Foundation site, it's most likely a bug in the Foundation framework. I suggest you open a new issue on the Foundation repo. Whenever they add a patch for the error, I will update this repo with the latest patches.

**Comment by mikevisions** [comment]
I have uploaded a test site of just foundation and the problem is present on that. I have raised an issue with Zurb.

**Comment by olefredrik** [comment]
:+1:
