### ISSUE TITLE
wp admin bar not there and dropdown doesn't work

### ISSUE THREAD

**Issue by musicgabser** [olefredrik/FoundationPress#301]
Hi,
I've created a new one and downloaded a fresh copy of FoundationPress and the wp adminbar is not showing and the sublevel menu is not working... Any ideas?
Thx in advance
musicgabser

**Comment by Eccola** [comment]
Hi musicgabser, wp-adminbar is problematic especially if used with fixed positioned top-bar.
Obviously wp-adminbar lies under your top-bar causing misbehaviour.
Try disabling the frontend wp-adminbar on "My account" settings page. 
Test sublevel menu again. It should work now.

**Comment by musicgabser** [comment]
Yes, thank you very much!!! this solves the Problem.
