### ISSUE TITLE
Top level menu items redirecting to index.php

### ISSUE THREAD

**Issue by dengrow** [olefredrik/FoundationPress#304]
Im not sure where I went wrong in this build but all my top level menu items are redirecting to the index.php file and not letting me see those pages. Even if I put in directly into the URL bar in my browser, anyone ever see an issue like this?

http://www.b-for.com.php53-13.dfw1-1.websitetestlink.com/

Thanks
-Dan

**Comment by olefredrik** [comment]
Hi Dan,

Looks good to me. Each of your top level menu items take me to the page I would expect. I guess you fixed it?

Ole Fredrik

**Comment by dengrow** [comment]
Ole Fredrik,

Thanks for taking a look but its actually not working still, I have my permalink set to "numeric" when really they should be set on "month and name" or "post name" but when its set to one of those it breaks.

I have set up a dev site with just a base install of foundationPress and its doing the same thing.

http://www.bfor.com.php53-13.dfw1-1.websitetestlink.com/

The same thing is happening, I didn't take the time to set up the walker menu but still you can see that all my parent pages are defaulting to index.php and my sub pages are going to the real page. Menu items with "sub" and child pages and everything else is a top level page.

Any idea whats going on?

Thanks
-Dan

**Comment by Eccola** [comment]
I was interested what's up with this, so I set up a testsite: http://demo.eccola.fi/tests-fpress/
Imported wordpress dot com theme unit test sample data and set up a left top-bar navi.

Navigation with subpage dropdowns is working on front page and archive pages, but not on pages and single posts. This is a new issue.

Couldn't reproduce @dengrow issue, the description is a bit complex.

**Comment by Aetles** [comment]
It seems like the class `not-click` is added (by Foundations javascript in `foundation.js`) to the topbar menu items on front page but not on single page. If you manually add the class (with web inspector) to menu items on single page then the dropdown works without click as on the front page. (But it should work with clicks as well, right?)

**Comment by Aetles** [comment]
Oh, stupid me, there's not `foundation.js` at all on the single page, that explains a lot :)

**Comment by Aetles** [comment]
It seems like the footer isn't added to single pages at all (on http://demo.eccola.fi/tests-fpress/), as if the `get_footer()` doesn't work. But setting up a similar test environment myself I don't see that error.

**Comment by Eccola** [comment]
@Aetles , 
I have vanilla installation from 20.4,  which still has the old '// Prevent access to this file directly' function on the comments.php. I see this was fixed two days ago!
I just updated the comments.php and all good now.

**Comment by Aetles** [comment]
Great!
