### ISSUE TITLE
Loading sass.js tasks...ERROR

### ISSUE THREAD

**Issue by ericabiz** [olefredrik/FoundationPress#306]
Hi, 

I'm on Mac OS X Yosemite and having the same issue as described in #209. I tried all of the fixes listed and could not get anything to work. I even tried uninstalling everything and installing node v0.10.33, and going through the whole setup for FoundationPress again. That did not work either.

I noticed the issue was closed, so has there been any resolution on this?

erica@[/Volumes/asz/wp-content/themes/asz]$ grunt build
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.

-- 

This all worked fine on my last FoundationPress site, but with this new one I haven't managed to get it working at all.

**Comment by olefredrik** [comment]
Hi Erica, 

If you have the latest version of node installed (0.12.0), that should be fully compatible with the latest version of FoundationPress. 

Check which version you are using by typing ```node -v``` in your terminal. It should echo v.0.12.0. When you have assured that you're using the latest node version, clone the FoundationPress repo to a folder on your harddrive and run a ```npm install && bower install && grunt build``` . This should work. Please report back if you have any problems. 

Cheers,
Ole Fredrik

**Comment by AdamChlan** [comment]
If we upgrade node to the latest version, will we have issue compiling older FoundationPress projects?

**Comment by olefredrik** [comment]
@AdamChlan : I would say yes and no. For older FoundationPress projects you will need to update the package.json file with the following config (if you run node v.0.12.0)
``` 
{
  "name": "foundationpress",
  "version": "5.5.1",
  "devDependencies": {
    "node-sass" : "~2.0.1",
    "grunt": "~0.4.1",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sass": "~0.18.0",
    "grunt-contrib-copy": "~0.4.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-uglify": "~0.2.7",
    "grunt-string-replace": "~0.2.7"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/olefredrik/FoundationPress.git"
  },
  "dependencies": {
    "time-grunt": "^1.1.0"
  }
} 
```

Save the package.json file, open your terminal, navigate to the theme folder and run a ```npm install && bower install && grunt build``` and you should be good to go.

**Comment by ericabiz** [comment]
I just tried this whole thing on a new Digital Ocean instance (instead of locally on my Mac) and it just worked. I will dig into further incompatibilities on my Mac today.

**Comment by ericabiz** [comment]
Wow. Okay, so it works now! Here's what I did:

I re-upgraded to Node 0.12.2 (latest) using the Mac package
I created a new directory locally, under my home directory
I re-cloned the git repo, ran all 5 commands to install FoundationPress starting with npm install -g grunt-cli

The last command was grunt build, which worked!

I then just copied over the directory where FoundationPress was causing an error, which is a mounted volume on WP Engine (I'm using Transmit to mount a SFTP folder as a drive, so I can actually work on the server live.)

The copy finished, I re-mounted as a drive, and ran grunt build and it worked!

I'm still not sure where the error was, but it seems a complete reinstall of everything was the charm. :)

As a side note, Transmit is great for being able to work directly on the server, and mounting a SFTP folder from a host on a drive, but don't try to run "npm install" etc. directly on the server that way--it takes FOREVER! Run everything locally first, then just copy all the files over and run grunt watch on the server. Saves an hour or so. ;)

**Comment by olefredrik** [comment]
I'm glad that it worked out :)

**Comment by nsberrow** [comment]
I had this error, was driving me crazy. Tried uninstalling, installing Node, in the end after 3 days of frustration it came down to the foundation.scss file, I added a custom scss and for some reason it was breaking the run build and prevented me to run watch.

Try that, see if that prevents your error.

**Comment by Aetles** [comment]
Just a FYI: when I got the `Error: libsass bindings not found. Try reinstalling node-sass` while running `npm install` a `npm rebuild node-sass` solved it.

**Comment by phylaxis** [comment]
I'm getting this error after upgrading to OS X 10.11 El Capitan. I attempted the `reinstalling node-sass` and it ran without errors. But I'm still seeing this:

```
Loading "sass.js" tasks...ERROR
>> Error: The `libsass` binding was not found in /Users/phylaxis/Sites/macobserver/tmo_wp/wp-content/themes/Observer/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node
>> This usually happens because your node version has changed.
>> Run `npm rebuild node-sass` to build the binding for your current node version.
```

I checked my Node version running a `node -v`, but I get 'v4.2.1' which is the latest on the Mac. I'm confused because in this thread it says '0.12.2' is the latest?

**Comment by arielnoname** [comment]
@phylaxis check this https://github.com/olefredrik/FoundationPress/issues/209#issuecomment-150751915

**Comment by phylaxis** [comment]
Thanks, but that didn'tt make any difference for me. Running node 0.10.33 yielded the same error

**Comment by phylaxis** [comment]
@arielnoname Ok. Got it working now. I realized I had already followed the instructions from @olefredrik to "fix" the `package.son` file to work with node 0.12.0. So I just followed your instructions, but did an `nvm install 0.12.0` and now things are working. Thanks for the help.

@olefredrik any chance on getting FoundationPress to play nice with the latest version of Node.js?

**Comment by FlakCannon** [comment]
After updating node (4.1.1) and npm (6.9.4) I am getting the same error. I have tried removing and installing node_modules with the above new package.json, clearing npm cache and still no joy. First of all I noticed you were missing the "scripts" from package.json but after adding still this error:

Error: 'libsass' bindings not found. Try reinstalling 'node-sass'?

I have tried reinstalling node-sass and rebuilding to no avail. Any ideas?

Error says to tell you this fails on my system: grunt build

Here is npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Mark\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundationpress@5.5.1~prebuild: foundationpress@5.5.1
6 silly lifecycle foundationpress@5.5.1~prebuild: no script for prebuild, continuing
7 info lifecycle foundationpress@5.5.1~build: foundationpress@5.5.1
8 verbose lifecycle foundationpress@5.5.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle foundationpress@5.5.1~build: PATH: C:\Users\Mark\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Mark\Documents\01.CLIENTS\Pauzeradio\v3\Live\www\wp-content\themes\pauzeradio\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;C:\Users\Mark\AppData\Local\Microsoft\WindowsApps;C:\Users\Mark\AppData\Roaming\npm
10 verbose lifecycle foundationpress@5.5.1~build: CWD: C:\Users\Mark\Documents\01.CLIENTS\Pauzeradio\v3\Live\www\wp-content\themes\pauzeradio
11 silly lifecycle foundationpress@5.5.1~build: Args: [ '/d /s /c', 'grunt build' ]
12 silly lifecycle foundationpress@5.5.1~build: Returned: code: 3  signal: null
13 info lifecycle foundationpress@5.5.1~build: Failed to exec build script
14 verbose stack Error: foundationpress@5.5.1 build: `grunt build`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Mark\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Mark\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid foundationpress@5.5.1
16 verbose cwd C:\Users\Mark\Documents\01.CLIENTS\Pauzeradio\v3\Live\www\wp-content\themes\pauzeradio
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mark\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.9.4
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error foundationpress@5.5.1 build: `grunt build`
22 error Exit status 3
23 error Failed at the foundationpress@5.5.1 build script 'grunt build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the foundationpress package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs foundationpress
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls foundationpress
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
