### ISSUE TITLE
Textdomain problem

### ISSUE THREAD

**Issue by HenkBarreveld** [olefredrik/FoundationPress#311]
Hi olefredrik,

I am not sure if this is the right GitHub-way to send you this, but it is the quickest for me and I think the message will come through:)

I just started with your wonderful FoundationPress and found that i18n, in order to work, requires a change in library/theme-support.php. In line 6, change the domain 'foundationpress' into CamelCase:

    load_theme_textdomain( 'FoundationPress', get_template_directory() . '/languages' );

I suppose this is because CamelCase is also used in the source, like:

    _e( ' (required)', 'FoundationPress' )

This is on a sandbox server using XAMPP 5.6.3.

Best regards,
Henk Barreveld

**Comment by Aetles** [comment]
The textdomain was recently change to lowercase as part of making FoundationPress following WordPress code style better: https://github.com/olefredrik/FoundationPress/pull/298

I think it would be better to change the source instead then.

**Comment by HenkBarreveld** [comment]
Hi Aetles,

I checked my copy of the code (19 April 2015) and it very much looks like FoundationPress has only been changed into foundationpress in the load_theme_textdomain call and nowhere else (yet). 

Like you (your comment on #298) I prefer the lowercase version, but it should of course be consistent.

**Comment by Aetles** [comment]
Absolutely, it should have been changed everywhere.

**Comment by olefredrik** [comment]
Thanks! Fixed https://github.com/olefredrik/FoundationPress/pull/315
