### ISSUE TITLE
Removing JS components

### ISSUE THREAD

**Issue by webthread** [olefredrik/FoundationPress#312]
This may not be an issue but me missing something.
I'm trying to remove some of the js components via the gruntfile on lines 73-88.
If I comment out or delete a file it seems to make no difference to the foundation.js build.
The build seems to run with no errors etc.. but the foundation.js stays the same.

Am I missing something?

**Comment by LukePettway** [comment]
Are you running grunt build after you comment them out?

**Comment by LukePettway** [comment]
@webthread Did you get a chance to try running "Grunt Build" and seeing if that resolved your issue?

**Comment by webthread** [comment]
Yes, I new I was missing something. Thanks for your quick response!

**Comment by olefredrik** [comment]
:+1:
