### ISSUE TITLE
Woocommerce Support

### ISSUE THREAD

**Issue by jacobgibbard** [olefredrik/FoundationPress#321]
Not sure if woocommerce changed the function.php support declaration or if something changed in the theme structure but I'm getting an error on new setups now.

Easily remedied by adding the woocommerce support declaration:
http://docs.woothemes.com/document/declare-woocommerce-support-in-third-party-theme/

**Comment by PharaohsTreasure** [comment]
I'm getting this message when someone clicks on the cart.
I have no idea what to do, everything is updated. Does anyone have any support for me?

PharaohsTreasureShop@aol.com

Fatal error: Call to undefined method WooCommerce::show_messages() in /home/pharaohstreasure/public_html/wp-content/themes/x/woocommerce/cart/cart.php on line 13

**Comment by jacobgibbard** [comment]
Try changing your Permalinks:

https://wordpress.org/support/topic/fatal-errors-25

**Comment by PharaohsTreasure** [comment]
Hi Jacobgibbard, 

I read that feed, do you mean when you open the page to edit it, at the top the permalink that shows the page address?    http://www.pharaohstreasure.co/cart/   Would  I then change it to something like  http://www.pharaohstreasure.co/carts/  ?

**Comment by PharaohsTreasure** [comment]
I have gone to woo commerce and under the "checkout" tab have updated the name of the page name to match the permalink "my cart" ...  and it doesn't seem to work. The best quick fix I was able to come up with was putting the "checkout" page in place of my cart page. So clicking the cart icon takes them to checkout, which is much better than going to a fatal error.... however it's not a lasting fix, since they cannot change the amount or delete items from their cart.  ... I changed the permalink to "mycart" on the page edit section as well as the title of the page to "My Cart" and then chose "mycart" page to be the go to page when someone clicks cart, but no luck.  I don't know how to downgrade to the lower level of any plugin either. 

Thank you again for your replies.

**Comment by jacobgibbard** [comment]
You should not have to change anything if you ran the WooCommerce page installer when prompted after you activated the plugin.

Have you set your websites permalinks structure? (This can be found under Settings > Permalinks)

You should have 'Post Name' selected under the common settings:
https://codex.wordpress.org/images/a/ad/permalink-settings.png

**Comment by PharaohsTreasure** [comment]
Hi,

I set the permalinks to "post" sadly the same error keeps showing.   (oddly enough my checkout page no longer calculates tax) 

Everything has been updated. as to say there are no more updates available. 

Fatal error: Call to undefined method WooCommerce::show_messages() in /home/pharaohstreasure/public_html/wp-content/themes/x/woocommerce/cart/cart.php on line 13
 

Chrystal Wright
President
Pharaohs Treasure
 
321-299-3705
www.PharaohsTreasure.co      
www.Facebook.com/PharaohsTreasure
 
Instagram: @PharaohsTreasure 



 
 
-----Original Message-----

**Comment by davenaylor** [comment]
@PharaohsTreasure Your WooCommerce template is using deprecated functions. This isn't a Foundationpress issue, it's the custom template that's been included in your theme.

You could try replacing WooCommerce::show_messages() with wc_print_notices(); inside the cart.php file shown in the above error message.

**Comment by olefredrik** [comment]
As @davenaylor said, this issue is not directly related to FoundationPress. I reckon that it is more likely to solve the problem using the woocommerce forums.

**Comment by PharaohsTreasure** [comment]
@davenaylor Thank you.  When I see that message I'm looking at the page as a customer would, do you know where I would go to do what you recommended? 
Thank you.

**Comment by PharaohsTreasure** [comment]
@jacobgibbard Thank you for your reply. I tried that, and was able to find what you meant by the permalinks. There is also a "Product Permalink Base" That has a default option or other options such as "product" "shop base" ect... Should that be default or should something else be checked?

**Comment by jacobgibbard** [comment]
@PharaohsTreasure -

Dave was advising you to add the quoted code into your WooCommerce cart.php template file.
http://docs.woothemes.com/document/template-structure/

As far as the Permalinks, that's entirely up to you and how you want your URL structure.

This board is reserved for matters related directly to the development of FoundationPress, not WooCommerce. It sounds like you might want to consider hiring a developer to help you with your project, there are lots on here such as myself. If you have anymore questions you can contact me directly through my profile.

**Comment by olefredrik** [comment]
If Github had a like button, I would probably hit it on @jacobgibbard 's comment above.
