### ISSUE TITLE
Main content columns dependent on existence of sidebar

### ISSUE THREAD

**Issue by coheractio** [olefredrik/FoundationPress#325]
First of all, thank you for this theme. Very flexible and easy to work with.

I suggest the following change to support the existence or not of the sidebar.
In the various template files, replace :
`<div class="small-12 large-8 columns" role="main">`
by :
`<div class="small-12 <?php echo ( is_active_sidebar() ) ? 'large-8' : 'large-12' ?> columns" role="main">`

Laurent

**Comment by LukePettway** [comment]
This could really be handy.

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/445
