### ISSUE TITLE
Closing div row missing for search.php?

### ISSUE THREAD

**Issue by marvinsss2005** [olefredrik/FoundationPress#327]
Hi,

Closing div row missing for search.php?

Thanks...

**Comment by brettlewis** [comment]
Could you post a row number or more details as to what div your are referencing? I see no errors.

**Comment by LukePettway** [comment]
Line 44 right before <?php get_footer(); ?> there isn't a closing </div>.

**Comment by olefredrik** [comment]
Fixed. https://github.com/olefredrik/FoundationPress/pull/402
