### ISSUE TITLE
Top Bar and Tab Bar Sticky

### ISSUE THREAD

**Issue by marvinsss2005** [olefredrik/FoundationPress#328]
Hi,

When sticky option is activated, the top bar will stick when you scroll but it's not smooth, it's like there is magnet when you reach 3 pixels down scrolling? I found out also the tab bar for small devices doesn't stick or work?

Thanks...

**Comment by olefredrik** [comment]
Hi,

Could not reproduce this error on my dev environment. Is this still an issue? Could you provide a live example?
