### ISSUE TITLE
Watch changes on js files

### ISSUE THREAD

**Issue by igarcez** [olefredrik/FoundationPress#329]
I think there should be already default, watch and rebuild js file,  I could make it work adding this to the watch directive on gruntfile

```javascript
js: {
        files: ['js/custom/**/*.js'],
        tasks: ['concat', 'uglify']
      },
```
Do you think this is valid? should I make a pull request for this?

**Comment by olefredrik** [comment]
You are probably right that 'grunt watch' should also monitor js files. While we're at it, perhaps the 'grunt watch' task should also include a livereload on change in *.php files. Feel free to post a pull request :)

**Comment by igarcez** [comment]
will do it, just need a little time! thanks!

**Comment by igarcez** [comment]
pull request created, closing this issue!
