### ISSUE TITLE
comments_template gone in Front Page

### ISSUE THREAD

**Issue by marvinsss2005** [olefredrik/FoundationPress#332]
Hi,

When i set the any page to front page the comments section of the page is gone. Automatic by default when making it front page?

Thanks...

**Comment by LukePettway** [comment]
The page is reverting to using the index.php, which doesn't have a comments section on it. 

https://github.com/olefredrik/FoundationPress/blob/master/index.php

Normally what I do for my homepage is duplicate page.php and name it page-home.php or whatever the name of the front page I want to use will be.

**Comment by marvinsss2005** [comment]
Im using hero.php template as a front page and it has comments_template totally ignored.

**Comment by olefredrik** [comment]
Hey, feel free to add in the comments_template wherever you need it. The whole point of this theme is to be a starting point for any design. Pick it apart, add the features you need get it exactly as you want.
