### ISSUE TITLE
What files do I need to upload my theme on the FTP ?

### ISSUE THREAD

**Issue by pierretusseau** [olefredrik/FoundationPress#339]
Hello,

I still have issues understanding how bower & grunt works. I know Foundationpress uses it to compile SASS. But right now I'm a bit lost when it's about finding what files in "node_modules" and "bower_component" I need to make the CSS work, after compile.

I uploaded the theme folder by folder, and now I got anything I need but those two folders I just quoted.

What are those folder used for ? 'cause they're heavy.
And which one do I need really on my final theme version, on the FTP (Without .gitignore, /scss, etc.)

**Comment by olefredrik** [comment]
Hello. You do not have to upload neither bower_components or node_modules to your production server. These are dev dependencies, which means you only need them during development. All styling gets minified and merged into foundation.css. So no need to upload any scss files.

**Comment by pierretusseau** [comment]
Well that's a bit odd, because my website isn't working without bower_component (I just tested out this)

**Comment by olefredrik** [comment]
Well that makes no sense as the default path to your stylesheet is ```/wp-content/themes/FoundationPress/css/foundation.css'```

**Comment by pierretusseau** [comment]
Yeah, I obviously am dumb. Sorry for the lost of time, but thanks for the quick backup !
