### ISSUE TITLE
Foundation not installed when "npm install" is run

### ISSUE THREAD

**Issue by f3cp** [olefredrik/FoundationPress#341]
There seems to be something wrong with either the scripts or the docs regarding the installation.
When I follow the documentation on the latest build, after I run "npm install" Foundation does not appear to be installed (The "bower_components" folder is missing).

I'm not very familiar with how node works, but looking at the package.json file I see the line "postinstall": "bower install && grunt build"

As far as I can tell, this will call bower, which would then install foundation. But "postinstall" never ran - is it suppose to run automatically?

I ran it myself, and everything is now installed.

I think either the docs needs to be updated to say you need to run the command "npm run postinstall" manually, or else the install script needs to be checked to make sure it updates automatically.

**Comment by olefredrik** [comment]
Hello. I did just a fresh install myself, and everything worked fine. Could it be that you have an old version of node installed? Run ```node -v``` in your terminal and see what version you have. I'm on Node v.0.12.0 / Mac OSX Yosemite and experiencing that everything runs smoothly.

**Comment by f3cp** [comment]
Thanks @olefredrik - my version of node was a few versions behind. I updated to the latest stable and tried again with a fresh install and "postinstall" was called and everything ran as expected. Thanks for your help.
