### ISSUE TITLE
WP admin Top bar showing over the top of the top menu bar 

### ISSUE THREAD

**Issue by dblackw** [olefredrik/FoundationPress#342]
is there an easy fix - other than moving the menu bar down using css - to stop the admin bar covering the foundation top bar?

**Comment by Eccola** [comment]
@dblackw, the easy fix is to hide the WP adminbar on front end. You can do so at My Account -page.
Unfortunately, FoundationPress does not include the Edit Post Link on its templates, so it could get tricky to get to the back end. I suggest you add it to your templates: https://codex.wordpress.org/Function_Reference/edit_post_link

**Comment by olefredrik** [comment]
@dblackw : Not sure if I understand what you mean? This is what is looks like on a fresh install. The WP-admin bar on top (if logged in, of course) and the site menu located just below. 

![admin-top-bar](https://cloud.githubusercontent.com/assets/1080017/7680459/164a624c-fd67-11e4-835e-3e724c2e8842.png)

**Comment by Eccola** [comment]
@olefredrik, I guess @dblackw is using fixed class with top-bar. We still need Edit Post Link at least on page.php and single.php. What do you think?

**Comment by dblackw** [comment]
Yes I'm using the fixed class - I have made a conditional Css fix if logged in

**Comment by Eccola** [comment]
@dblackw, how's about sharing your fix?
