### ISSUE TITLE
Do I need to upload everything to my server?

### ISSUE THREAD

**Issue by vanduzled** [olefredrik/FoundationPress#343]
Hi

It's my first time using grunt or FoundationPress for that matter.

I already generated a FoundationPress theme using Grunt. Now I'm ready to upload it to my server and use it as a theme. The folder's size is a whopping 45mb but it works fine on my localhost. When I try to upload it on my server, WordPress (or maybe my server) couldn't handle it. It'll upload for 20~30min and then a "Do you really want to do this" screen appears it goes back again.

The node_modules, bower_components and .git folder takes up a lot of space. Do I need to upload this on the server? Will it affect my theme if I don't upload them?

**Comment by olefredrik** [comment]
Hello. You do not have to upload neither bower_components or node_modules or .git to your production server. These are dev dependencies, which means you only need them during development.
