### ISSUE TITLE
"missing script: watch" When Installing

### ISSUE THREAD

**Issue by jwindeknecht** [olefredrik/FoundationPress#345]
I followed the Quickstart and once I got to *npm run watch*, I get the following error:

    yadayadayada$ npm run watch
    npm ERR! Darwin 14.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "run" "watch"
    npm ERR! node v0.12.4
    npm ERR! npm  v2.10.1

    npm ERR! missing script: watch
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     yadayadayada/npm-debug.log

Any thoughts? Thanks and let me know if you need any more info from me.

**Comment by olefredrik** [comment]
Check that you have the latest [package.json](https://github.com/olefredrik/FoundationPress/blob/master/package.json) file on your dev environment. If something is missing, please add it and run ```npm install```

**Comment by jwindeknecht** [comment]
That was it; I had an outdated package. Thanks much. -J
