### ISSUE TITLE
PHPCS gives different results than Travis CI when run locally with codesniffer ruleset

### ISSUE THREAD

**Issue by Larzans** [olefredrik/FoundationPress#352]
I have been trying for a while now to get PHPCS to behave exactly the same as the Travis CI version to be able to correct the 'errors' automatically.
Somehow when i run the command

    > wpcs\vendor\bin\phpcs.bat -p -s -v -n --standard="FoundationPress\codesniffer.ruleset.xml" "FoundationPress\library\navigation.php"
It shows me different 'errors' than the one run by Travis.

On startup it tells me 

    Registering sniffs in the FoundationPress Theme, WordPress Coding Standards Configuration standard
    DONE (42 sniffs registered)

While the Travis CI one gives us

    Registering sniffs in the WordPress Theme Coding Standards standard
    DONE (75 sniffs registered)

So it somehow loads different configurations. Now i don't know if this is due to my setup or some configuration problem (Win 7 64-bit, FoundationPress and WPCS called in subdirs).

Can somebody shed some light on this?

To me it looks as if Travis CI does not use the FoundationPress xml because the name of the standard is given as **WordPress Theme Coding Standards** and not **FoundationPress Theme, WordPress Coding Standards Configuration** as it is written in the FoundationPress\codesniffer.ruleset.xml.

**Comment by Aetles** [comment]
To me it looks like it only says `WordPress Theme Coding Standards` in  https://github.com/olefredrik/FoundationPress/blob/master/codesniffer.ruleset.xml (since the change made in https://github.com/olefredrik/FoundationPress/commit/ce2b52910b8d113ca8eb520078b6c2f9ddad7ed2).

**Comment by Larzans** [comment]
Yes, you are absolutely right. It looks like he changed the settings a couple of hours after i did my fork, i didn't notice that.

Now it looks more like the errors i am seeing on Travis bit i am not a hundred percent sure, i will see what happens with future changes :)

Thanks
