### ISSUE TITLE
Megamenu in TopBar

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#353]
Not really an issue, but does someone already wrote a Walker that would generate a Megamenu with the topbar?
I'm on the verge of doing it.
My inspiration: http://foundation.zurb.com/forum/posts/2082-mega-menu---full-width-dropdown-challenge

**Comment by FlatspinZA** [comment]
I think it's been done, you'll have to check back through the closed issues.

**Comment by zamson** [comment]
@dantahoua If you end up doing a walker for a mega menu please be kind and share it if possible :)

**Comment by dantahoua** [comment]
Finally I ended up using http://welcome.totheinter.net/columnizer-jquery-plugin/ because I didn't have much time on this one... It tested well in all browser from IE9 to IE"12" , Safari, FF, Chrome...
The CSS3 column was not good enough, so I had to use jquery...
