### ISSUE TITLE
Grunt Vs. Gulp

### ISSUE THREAD

**Issue by nusserstudios** [olefredrik/FoundationPress#357]
I would use this theme if you didnt use Grunt. Have you thought of switching to Gulp? Gulp is so much faster than Grunt.

**Comment by AdamChlan** [comment]
You would really avoid a really great theme altogether just because it uses Grunt instead of Gulp?

**Comment by radel** [comment]
I've ported a small part of the Gruntfile to Gulp for a personal project, It's not that difficult after all. I hope to find some spare time to fully port the build system from grunt to gulp, then I'll make a pull request. You can do the same, of course. This is the beauty of open source.

**Comment by Aetles** [comment]
Since FoundationPress uses libsass (through grunt-sass) it's not that slow (as it would have been with ruby SASS).

**Comment by olefredrik** [comment]
Gulp might be somewhat faster than Grunt. But libsass (through grunt-sass) is also ridiculously much faster than ruby sass. For me grunt and libsass is fast enough. Anyway, this is open source, so feel free to tear it apart to fit your needs.
