### ISSUE TITLE
double title tags

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#359]
Hi, in the header.php there is a title tag supplied at line 18, and then at line 46 a call to wp_head() which adds another title.

**Comment by jimlongo56** [comment]
I guess you need to make sure you don't declare  add_theme_support( 'title-tag' ); in your custom functions?

**Comment by olefredrik** [comment]
I was not actually not aware of that title-tag declaration via add_theme_support were supported. I see that it was introduced in version 4.1. Pull request is soon on the way. Thanks for the heads up!
