### ISSUE TITLE
Where to put custom functions?

### ISSUE THREAD

**Issue by swthate** [olefredrik/FoundationPress#360]
Sorry if this is a pretty "noob" question, but where in this theme's structure is the best place to put custom php functions? Should I put them in at the bottom of functions.php? Create a separate file in the library dir? Just wondering what the best practice would be, thanks :)

**Comment by AdamChlan** [comment]
I typically create a new file in the library dir, and call it from the functions.php file.

**Comment by swthate** [comment]
Thanks :)
