### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by swthate** [olefredrik/FoundationPress#361]
I have a custom post type and the pagination link display correctly, but nothing happens when they are clicked. When hovered, the status bar on the browser displays "localhost/page/2", I'm not sure how it's coming up with that url.

I read [Issue 286](https://github.com/olefredrik/FoundationPress/issues/286) and was hoping it would fix it for me. I was using a custom query name, $loop, but changed all references of that to $wp_query as per 286.

Sadly, my paginate links are still unresponsive.

Any ideas?

**Comment by olefredrik** [comment]
Pagination should work out of the box. Not sure I understand your challenge? See the pagination at the bottom of this demo page: http://foundationpress.olefredrik.com/category/first-category/

**Comment by swthate** [comment]
Thank you for your reply.

I'll try to explain it a little better. Here's a gist of what I think is my relevant code: https://gist.github.com/swthate/edfb3eb373df6d4123a0

I haven't edited any of the original code dealing with pagination. On my archive page for the custom post type "veterans", the pagination links are displayed, but nothing happens when I click on them.

However, when I disable my "Search & Filter Pro" plugin, the behavior changes slightly. When that plugin is disabled, the url updates to ".../page/2", but the content on the page itself doesn't change. This Search & Filter Pro plugin handles the creation of AJAX powered searching and filtering based on some of my Advanced Custom Fields.

I must be missing something with my query, and/or this Search & Filter plugin is getting in the way somehow. I just can't spot it.

Many thanks!

**Comment by swthate** [comment]
I got it fixed.

In the future, if anyone is using the [Search & Filter](http://www.designsandcode.com/wordpress-plugins/search-filter/) plugin in conjunction with FoundationPress and is having pagination problems, the problem area might be with your "results container".

To solve this I added `#search-filter-results-container` (you can use whatever name you want) to my containing row class and used that in my "results container" option and all is well now :)

**Comment by yajuvendra1990** [comment]
Is there anyway to customize next prev pagination to load more pagintaion
