### ISSUE TITLE
Problem with "centered" classes for sidebar area

### ISSUE THREAD

**Issue by HenkBarreveld** [olefredrik/FoundationPress#362]
Example: 
aside id="sidebar" class="small-12 medium-5 medium-centered large-3 large-uncentered large-pull-9 columns"

For medium viewport the sidebar widgets now appear nicely centered below the page content, but the first article element in the aside element covers the page content as well! You do not see this, unless you use Firebug or so, but the consequence is that links in the page content area "covered" by the aside do not work.

I created a work-around by adding div[role="main"] { z-index: 1; } to my scss file, but that is of course not a nice solution.

Any idea what I can do about this (other than not using medium-centered of course)?

**Comment by linuxbastard** [comment]
I doubt this would still be an issue with the new version, but is the OP still interested? It has been 2 years LOL.

**Comment by olefredrik** [comment]
I'm seeing that this has been hanging unanswered too long (sorry about that). I expect that it has been solved and is no longer an issue. Feel free to reopen if there is still a problem with this.
