### ISSUE TITLE
Top Bar Elements

### ISSUE THREAD

**Issue by joewellmade** [olefredrik/FoundationPress#364]
Hi Ole, is there a way to align the topbar nav elements with columns? I've attached a screenshot of what i'd like to try and achieve. 
![screen shot 2015-06-17 at 11 38 15](https://cloud.githubusercontent.com/assets/1428597/8205096/61029b98-14e5-11e5-9e22-4be27d43cb9b.png)

**Comment by olefredrik** [comment]
Everything is possible. But column layout in the top bar is not supported out of the box in the Foundation. As of now you can choose left and right. Or create a custom solution. If you end up creating a clever solution for this, please share :-)
