### ISSUE TITLE
how to change row width?

### ISSUE THREAD

**Issue by killerwhale65** [olefredrik/FoundationPress#365]
Hi,

I just did a fresh WP install + a fresh foundationpress install. I want to change the width of the entire content, so i guess i must change and uncomment $row-width in _settings.scss. But nothing happens when i change it. 

What could be wrong?

Thanks!

Matt

**Comment by AdamChlan** [comment]
Yes, uncommenting and changing should do the trick. I tend to create a separate scss file for settings changes, and leave the default file alone, but your method should work. Is your project being "watched" for changes so it can recompile?

**Comment by olefredrik** [comment]
Hi guys,

To change the width of the entire content, you will have to set your new desired width in the $row-width variable in _settings.scss. Personally I prefer to keep the original _settings.scss file clean, and copy the settings I need to change in a separate _custom-settings.scss file. 

In this case, copy ```// $row-width: rem-calc(1000);``` to _custom-settings.sccs, uncomment it and edit the value. You could set a new fixed rem-calc value, or use percentages. 

None of your changes in scss files will be compiled to foundation.css unless you run the grunt watch task in the background. You can do this by running  ```npm run watch ``` in your terminal, or  ```grunt watch ``` if you have installed grunt as a global dependency. Please see the quickstart guide for all the details: https://github.com/olefredrik/foundationpress#quickstart

I've attached two screenshots demonstrating what you want to achieve (click to enlarge).

![rem-calc1000](https://cloud.githubusercontent.com/assets/1080017/8215386/c3b4e7f6-152f-11e5-97a5-3d05211eb81d.png)

![100percent](https://cloud.githubusercontent.com/assets/1080017/8215389/c82f7fbc-152f-11e5-8cfe-aa31633767f5.png)
