### ISSUE TITLE
FoundationPress crashes Netbeans 7.4 (or makes it stall)

### ISSUE THREAD

**Issue by nmendrila** [olefredrik/FoundationPress#370]
Hi,

I'm not sure whether this would be solely a FoundationPress issue or a Netbeans one as well, but if I have a FoundationPress project loaded up, Netbeans starts stalling on "Background scanning of projects" and I'm not exactly sure what's causing this. In the beginning Netbeans was reporting a sass compiler was missing and would also crash/stall, but I've installed one since then. Now, it just keeps stalling.

I'm using Windows 7, Netbeans 7.4 and the latest FoundationPress version.

Any ideas why this is happening?

**Comment by olefredrik** [comment]
Hello. Unfortunately I have no experience with NetBeans.

**Comment by nmendrila** [comment]
You did a great job with the theme, and I'd really like to keep using it but it keeps crashing my installation of Netbeans :/ 

Thanks anyway.

**Comment by olefredrik** [comment]
Ok, thanks.

**Comment by FlatspinZA** [comment]
I haven't tried Netbeans with FoundationPress - WebMatrix works fine, and seems a lot less complex than Netbeans to me.
