### ISSUE TITLE
[Feature Request] Add GitHub Theme URI: olefredrik/FoundationPress to style.css

### ISSUE THREAD

**Issue by bradmkjr** [olefredrik/FoundationPress#371]
Can the following line be added to the style.css to allow the theme to be updated with the Github Updater plugin when FoundationPress when going to be used as a parent theme?
```
GitHub Theme URI: olefredrik/FoundationPress
```
For more details, please see instruction here:
https://github.com/afragen/github-updater

This will allow anyone to quickly install the theme from Github directly into the WP site using Github Updater plugin. 

I want to use FoundationPress Theme in combination with https://github.com/thetrickster/FoundationPress-child child theme, which I have cloned into my own repository for customization. I think the development of both Foundation and FoundationPress is too active for anyone to just start editing files to meet their needs, and a proper parent child theme is a better solution.

Thanks
Brad

**Comment by olefredrik** [comment]
Hi Brad, 

It's already there: https://github.com/olefredrik/FoundationPress/blob/master/style.css#L4

According to the [plugin description](https://github.com/afragen/github-updater#description), you can use either the full url (as I have done) or shorthand, as you request. Both should work. 

Or am I missing something?

Cheers,
Ole Fredrik

**Comment by olefredrik** [comment]
That said, I'm not sure if I'd go for a child-theme with FoundationPress. This theme was originally meant to be a parent starter-theme which would act as a springboard for further development. But what you should do, of course, is up to you :)

**Comment by bradmkjr** [comment]
Thank you,
I must have glanced over that line when checking for it.

My reason for preferring child theme is to keep minimal number of unique php files in the customized theme. It makes it much faster when working with a team to locate template files which may have been modified, instead of having to review all possible template files.

Thanks for the great work,
Brad
