### ISSUE TITLE
Header Image not being displayed

### ISSUE THREAD

**Issue by Glitcherx1** [olefredrik/FoundationPress#372]
I have installed FoundationPress a few days ago, and I've noticed that there's no way to display a header image.

I've partially fixed it with:
<img src="<?php echo( get_header_image() ); ?>" />

I added that code in the top-bar.php file. But I think this is a temporary.

**Comment by altjon** [comment]
Hi, in the file top-bar.php (in the parts folder) line 15, replace the <h1> tag with this:

<?php if ( get_header_image() ) : ?>
                <div class="header-logo">
                    <a href="<?php echo esc_url( home_url( '/' ) ); ?>"><img src="<?php header_image(); ?>" class="header-image" alt="<?php echo esc_attr( get_bloginfo('name', 'display') ); ?>" /></a>
                </div>              
<?php endif; ?>

Hope it helps :)
