### ISSUE TITLE
To create a blank page

### ISSUE THREAD

**Issue by carms642** [olefredrik/FoundationPress#374]
When it creates a blank page, drop-down menus does not appear,menu is happening under the blank page

**Comment by olefredrik** [comment]
Can you please add more context and information about the issue?

**Comment by mahmutkyk** [comment]
http://i.imgur.com/pSzdweK.png
http://i.imgur.com/K3eu1uA.png

**Comment by olefredrik** [comment]
Sorry mate, but I have no idea what you're talking about. I'm afraid I can not help you here.
