### ISSUE TITLE
Button Center

### ISSUE THREAD

**Issue by carms642** [olefredrik/FoundationPress#376]
How to center the button
```
<div class=" large-6 columns ">
<a href="http://yazilimodasi.com/" class="button large">Software Site</a>
</div>
```

**Comment by carms642** [comment]
,,,
<div style="text-align:center;">
<a href="http://yazilimodasi.com/" class="button large">Software Site</a>
</div>
,,,

**Comment by FlatspinZA** [comment]
Foundation provides its own classes for centering items without using 'text-align'. 

http://foundation.zurb.com/docs/utility-classes.html
