### ISSUE TITLE
Unable to change bg color of topbar from settings

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#377]
I just find out that changing those line in setting are always overriden by:

In Top-bat section of settings: 
$topbar-link-bg-color-hover: red;
$topbar-link-bg-active: red;
$topbar-link-bg-active-hover: red;

Overriden by:
.top-bar-section li.active:not(.has-form) a:not(.button){background: #272727;}

Always have to add in my global manually, not a big deal, but I wanted to point it out.

**Comment by johnReeve** [comment]
I had this problem too.  It took me a bit to figure out that this was being overridden by the default foundationpress.  Not a big deal for me either, but also it took me a little while to see it.

**Comment by dantahoua** [comment]
Yes it's in _topbar.scss
