### ISSUE TITLE
Top-bar / off-canvas parent link

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#378]
Hello.
I just find out that if you have a Parent page with content, you can't access it from the mobiles menus...

Exemple: Home->Guitars->Acoustic. If I want o access "guitars", because this page has content and is the parent of the page "acoustic", I can't from the mobile menus... I must have somewhere a walker I used a long time ago (Before foundationPress) that generate the parent link in the "sub-menu"...

**Comment by dantahoua** [comment]
Oups, my mistake, it's here, it was a CSS matter for the top-bar...
BUT for the Off-canvas, the Parent item is not generated...

**Comment by olefredrik** [comment]
This is the WP-admin menu structure for the FoundationPress demo site. 

![menu-structure](https://cloud.githubusercontent.com/assets/1080017/8728312/b6a22aee-2be4-11e5-9bee-3f3caca77dbf.png)

If you look at the site in a mobile browser, you will see that all links in the off-canvas menu works as expected. Am I missing something?

**Comment by dantahoua** [comment]
Arf, I didn't think of adding them in the mobile menu! I was stuck on the "automatic generation of the link" like in the top-bar, my head was in "coding" mod...
Sorry!
