### ISSUE TITLE
Error with bower_components not found or unreadable

### ISSUE THREAD

**Issue by RachelRVasquez** [olefredrik/FoundationPress#379]
Hi!

This is my first time with this theme and also my first time attempting npm/grunt/bower. I followed the directions from the main page under ["Quick Start"](https://github.com/olefredrik/FoundationPress) and am running the `npm run watch` command.  However every time I update my project, I'm getting this error in terminal:
'
>> file to import not found or unreadable: ../bower_components/foundation/scss/foundation/components/grid
>> Current dir: /usr/local/zend/apache2/htdocs/project-name/wordpress/wp-content/themes/my-theme/scss/
>>   Line 15  Column 9  scss/foundation.scss
Warning:  Use --force to continue.`

It doesn't appear any of my changes are showing on the front-end due to this error. I noticed I don't actually have this bower_components folder in my FoundationPress custom theme. So I tried following the [original Foundation Docs](http://foundation.zurb.com/docs/sass.html). I followed "How to install the CLI". Bower appears to be installed.

I tried to physically create the bower_components/foundation/scss path in my FoundationPress custom theme too. Still getting the error.

If it helps, I did comment out components in the grunt.js folder as well as foundation.scss.

Am I missing a step? Was that bower_components directory supposed to set itself up at some point?

Thanks. :-)

----------------------------------------

**Update:** I just tried running `npm run watch`  on a fresh copy of FoundationPress and receive the same error after installing npm in that theme. So it doesn't appear to be any customizations I made, rather something I'm missing?

**Comment by RachelRVasquez** [comment]
Resolved in https://github.com/olefredrik/FoundationPress/issues/375 - basically needed bower to install correctly, but it was a permissions issue. Then had to re-build node sass.

**Comment by olefredrik** [comment]
:+1:
