### ISSUE TITLE
bower_components Folder is missing

### ISSUE THREAD

**Issue by amelancon** [olefredrik/FoundationPress#380]
Hi,
Is there a problem with an update on GitHub but the /bower_components folder is missing.
Do I now have to install it myself from Zurb?

Regards

**Comment by olefredrik** [comment]
Hi,

If you followed the quick start instructions by running the ```npm install``` command, the bower_components folder should be there, as it gets generated by npm post install. If that did not happen for some strange reason, you could simply run ```bower install``` (if you have bower installed as a global dependency).

**Comment by amelancon** [comment]
Thanks!
