### ISSUE TITLE
Backup Buddy Zip Process Fails Since FoundationPress Update

### ISSUE THREAD

**Issue by JayCadilak** [olefredrik/FoundationPress#381]
It seems that since the latest changes to FoundationPress in which Grunt and Bower are installed via npm scripts, I am no longer able to use the BackupBuddy plugin. I have used this plugin with every single FoundationPress site I have ever made (which is a lot) and have never had any issue whatsoever. However since this major change to FoundationPress I get the following error:

-----
12:59:16.70 	4.49sec 	36.43MB	Zip process exit code: -4
12:59:16.70 	4.49sec 	36.43MB	Zip process reported: 0 warnings
12:59:16.70 	4.49sec 	36.43MB	Zip process reported: 1 error
12:59:16.70 	4.49sec 	36.43MB	Zip process reported: PCLZIP_ERR_MISSING_FILE (-4) : File 'F:/wamp/www/CanCorp/wp-content/themes/ContinuumPress/node_modules/bower/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/node_modules/duplexify/node_modules/end-of-stream/node_modules/once/node_modules/wrappy' does not exist
12:59:16.70 	4.49sec 	36.43MB	Zip Archive file not created - check process exit code.
12:59:16.71 	4.49sec 	36.43MB	Removing temporary directory.
12:59:16.71 	4.50sec 	36.43MB	The pclzip method for ZIP was unsuccessful.
12:59:16.71 	4.50sec 	36.43MB	Failed to create a Zip Archive file with any nominated method.
12:59:16.71 	4.50sec 	36.43MB	Removing temp data directory.
12:59:16.71 	4.50sec 	36.43MB	Error #4001: Unable to successfully generate ZIP archive. Backup FAILED. See logs above for more information.
-----------		-------	-------	***
-----------		-------	-------	* Unfinished function: `backup_zip_files`.
-----------		-------	-------	* No in-progress action detected.
-----------		-------	-------	***
12:59:16.71 	4.50sec 	36.43MB	ERROR: Failed function `backup_zip_files`. Backup terminated.
12:59:16.71 	4.50sec 	36.43MB	Peak memory usage: 36.427 MB
-----

That's just the snippet with the error in it. It throws up a missing file error despite the files being present. And yes, this is happening on a localhost install running off of Windows 7, but note that I have always used BackupBuddy successfully in the past using this exact process; nothing has changed except FoundationPress.

I really don't want to have to abandon FoundationPress! But BackupBuddy is far more useful so that one has to stay. This is not an issue with BackupBuddy, either, that is certain. Let me know if there is any further info I can provide to help find a solution. Thanks!

**Comment by olefredrik** [comment]
Hi,

I have no experience with the plugin you are referring to. But I can't see the benefit of backing up the ```node_modules``` and ```bower_components``` in any case. These are just dev dependencies that you don't modify (if you're doing it right). 

If I were you, I would exclude these folders from your backup routine. These folders will be automatically generated based on the contents of ```package.json``` and ```bower.json``` when running ```grunt build``` anyway.

**Comment by LukePettway** [comment]
I'd definitely avoid backing those up as well unless you absolutely need to for some reason (I don't think there really is a good reason to though). That being said, have you checked to see if that file actually exists and if it does, is it a hidden file and are the permissions okay on it? Sometimes broken permissions on a file can cause that issue as well.

**Comment by JayCadilak** [comment]
Thanks for the fast reply guys! Excluding those directories worked like a charm. I suspect the root of the problem I was experiencing lies in Windows server anyway haha. Thank you both again and olefredrik you're the man for making FoundationPress!

**Comment by olefredrik** [comment]
No worries! Glad it worked out for you :)
