### ISSUE TITLE
cannot run in wd 

### ISSUE THREAD

**Issue by krisnaw** [olefredrik/FoundationPress#387]
Hi Fredrik, 

I go this error while try to do npm install 

npm WARN cannot run in wd foundationpress@5.5.2 bower install && grunt build

For you information I tried to install it on digitalocean VPS running Ubuntu 14.04

Then when I tried to do npm run watch, I got this error: 

This failure might be due to the use of legacy binary "node"

**Comment by olefredrik** [comment]
Hi. I made a quick screencast on installing FoundationPress with npm. 
Check it out on YouTube

Make sure you have the current version of Nodejs installed https://nodejs.org/
