### ISSUE TITLE
Pass an existing project to another dev

### ISSUE THREAD

**Issue by joshsmith01** [olefredrik/FoundationPress#390]
I am about to pass an existing FP project to another developer and realized that they may not have the same setup as I do. I have never passed a project to anyone before. 

Do they follow the same Quickstart guide but with my repo instead of the FP repo? Can they just ftp everything?

**Comment by olefredrik** [comment]
If you use git, you could easily just transfer your repo to another dev. Just make sure he or she follow the instructions. That is, install nodejs and get up to speed with the recommended workflow (as described in the quickstart guide). Or you could ftp the project folder, put in on a memory stick or whatever works best for you. There is no correct or incorrect answer here. But most devs these days would probably prefer to get access to a git repository (where they can access the project history in the commit log and so on).
