### ISSUE TITLE
How to insert blog posts onto the home page?

### ISSUE THREAD

**Issue by jdfweb** [olefredrik/FoundationPress#391]
Hey all,

Just wondering how I would add blog posts onto the front page? I'd like to have them line up preferably in a row of 3 on desktop, that would be awesome. I'm not too big into PHP so I figured someone could give me a hand here.

Screenshot of design: http://i.imgur.com/VpNDM6k.jpg

Any help would... help! lol.

Cheers,
JD

**Comment by Eccola** [comment]
Hello @jdfweb, here's for starters, a very basic custom query and loop:

<div class="row">
<?php $args = array( 'post_type' => 'post', 'posts_per_page' => 3 );
$the_query = new WP_Query( $args );
if ( $the_query->have_posts() ) :
while ( $the_query->have_posts() ) : $the_query->the_post();?>
<div class="large-4 columns">
<?php $thumb = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'post-thumbnail' );$url = $thumb['0'];?>
<a href="<?php the_permalink();?>"><img src="<?php echo esc_url($url); ?>"  alt="" /></a>
<h3><a href="<?php the_permalink();?>"><?php the_title();?></a></h3>
<?php foundationpress_entry_meta(); ?>// see: /library/entry-meta.php
<span><?php the_excerpt();?></span>
<a class="button medium" href="<?php the_permalink();?>">Read more</a>
</div>
<?php endwhile; endif; wp_reset_postdata();?> 
</div>
