### ISSUE TITLE
Jquery never registered in enqueue-scripts.php and enqueued twice?

### ISSUE THREAD

**Issue by rebekahmonson** [olefredrik/FoundationPress#397]
When adding some custom scripts in [enqueue-scripts.php](https://github.com/olefredrik/FoundationPress/blob/master/library/enqueue-scripts.php), I noticed the following:

1. Wordpress version of jquery is deregistered.
```
// Deregister the jquery version bundled with WordPress.
	wp_deregister_script( 'jquery' );
```
2. CDN version of jquery is enqueued (but not registered).
```
// CDN hosted jQuery placed in the header, as some plugins require that jQuery is loaded in the header.
	wp_enqueue_script( 'jquery', '//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js', array(), '2.1.0', false );
```
3. Then jquery is enqueued again.
```
wp_enqueue_script( 'jquery' );
```
Everything seems to be working, as-is, I just wasn't sure why jquery was enqueued twice and not registered. Could someone help me learn?

Sorry for the noob question, and thanks for the help. This is my first full-on theme build, and it's been great to learn using FoundationPress. Thanks for your hard work. :raised_hands:

**Comment by kermage** [comment]
A typo, should be
```
wp_register_script( 'jquery', '//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js', array(), '2.1.0', false );
```
or could leave it as is and just delete the last enqueue line
```
wp_enqueue_script( 'jquery' );
```

**Comment by rebekahmonson** [comment]
Thanks! Glad to know I'm not crazy. Thanks!
