### ISSUE TITLE
Error with "npm run watch"

### ISSUE THREAD

**Issue by bekircem** [olefredrik/FoundationPress#399]
Hi,

I have problem with "npm run watch" command. Here is the screenshot:

http://prntscr.com/7zztyd

Edit: It my mistake. It fixed. Thanks. :)

**Comment by olefredrik** [comment]
Not quite sure what's going on here, as you didn't attach the debug log. But you could try ```npm rebuild node-sass``` .

**Comment by olefredrik** [comment]
There have been a known issue with ```npm grunt build```. The issue is now fixed. See this thread for details: https://github.com/olefredrik/FoundationPress/issues/386

And, of course, you will need to run a ```npm install``` before you can build or watch.
