### ISSUE TITLE
WooCommerce compatability

### ISSUE THREAD

**Issue by standardspace** [olefredrik/FoundationPress#40]
Hi,
Apologies, this is plugin related so feel free to ignore.
Activating WooCommerce causes the off-canvas navigation to become unresponsive ie. Clicking on the burger icon no longer triggers the slide in.
Here's a screenshot from Chrome Dev Tools
![screen shot 2014-05-07 at 16 22 23](https://cloud.githubusercontent.com/assets/517903/2904421/736d6be8-d5fb-11e3-9cf7-ede45bc6ae19.png)

Any ideas?

**Comment by zitrusblau** [comment]
Well, it's actually even simpler to be done.

WooCommerce does a version check in class-wc-frontend-scripts.php (function check_jquery()) whether the enqueued jquery core script is at least at version 1.8. If not, it uses the one shipped w/ woocommerce.

Now, to fix it just change the version on the script enqueuing part of your foundation theme, like in /library/enqueue-scripts.php and use the version string from /js/vendor/jquery.js (i.e. '2.1.1')

@olefredrik you should use those version strings anyway.
