### ISSUE TITLE
Entry Content Class Twice 

### ISSUE THREAD

**Issue by LukePettway** [olefredrik/FoundationPress#401]
I'm not sure if this is intended or necessarily a bug but I figured it would be worth mentioning just in case. I was working on a blog roll and noticed that there is an entry content container div with <?php the_content(); ?> inside of it which creates another .entry-content element.

			<div class="entry-content">
				<?php the_content(); ?>
			</div>

Both page-full.php and single.php have this occurrence so I was wondering if it is necessary to repeat that element a second time as removing it hasn't had any impact in what I am currently working on.

**Comment by AdamChlan** [comment]
Can you confirm the version of FoundationPress you are using. Looking at the demo site full width page and single page - 

http://foundationpress.olefredrik.com/page-templates/full-width/
http://foundationpress.olefredrik.com/post-with-an-image-and-caption/

I don't believe I am seeing the duplicate. Maybe an older version had this issue?

**Comment by LukePettway** [comment]
@AdamChlan good point, it looks like something must have changed within the last few times I've used the theme! All good now. Doh x)
