### ISSUE TITLE
How to NOT install local bower & grunt?

### ISSUE THREAD

**Issue by Eccola** [olefredrik/FoundationPress#405]
A question: I have bower & grunt installed globally on my server. What would be the best approach to not install them locally, to minimize disk space usage?

**Comment by pmccauley** [comment]
I would have a local development server and then only deploy the theme files not the node and bower files, or even scss For example I have a local WP that I use as dev. I then would setup a separate grunt command to push to the test / production server.

Other than that I would use an ftp and only deploy the files, folders you need for the theme.

**Comment by Eccola** [comment]
@pmccauley , thanks for your answer. Not quite what I was looking for. What I meant was how to run npm install without installing bower & grunt as local dependencies.

**Comment by Aetles** [comment]
You could look at the changes that where made in https://github.com/olefredrik/FoundationPress/commit/85e631db7a7b9ded92a37caf48f38407ab0ed513 where the global dependencies where removed.

**Comment by Eccola** [comment]
@Aetles, that's what I thought.. So it looks I have to install the 80 megabytes of node_modules for every theme development project. It was just mere 24 megabytes before the global dependencies were removed.

**Comment by Aetles** [comment]
Yeah, that's a drawback but I still think it's better than using global installations. John Albin Wilkins wrote [a convincing article](https://www.previousnext.com.au/blog/getting-started-front-end-automation-intro-npm) about why installing packages globally is not recommended.

**Comment by Eccola** [comment]
Ok, thanks, good read, I'm convinced, though I've never had any problems with global installations .
