### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by peteratomic** [olefredrik/FoundationPress#408]
Getting this error message in my Firebug console:

`TypeError: $ is not a function

...document),jQuery(document).foundation(),$("#start-jr").on("click",function(){$(d...
	
foundation.js (line 4, col 9648)`

The developer of a sticky footer for foundation said that this error was preventing his script from firing. That possible?

**Comment by runofthemill** [comment]
jQuery runs in Safe Mode by default on Wordpress, so $ doesn't work out of the box. 

Have you set up a wrapper function? If not, check out the [Wordpress Codex](https://codex.wordpress.org/Function_Reference/wp_enqueue_script#jQuery_noConflict_Wrappers) entry w/ details of how to allow $ to work.

**Comment by peteratomic** [comment]
Had to come back to this as a plugin developer is telling me that this error is preventing his plugin from working. Checked the codex link mentioned above but there's nothing mentioned about "wrapper functions".

I don't need joyride and need to know exactly what to delete to make the error go away. Have tried six or seven variations but it either kills the script or just results in different errors.

**Comment by peteratomic** [comment]
For anyone else having this problem, this is what you need to delete at the end...

`,$("#start-jr").on("click",function(){$(document).foundation("joyride","start")})`
