### ISSUE TITLE
Offcanvas overlap

### ISSUE THREAD

**Issue by hellofantastic** [olefredrik/FoundationPress#409]
From the foundation docs it seems all I need to do Is add 
```javascript
$(document).foundation({
offcanvas : {
    open_method: 'overlap'
  }
});
```
But it still moves left instead of overlapping 

I have added this in app.js

Things to note I'm not on a setup where I have the grunt bower and whatever else it's all manual edit and save...
no command line on a particular shared host

Foundation press Im using is fairly recent, I can see overlap overlap_single in the foundation.js

Any insight?

**Comment by olefredrik** [comment]
Hi,

I just verified that the offcanvas overlap setting is working well when using grunt.

![screen shot 2015-08-24 at 17 39 12](https://cloud.githubusercontent.com/assets/1080017/9444497/6660d334-4a87-11e5-8b7e-b92d849fb58e.png)

When ```npm run watch``` or ```grunt watch``` is running in the background, the task runner is watching for changes in your themes directory. Stuff will happen each time you hit save.

![screen shot 2015-08-24 at 17 43 23](https://cloud.githubusercontent.com/assets/1080017/9444540/b75a0a3a-4a87-11e5-90ce-28e2cea0f9a6.png)

I would absolutely recommend using grunt as a part of your workflow.

**Comment by hellofantastic** [comment]
Client is on a cloud site without shell access so all those goofiest are not an option

**Comment by olefredrik** [comment]
If you setup a local dev environment (using MAMP for mac or WAMP for windows), you won't need shell access to the client cloud site. It's recommended that you do all development locally, then do a ```grunt build``` and transfer the minified files to the client server. Note that the ```node_modules```, ```bower_components``` and ```scss``` folders are dev dependencies, meaning they don't need to be put on the production server. Grunt will concatinate and minify your scripts and styles, optimized for speed and performance.

**Comment by hellofantastic** [comment]
Right of course ... Free time permitting I'll get my local setup dialed. Thanks.
