### ISSUE TITLE
/js/vendor/ contents are gitignored

### ISSUE THREAD

**Issue by zanetaylor** [olefredrik/FoundationPress#415]
Any additions or updates to these files are excluded from the repo, breaking deployment.

**Comment by olefredrik** [comment]
The /js/vendor contents will be automatically updated when running ```grunt build``` :
https://github.com/olefredrik/FoundationPress/blob/master/Gruntfile.js#L26

I don't see how this is breaking deployment. Can you please elaborate on your concern?
