### ISSUE TITLE
How to understand the current version?

### ISSUE THREAD

**Issue by oviliz** [olefredrik/FoundationPress#423]
I'm running FoundationPress 5.5.2 but here the changelog currently shows 1.1.0. The template is based on Foundation 5 and checking their website actually the latest version is 5.5.2.
This is a little confusing for me... How I should proceed for an eventually update?

**Comment by Aetles** [comment]
Semantic versioning [was introduced recently](https://github.com/olefredrik/FoundationPress/releases/tag/v1.0.0), see the discussion behind it [in this issue](https://github.com/olefredrik/FoundationPress/issues/395).
