### ISSUE TITLE
Strange menu icon problem when viewing site in mobile mode

### ISSUE THREAD

**Issue by pipallnut** [olefredrik/FoundationPress#429]
Hi,

I am having an issue with the menu icon when I view my site in mobile viewport size, it seems the menu icon is being duplicated. Sadly, I cannot figure out how I have managed to do this.

Can you help please? You should be able to view the issue here http://www.northerncityjfc.website

Cheers

Phil

**Comment by olefredrik** [comment]
Hi,

Have no idea how this have happened, to be honest. But the cause of your error is here:

![screen shot 2015-08-24 at 17 31 38](https://cloud.githubusercontent.com/assets/1080017/9444319/2a756688-4a86-11e5-9b7e-c4dea3c91dc4.png)

If I was able to reproduce the error on the master branch, I could debug the error and apply a patch. But everything seems to work well on a clean install.

**Comment by pipallnut** [comment]
Thanks for responding. I will try a clean install to fix this.
