### ISSUE TITLE
Where did the css folder go?

### ISSUE THREAD

**Issue by addisonlegere** [olefredrik/FoundationPress#431]
I just downloaded the zip and found that the "css" folder is no longer in there. This is a problem as the site is trying to load files located in this folder and says it has failed to load(404).

**Comment by olefredrik** [comment]
Hi @addisonlegere ,

That's correct. The ```css``` folder was added to .gitignore in this pull request last week https://github.com/olefredrik/FoundationPress/pull/419

```css/foundation.css```, ```css/foundation.css.map``` and ```js/foundation.js``` are part of the build process and shall therefore not be tracked by git.

After downloading the project (or cloning the repository) you will need to run ```npm install```. This will trigger a ```grunt build``` which will automatically build your css files, based on the content in the scss files.

I hope that this was clarifying?
