### ISSUE TITLE
Top Bar Button

### ISSUE THREAD

**Issue by indadam** [olefredrik/FoundationPress#436]
Quick question: how do you use the button within the Top Bar in FoundationPress? In your Kitchen Sink file you're utilizing the button in the Top Bar at the top, and there's the documentation on Foundation's site (http://foundation.zurb.com/docs/components/topbar.html#built-in-components), but is the only way to have a button to hardcode it and not use WordPress's menu system?

**Comment by olefredrik** [comment]
Hi @indadam,

In the Appearance -> Menus in WP-admin, you can set custom css classes on each menu item. For the 'Getting started' button in the top-bar on the demo site, I've added the css class ```has-form ```.

<img width="441" alt="screen shot 2015-08-29 at 18 17 12" src="https://cloud.githubusercontent.com/assets/1080017/9562938/3a1390cc-4e7a-11e5-84c4-8de37575545b.png">

**Comment by indadam** [comment]
I'm not sure it's working correctly, here's my menu settings: 
![screen shot 2015-09-01 at 10 20 57 am](https://cloud.githubusercontent.com/assets/6856247/9611206/33fd9fd2-5093-11e5-8c48-7c8715090808.png)

But, here's how it's displaying: 
![screen shot 2015-09-01 at 10 19 56 am](https://cloud.githubusercontent.com/assets/6856247/9611213/3c01aaca-5093-11e5-9327-c6a3ffb20ce9.png)

**Comment by ecclescake** [comment]
I encountered the exact same issue (second button not receiving button styles).

This is caused by the parameters for preg_replace() used in foundationpress_add_menuclass(), which is defined in library/navigation.php.

For my purposes, I changed the limit parameter (the last one) from 1 to -1, or no limit. That might work for you too, @indadam.

**Comment by indadam** [comment]
@ecclescake thank you, I'll give it a try!
