### ISSUE TITLE
Download (zip) not working

### ISSUE THREAD

**Issue by Magic4you** [olefredrik/FoundationPress#437]
Normally I could download a zip and install and everything works. But not yet, if I do this, the theme looks broken. Did you change something what I missed? screenshot is attached
<img width="791" alt="bildschirmfoto 2015-08-30 um 22 13 41" src="https://cloud.githubusercontent.com/assets/12445413/9569201/a6fde238-4f64-11e5-9175-401d6460b241.png">

and here screenshot with older version

<img width="1007" alt="bildschirmfoto 2015-08-30 um 22 14 18" src="https://cloud.githubusercontent.com/assets/12445413/9569212/f7969ac8-4f64-11e5-8d2d-ee1f30bc1bf7.png">

is there a Problem with WP 4.3 ?

**Comment by olefredrik** [comment]
The css file is not longer under version control, as it is automatically generated by grunt build. Please follow the quickstart instructions, and you will be fine.

**Comment by Aetles** [comment]
Based on this and other issues lately it seems like a lot of people are using FoundationPress as is, without SASS and grunt workflow. It just became apparent when the generated CSS was removed.

**Comment by olefredrik** [comment]
@Aetles : I think you're right. That said, I can not quite understand why anyone would want to use a sufficiently advanced theme such as this, if one is not interested in utilizing the SASS and grunt workflow. Anyway, I guess I could re-add the .css and .js files to the repository to avoid confusion for those who just want to use it as-is.

**Comment by Magic4you** [comment]
I work with SASS but, if I could download, all the time the theme, without any preparation I was wondering whats happend now ...
I use it on a mac with sublime and codekit and normaly i could copy that zip and all was good.
For this reason Iam happy with a changelog, so that I can see whats happend since my last download ...

Thanks for the work and the good theme !!

**Comment by olefredrik** [comment]
:+1:
