### ISSUE TITLE
Issues with WordPress Admin Panel

### ISSUE THREAD

**Issue by sbuckowing** [olefredrik/FoundationPress#441]
FoundationPress causes the Admin Menu to overlay the posts and pages Administration screens so you can't read the content along the left edge. The other admin pages such as plugins all push the content over.

**Comment by olefredrik** [comment]
Could you please provide a screenshot of the error? As I'm not able to reproduce the error on my side, a visual explanation would be helpful.

**Comment by sbuckowing** [comment]
![capture](https://cloud.githubusercontent.com/assets/10672275/9605330/a65248be-5082-11e5-9adf-e85138912c3b.JPG)

**Comment by LukePettway** [comment]
Could you provide some info as far as OS/Browser?

**Comment by sbuckowing** [comment]
Windows 10 .. edge browser. I'll try it in another browser and see if it works correctly.

Thank you,

Sherry Buckowing



On Tue, Sep 1, 2015 at 8:01 AM -0700, "Luke Pettway" <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you provide some info as far as OS/Browser?

-

**Comment by sbuckowing** [comment]
I tried it in firefox and ie and have the same issue. For whatever reason the wordpress login isn't working in chrome so I wasn't able to try it there.

**Comment by LukePettway** [comment]
That's very odd, I tested in FF and I'm not seeing the issue, but I am able to recreate it visually by changing the styling of .wp-submenu to make left: 20px instead of auto.  Have you tried disabling plugins, and anything else that might be affecting the CSS in the Admin Panel?

**Comment by sbuckowing** [comment]
Yes. It seems to be the actual foundation.css file that is causing it because it I unlink it, it corrects the error.

Thank you,

Sherry Buckowing



On Wed, Sep 2, 2015 at 6:35 AM -0700, "Luke Pettway" <notifications@github.com<mailto:notifications@github.com>> wrote:


That's very odd, I tested in FF and I'm not seeing the issue, but I am able to recreate it visually by changing the styling of .wp-submenu to make left: 20px instead of auto. Have you tried disabling plugins, and anything else that might be affecting the CSS in the Admin Panel?

-

**Comment by sbuckowing** [comment]
I found the issue. It's the .fixed element in foundation.css that was doing it. The edit.php page in Wordpress uses fixed as part of the table layout and the foundation.css was breaking it.
