### ISSUE TITLE
Using jQuery bundled with WordPress

### ISSUE THREAD

**Issue by David-van-den-Bor** [olefredrik/FoundationPress#451]
Hi, Ole! I just have a small question regarding enqueuing scripts in FoundationPress. Is it also possible to enqueue scripts and styles like so? (using the jQuery version that comes with WordPress?)

```php
<?php
/**
 * Enqueue all styles and scripts
 */
if ( ! function_exists( 'foundationpress_scripts' ) ) :
  function foundationpress_scripts() {
  // Enqueue the main Stylesheet.
  wp_enqueue_style( 'main-stylesheet', get_stylesheet_directory_uri() . '/css/foundation.css' );
  // Enqueue all registered scripts.
  	wp_enqueue_script( 'modernizr', get_template_directory_uri() . '/js/vendor/modernizr.js', array(), '2.8.3', false );
  	wp_enqueue_script( 'fastclick', get_template_directory_uri() . '/js/vendor/fastclick.js', array(), '1.0.6', false );
  	wp_enqueue_script( 'foundation', get_template_directory_uri() . '/js/foundation.js', array('jquery'), '5.5.2', true );
  }
  add_action( 'wp_enqueue_scripts', 'foundationpress_scripts' );
endif;
?>
```

The above loads the **no-conflict mode** version of jQuery **bundled with WordPress**? So jQuery code using the $ variable will probably need this hack:

```javascript
jQuery(document).ready(function($) {
 // /* You can safely use $ in this code block to reference jQuery */
});
```
In order for jQuery scripts in plugins or Foundation to work(?) 

My version of enqueuing scripts doesn't seem to break FoundationPress, so what's your reason for doing it the way you do in your **enqueue-scripts.php**? Is yours better, or is it pure preference?
Also confusing: half of the WP community advises to use the CDN call, the other half strongly advices **against** it! 

The CDN way in your **enqueue-scripts.php** of course works for Foundation, but will I run into trouble (down the line) with plugins who use jQuery coding style in no-conflict mode fashion? (which is the "best practice" way WordPress tells them to do so)

Regards, and thanx in advance :-)

**Comment by olefredrik** [comment]
Hi, David. It has proven to be challenging to get all Foundation components to operate correctly with the WordPress bundled version of jQuery. There are certainly several ways to solve this, but one of [the recommended methods](http://www.thewirelessguy.co.uk/2013/03/using-zurbs-foundation-framework-4-with-wordpress-jquery/) is to deregister the jQuery that is bundled with WordPress, and load a CDN version of jQuery instead. 

There are many opinions out there about whether it is good or bad to use CDN's. I'm no expert in this domain, but [I understand that there are certain advantages to doing it this way.](https://gtmetrix.com/why-use-a-cdn.html). 

As long as speed, availability and compatibility is safeguarded, I'm open to any suggestions :)
