### ISSUE TITLE
Sticky bar and Admin Bar

### ISSUE THREAD

**Issue by brettlewis** [olefredrik/FoundationPress#452]
If sticky is used on the nav bar, the admin bar overlaps it.

fix applied in _wp-admin.scss

body.admin-bar.f-topbar-fixed{
    .sticky.fixed {
        margin-top: 32px;
    }
}

**Comment by olefredrik** [comment]
Thanks! Fixed https://github.com/olefredrik/FoundationPress/pull/456

**Comment by steelwolf** [comment]
This issue appears to be occurring again. When the sticky nav bar is set to "top" it jumps to the top of the document regardless of whether or not the admin bar is present.

**Comment by MrAndreius** [comment]
@steelwolf 
I have to solve this problem myself
add `$data_margin_top = (is_admin_bar_showing()) ? '2' : '0';`
`<div data-sticky data-margin-top="<?php echo $data_margin_top; ?>" style="width:100%" data-top-anchor="header-media:bottom" data-btm-anchor="footer-container:bottom">`

just enter your anchor

**Comment by steelwolf** [comment]
Oh wow, good thought. Works perfectly, thanks.
