### ISSUE TITLE
Let's use autoprefixer for prefixing

### ISSUE THREAD

**Issue by KLVTZ** [olefredrik/FoundationPress#453]
Idea
------
Let's use [autoprefixer](https://github.com/postcss/autoprefixer) for supporting older browsers. Since we are dependent on grunt, we could take advantage of [grunt-postcss](https://github.com/nDmitry/grunt-postcss). In our current project we have our task setup as the following:

```
...
    postcss: {
      options: {
        map: true,
        processors: [
          require('autoprefixer')({browsers: 'last 2 versions'})
        ]
      },
      dist: {
        src: 'assets/css/foundation.css'
      }
    }
  });

  grunt.loadNpmTasks('grunt-sass');
  grunt.loadNpmTasks('grunt-postcss');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-string-replace');


  grunt.registerTask('build', ['copy', 'string-replace:fontawesome', 'sass',
    'postcss', 'concat', 'uglify']);
  grunt.registerTask('default', ['watch']);
};
```

Discussion 
---------------
Some projects take responsibility in adding this as a bonus. Others do not. This decision is up to the project maintainer in deciding if it should be the projects responsibility in including this. To many, the above packages are default in css prefixing. In addition, postcss projects are heavily maintained by many contributors. As a front-end theme/package, you care about compatibility with as many browsers as possible. Or you may feel that such details should be left to the responsibility of the person that digests it. 

From my perspective, I think it is something that should be added. But other developers feel different:
https://github.com/ConnorAtherton/loaders.css/issues/18#issuecomment-91104907

**Comment by radel** [comment]
Lovely, I often add this too.
+1 for including it in the build process.

**Comment by KLVTZ** [comment]
For full reference of the above snippet: https://gist.github.com/569f1a48fe61aa519be0

**Comment by LukePettway** [comment]
I would really love to see this added.

+1

**Comment by arielnoname** [comment]
+1

**Comment by AllyReid** [comment]
+1

**Comment by olefredrik** [comment]
Done https://github.com/olefredrik/FoundationPress/pull/544
