### ISSUE TITLE
npm run watch fails

### ISSUE THREAD

**Issue by jochienabuurs** [olefredrik/FoundationPress#460]
<img width="577" alt="screen shot 2015-09-09 at 21 09 30" src="https://cloud.githubusercontent.com/assets/1541475/9771529/21a90484-5737-11e5-853f-2ad984c2def5.png">

Here is the npm log contents:

    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'watch' ]
    2 info using npm@2.14.1
    3 info using node@v0.12.2
    4 verbose node symlink /usr/local/bin/node
    5 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
    6 info prewatch foundationpress@1.4.0
    7 info watch foundationpress@1.4.0
    8 verbose unsafe-perm in lifecycle true
    9 info foundationpress@1.4.0 Failed to exec watch script
    10 verbose stack Error: foundationpress@1.4.0 watch: `grunt watch`
    10 verbose stack Exit status 1
    10 verbose stack     at EventEmitter.<anonymous>         (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
    10 verbose stack     at EventEmitter.emit (events.js:110:17)
    10 verbose stack     at ChildProcess.<anonymous>     (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    10 verbose stack     at ChildProcess.emit (events.js:110:17)
    10 verbose stack     at maybeClose (child_process.js:1015:16)
    10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    11 verbose pkgid foundationpress@1.4.0
    12 verbose cwd /Users/jochem/Sites/foodly/wp-content/themes/foodly
    13 error Darwin 14.5.0
    14 error argv "node" "/usr/local/bin/npm" "run" "watch"
    15 error node v0.12.2
    16 error npm  v2.14.1
    17 error code ELIFECYCLE
    18 error foundationpress@1.4.0 watch: `grunt watch`
    18 error Exit status 1
    19 error Failed at the foundationpress@1.4.0 watch script 'grunt watch'.
    19 error This is most likely a problem with the foundationpress package,
    19 error not with npm itself.
    19 error Tell the author that this fails on your system:
    19 error     grunt watch
    19 error You can get their info via:
    19 error     npm owner ls foundationpress
    19 error There is likely additional logging output above.
    20 verbose exit [ 1, true ]

Can you tell me what's wrong. It has worked before...

**Comment by olefredrik** [comment]
Try npm install followed by a npm run watch. Do you still get an error message?

**Comment by sean4500** [comment]
I'm having the same issue but when I try "npm install" I'm getting the following errors
![screen shot 2015-09-09 at 1 23 08 pm](https://cloud.githubusercontent.com/assets/427399/9773231/1685f512-56f6-11e5-9756-0fe3e485249c.png)

**Comment by jochienabuurs** [comment]
Npm install works without errors but npm run watch fails as I mentioned. Will try to take a look at it tomorrow again...

Verstuurd vanaf mijn iPhone

**Comment by olefredrik** [comment]
Hi @jochienabuurs  and @sean4500 ,

I just cloned the FoundationPress repository to a test folder. Both ```npm install``` and ```npm run watch``` seems to run just fine on my Macbook Pro.

![npm-watch](https://cloud.githubusercontent.com/assets/1080017/9781682/609f2852-5797-11e5-8ce5-06292d187fa8.png)

That said, I have not tested compatibility with latest major version of Nodejs which was released a few days ago. Here are the versions I'm on

![screen shot 2015-09-10 at 08 39 51](https://cloud.githubusercontent.com/assets/1080017/9781702/85cfa39a-5797-11e5-83e6-a16469f2e44e.png)

Have you installed or updated Node during the last few days? Can you check what version you're on?

**Comment by jochienabuurs** [comment]
[image: Inline afbeelding 1]

Note that I use older versions... updated node and npm...

[image: Inline afbeelding 2]


Still not working... but then i noticed the following message...

[image: Inline afbeelding 1]


Apparently, I had another terminal window open that was already watching
the same directory.
Mental note: check for open terminal windows when encountering an error...

Met vriendelijke groet,


*Jochem NabuursJaffiro*
Koninginnelaan 97  |  6542 ZK Nijmegen  |  T 024 845 7867  |  M 06 52 09 10
09  |  www.jaffiro.nl

2015-09-10 8:42 GMT+02:00 Ole Fredrik Lie <notifications@github.com>:

**Comment by sean4500** [comment]
Looks like I am running the most up-to-date versions of Node and NPM, I'll try rolling back to the versions you're running to see if that helps.

![screen shot 2015-09-10 at 11 06 12 am](https://cloud.githubusercontent.com/assets/427399/9796695/58e457e4-57ac-11e5-89ab-1cba4a04a339.png)

**Comment by sean4500** [comment]
I've rolled back to Node v0.12.4 and everything is working fine.

Thanks for the help

**Comment by olefredrik** [comment]
:+1:
