### ISSUE TITLE
FoundationPress will not install with Node.js version 4.0

### ISSUE THREAD

**Issue by timeighty5** [olefredrik/FoundationPress#461]
Installing version 0.1.5 (https://nodejs.org/dist/v0.12.5/) allowed grunt to install correctly.

**Comment by torican** [comment]
Same problem here and the suggested fix worked. OS X 10.10.2 - was receiving Xcode errors

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/478

**Comment by xiaohangJose** [comment]
i have this problem with node-8.00
