### ISSUE TITLE
"Display Header Text" Checkbox Not Displaying in Customizer

### ISSUE THREAD

**Issue by lmvincent** [olefredrik/FoundationPress#464]
I can't get the default "Hide Header Text" checkbox to display in Customizer when using FoundationPress. This checkbox usually strips the text version of the blog name and/or description out of the header when the user checks it (screenshot of the typical display from twentyfifteen). I've tried to figure out where it might have been removed, and tried to force it back but haven't had much luck.
![screen shot 2015-09-14 at 12 54 12 pm](https://cloud.githubusercontent.com/assets/510493/9860315/4106ec04-5ae0-11e5-8f00-3c03bc3abd6c.png)

**Comment by linuxbastard** [comment]
It's a bit involved but basically you create a function that will add the settings. Please refer to the WP Theme Customization API.

https://codex.wordpress.org/Theme_Customization_API

And here's a small tutorial on adding new settings and controls to the 'title_tagline' section or the 'Site Identity' section of the customizer:

https://getflywheel.com/layout/how-to-add-options-to-the-wordpress-customizer/

I would enclose the site name and tagline inside an if statement that checks if the control for your new setting is ticked.
