### ISSUE TITLE
Have you considered supporting Gulp?

### ISSUE THREAD

**Issue by cyberscribe** [olefredrik/FoundationPress#466]
Would you consider supporting a gulp-based build process alongside the existing grunt process? Or switching at some point? I look forward to your thoughts.

**Comment by olefredrik** [comment]
I am no stranger to the idea of replacing Grunt with Gulp. From what I understand, Gulp will be the preferred task manager for Foundation 6. So then it would be natural to move in that direction when the time comes. That being said, Grunt works pretty good in my view. But if Gulp is faster and better, why not :)

**Comment by LukePettway** [comment]
This would be exciting!
