### ISSUE TITLE
Custom Header Image

### ISSUE THREAD

**Issue by ghost** [olefredrik/FoundationPress#467]
I have a question I've just installed your theme and love it so far, the only problem I have is when I go to the theme customizer and add a new Header Image it won't show up. Is there something I missed or do I have to add some code into the theme. Thank you for your help.

**Comment by arielnoname** [comment]
This is part of my header.php for example

![screen shot 2015-11-22 at 8 15 07 pm](https://cloud.githubusercontent.com/assets/11996305/11326937/c8eda9ae-9155-11e5-9b42-cac93c025951.png)

**Comment by Eccola** [comment]
@ghost,  Header Image is used as background image for the masthead in WordPress default themes.

Header Image could be used for a logo image. This snippet is from Automattic _s underscores theme:

```
<?php if ( get_header_image() ) : ?>
<a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home">
<img src="<?php header_image(); ?>" width="<?php echo esc_attr( get_custom_header()->width ); ?>" height="<?php echo esc_attr( get_custom_header()->height ); ?>" alt="" />
</a>
<?php endif; // End header image check. ?>
```
