### ISSUE TITLE
NPM build error

### ISSUE THREAD

**Issue by oksodavid** [olefredrik/FoundationPress#468]
Hi,
Originally I had Node4.0 but now have v0.12.5 after reading threads on similar issues.
Any help really appreciated. Here's the log.

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild foundationpress@1.4.0
6 info build foundationpress@1.4.0
7 verbose unsafe-perm in lifecycle true
8 info foundationpress@1.4.0 Failed to exec build script
9 verbose stack Error: foundationpress@1.4.0 build: `grunt build`
9 verbose stack Exit status 3
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid foundationpress@1.4.0
11 verbose cwd /wp-content/themes/theme
12 error Darwin 10.8.0
13 error argv "node" "/usr/local/bin/npm" "run" "build"
14 error node v0.12.5
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error foundationpress@1.4.0 build: `grunt build`
17 error Exit status 3
18 error Failed at the foundationpress@1.4.0 build script 'grunt build'.
18 error This is most likely a problem with the foundationpress package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt build
18 error You can get their info via:
18 error     npm owner ls foundationpress
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by olefredrik** [comment]
Have you tried this https://github.com/olefredrik/FoundationPress/issues/475 ?

**Comment by oksodavid** [comment]
@olefredrik yes, sorry, I commented in Error on npm install #465. I still have build error after following your workaround

**Comment by olefredrik** [comment]
I think I might got it. Use nvm to install the most recent version of Node


```nvm install 4.1.1``` and make sure you use the latest version by typing ```nvm use 4.1.1```

Then clone a fresh version of the FoundationPress repository. And BEFORE you do a ```npm install```, replace the contents of package.json with the following

```
 {
  "name": "foundationpress",
  "title": "FoundationPress",
  "version": "1.4.0",
  "description": "FoundationPress is a WordPress starter theme based on Foundation 5 by Zurb",
  "keywords": [
    "FoundationPress",
    "WordPress",
    "starter theme",
    "Foundation",
    "semantic",
    "mobile first",
    "customizable",
    "responsive"
  ],
  "homepage": "http://foundationpress.olefredrik.com/",
  "bugs": "https://github.com/olefredrik/FoundationPress/issues",
  "license": "MIT",
  "main": "Gruntfile.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/olefredrik/FoundationPress.git"
  },
  "devDependencies": {
    "bower": "~1.4.1",
    "grunt": "~0.4.5",
    "grunt-cli": "^0.1.13",
    "grunt-contrib-compress": "~0.13.0",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.4.1",
    "grunt-contrib-uglify": "~0.2.7",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sass": "~1.1.0-beta",
    "grunt-string-replace": "~0.2.7",
    "node-sass": "~3.3.0",
    "time-grunt": "~1.1.0"
  },
  "scripts": {
    "build": "grunt build",
    "grunt": "grunt",
    "postinstall": "bower install && grunt build",
    "watch": "grunt watch",
    "package": "grunt package"
  }
}
```

Save the package.json file and type ```npm install``` in your terminal. I've verified that this solution works on my mac with OSX 10.10.5. 

Can you try this and let me know how it goes?
