### ISSUE TITLE
Incompability issues with Node v.4.x.x

### ISSUE THREAD

**Issue by olefredrik** [olefredrik/FoundationPress#475]
Currently there are certain compatibility issues with Node v.4.x.x and node-sass. This means that the NPM install will not work as expected, for those running the latest version of Node. To check which version of the node running, type ```node -v``` in your terminal.

There is however a fix for this, if you want to roll back to Node v.0.12.5:

#### 1. Install Node version manager 
```curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash```

#### 2. Activate nvm
```. ~/.nvm/nvm.sh```

#### 3. Install Node v.0.12.5
```nvm install 0.12.5```

#### 4. Use Node v.0.12.5
```nvm use 0.12.5```

#### 5. Verify that you're using the correct version
```node -v```

#### 6. Clone the FoundationPress repository
```git clone git@github.com:olefredrik/FoundationPress.git```

and enter the folder for your latest clone ```cd FoundationPress```

#### 7. Make shit work
```npm install```

This worked for me. And hopefully it should work for you too. I'll keep an eye out and update dependencies as things become more compatible with the latest version of the node. Sorry for the inconvenience.

**Comment by jmbarlow** [comment]
Using the latest version of node-sass seems to be a solution. Update package.json DevDependencies to:
```
    "node-sass": "3.3.3",
```
and `npm install` works on my machine™

**Comment by SenecaOne** [comment]
I can verify that after following this and updating node-sass, I was able to to get `npm install` to work (though I still had to run `bower install && grunt build` separately--they did not install while running `npm install`). 

Yosemite 10.10.4 mac mini

**Comment by olefredrik** [comment]
Fixed by updating dev dependencies in package.json https://github.com/olefredrik/FoundationPress/pull/478

**Comment by Reddy1985** [comment]
I installed bower install globally (bower install -g) but running bower install in my project folder gives bower: command not found. @roborracle can you help?
