### ISSUE TITLE
_keystrokes.scss does not use global for monospace font

### ISSUE THREAD

**Issue by 5AMsan** [olefredrik/FoundationPress#476]
We can read in _keystrokes.scss on line 13
`$keystroke-font: "Consolas", "Menlo", "Courier", monospace !default;`
So modifying _custom-settings.sccs monospace font (line 9) won't have any effect on keystroke style.

**Comment by olefredrik** [comment]
If you open _custom-settings.scss and type this, your keystroke font will be typeset with verdana
```$keystroke-font: Verdana, "Consolas", "Menlo", "Courier", monospace;```

I just verified that this works. 
<img width="378" alt="screen shot 2015-11-04 at 21 17 14" src="https://cloud.githubusercontent.com/assets/1080017/10950760/bf3aadf0-8339-11e5-8996-8559398c250b.png">

As with any style changes, you are dependent on ```npm run watch``` (or ```npm run browsersync```) to be running in the background for the changes to take effect.
