### ISSUE TITLE
posts per page function not working on archive

### ISSUE THREAD

**Issue by swthate** [olefredrik/FoundationPress#477]
Hi there.

Full disclosure: I'm not entirely sure if this is an issue with FoundationPress itself. This is sort of my last resort, to see if anyone here can spot something I can't... if there's any conflict I'm running into or if I'm getting in the way of any kind of default FoundationPress behavior that is causing this.

Here's the issue:

I'm trying to give a simple command to my custom post type archive: `'posts_per_page', '-1'`. I have this in my own custom-functions.php file in the library directory. You can see the code here: https://gist.github.com/swthate/0fbd3a449455c9ddbf1a

My archive page is displaying only 9 items. No matter what I set my posts_per_page to, it displays 9 items.

Any ideas?

**Comment by Eccola** [comment]
Hey, check your Settings > Reading > Blog pages show at most: ??
I guess it's ten?

**Comment by swthate** [comment]
It's not that, sadly. I actually set that to 50, just so it'd be noticeable. It still ignores everything and chooses to display only 9 items.

**Comment by swthate** [comment]
Turns out it was a conflict between my archive page and "results" page from Search and Filter Pro.
