### ISSUE TITLE
How to enable livereload?

### ISSUE THREAD

**Issue by emcniece** [olefredrik/FoundationPress#482]
I see that livereload is enabled through `npm run watch` and Gruntfile.js but on a fresh install I couldn't figure out how to enable the connection from the browser - clicking the Livereload toolbar icon in Chrome says that the script couldn't connect to the server. 

This is a trivial issue - adding the script manually to the footer makes it work as expected:

    <script src="http://mysite.dev:35729/livereload.js?snipver=1"></script>

... and it would even be feasible to add this through a WP hook:

    add_action('wp_footer', 'fp_livereload');

    function fp_livereload(){
      ?><script src="http://mysite.dev:35729/livereload.js?snipver=1"></script><?php
    }

Is this recommended? Am I missing a step somewhere?

**Comment by olefredrik** [comment]
I use the LiveReload chrome extension: https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei

![livereload](https://cloud.githubusercontent.com/assets/1080017/10073636/9f65005a-62ca-11e5-8b0b-8280d8c33234.png)

Whenever I make a change and save, the browser is reloading the content if LiveReload is enabled.

**Comment by LukePettway** [comment]
Good to know, I've been using http://www.browsersync.io/ for a while now on my FP projects.

**Comment by olefredrik** [comment]
Browsersync seems really nice. Have to try that out. Thanks for the tip!

**Comment by emcniece** [comment]
Uh guys - I use the LiveReload Chrome extension too, that wasn't the question!

The problem is that the livereload script tag with the site URL and port isn't being added to the page anywhere, so when I try and enable LiveReload through Chrome the extension says that it can't connect, even though the port (35729) in Node.js is clearly open.

What is responsible for adding the `<script src="http://mysite.dev:35729/livereload.js?snipver=1"></script>` tag to the page?

**Comment by phillbooth** [comment]
<meta http-equiv="refresh" content="5">

**Comment by emcniece** [comment]
@phillbooth lol... cheeky.

Does nobody else have this issue?

**Comment by olefredrik** [comment]
I guess you're getting this error message when trying to enable the LiveReload Chrome extension?

![livereload-cant-connect](https://cloud.githubusercontent.com/assets/1080017/10098000/dc3ebe2c-637d-11e5-9554-9ba59d92b745.png)

If this is the case, simply run ```npm run watch```. 

And then try to enable the LiveReload extension. It won't work unless the watch task is running.

**Comment by fourhexagons** [comment]
Sorry to open this closed issue, but I'm getting the above error after having already run `npm run watch`. LiveReload works for my FoundationPress sites built with the previous Foundation 5 version.

This message appears at the end of the gulp status:

![livereload script include message](https://dl.dropboxusercontent.com/u/67288784/livereload-script-include.png)

But if I do this, won't I then have to remove it before pushing to production?
Is there another way around this, or am I just missing something?
