### ISSUE TITLE
Mobile Menu doesn't load

### ISSUE THREAD

**Issue by tonybrown85** [olefredrik/FoundationPress#485]
Hi Ole, firstly thanks for such a great theme - I use this for all my wordpress theme development. I was just getting in touch as I seem to be having a problem with the mobile menu. I am using both the left and right menus for my desktop viewports and then creating a separate mobile menu consolidating both of these menu's into one. It's loading the mobile menu OK (not the off canvas menu - the slide down one) but for some reason it's loading the left menu in mobile rather than the menu created in wordpress that is mapped to Mobile. Any advise as to why it may be doing this would be greatly appreciated. Thank you, Tony

**Comment by olefredrik** [comment]
@tonybrown85 : Sorry for the late reply on this. Is this still an issue? What version of FP are you using?
