### ISSUE TITLE
Custom Grids?

### ISSUE THREAD

**Issue by roborracle** [olefredrik/FoundationPress#486]
Just a general question here - if I want to download a custom grid from the Zurb site, how would you recommend incorporating that with FoundationPress?? Don't if it would complicated or would just be a replacement of the core foundation files. Would love to be able to add my own custom grid.

http://foundation.zurb.com/develop/download.html

**Comment by AdamChlan** [comment]
You should take a look at the assets -> scss -> config -> _settings.scss file. In there are setting for the grid starting on line 76. You can copy and past those grid variables into the _custom-setting.scss file and change the values for your custom grid.

**Comment by Aetles** [comment]
If you change the grid to a custom one you also have to change the templates where the grid is used, since they are built for the default 12 column grid. Lines like:
`<div class="small-12 large-8 columns" role="main">`

**Comment by AdamChlan** [comment]
Good point. I've started using the grid mixins to start making my code more semantic, so that may be worth checking out as well.
