### ISSUE TITLE
Installed w/ No Issues, but Styling/Layout Not Showing

### ISSUE THREAD

**Issue by jwindeknecht** [olefredrik/FoundationPress#493]
I installed the theme with no issues, however upon activating the theme, I'm not seeing any sort of styling or layout.

![screen shot 2015-10-02 at 10 22 20 am](https://cloud.githubusercontent.com/assets/11090743/10250300/82824f58-68ef-11e5-812d-52fe408ff22f.png)

I tried a fresh install after updating Node/bower/grunt but am having the same issue.

Any ideas? Thanks, -Joe

**Comment by olefredrik** [comment]
npm run build :)

**Comment by hocu** [comment]
#530 has solved my problems with `npm run build`, FYI.
