### ISSUE TITLE
npm install completion blocked by Windows Firewall

### ISSUE THREAD

**Issue by HenkBarreveld** [olefredrik/FoundationPress#495]
This problem has already been solved (I think), but it may be useful for other people.

Platform: XAMPP sandbox on Windows 10, FoundationPress fork contents 2015-10-04, node.js v4.1.1

Running npm install failed - that is to say: it looks like quite a lot had worked but it failed in the end, with the following information (end of the npm-debug.log file:

75846 verbose cwd C:\Sandbox\xampp\htdocs\bcstar\wp-content\themes\FoundationPressStar
75847 error Windows_NT 10.0.10240
75848 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
75849 error node v4.1.1
75850 error npm  v2.14.4
75851 error code ELIFECYCLE
75852 error foundationpress@1.4.0 postinstall: `bower install && grunt build`
75852 error Exit status 1
75853 error Failed at the foundationpress@1.4.0 postinstall script 'bower install && grunt build'.
75853 error This is most likely a problem with the foundationpress package,
75853 error not with npm itself.
75853 error Tell the author that this fails on your system:
75853 error     bower install && grunt build
75853 error You can get their info via:
75853 error     npm owner ls foundationpress
75853 error There is likely additional logging output above.
75854 verbose exit [ 1, true ]

After that I just ran 'grunt build' from the command prompt. resulting in a pop-up Window from Windows Firewall. I granted firewall permission (stupid enough I did not register for which program), after which everything worked. To be sure I removed the repository, forked it again, ran npm install: everything ok - or so it seems, so far :)

**Comment by olefredrik** [comment]
Thanks for this info!
