### ISSUE TITLE
npm run package takes long time an failed

### ISSUE THREAD

**Issue by drosanda** [olefredrik/FoundationPress#497]
Hi All,

OS: WIndows 10

When I packaging, its takes too long almost 13 hours. and the the packaging size it almost 500GB the package never built.

I Dont know how its happens. But I change gruntfile.js to relative path not working too.

 cwd: 'D:/xampp/htdocs/nyingspot.com/wp-content/themes/NyingSpot/',

Any suggestion?

**Comment by olefredrik** [comment]
Wow. The total execution time on Mac OSX 10.11 is 12.4 sec.

I have no idea why this should not work on Windows 10. Have you tried to run ```npm run package``` just after ```npm install``` on a clean install?

**Comment by FlatspinZA** [comment]
I ran it on a clean install, with Windows 10 Professional.

Total time: 3m 55s (Intel Core i5-3570 with 8GB RAM & dedicated GPU)

It seems a bit long for the resulting 2.5MB zip file, but at least its not 13 hours. 

I am using WebMatrix for my web server, FYI.

**Comment by FlatspinZA** [comment]
Even though this is closed, I updated my node.js to the latest version, and now running `npm run package` executes in a much improved time of 1m28s

**Comment by drosanda** [comment]
yes I do, I ran 

npm run package

futhermore I have start over clean installed too, but the result are same.

Maybe sometime, someone can help me.

Thx.

**Comment by scorchio** [comment]
We've experienced the same with Windows 7 Ultimate SP1 + Node.js v4.1.1. Updating to Node v4.2.1 did not solve the issue: packaging is still way too slow (I had to kill it after 10 minutes). Could someone please look into this?
