### ISSUE TITLE
Adding FlexVideo automatically? Any idea?

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#500]
Hello.
Would be great to find a way to "hook" the auto-embed wordpress function so when someone put a youtube video in the editor it's automatically put in a flex video...
https://codex.wordpress.org/Embeds
Any idea? I can't find any doc on it...

**Comment by dantahoua** [comment]
Ok I found it finally! Maybe would be good to add it to the library folder!
`add_filter('embed_oembed_html', 'my_embed_oembed_html', 99, 4);
function my_embed_oembed_html($html, $url, $attr, $post_id) {
    return '<div class="flex-video widescreen">' . $html . '</div>';
}`

**Comment by arielnoname** [comment]
I was using this little piece of code with jquery:

`$('iframe[src*="youtube.com"]').wrap("<div class='flex-video'/>");`

You can change it if you want Vimeo, for example

`$('iframe[src*="vimeo.com"]').wrap("<div class='flex-video'/>");`

Cheers

**Comment by JeremyEnglert** [comment]
@dantahoua - that works great for videos, but it also adds the code to Twitter embeds, which makes them look a bit odd. I wish there was a way to target just videos with that filter.

@arielnoname - that works like a charm. You can also do something like this to make sure you target YouTube and Vimeo:

````jQuery( 'iframe[src*="youtube.com"], iframe[src*="vimeo.com"]' ).wrap("<div class='flex-video'/>");````

**Comment by arielnoname** [comment]
Really nice @JeremyEnglert . I'm not a big jQuery guy, didn't know one could pick more than one selector. Cheers

**Comment by dantahoua** [comment]
Thanks, love it! I didn't notice for tweeter because I didn't use it on this website, but good to know! I'll use the jquery method.

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/620

(Note that vimeo embeds will require an extra ```vimeo``` class)
