### ISSUE TITLE
npm ERR! code ELIFECYCLE / Failed at postinstall script

### ISSUE THREAD

**Issue by jwindeknecht** [olefredrik/FoundationPress#501]
npm ERR!    Darwin 14.5.0
    npm ERR!    argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR!    node v4.1.2
    npm ERR!    npm  v2.14.4
    npm ERR!    code ELIFECYCLE
    npm ERR!    foundationpress@1.5.0 postinstall: `bower install && grunt build`
    npm ERR!    Exit status 1
    npm ERR!
    npm ERR!    Failed at the foundationpress@1.5.0 postinstall script 'bower install && grunt build'.
    npm ERR!    This is most likely a problem with the foundationpress package,
    npm ERR!    not with npm itself.
    npm ERR!    Tell the author that this fails on your system:
    npm ERR!    bower install && grunt build

I'm thinking it's just some sort of versioning issue but I'm not sure how to go about resolving the error. Thanks for any insight you can provide.

**Comment by olefredrik** [comment]
Hmm. Strange. I just cloned the repository and did a ```npm install``` with no issues. Running node v4.1.2 and npm v.2.14.4 on Mac OSX 10.11. 

Here is an example https://github.com/olefredrik/FoundationPress/issues/481 , and here is another one https://github.com/olefredrik/FoundationPress/issues/468 .

**Comment by jwindeknecht** [comment]
I tried editing the json package, but no luck. I'm going to try an install on non-admin OSX account.

**Comment by olefredrik** [comment]
That should not be necessary. My OSX account has admin rights, and I have no problems. This is kind of weird. What error message you get if you take away postscripts from package.json?

Have you tried uninstalling re-installing Node.js with the latest build from https://nodejs.org?

**Comment by ottz0** [comment]
Same issue here
This is most likely a problem with the foundationpress package...
node -v v4.1.2
npm -v 3.3.5
