### ISSUE TITLE
Topbar breakpoint trouble

### ISSUE THREAD

**Issue by joewellmade** [olefredrik/FoundationPress#503]
Hi, i'm having trouble changing the topbar breakpoint, i'd like it to switch to the 'hamburger' menu when it hits 1240px. I've changed this line of code: 

$topbar-breakpoint: 1240px; // Change to 9999px for always mobile layout

Can anyone tell me if there's something else I need to do?

Thanks in advance!

**Comment by olefredrik** [comment]
Copy the settings you would like to override from _settings.scss to _custom-settings.scss. Remove the # and update the setting to your needs. Top-bar breakpoint is already in custom-settings.css.

https://github.com/olefredrik/FoundationPress/blob/master/assets/scss/config/_custom-settings.scss#L69

In your case, simply replace ```$topbar-breakpoint: em-calc(820);``` with $topbar-breakpoint: em-calc(1240);

And make sure ```npm run watch``` is always running in the background while you're working.. I just verified that this works well.

**Comment by joewellmade** [comment]
Thanks Ole, that's all sorted now. Much appreciated.

**Comment by olefredrik** [comment]
:+1:
