### ISSUE TITLE
SCSS is Compiling in the Wrong Place

### ISSUE THREAD

**Issue by indadam** [olefredrik/FoundationPress#504]
I'm having an odd issue with my most recent clone, my SCSS is compiling into a folder called "assets/css" and not into "assets/stylesheets" like the enqueue file is directing to. I can't tell if this is because I'm using CodeKit as the compiler, but I haven't had an issue in the past, but this is the first clone I've used where the SCSS is in the assets folder. Should I just redirect the enqueue script to the CSS folder to fix this? Is this an actual issue or just me?

**Comment by AdamChlan** [comment]
What happens when you delete out the css folder and rebuild the project?

**Comment by indadam** [comment]
@AdamChlan sorry, I know just enough to be dangerous here. Are you meaning just deleting the css folder and compiling the SCSS? Or is there a NPM command to rebuild? Can you be a little more specific?

**Comment by AdamChlan** [comment]
@indadam first off, does your grunt file have this code on or around line 22?

`'assets/stylesheets/foundation.css': 'assets/scss/foundation.scss'`

If so then it is strange that you would have a 'css' folder instead of 'stylesheets'. 

If you delete out that css folder and then "watch" your project with grunt via the `npm run watch` command, and then save one of the SCSS files in your assets folder, it should trigger the build. Do this after you delete out the css folder. Does it regenerate the "css" folder or does it create a "stylesheets" folder?

**Comment by olefredrik** [comment]
Any progress on this, @indadam ?

**Comment by indadam** [comment]
Sorry @olefredrik, have been slammed. I have not had a chance to experiment. After this project is done, I'll play around with it and try @AdamChlan's suggestions. Thank you!

**Comment by olefredrik** [comment]
No worries. Assumed that the problem was solved, since I did not hear anything. If you get stuck, feel free to reopen the issue.

**Comment by indadam** [comment]
@olefredrik I finally had a chance to play with it, I think the issue is in my compiler, CodeKit, ignoring the bower file. I went in and changed the compile location in CodeKit for foundation.scss to the "stylesheets" folder and it's working correctly now. So, I guess it could be in an incorrectly formatted bower file, but my guess is that CodeKit is just ignoring it. Thank you, you can keep this closed.

**Comment by FlatspinZA** [comment]
Ultimately, this is a platform developed on a Mac (I assume @olefredrik is using a Mac from past responses), that doesn't play well with an IDE developed for Mac, or is it that building, and compiling, should be done independent of the IDE, regardless of how good that IDE is at helping you develop your code?

Personally, I think it's the latter, but I stand open for correction.

**Comment by indadam** [comment]
@FlatspinZA I might be misunderstanding what you're saying, but CodeKit isn't an IDE, it's just a compiler. I don't use an IDE for my web programming, I'm doing my coding in Sublime Text. I also could be wrong, but I highly doubt the operating system has anything to do with the issue I'm having. Just my two cents.

**Comment by FlatspinZA** [comment]
@indadam No, you understood what I said - I don't use Mac, or CodeKit, so I assumed it was an IDE. Thanks for the correction. ;)

**Comment by indadam** [comment]
@FlatspinZA cool! Thanks for asking. An IDE would probably be a good idea, but I haven't found one I was happy with for web programming. Apple's Xcode is great for some programming, but it doesn't really handle web.

**Comment by olefredrik** [comment]
[Atom](https://atom.io/) - the open source text-editor for web development is quite nice. I switched from SublimeText2 to Atom a few months ago, and I haven't looked back. You still need a compiler though (e.g the built in terminal or CodeKit).
