### ISSUE TITLE
entering a comment redirects to wp-comments-posts.php 

### ISSUE THREAD

**Issue by Taitrnator** [olefredrik/FoundationPress#505]
I tried entering a comment and got redirected to wp-comments-posts.php, and comment never actually went through. I've tried disabling plugins. I also fresh-installed the theme on wordpress and it still does this. I also tried commenting with a a default theme (twenty-fifteen) and that did work. So Its go to be a theme issue as far as I can tell.

**Comment by olefredrik** [comment]
Unable to recreate issue on latest version of FP. Closing issue.
