### ISSUE TITLE
Button height problem

### ISSUE THREAD

**Issue by magnyld** [olefredrik/FoundationPress#506]
Hi
I have a problem with creating forms with combining inputs and buttons. Buttons and input boxes don't get the same height .

It works on foundation, but not with FoundationPress, 
http://codepen.io/anon/pen/qOjrMN

Reproduce it easy removing prefix on the search button here:  https://foundationpress.olefredrik.com/ 

Best regards Andreas

**Comment by AdamChlan** [comment]
I believe this is working as is should be. See this page for more info on prefix/postfix: http://foundation.zurb.com/docs/components/forms.html

**Comment by magnyld** [comment]
Is there a way to get input and a button next to each other with the same height as in the example with radius or round?

http://codepen.io/anon/pen/qOjrMN

If I use prefix/postfix it will remove the rounded corner on one side. I would ask on the foundation forums but it seems broken to add a new post at the moment.

Best regards Andreas
