### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by joewellmade** [olefredrik/FoundationPress#514]
Hi Ole, I can't seem to run npm package, I get this error: missing script: package

I've uploaded the whole theme folder instead after running npm run build.

Also, I have a scroll to page id plugin that worked fine on my local development site and now it's live it's not functioning properly in Chrome and Firefox, it's working ok but one of the options is playing up and the plugin does not work at all in Safari (javascript is enabled). I've had a couple of styles from my stylesheet go missing too.

Do you know what could be going on? www.buyers-club.co.uk

**Comment by olefredrik** [comment]
Hi Joe,

The [package feature](https://github.com/olefredrik/FoundationPress/pull/474) was added in [v1.5.0]( https://github.com/olefredrik/FoundationPress/releases/tag/v1.5.0)

Have you checked that the version you're working on is using this feature? Your package.json should include the grunt-conbrib-compress dependency. https://github.com/olefredrik/FoundationPress/blob/master/package.json#L28

Also, make sure that your Gruntfile is up to date with the package compress task.
