### ISSUE TITLE
archive.php check if sidebar exist

### ISSUE THREAD

**Issue by dioogbento** [olefredrik/FoundationPress#517]
Is it possible that archive.php would also check if sidebar exist, like in index.php?
Well, I'm already guessing the answer is negative, otherwise the file would have been updated. But may I please get to know why?

**Comment by AdamChlan** [comment]
It was likely just assumed that you would want a sidebar on the archive page since typically you would have categories or other links in the sidebar or the archive page. I don't see any reason why you couldn't modify the file to fit your needs though.
