### ISSUE TITLE
Bower components

### ISSUE THREAD

**Issue by DONSA** [olefredrik/FoundationPress#518]
I've install the Chart.js through bower.
How should I include it now? I run grunt build without success.

**Comment by AdamChlan** [comment]
Someone can correct me if I'm wrong, but you should be able to just add the file to assets -> javascript ->   custom and the build should include it into the minified JS file.

**Comment by DONSA** [comment]
Yes, I do that provisionally. The problem is that javascript files inside custom folder aren't minified and concatenated with foundation.js file, like fastclick and modernizr for instance.

**Comment by ScottyZA** [comment]
You can concat the Chart.js file by adding it as a source in Gruntfile.js therefore if you update your bower packages then it will update the files in your project. I usually place scripts between the Foundation scripts and the custom js script as you can see with the Slick Carousel JS file below.

    concat: {

			options: {
				separator: ';'
			},

			dist: {

				src: [

					// Foundation core
					'assets/components/foundation/js/foundation/foundation.js',

					// Pick the componenets you need in your project
					'assets/components/foundation/js/foundation/foundation.abide.js',
					'assets/components/foundation/js/foundation/foundation.accordion.js',
					'assets/components/foundation/js/foundation/foundation.alert.js',
					'assets/components/foundation/js/foundation/foundation.clearing.js',
					'assets/components/foundation/js/foundation/foundation.dropdown.js',
					'assets/components/foundation/js/foundation/foundation.equalizer.js',
					'assets/components/foundation/js/foundation/foundation.interchange.js',
					'assets/components/foundation/js/foundation/foundation.joyride.js',
					'assets/components/foundation/js/foundation/foundation.magellan.js',
					'assets/components/foundation/js/foundation/foundation.offcanvas.js',
					// 'assets/components/foundation/js/foundation/foundation.orbit.js',
					'assets/components/foundation/js/foundation/foundation.reveal.js',
					'assets/components/foundation/js/foundation/foundation.slider.js',
					'assets/components/foundation/js/foundation/foundation.tab.js',
					'assets/components/foundation/js/foundation/foundation.tooltip.js',
					'assets/components/foundation/js/foundation/foundation.topbar.js',

					// Include Slick JS file
					'assets/components/slick-carousel/slick/slick.js',

					// Include your own custom scripts (located in the custom folder)
					'assets/javascript/custom/*.js'

				],

				// Finally, concatinate all the files above into one single file
				dest: 'assets/javascript/foundation.js'

			}

		},

**Comment by DONSA** [comment]
Perfect! Thanks.
