### ISSUE TITLE
Demo seems broken on IE9

### ISSUE THREAD

**Issue by gthapar** [olefredrik/FoundationPress#519]
Check the attached screenshot.. What could be the reason? How to fix?

![screen shot 2015-10-18 at 3 43 41 am](https://cloud.githubusercontent.com/assets/4481867/10561557/23f21bae-754b-11e5-8e2c-58c6d45b37c6.png)

**Comment by dpkonofa** [comment]
This isn't a Foundation or FoundationPress issue, it's an IE9 issue.  IE9 cuts off CSS files that are longer than some length (though I can't remember what the exact length is).  You can check out BlessCSS to fix this.

**Comment by gthapar** [comment]
Thanks for replying!

I was aware about it but just wanted to make sure. I will reopen this (if required) after I try out BlessCSS.
