### ISSUE TITLE
Sourcemaps in chrome not correct

### ISSUE THREAD

**Issue by msacchetti** [olefredrik/FoundationPress#521]
Hi,

The sourcemaps for this theme are not correct in chrome inspect element on OSX. They point to seemingly random stylesheets.

Not sure if this is a localized issue because sourcemaps usually work for me in Chrome, just not with this theme. 

Anyone else have this issue?

**Comment by michaelbrazell** [comment]
Check out the gruntfile.js, there is a comment:

If you can't get source maps to work, run the following command in your terminal:
$ sass scss/foundation.scss:css/foundation.css --sourcemap
(see this link for details: http://thesassway.com/intermediate/using-source-maps-with-sass )

It's on line 34 of the gruntfile in the theme root.  Hope it helps.
