### ISSUE TITLE
Missing CSS/JS files when installed on Wordpress version 4.3.1

### ISSUE THREAD

**Issue by pymoza** [olefredrik/FoundationPress#523]
After installing the theme on WP no styling appears on the web... 
Here's the ressources missing : 

Failed to load resource: the server responded with a status of 404 (Not Found)
http://(...)/wp-content/themes/FoundationPress-master/assets/stylesheets/foundation.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(...)/wp-content/themes/FoundationPress-master/assets/javascript/vendor/fastclick.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://(...)/wp-content/themes/FoundationPress-master/assets/javascript/foundation.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://(...)/wp-content/themes/FoundationPress-master/assets/stylesheets/foundation.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Aetles** [comment]
These files needs to be built. Did you follow the [quickstart guide](https://github.com/olefredrik/FoundationPress#quickstart)?
