### ISSUE TITLE
npm commands = compilation errors

### ISSUE THREAD

**Issue by 4rouesel** [olefredrik/FoundationPress#530]
I just installed a clean version of FoundationPress and the components folder seems to be missing. When I run "npm run watch", there's some error due to the missing file for Normalize and function. Can you help me with that? Is there something I don't understand?

Otherwise if I do the "npm run build" command, I got this error message :  This is most likely a problem with the foundationpress package, npm ERR! not with npm itself. Maybe this could help to find the problem.

**Comment by anthonywjackson** [comment]
Experiencing same issue as 4rouesel. Node v4.2.1 npm v2.14.7

When make changes to a file while running "npm run watch", I get the error: 
>> file to import not found or unreadable: ../components/foundation/scss/normalize
>>   Line 4  Column 9  assets/scss/foundation.scss

When I try to run "npm run build" I get the same error 4rouesel lists above. Additionally:
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build

Any suggestions?

**Comment by 4rouesel** [comment]
Hi, I Just resolve it by running bower install. Hope it will help you too.

**Comment by hocu** [comment]
@4rouesel `bower install` solved my problems as well, thanks.
