### ISSUE TITLE
BrowserSync "Is it installed ?" error

### ISSUE THREAD

**Issue by pierretusseau** [olefredrik/FoundationPress#540]
Hello,

*I'm a bit worry to create a second issue, warn me if it's too much*

I recently updated my Grunfile.js (from an other Issue report). Then I saw the new BrowserSync in the foundationpress package ! I loved this one when I tried it myself and I'm pretty excited about the idea to have it on any of my FoundationPress project.

But I have quiet a problem, when I run `npm run watch` it sends back `>> Local Npm module "grunt-browser-sync" not found. Is it installed?`

I checked **./themes/my_theme/node_modules/browser-sync** and everything seems okay to me.
I tried `npm install browser-sync` and `npm install -g browser-sync` but none changed anything.

I did not really understand the value of "proxy server" and just wrote `localhost` I don't know if it works like this really, but that's the only local adress I got.

If I did something wrong, or forgot a step please explain.

**Comment by olefredrik** [comment]
Hi, 

Do you have the browser-sync package added to your package.json file, like this? https://github.com/olefredrik/FoundationPress/blob/master/package.json#L27

If you copy the contents of this package.json file and save, the only thing you should have to do is a ```npm install``` (to get the package installed in your node_modules folder).

If ```localhost``` is your local webserver url, you should be good to go using this as the proxy server value.

To test that everything is working as you would expect, run ```npm run browsersync```

**Comment by pierretusseau** [comment]
Ok so, browsersync has been added few days ago, I have a clear install from one week ago.

I decided to retry the entire instructions : 
- I added the line in package.json like you told
- I ran `npm install` there were lots of `gyp ERR!` (configure error, stack, System, etc...)
- I uploaded my gruntfile.js witht the one in source code (copypasta entire file)
- Added `proxy: "localhost/dentiste"` on line 184 (**dentiste** is the name of my folder in the root directory for sites of wamp)
- ran `npm run browsersync` had no result, just going back the folder
- ran `npm run watch` browser-sync doesn't seem to update when I change a line in SCSS, but `watch` is working.

I didn't have the same error : `>> Local Npm module "grunt-browser-sync" not found. Is it installed?`

**Comment by olefredrik** [comment]
As of now there is an opt-in to use browsersync by running ```npm run browsersync```. It is not included in the default watch task, simply because I am not sure that everyone wants to use it. If you want to have browsersync in your watch task, you can easily add it to the Gruntfile.

If everything now works fine, it's fine if you close the issue. :)

**Comment by pierretusseau** [comment]
I see, thanks for the support _again_ !
