### ISSUE TITLE
Stupid Question - how to set menu order to follow page order

### ISSUE THREAD

**Issue by ACG69** [olefredrik/FoundationPress#541]
Probably a dumb question but after looking through the WP Codex,  issues here and staring at the code I am going to ask anyway - be gentle with me...

I want to set the nav menu up to show pages in the order shown in the back end of WordPress, using the simple page order plugin allows m,y users to drag and drop pages in a large documentation site. There are many pages and more being added all the time so a custom menu is out. I was hoping to be able to set the nav menus to simple use the list of pages but short of writing a custom menu for just pages I can't see how to set the order for the content. I'm probably missing something very obvious - I am more used to writing themes from scratch than picking up a framework as a start - though I very much appreciate the effort that has gone into this theme and would love to be able to use it for the current project.

pointers to the codex or issue link that I am sure I missed finding most welcome...

**Comment by eallenOP** [comment]
So, more than the functionality of the "Automatically add new top-level pages to this menu" tick box? I'm not sure what you mean by "the order shown in the back end of Wordpress". In the list of all pages they seem to show up in alphabetical order, so you can't mean that. In the menu structure area (under appearance>menus) you just drag and drop things in the order you want them. Are you asking about something different?

**Comment by olefredrik** [comment]
@ACG69 : will you be able to provide some more info, or should we close this issue?
