### ISSUE TITLE
Protocol Relative URL not compatible with CDN Rewrites

### ISSUE THREAD

**Issue by KLVTZ** [olefredrik/FoundationPress#546]
> Per PR #430

Problem
------------
[Protocol Relative Theme Assets Plugin](https://github.com/ryanjbonnell/Protocol-Relative-Theme-Assets) takes advantage of adding filters to common src methods. This includes: style and script loader src. This takes precedence over any CDN Rewrite tool that may require a different URL.

Discussion
--------------
We currently use [CDN Linker](https://github.com/wmark/CDN-Linker). When this plugin is activated and setup, it rewrites our assets from within `wp-content` folder to point to our CDN. It appears when we use both this and FoundationPress, the protocol relative plugin takes place last and therefore over any CDN Rewrite.

It would be best to allow the user to decide whether or not they want to use a protocol relative url plugin. Since this plugin is built-in to the theme, it forces all to use it. One possible solution would be to remove it and list it in recommended plugins in the readme. The theme should not make the assumption that all would want to use the plugin.

**Comment by olefredrik** [comment]
@KLVTZ : I see the challenge. You have a valid point. Let's remove it from the framework and let people decide whether the plugin should be installed or not. I'll add it to my todo list.

**Comment by KLVTZ** [comment]
:+1:

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/562
