### ISSUE TITLE
Gruntfile and fontawesome

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#568]
Hi Ole, I may be wrong but since we copy the fontawesome fonts to assets/fonts the following string-replace should use those.  Instead it is using the files in components.  To stay with the philosophy of not directly using the files in components, the replacement pattern should be changed.

     'string-replace': {
      fontawesome: {
        files: {
          'assets/components/fontawesome/scss/_variables.scss': 'assets/components/fontawesome/scss/_variables.scss'
        },
        options: {
          replacements: [
            {
              pattern: '../fonts',
              replacement: '../../assets/fonts'
            }
          ]
        }
      }
     },

**Comment by olefredrik** [comment]
Hi Jim.

Not sure if I get what you mean? You are suggesting pointing the string-replace task to the assets/fonts folder and not modify anything at all in the components folder, right? 

[That's exactly what we're doing](https://github.com/olefredrik/FoundationPress/blob/master/Gruntfile.js#L76)

1. [We copy the fontawesome fonts folder to from the components to the assets folder](https://github.com/olefredrik/FoundationPress/blob/master/Gruntfile.js#L63)

2. We do a string-replace for the fontawesome-folder URL path in ```assets/fontawesome/scss/_variables.scss``` 

What am I misinterpreting here?

**Comment by jimlongo56** [comment]
I believe the end result is that you're using the fonts from **assets/components/fontawesome/fonts**, instead of **assets/fonts**.  

It works, but it's the only case were you're using items directly from the components, instead of the copied items.

**Comment by olefredrik** [comment]
Doh. *facepalm*. You're absolutely right. Let's change that.

**Comment by olefredrik** [comment]
Actually we don't need the string-replace task at all. Because the fonts folder is only one level up, relative to the foundation.css file. I don't know what's happened here. Must have been a late night with too little coffee, then this was added. I'll remove it. Thanks for the heads up :+1:

**Comment by jimlongo56** [comment]
Yes and in that case you could remove the copy of "iconfonts" as well as it's unnecessary.

**Comment by olefredrik** [comment]
Not so sure of that. Because we don't want to target any files in the components folder. The entire components folder is ignored in the ```npm run package``` script, which bundles all files needed for deployment. The entire components folder is really just a devDependency.

**Comment by jimlongo56** [comment]
Yes, sorry.  But that is why I thought the string replace was still needed.  It's just that you have to point to the assets/fonts folder, instead of the assets/components/fontawesome/fonts folder.  I'll leave it to you.

**Comment by olefredrik** [comment]
The path defined (by default) in ```components/fontawesome/scss/_variables.scss``` is ```$fa-font-path:        "../fonts" !default;```. In our foundation.scss file we import the font-awesome.scss from the components folder. All the imports (and other scss stuff going on) will be distributed to ```stylesheets/foundation.css```. Our fonts folder is one level up, relative to the .css file in our stylesheets folder. Which means we really don't have to do anything, except from removing the string-replace task in Gruntfile.js, because that is totally unnecessary. Does that make sense?

**Comment by jimlongo56** [comment]
Ahh, I got it now, it's very confusing.  
The $fa-font-path is ultimately relative to foundation.css . . . not fontawesome's css.

**Comment by olefredrik** [comment]
Exactly. I'll make it less confusing here and now, by removing the unnecessary hassle from the Gruntfile :)

**Comment by olefredrik** [comment]
https://github.com/olefredrik/FoundationPress/pull/569
