### ISSUE TITLE
Fully-functional and easy-to-use Sticky Sidebar available

### ISSUE THREAD

**Issue by HenkBarreveld** [olefredrik/FoundationPress#571]
Hello,

I needed a good working sticky sidebar for FoundationPress and now that it is working, I thought I should make it available for anybody who might be interested. You will find it here:

Code: https://github.com/HenkBarreveld/FoundationPress-Sticky-Sidebar
Demo: http://fpdemo-ss.urbino.nl/

**Comment by HenkBarreveld** [comment]
Please be aware: this only works with FoundationPress up to v1.7.2
FoundationPress v2.0.0 and later, based on Foundation 6, use a different html structure for which Sticky Sidebar still has to be adapted.

**Comment by olefredrik** [comment]
:+1: Cool! You should consider adding your plugin to the WordPress plugin repository.
