### ISSUE TITLE
npm run watch taking a long time

### ISSUE THREAD

**Issue by rdrewniak** [olefredrik/FoundationPress#573]
I've been experiencing some rather long wait times for the `watch` command. Here's my results from terminal:

```
OK 
>> File "assets/scss/site/_topbar.scss" changed.
Running "sass:dist" (sass) task 
Done, without errors. 

Execution Time (2015-12-01 22:25:29 UTC) 
loading tasks 11.5s ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 94% 
sass:dist 727ms ▇▇▇ 6% 
Total 12.2s 

Completed in 14.349s at Tue Dec 01 2015 15:25:42 GMT-0700 (MST) - Waiting...
```

I'm running a fresh installation of FoundationPress (cloned from the repository today), and my package versions are as follows:

Node v4.2.2
NPM v2.14.7

Could anyone shed any light on why the loading tasks element is taking so long?

**Comment by olefredrik** [comment]
We just switched from Grunt to Gulp https://github.com/olefredrik/FoundationPress/pull/583. Can you try updating your package.json file and add a gulpfile.js , remove your node_modules folder and do a clean ```npm install```. This might fix the issue with a slow watch task. Gulp should be significantly faster than Grunt.

**Comment by rdrewniak** [comment]
I just started work on a new site, and installed the latest version of FoundationPress. It's **INSANELY** faster!

Great work (on both this update, and FoundationPress, altogether)! It's developers like you providing exceptional open-source systems that make advances in web development so much easier and better.

Hats off to you!
