### ISSUE TITLE
Question on Gruntfile.js Line 200

### ISSUE THREAD

**Issue by DaveyJake** [olefredrik/FoundationPress#575]
I know I probably sound like an idiot but when viewing Gruntfile.js, this is all I see from lines 198-200:
```javascript
	grunt.registerTask('browser-sync', ['browserSync', 'watch']);
	grunt.registerTask('default', ['watch']);
};
```
The instructions say we are to add our local WP-Server address to line 200.  The only line where there's any indication of adding URL or any kind is at Line 180 for the `proxy` value.  Shouldn't that be where we add the address of our local WP-Server -- Line 180?

I just want clarification as I'm confused by the instructions given.

**Comment by LukePettway** [comment]
I think the line numbers are wrong, look for this block of code 

```javascript

browserSync: {
            dev: {
                bsFiles: {
                    src : [
                        'assets/stylesheets/*.css',
                        '**/*.php',
                        'assets/javascript/**/*.js'
                    ]
                },
                options: {
                    watchTask: true,
                    // fill in proxy address of local WP server
                    proxy: ""
                }
            }
        }

```


the proxy server is what you want to change under options. For my WordPress site I simply just put in site.dev. I'm running AMPPS for my server.

**Comment by DaveyJake** [comment]
That's what I was thinking too about the line numbers being wrong.  Definitely going to add my local dev to the proxy key.  On a side note, I also found adding my local dev to `Line 199` also works.
```javascript
    grunt.registerTask('default', ['http://local.dev/','watch']);
```
I'm using my Mac's native stack w/ `MariaDB` and `DNSMasq` as my server.  <a href="https://mariadb.com/kb/en/mariadb/building-mariadb-on-mac-os-x-using-homebrew/">`MariaDB`</a> & <a href="http://www.thekelleys.org.uk/dnsmasq/doc.html">`DNSMasq`</a> were both installed using <a href="http://brew.sh/">`Homebrew`</a>.

**Comment by colin-marshall** [comment]
The line # has changed over time since Browsersync was first implemented and the README needs an update to reflect that. @LukePettway has pointed out the correct location to place the URL.

**Comment by olefredrik** [comment]
We just switched from Grunt to Gulp. [This](https://github.com/olefredrik/FoundationPress/blob/master/gulpfile.js#L11) will be the correct place to add your local dev URL:
