### ISSUE TITLE
[2.0.0] not seeing offgrid in showcase

### ISSUE THREAD

**Issue by KLVTZ** [olefredrik/FoundationPress#585]
Per:
https://github.com/olefredrik/FoundationPress/compare/v2.0.0...master

I don't see:
https://github.com/olefredrik/FoundationPress/pull/579

BTW congrats on the 2.0.0 release --very exciting :dancer:

**Comment by olefredrik** [comment]
@KLVTZ : sorry about that. It disappeared in the heat of the 2.0.0 release. I'll add it back in :+1:

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/586

**Comment by KLVTZ** [comment]
@olefredrik thanks! :tada:
