### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#589]
@colin-marshall @olefredrik Seems to be working pretty well! Thanks.

I'm getting this error in **gulp watch** when saving **scss files**.

    [WATCH] assets/scss/modules/_footer.scss was changed, running tasks...
    [17:30:49] Starting 'sass'...
    Error in plugin 'sass'
    Message:
        assets/scss/foundation.scss
    Error: no mixin named foundation-progress-bar

       Backtrace:
       	stdin:92, in mixin `foundation-everything`
       	stdin:106
        on line 92 of stdin
    >>   @include foundation-progress-bar;
      -----------^

I get errors all the way down the foundation.scss includes tree
I need to comment all of these out to eliminate the errors

//@import '../components/foundation-sites/scss/components/progress-bar';
//@import '../components/foundation-sites/scss/components/reveal';
//@import '../components/foundation-sites/scss/components/slider';
//@import '../components/foundation-sites/scss/components/sticky';
//@import '../components/foundation-sites/scss/components/switch';
//@import '../components/foundation-sites/scss/components/table';
//@import '../components/foundation-sites/scss/components/tabs';
//@import '../components/foundation-sites/scss/components/title-bar';
//@import '../components/foundation-sites/scss/components/top-bar';
//@import '../components/foundation-sites/scss/components/thumbnail';
//@import '../components/foundation-sites/scss/components/tooltip';

**Comment by colin-marshall** [comment]
Can you show me your entire `foundation.scss` file?

**Comment by jimlongo56** [comment]
I'm sorry that one's on me.  I commented out the **@import**s as I have in my previous foundation projects to reduce the size of the css, but I hadn't also commented out the **@include**s
