### ISSUE TITLE
npm ERR! argv "node" "/usr/bin/npm" "install"

### ISSUE THREAD

**Issue by wishe** [olefredrik/FoundationPress#594]
Hi!

Love this starter theme but after recent updates to the theme i can no longer run npm install when i start a new site and i am recieving the following error:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v3.5.1
npm ERR! path /vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/esprima/bin/esparse.js
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chmod '/vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/esprima/bin/esparse.js'
npm ERR! enoent ENOENT, chmod '/vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/esprima/bin/esparse.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/npm-debug.log
```

Is this a known error and do you have any idea how to fix it?

**Comment by colin-marshall** [comment]
This is probably relevant: https://github.com/npm/npm/issues/7308

Do you have to run `npm install` from inside your vagrant box?

**Comment by wishe** [comment]
Thanks for the suggestion. I am not running vagrant on a windows machine though. I am running it on Ubuntu 14.04 LTS same as inside the vagrant box. 

If i try running npm install on my local machine i get a different error:

```
npm ERR! foundationpress@2.1.0 postinstall: `bower install && gulp build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the foundationpress@2.1.0 postinstall script.
npm ERR! This is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-55-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/alex/code/sites/www/metallbygg/htdocs/wp-content/themes/metallbygg
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/alex/code/sites/www/metallbygg/htdocs/wp-content/themes/metallbygg/npm-debug.log
npm ERR! not ok code 0
```
This only happened a week ago, before that this would always work.

Any ideas?

**Comment by tomhermans** [comment]
@wishe  same issue here

**Comment by olefredrik** [comment]
what versions of node and npm are you running?

**Comment by wishe** [comment]
I am running node v0.10.37 and npm is @3.5.1 on both now. I can still run npm install on my older installs that use previous versions of your starter theme.

**Comment by colin-marshall** [comment]
The theme uses Gulp now so there are a whole different set of node_modules. Updating node/npm would be my suggestion.

**Comment by olefredrik** [comment]
node v0.x.x is not supported anymore due to updated devdependencies. If you update to node v.4.x.x, it should work. I'm currently running node v4.2.2 and npm v2.14.7. 

If you don't want to update node, you can still find previous releases in the [release archive](https://github.com/olefredrik/FoundationPress/releases).

**Comment by tomhermans** [comment]
Thanks. Solved indeed.
found new issue through WP_Debug though
'Notice: Undefined variable: filtered_classes in ../../FoundationPress/library/cleanup.php on line 164'

**Comment by olefredrik** [comment]
Hmm. That was added in https://github.com/olefredrik/FoundationPress/commit/2a59f617e34f69b9dab9b687276fc4dd8609002a . Should have catched that before merge. Could you have a look at this @josh-rathke ?

**Comment by wishe** [comment]
This did indeed fix the issue. Thanks alot for the help, this was giving me a headache.

**Comment by wishe** [comment]
I am also getting the php notice that @tomhermans is getting though.

**Comment by josh-rathke** [comment]
Sorry guy's, that one is on me. This bit of code as a whole may need some re-evaluation. The only that error would pop up is if the images were being processed somewhere without any pre-existing tags which suggests something strange is going on. Because the error doesn't appear until after the post images have been rendered correctly.

This fixes it, but I am thinking there might be a bigger issue here.

**Comment by tomhermans** [comment]
Yep, found this solution as well..  sent a file change request too (didn't fork the repo earlier)

**Comment by medianagraphic** [comment]
i have a problem with npm :label: npm install

**Comment by Cistron** [comment]
FoundationPress 2.8 had no issues, but 2.9 does.
Do I have a Bower issue?
```bash
$ npm install

> foundationpress@2.9.0 postinstall C:\Program Files (x86)\Ampps\www\wp\wp-content\themes\immerschlank
> bower install && gulp build

bower foundation-sites#~6.3.0   cached https://github.com/zurb/foundation-sites.git#6.3.1
bower foundation-sites#~6.3.0 validate 6.3.1 against https://github.com/zurb/foundation-sites.git#~6.3.0
bower what-input#~4.0.3         cached https://github.com/ten1seven/what-input.git#4.0.6
bower what-input#~4.0.3       validate 4.0.6 against https://github.com/ten1seven/what-input.git#~4.0.3
bower                        ECONFLICT Unable to find suitable version for what-input

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.9.0 postinstall: `bower install && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundationpress@2.9.0 postinstall script 'bower install && gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\Ampps\www\wp\wp-content\themes\immerschlank\npm-debug.log
```

**Comment by tde-desc** [comment]
Same problem here

**Comment by Cistron** [comment]
I managed to get it to work by deleting the asset folders. Mine wasn't a clean install but a merge from an older FP version with the current one.

**Comment by soemoethunyaunggaing** [comment]
$ npm install
npm ERR! Linux 4.15.0-34-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pngquant-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pngquant-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/soemoethu/code/vuebnblara5.5/npm-debug.log

**Comment by SATYANARAYAN-MISHRA** [comment]
> Hi!
> 
> Love this starter theme but after recent updates to the theme i can no longer run npm install when i start a new site and i am recieving the following error:
> 
> ```
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
> npm ERR! Linux 3.13.0-71-generic
> npm ERR! argv "node" "/usr/bin/npm" "install"
> npm ERR! node v0.10.37
> npm ERR! npm  v3.5.1
> npm ERR! path /vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/esprima/bin/esparse.js
> npm ERR! code ENOENT
> npm ERR! errno 34
> 
> npm ERR! enoent ENOENT, chmod '/vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/esprima/bin/esparse.js'
> npm ERR! enoent ENOENT, chmod '/vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/esprima/bin/esparse.js'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /vagrant/www/metallbygg/htdocs/wp-content/themes/metallbygg/npm-debug.log
> ```
> Is this a known error and do you have any idea how to fix it?

same problem is here......how to solve....?

**Comment by SATYANARAYAN-MISHRA** [comment]
how to solve this problem ??

npm ERR! Linux 4.15.0-34-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/satya/reactApp/npm-debug.log
