### ISSUE TITLE
Problems Mobile and Top Bar in FP6

### ISSUE THREAD

**Issue by arielnoname** [olefredrik/FoundationPress#598]
Check gif please.

![foundationpress](https://cloud.githubusercontent.com/assets/11996305/11700670/fd079a68-9ea9-11e5-9ee6-7df188ef815a.gif)

**Comment by josh-rathke** [comment]
Have you changed anything with relation to the Mobile Off-Canvas Menu? Mine seems to work fine.

**Comment by arielnoname** [comment]
Clean install.
Going to try again if I can reproduce on a new clean install.

**Comment by josh-rathke** [comment]
I just noticed that the option that enables the user to choose between "topbar" and "offcanvas" as a means of Navigation doesn't take effect until after a user saves the option in the "Customizer". This may need more documentation as most developers don't even know they need to select a setting.

By default it is supposed to be "topbar" mobile navigation. But I don't think it actually saves it until the user opens up the customizer, navigates to the mobile menu section and "saves". After the initial save, it seems to work just fine.

**Comment by arielnoname** [comment]
Haven't checked code-wise it yet, so correct me if I'm wrong. 

In FP5 the thing was like this:
1.-
![fp5-1](https://cloud.githubusercontent.com/assets/11996305/11727923/9ed83bb6-9f65-11e5-9664-f292103389c7.gif)
2.-
![fp5-2](https://cloud.githubusercontent.com/assets/11996305/11727941/ba44b208-9f65-11e5-85c4-de850da002e8.gif)

And in FP6 this is it:
1.- ![fp6-1](https://cloud.githubusercontent.com/assets/11996305/11727951/c2a294e2-9f65-11e5-9657-ca3d035b394b.gif)

2.- My first pic that shows that this doesn't work

So. I think that having those Menus for Right and Left Topbar AND the Mobile tick boxes, was a very big win.

Ps. In the first Picture, the dropdown corresponds to a Topbar element.
Please tell me if you need some assistance with the spanish that's in the GIF. I think you won't need any.

Cheers

**Comment by olefredrik** [comment]
Thanks for pointing out the error @josh-rathke . A pull request in on the way. 

@arielnoname : I could not get the "left" and "right" options for the offcanvas to work as I wanted before the F6 launch, so I decided to remove it from the theme customizer.

In the menu settings, you can select where your menus will display (topbar and/or mobile)

![menu-settings](https://cloud.githubusercontent.com/assets/1080017/11762016/e6c4f360-a0d7-11e5-99e0-c625ae7aa2d9.png)

In the theme customizer you can select a topbar mobile menu or offcanvas mobile menu

![customizer](https://cloud.githubusercontent.com/assets/1080017/11762017/f4e4fef4-a0d7-11e5-95c8-e259210fbec9.png)

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/611
