### ISSUE TITLE
Less settings than before?

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#602]
Is it me or we have less settings possibility in the setting.scss? I want to change the burger icon color, I want it black hover white but I can't find any place to change that... 
The class is menu-icon::after...
Anyway I will change it in my custom scss, but it'll add some line to the css...

**Comment by colin-marshall** [comment]
There are less settings in Foundation 6. This was to make the framework be less opinionated in styling. The hamburger icon setting was not in F6 at first and then it was added in this commit: https://github.com/zurb/foundation-sites/commit/573e9336fb49f6188927358c30fc9e1ebf8a1f73

The setting you want to use is `$titlebar-icon-color`.

Here is the issue discussing that commit: https://github.com/zurb/foundation-sites/issues/7294

**Comment by dantahoua** [comment]
Ok, so if I want to change this without adding too much stuff I can declare $titlebar-icon-color in the setting.scss of my theme?
Anyway I ended up changing too much stuff on the burger icon but for the next time I would like to know the best way to go... :)

**Comment by colin-marshall** [comment]
They're already in the FP settings file:
https://github.com/olefredrik/FoundationPress/blob/master/assets/scss/global/_settings.scss

Got to the very bottom section.

**Comment by dantahoua** [comment]
No they aren't! Or I need new glasses! :) No $titlebar-icon-color in the last section (which is a section about the topbar ) or before (section 31 is about tabbar). Anyway I think we must concentrate before on typekit, image (with wp 4.4) small bugs before those little stuff! :) As I'am using the theme for a new production I'll try to test as much as possible.

**Comment by Aetles** [comment]
They clearly are not there. But I assume they will be once FP is upgraded to Foundation 6.0.5.

**Comment by colin-marshall** [comment]
My bad I was looking at the wrong file. I'll make a PR to fix this in a bit.

**Comment by olefredrik** [comment]
Settings file is updated to v6.0.5 https://github.com/olefredrik/FoundationPress/pull/612
