### ISSUE TITLE
Font "reloading" after page load

### ISSUE THREAD

**Issue by dinoquarin** [olefredrik/FoundationPress#604]
If anyone else is getting this (see gif), I have a temporary fix. It acts a bit like FOUC.

![dec 10 2015 17 12 - text issue](https://cloud.githubusercontent.com/assets/5267063/11730312/34c47954-9f62-11e5-9e28-643c80252057.gif)

If you comment out line 26 and 30 from the library/enqueue-scripts.php it loads "properly". Both need to be commented out at least in this quick "fix"

![screen shot 2015-12-10 at 5 20 15 pm](https://cloud.githubusercontent.com/assets/5267063/11730358/859387b2-9f62-11e5-875d-5be932ec4f2f.png)

This is from a clean download, cache cleared, no scripts blocked. Typekit and JQuery looks like they are loading properly too. 

Hope this helps.

**Comment by colin-marshall** [comment]
I noticed this when I built the gulpfile but I didn't have time pinpoint the problem. My best guess is that some JavaScript that loads in the footer is causing this. It also might be Browsersync related. I would love to get this fixed.

**Comment by colin-marshall** [comment]
Ok so this has nothing to do with Gulp or Browsersync as the problem can be seen on the FoundationPress demo site on page load.

**Comment by colin-marshall** [comment]
Found it! It's an issue with the Typekit embed script that loads at the bottom of the page. To confirm this, while the watch tasks were running with `gulp` I renamed `assets/javascript/custom/typekit.js` to `typekit` with no js extension so it would not be included when javascript builds. When I did that the problem was gone.

http://help.typekit.com/customer/portal/articles/6852-Controlling-the-Flash-of-Unstyled-Text-or-FOUT-using-Font-Events

**Comment by colin-marshall** [comment]
typekit.js is actually being loaded in the header and the footer. It's enqueued in the header and concatenated into `foundation.js` in the footer.

When I made `gulpfile.js` I used this from the `Gruntfile.js`:
```
// Include your own custom scripts (located in the custom folder)
'assets/javascript/custom/*.js'
```

That is concatenating everything with the `js` extension in the `/custom` folder, including `typekit.js`, into `foundation.js`. @olefredrik do we want `typekit.js` to be ignored for the concatenation of `foundation.js` or do we want to not be enqueueing it in `enqueue-scripts.php`?

**Comment by olefredrik** [comment]
@colin-marshall : Typekit should be placed in the ```<head>``` section of the page. So it would be best to ignore it for the concatenation of ```foundation.js```. It would perhaps be best to move the typekit script out of the custom folder. I have worked day and night on a project at work, so unfortunately I have not had time to follow up all FP issues in recent days. Appreciate your efforts on issues and pull requests!

**Comment by colin-marshall** [comment]
No problem! Where would you suggest we put `typekit.js`? In `vendor` instead of `custom`?

**Comment by olefredrik** [comment]
https://github.com/olefredrik/FoundationPress/pull/610

**Comment by dinoquarin** [comment]
Thank you for fixing this @colin-marshall and @olefredrik

**Comment by olefredrik** [comment]
If you're using Typekit with async javascript and want to remove the text-flash (FOUT) on page load, you can add this to your stylesheet.

```
.wf-loading {
   visibility: hidden;
 }

 .wf-active, .wf-inactive {
   visibility: visible;
 }
```
