### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#605]
As FoundationPress matures it might be worthwhile to add documentation to the official FoundationPress site. The official [Foundation Sites](https://github.com/zurb/foundation-sites) repo already has a built-in system for building docs. We could just modify that system for FoundationPress docs. Not sure if it would be better to use a separate repo for this or just have a "Documentation" branch that is completely different from the master branch. Thoughts?

**Comment by olefredrik** [comment]
Great idea. If we decide to make this happen, it should be meged into the master branch, as managing and updating different branches is not something we would like to do more than we have to.

**Comment by colin-marshall** [comment]
I agree. I wasn't sure if adding the Docs to the master branch of the repo would add too much bloat, since I know you're trying to keep it light.

**Comment by rlynjb** [comment]
hi @olefredrik i was wondering for documentation, if its a good idea to add an explanation of each directory. like which directory can we add our custom sass and custom js files.


thanks,
rlyn

**Comment by olefredrik** [comment]
@rlynjb This info is already available in the README file. 

@colin-marshall I'm not sure I will be able to maintain a fancy system for docs, to be honest. I've written a short blogpost that explains the basic stuff for beginners. I'm also continuously working on improving/simplifying the readme section and answering issues.
