### ISSUE TITLE
Responsive images WP 4.4

### ISSUE THREAD

**Issue by ottimoto** [olefredrik/FoundationPress#607]
FoundationPress 6 seems to have a problem with responsive images, using the new released Wordpress version 4.4. The new functionality in 4.4 with srcset and sizes for images works in any basic theme, but not in a clean install of Foundationpress 6. Do I need to add specific code to get it to work?
otti

**Comment by Aetles** [comment]
Have you tried disabling the image altering in cleanup.php? If not, try commenting out [line 247 in cleanup.php](https://github.com/olefredrik/FoundationPress/blob/master/library/cleanup.php#L247). (This is just a guess, I have not tried it myself.)

**Comment by ottimoto** [comment]
Great suggestion. At least the responsive image tags are loading now with the various sizes. Only the src file stays the large file for any device. Any idea what might stops it from replacing with the appropriate image size?

**Comment by ottimoto** [comment]
Even not enqueuing the complete cleanup.php does not fix this issue. I tried to locate other resources responsible for the image tag, but I'm a bit at a loss here. @olefredrik can you point me in the right direction where I would need to look? Many thanks.

**Comment by olefredrik** [comment]
Responsive images is one of the new and perhaps the most anticipated feature in WordPress for a long time. To be perfectly honest I have not had time to look at it before now. I have gone through the old "responsive image" solution and taken away what is no longer relevant, and adopted a new and better approach that seems to work fairly well. Having said that, I want really a code review and proper testing on this before we take it into the master. https://github.com/olefredrik/FoundationPress/pull/657 . Any takers? :)

**Comment by ottimoto** [comment]
Thanks so much for looking into the responsive images. I'm more than happy to test it all in regards to the images. Since I'm fairly new to SASS and git I might need some direction: How do I get your pull request? I would throw a test site onto it and would let you know what my findings are.

**Comment by olefredrik** [comment]
Hi @ottimoto , 

You can check out the pull request by running the following commands in your terminal. 

```
git checkout -b responsiveImages
git pull origin responsiveImages
npm run build
```

**Comment by ottimoto** [comment]
Hi @olefredrik,

I have followed your terminal commands and can now add the images with srcset etc. I used your additional image sizes and inserted a 1440 wide image. Observations I have made:
* The browser needs to be refreshed each time in order to see the updated image – just changing the viewport by dragging does not change the image as it does i.e. with Interchange. But I think as only we web people scale the viewport manually it is not an issue..
* The image replacement does not happen at the required screen sizes. I think this has to do with the usage of the viewport width. I will have a look around for good media query/length combinations.
* The image breakpoint changes seem to happen intermittently. When scaling and refreshing from small to medium/large the image replacement might not happen from 768 to 1024 but does happen when scaled and refreshed from large to medium – at least in Safari. Probably again just an issue of selecting the right vw.
* Chrome does require a cache clean in order to show the appropriate image (refresh is not enough) and still has the double download issue https://wordpress.org/support/topic/double-downloading

I think you have done a great job and it just needs a bit of tweaking.

**Comment by ottimoto** [comment]
I have made some changes to responsive-images.php, replacing the sizes with:
$sizes = '
     (max-width: 640px) 640px,
     (max-width: 1024px) 1024px,
     (max-width: 1200px) 1200px,
     (max-width: 1440px) 1440px, 100w';
The image replacement takes now place at the correct breakpoints. The refresh is still required to see the change and Chrome still has the double download issue and displays the larger image if it has downloaded it already, even if a smaller image is also available and downloaded too.
What do you think?

**Comment by Aetles** [comment]
Which of these issues with responsive are related to the FoundationPress implementation specifically and which are general for WordPress?

**Comment by ottimoto** [comment]
I just tested in a plain 4.4 WP install and the refreshing issue and the Chrome double download also happen there without FP. I think using a similar sizes setup as above should give us the same result as with a plain WP install. Maybe another screen size i.e. 768 or 940 would be good, but this can be done project dependant.

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/657

**Comment by ottimoto** [comment]
Thanks very much Ole for looking into this issue and fixing it.
Looking forward to my next project where I pout it into place.
