### ISSUE TITLE
Grid vs Flex-Grid (Which leads me to a philosophical question)

### ISSUE THREAD

**Issue by josh-rathke** [olefredrik/FoundationPress#619]
Just noticed that by default FoundationPress uses the "Grid". Which I think is fine.

However, I then got to thinking how we could enable it for developers who want to use the flex-grid, even if we just added an uncommented `@include foundation-grid;` to the `foundation.scss` file.

But then I thought of how the end-user can change the preferred method of mobile menu, which likely has few consequences in terms of design and functionality. However, it got me trying to identify whether FoundationPress is being developed for "developers", or for the "end-users" those developers are working for. I think the answer to that question would greatly impact how we handled an issue like this. If FoundationPress is for developers, then we are done after adding the uncommented line above. If it's geared for the end users of those developers, we may want to let the user choose whether they use a static grid, or a flex-grid.

Maybe this is crazy, but I guess it took me a little off guard when I realized the end-user could change whether the mobile menu appeared as an Off-Canvas, or Topbar Menu. If we are allowing the end-user to change things (Which I think can be a good thing...or a bad thing depending on the project), are we also allowing the developer easy access to an "off-switch" that kills the end-user's ability to potentially break something?

**Comment by tomhermans** [comment]
I think no end-user is using FoundationPress, and if they are, they lack the necessary skills to get this running imho.
So I think you should let the developer make the decision on which route to pursue, and prevent the end-user from breaking the solution he/she developed. (there's enough in a WP install to break already ;) )

**Comment by josh-rathke** [comment]
Yeah, I agree. I think at the end of the day anything that adds functionality to the end-user needs to have an easy to find and easy to flip kill-switch for the developer. For example the WYSIWYG Shortcode stuff we are working on is easy to turn off, either by deleting the directory and call in `functions.php`, or by commenting which shortcodes you don't want to be active.

**Comment by tomhermans** [comment]
Yep, been thinking of collecting a few of my own snippet I frequently use and post them in a similar fashion or via a PR.
Simple stuff like move-yoast-to-bottom, remove-empty-p kinda functions, or sass stylesheet for Gravity Forms. Not necessary-necessary for FoundationPress, but handy if it's in there and usable by uncommenting a line for instance.

**Comment by olefredrik** [comment]
I strongly doubt that the typical end-user has (or should have) knowledge of standard floating grid vs flex-grid. From what I understand, switching to using the flex-grid is as easy as

 ```
// @include foundation-grid;
@include foundation-flex-grid;
``` 

In my opinion, we should leave that choice to the individual developers and let the end-users focus on the site content. Shortcodes for buttons etc. is a different matter, as it is very closely related with presentation of content.

**Comment by jimlongo56** [comment]
I've said before, that to me, one of the main attractions to FP is how clean and adaptable it is. It's easy for a developer to add more dependencies for their purposes. I don't think it's going to be used by many end users without development skills, they generally go for themes with a lot of bells and whistles, which is the opposite of what FP currently represents.

In this vein I also think that it would be best if any major end user additions like shortcodes or other theme "options" would be best as plugins (or at least totally compartmentalized) that wouldn't interfere with the basic functioning of the theme. imo Once you venture down the road of adding features to a theme it's hard to stop, and theme bloat is waiting around the corner.

**Comment by Aetles** [comment]
+1 on what @jimlongo56 said. (I'm already using my own fork of FP to cut out stuff I don't need and make some changes I personally prefer, but I think it is in everyones interest to keep FP simple.)

**Comment by olefredrik** [comment]
I obviously agree with you. Simplicity and lack of blood has always been the focus. It would therefore not be appropriate to let the end-user customize whether the layout should be based on floats or flex. 

When it comes to shortcodes, @josh-rathke and @colin-marshall have taken the initiative to test how this would work in a separate development branch. If it turns out to work great, it may be merged into the master branch. It should be possible to easily switch the shortcode feature on/off by uncommenting/commenting a single line in functions.php. 

We can discuss whether shortcodes should be completely separate in a stand-alone plugin, or baked in like a theme-option that can easily be toggled (by the developer). I will nevertheless give great honor to those who take the initiative to test new possibilities and features. Can assure you all that the FP will never be bloated with a ton of useless features. Let's keep it simple, usable, and a good platform to build on.
