### ISSUE TITLE
Can't get stylesheets to build

### ISSUE THREAD

**Issue by Boogonie** [olefredrik/FoundationPress#622]
I'm very new to Sass and Foundation, but very motivated to learn. I've succussfully installed FoundationPress (I think), but can't get the stylesheets to build using npm run build. I get the following error:

[22:26:37] Using gulpfile /Applications/MAMP/htdocs/allcards/wp-content/themes/FoundationPress/gulpfile.js
[22:26:37] Starting 'build'...
[22:26:37] Starting 'copy'...
[22:26:37] Finished 'copy' after 42 ms
[22:26:37] Starting 'sass'...
[22:26:38] Starting 'javascript'...
Error in plugin 'sass'
Message:
    assets/scss/global/_settings.scss
Error: File to import not found or unreadable: ../../components/foundation-sites/scss/util/util
       Parent style sheet: /Applications/MAMP/htdocs/allcards/wp-content/themes/FoundationPress/assets/scss/global/_settings.scss
        on line 42 of assets/scss/global/_settings.scss
>> @import '../../components/foundation-sites/scss/util/util';
   ^

[22:26:38] Finished 'sass' after 905 ms
[22:26:38] Finished 'javascript' after 224 ms
[22:26:38] Finished 'build' after 958 ms

Any ideas on how to fix this?  Thanks

**Comment by olefredrik** [comment]
Hi @Boogonie ,

The stylesheets should build automatically when running ```npm run build```. Did you get any errors on ```npm install```? Seems like some of the foundation files are missing in your /components/foundation-sites folder.

**Comment by Boogonie** [comment]
No errors on the intsall, but I'm missing the /components/foundation-sites folder, so something obviously went wrong. I'll try installing again.

**Comment by Boogonie** [comment]
Just reinstalled. This is the only warning I receive:  npm WARN cannot run in wd foundationpress@2.2.0 bower install && gulp build (wd=/Applications/MAMP/htdocs/allcards/wp-content/themes/FoundationPress)
colors@1.1.2 node_modules/colors

Still no foundation-sites folder.

**Comment by olefredrik** [comment]
That explains a lot. Can you check what version of Node.js and npm you're using? Type ```node -v``` and ```npm -v``` in your terminal.

**Comment by Boogonie** [comment]
node v4.2.3
npm v2.14.7

**Comment by olefredrik** [comment]
Hmm. Probably a permission error then. There is a workaround for this in this thread https://github.com/olefredrik/FoundationPress/issues/596

**Comment by Boogonie** [comment]
It worked! The issue was with my use of sudo.

Many thanks!

**Comment by olefredrik** [comment]
Great! :+1:
