### ISSUE TITLE
Error: File to import not found or unreadable

### ISSUE THREAD

**Issue by benaut** [olefredrik/FoundationPress#624]
I'm having a problem running FoundationPress new install.
I thought it might be something to do with gcc compiler, but I'm not sure. It looks like the @import of the _settings.scss file on line 42 doesn't go anywhere... not sure why my files are corrupted...
I've run previous verisons of FoundationPress with no problem, but can't quite work out what I'm doing wrong at this point:

$ npm run build

> foundationpress@2.2.0 build /Users/Ben/Desktop/CPlusFoundation6
> gulp build

[22:42:01] Using gulpfile ~/Desktop/CPlusFoundation6/gulpfile.js
[22:42:01] Starting 'build'...
[22:42:01] Starting 'copy'...
[22:42:01] Finished 'copy' after 24 ms
[22:42:01] Starting 'sass'...
[22:42:01] Starting 'javascript'...
Error in plugin 'sass'
Message:
    assets/scss/global/_settings.scss
Error: File to import not found or unreadable: ../../components/foundation-sites/scss/util/util
       Parent style sheet: /Users/Ben/Desktop/CPlusFoundation6/assets/scss/global/_settings.scss
        on line 42 of assets/scss/global/_settings.scss
>> @import '../../components/foundation-sites/scss/util/util';

**Comment by colin-marshall** [comment]
Does the folder `assets/components/foundation-sites` exist after running `npm run build`? If it does not exist you might want to check out issue https://github.com/olefredrik/FoundationPress/issues/622. You might have the same problem which was solved by correcting npm permissions as suggested in issue https://github.com/olefredrik/FoundationPress/issues/596

**Comment by benaut** [comment]
thanks very much… the folder was missing
I fixed permissions on the subfolders lib/node_modules, bin, and share, as suggested:
https://docs.npmjs.com/getting-started/fixing-npm-permissions
after that I had to install FoundationPress from start, and it worked a treat… Cheers!
