### ISSUE TITLE
Mobile Menu, all but first child

### ISSUE THREAD

**Issue by BlackSheepWithMe** [olefredrik/FoundationPress#627]
Hi there! Just started from a new install and I have 7 Custom Links all on the same level, but in the mobile menu only the first one is on the correct level. The rest of the links are indented.
Here is what the output is vs the builder.

![image](https://cloud.githubusercontent.com/assets/7980606/11790107/3ab3f626-a257-11e5-9f00-d9c0b42c32a0.png)

What am I doing wrong?

**Comment by beniven** [comment]
Having the same problem

**Comment by beniven** [comment]
Hey @BlackSheepWithMe, it looks like the `ul` of the mobile navigation on line 46 of `/library/navigation.php` wasn't closed.

Should look like this:
`'items_wrap'     => '<ul id="%1$s" class="%2$s show-for-small-only" data-accordion-menu>%3$s</ul>',`

**Comment by BlackSheepWithMe** [comment]
@beniven Thanks!

I'll leave this open so we can actually get it resolved in the repo

**Comment by erwinpagulong** [comment]
@beniven it works! Thanks a lot.

**Comment by colin-marshall** [comment]
Good find @BlackSheepWithMe and thanks for the fix @beniven! PR submitted.
