### ISSUE TITLE
Second-level submenus don't fly out

### ISSUE THREAD

**Issue by eallenOP** [olefredrik/FoundationPress#634]
I have a site that is probably more suited to using mega-menus, but this is not supported by Foundation so I'm trying to make the most of the topbar. However, unlike the normal Foundation install, FoundationPress does not seem to fly the sub-sub menus out to the right — instead they appear exactly below the parent menu item (the same as a top-level sub-menu does, which is what you want for that level of course) and cover the menu items below.

So instead of cascading menus you get second sub-menus on top of first sub-menus.

I looked at the classes being assigned and both levels seem to be getting "first-sub", which is the type that comes out directly below the parent. I found some code which might be doing this, but don't know how to add a bit to create second-subs.

```
DropdownMenu.prototype._init = function(){
    var subs = this.$element.find('li.is-dropdown-submenu-parent');
    this.$element.children('.is-dropdown-submenu-parent').children('.is-dropdown-submenu').addClass('first-sub');
```
The lines above are in foundation.dropdownMenu.js

Is it possible to add something here which creates second-level sub-menus that come out to the right? If I change the class to second-sub in the dom inspector the menu comes out to the right, so the styling is obviously already in place. I just can't work out the js to assign class "second-sub" to the next level of menu.

**Comment by eallenOP** [comment]
Actually I might have fixed it by duplicating one of the menu walkers, replacing `data-dropdown-menu` with `data-toggle` and calling my new walker instead of `Foundationpress_Top_Bar_Walker`in navigation.php

**Comment by AdamChlan** [comment]
I can confirm that changing ```data-dropdown-menu``` to ```data-toggle``` fixed this issue for me. Perhaps this should be the default behavior, since having the second level menu appear to the right seems more common?

**Comment by olefredrik** [comment]
Thanks for your input! The fix is applied in this pull request: https://github.com/olefredrik/FoundationPress/pull/699
