### ISSUE TITLE
Prepping theme for deployment

### ISSUE THREAD

**Issue by rdrewniak** [olefredrik/FoundationPress#636]
Okay...I have (what is most likely) a REALLY stupid question...

Where do I find the packaged files to upload to my live site when I'm ready to deploy my site (from my local development environment to the live site)? With the previous version (the Foundation 5 based starter theme) I would run:
```
npm run build
```
to package the files, which would generate a zip file of my theme into a newly generated *packaged* folder, ready for deployment on my live site. On this new version (the Foundation 6 based one), when I run the same terminal command, I don't get a *packaged* folder, nor do I get a zip file of my theme.

Is there something that I'm just not seeing, or is there a step that I'm missing?

**Comment by colin-marshall** [comment]
You now run `npm run package` to get the .zip file. `npm run build` runs the build task which complies the Sass and concatenates the JavaScript.

**Comment by rdrewniak** [comment]
That did it! 

Thanks for your help @colin-marshall!
