### ISSUE TITLE
Having trouble committing project to BitBucket!

### ISSUE THREAD

**Issue by jdfweb** [olefredrik/FoundationPress#638]
Hey all!

So I use a BitBucket account for work, and usually projects go swimmingly when committing! However I just cloned FoundationPress and tried setting up the project to BitBucket to get things going. Commiting a change is okay, but when I try to push, it automatically reverts to trying to submit to this repository (FoundatPress')! Which is really odd. 

Here's a screenshot! I also don't have any option to select any other repositories - they're all greyed out!

![pic](https://cloud.githubusercontent.com/assets/11800545/11877441/4b853790-a4bd-11e5-971f-1bb15e5348e4.jpg)

Is anyone able to help me get this going so I can commit to my own repository? Any help would be appreciated!

**Comment by colin-marshall** [comment]
You should fork the repo instead of cloning it. Here's how to remove this repo as the origin: `git remote rm origin`.  Then create a new repo on bitbucket and it will give you a command to run to add the bitbucket repo as the origin. It will be something like `git remote add origin ...`.

**Comment by jdfweb** [comment]
Awesome it worked! Thank you!
