### ISSUE TITLE
Nav Questions

### ISSUE THREAD

**Issue by Boogonie** [olefredrik/FoundationPress#639]
I've been struggling with several Nav issues. I've downloaded a fresh install of the theme, added one menu assigned to the right top bar and mobile, and selected the off canvas option for mobile.
1. Mobile doesn't work. I click the menu icon and nothing happens; and
2. Is there a menu location for the left top bar? I've seen it in several screen shots here in the forum, but it's missing from the current version.

**Comment by andreaarcher** [comment]
I have the same problem

**Comment by mlangone** [comment]
This seemed to work for me with current version

Customize > Menus > Menu Location Mobile - Set the menu to use  - Save
Then Customize > Mobile Menu Settings > Mobile navigation layout > Offcanvas - Save
Gives me a menu that opens like this

![screen shot 2016-02-03 at 5 22 59 pm](https://cloud.githubusercontent.com/assets/4027703/12801584/f5dad210-ca9a-11e5-9fe4-4e71c8b1f927.png)

**Comment by samirgh** [comment]
> Mobile doesn't work. I click the menu icon and nothing happens

Check **mobile** for menu location and it should work.

**Comment by cmpreshn** [comment]
I was able to add a top-bar-left menu location, but can't get the toggle to work for this menu. In [theme]/library/navigation.php, first add the top bar left element to the register nav menus array:

`register_nav_menus(array(
	'top-bar-l'  => 'Left Top Bar',
	'top-bar-r'  => 'Right Top Bar',
	'mobile-nav' => 'Mobile',
));
`
Then add the following function after the register_nav_menus function call:
`/**
 * Desktop navigation - left top bar
 *
 * @link http://codex.wordpress.org/Function_Reference/wp_nav_menu
 */
if ( ! function_exists( 'foundationpress_top_bar_l' ) ) {
	function foundationpress_top_bar_l() {
		wp_nav_menu( array(
			'container'      => false,
			'menu_class'     => 'dropdown menu',
			'items_wrap'     => '<ul id="%1$s" class="%2$s desktop-menu" data-dropdown-menu>%3$s</ul>',
			'theme_location' => 'top-bar-l',
			'depth'          => 3,
			'fallback_cb'    => false,
			'walker'         => new Foundationpress_Top_Bar_Walker(),
		));
	}
}
`
This creates a Left Top Bar menu location which will show in WordPress Menu Settings / Theme Locations. I'm now able to get my menu to appear in either left or right top bar locations. However, when I select the left top bar, the menu toggle does not work. I do also have the 'Mobile' box checked for the menu.
