### ISSUE TITLE
Theme check errors

### ISSUE THREAD

**Issue by klausbrinch** [olefredrik/FoundationPress#641]
When i run FoundationPress through the plugin Theme Check on a fresh site and a fresh install of FoundationPress i see some warnings like missing pagination code and missing content widht.

Are these errors just to be ignored? When i run the theme Twentyfifteen through Theme check i dont see any errors.

**Comment by colin-marshall** [comment]
There is definitely pagination in FoundationPress. Theme Check must not be picking it up for some reason. Can you post a screenshot of all the warnings please?

**Comment by klausbrinch** [comment]
Hi Colin - Yes here is a screenshot
![theme_check_12-19-2015_foundationpress](https://cloud.githubusercontent.com/assets/8272893/11915312/0b4e7ce6-a6a1-11e5-9a5e-6cfea5d91bd4.png)

**Comment by olefredrik** [comment]
@klausbrinch : I'm aware of these warnings. As I see it, none of these are critical. If you want to fix, feel free to open a pull request :)
