### ISSUE TITLE
jquery.js conflict with popular wordpress plugins

### ISSUE THREAD

**Issue by colourweaver** [olefredrik/FoundationPress#645]
The latest version of FoundationPress is experiencing jquery.js conflict with popular wordpress plugins. 

Below are 2 examples of well known wordpress plugins that are no longer working with the latest version of this theme. Other plugins that I regularly use are also no longer working.

Slider Revolution 5.1.5 - ThemePunch:

- The slider does not work  
- Also followed trouble shooting tips outlined via the theme provider http://www.themepunch.com/faq/troubleshooting-tips-for-5-0/

Hero Menu Version 1.6.2 - Hero Plugins:

- Error occurs when activating the sticky menu capability 

Settings:

Mamp Pro Version 3.5
FoundationPress Version 2.2.0
Wordpress Version 4.4
Xcode Version 7.2 (7C68)
Node.js Version 4.2.3
OS x EI Capitan version 10.11.12

- Also tested both wordpress plugins via live websites.

**Comment by David-van-den-Bor** [comment]
Hi Colorweaver :-)

Could this be the same issue as the issue that I mentioned to Ole 3 months ago? See here (https://github.com/olefredrik/FoundationPress/issues/451) My guess is that FoundationPress comes bundled with the CDN version of jQuery, and this causes issues with WordPress plugins, as WordPress plugins assume that WordPress takes care of "al things jQuery". Every version of WordPress comes bundled with jQuery, so you could either wrap your js code in "no-conflict" code tags, or enqueue jQuery the "WordPress way"

**Comment by colourweaver** [comment]
Hey David,

Thanks for the tip, I have managed to resolve the errors for both of the plugins, "Slider Revolution" + "Hero Menu" through changing the following slice of code:

Step 1:
Location of file:
FoundationPress> Assets> Javascript> Custom> init-foundation.js>


Step 2:
Placed the following text in the "init-foundation.js" file:
<script>
jQuery.noConflict();
jQuery(document).foundation();
</script>

Step 3:
Problem resolved


Another method that was also able to be use to resolve issue, was to delete all contents of the "foundation.js" file. I think this file may need a bit of fine tuning via the community. Foundation 5 had no issues with this functionality, only the recently published Foundation 6.

Thanks again :)

**Comment by toddnagel** [comment]
I was having similar issues, mainly with the plugin 'Ultimate Member', was giving me a jQuery(...).tipsy is not a function error..

I resolved this, (finally) buy replacing this:

jQuery(document).ready(function() {

with this:

(function($) {

in the file um-script.js .. hope this helps someone..

**Comment by olefredrik** [comment]
Running jQuery in noConflict mode should not be necessary since we only load one version of jQuery (Google CDN). I don't know if some third-party plugins require that jQuery is bundled with WordPress. Can't see why they would do that. There are [many reasons](http://encosia.com/3-reasons-why-you-should-let-google-host-jquery-for-you/) why it's beneficial to use a CDN.

> If for some reason two versions of jQuery are loaded (which is not recommended), calling $.noConflict( true ) from the second version will return the globally scoped jQuery variables to those of the first version.

https://api.jquery.com/jquery.noconflict/
