### ISSUE TITLE
Small issue with offcanvas menu

### ISSUE THREAD

**Issue by wishe** [olefredrik/FoundationPress#646]
In "navigation.php", there is a small error in the build up of the menu. More specifically in the foundationpress_mobile_nav(). 

```
'items_wrap'     => '<ul id="%1$s" class="%2$s show-for-small-only" data-accordion-menu%3$s</ul>'
should be changed to
'items_wrap'     => '<ul id="%1$s" class="%2$s show-for-small-only" data-accordion-menu>%3$s</ul>'
```

This should fix the menu so that the first item also gets put in its own li and the ul gets closed correctly!

**Comment by olefredrik** [comment]
Hi, 

This was fixed 6 days ago :)
https://github.com/olefredrik/FoundationPress/commit/f25bf3a5d95013032ba2fd3b7b2eda1bf98ab726

**Comment by wishe** [comment]
Oops my bad!
