### ISSUE TITLE
How to commit WordPress database to Github or Bitbucket?

### ISSUE THREAD

**Issue by jdfweb** [olefredrik/FoundationPress#648]
So I use Bitbucket for version control, but I've always use it for static websites! I know that when you commit WP websites to Github or Bitbucket, you usually just commit and keep track of  your theme folder.

Issue is, if I'm on a different machine, the actual database filled with data doesn't live in the themes folder - it lives somewhere else! Therefore, if I were to pull my site onto another computer, it's almost useless because there's no database attached!

What's the most common and modern way of committing a WP site fully to Github or Bitbucket, that includes the database?

Any help would be appreciated!

**Comment by swthate** [comment]
I've never thought to attempt to include the database in git. I'm not sure
if it's possible. But if anyone else had an idea that'd be awesome. I
usually use a plugin called All In One WP Migration to migrate my local db
to staging and production servers.

**Comment by jdfweb** [comment]
@swthate I do the same thing! Except I use a plugin called Duplicator (same deal!).

I have no issue keeping track of my project in Bitbucket - and then when I'm done, simply backing everything up with Duplicator and deploying to stage / production - but it's just a pain that anytime I want to work remotely (and locally) on another machine, I need to back up the WordPress database separately!
