### ISSUE TITLE
Exit status 8 while running npm install

### ISSUE THREAD

**Issue by ashchat404** [olefredrik/FoundationPress#649]
Hi Guys, I ran npm install in the Foundation Press folder and i get exit status 8 error - below is the log

69 info foundationpress@2.2.0 Failed to exec postinstall script
70 error foundationpress@2.2.0 postinstall: `bower install && gulp build`
70 error Exit status 8
71 error Failed at the foundationpress@2.2.0 postinstall script.
71 error This is most likely a problem with the foundationpress package,
71 error not with npm itself.
71 error Tell the author that this fails on your system:
71 error     bower install && gulp build
71 error You can get their info via:
71 error     npm owner ls foundationpress
71 error There is likely additional logging output above.
72 error System Darwin 15.2.0
73 error command "node" "/usr/local/bin/npm" "install"
74 error cwd /Applications/MAMP/htdocs/wordpress/wp-content/themes/FoundationPress
75 error node -v v0.10.25
76 error npm -v 1.3.24
77 error code ELIFECYCLE
78 verbose exit [ 1, true ]

Any help is appreciated, thanks

**Comment by colin-marshall** [comment]
You need to be using Node 4.0+. Update node/npm and try again.

**Comment by ashchat404** [comment]
@colin-marshall Thanks, I updated node, now have exit status 1 error

277 error Darwin 15.2.0
278 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
279 error node v5.2.0
280 error npm  v3.5.2
281 error code ELIFECYCLE
282 error foundationpress@2.2.0 postinstall: `bower install && gulp build`
282 error Exit status 1
283 error Failed at the foundationpress@2.2.0 postinstall script 'bower install && gulp build'.
283 error Make sure you have the latest version of node.js and npm installed.
283 error If you do, this is most likely a problem with the foundationpress package,
283 error not with npm itself.
283 error Tell the author that this fails on your system:
283 error     bower install && gulp build
283 error You can get information on how to open an issue for this project with:
283 error     npm bugs foundationpress
283 error Or if that isn't available, you can get their info via:
283 error     npm owner ls foundationpress
283 error There is likely additional logging output above.
284 verbose exit [ 1, true ]

**Comment by colin-marshall** [comment]
What does it say just before line 277?

**Comment by ashchat404** [comment]
270 verbose lifecycle foundationpress@2.2.0~postinstall: CWD: /Applications/MAMP/htdocs/wordpress/wp-content/themes/FoundationPress
271 silly lifecycle foundationpress@2.2.0~postinstall: Args: [ '-c', 'bower install && gulp build' ]
272 silly lifecycle foundationpress@2.2.0~postinstall: Returned: code: 1  signal: null
273 info lifecycle foundationpress@2.2.0~postinstall: Failed to exec postinstall script
274 verbose stack Error: foundationpress@2.2.0 postinstall: `bower install && gulp build`
274 verbose stack Exit status 1
274 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
274 verbose stack     at emitTwo (events.js:88:13)
274 verbose stack     at EventEmitter.emit (events.js:173:7)
274 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
274 verbose stack     at emitTwo (events.js:88:13)
274 verbose stack     at ChildProcess.emit (events.js:173:7)
274 verbose stack     at maybeClose (internal/child_process.js:819:16)
274 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
275 verbose pkgid foundationpress@2.2.0
276 verbose cwd /Applications/MAMP/htdocs/wordpress/wp-content/themes/FoundationPress

**Comment by colin-marshall** [comment]
I think you're going to have to back even further because I believe the error occurs before all that.  Can you just post the whole log in a gist please?

**Comment by ashchat404** [comment]
Hey sorry for late reply, i just deleted the entire project and started again, and it works now!!! Thanks for your help :)

**Comment by colin-marshall** [comment]
Great! No problem.
