### ISSUE TITLE
woocommerce template overrides not working

### ISSUE THREAD

**Issue by kevinalves** [olefredrik/FoundationPress#651]
Normally to override Woocommerce template files you can really simply do that by copying woocommerce/templates into your theme folder and renaming it woocommerce.

With FoundationPress this does not work. I've confirmed that it does work with, for instance, the default wordpress themes.  Any idea's why? this would greatly improve my workflow.
Thanks!

**Comment by zamson** [comment]
Maybe this has something to do with the renaming of hooks in library/cleanup.php on line 251. Not able to test at the moment.

**Comment by Growthmill** [comment]
Probably related to https://github.com/olefredrik/FoundationPress/issues/601

**Comment by zamson** [comment]
Any updates? Still not working

**Comment by Eccola** [comment]
Just a thought:
https://docs.woothemes.com/document/template-structure/
Especially this part:
"Note: When creating woocommerce.php in your theme’s folder, you will be unable to override the woocommerce/archive-product.php custom template in your theme, as woocommerce.php has priority over all other template files. This is intended to prevent display issues."

**Comment by zamson** [comment]
@Eccola That's correct. I wonder if this issue should be marked as solved.
