### ISSUE TITLE
SCSS Documentation

### ISSUE THREAD

**Issue by joshtipton28** [olefredrik/FoundationPress#652]
I am having trouble figuring out what SCSS is yours and what is packaged with Foundation 6. There are no comments on the styles in the  assets/scss files and it is very confusing compared to the previous version of Foundationpress. I see none of these styles in the Foundation 6 documentation so I'm assuming they are base styles that you created. It would be helpful to have comments on all of it.

**Comment by colin-marshall** [comment]
None of Foundation 6 resides in `assets/scss`. Foundation 6 is installed through bower and all bower packages are installed to `assets/components`.

**Comment by colin-marshall** [comment]
None of Foundation 6 resides in `assets/scss`. Foundation 6 is installed through bower and all bower packages are installed to `assets/components`.

**Comment by Aetles** [comment]
But there are files based on Foundation, like [assets/scss/global/_settings.scss](https://github.com/olefredrik/FoundationPress/blob/master/assets/scss/global/_settings.scss) that is a copy of the Foundations [_settings.scss](https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss).

**Comment by colin-marshall** [comment]
Oh yes, I forgot about the settings file. Thanks!
