### ISSUE TITLE
gulp error notification

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#654]
Does gulp have an error notification in the same way that grunt does?

I mean previously when a css or js compilation error occurred, the terminal would get angry and bounce and display a red badge to notify you of a problem.  Now it quietly proceeds and you won't know it unless you look.

**Comment by colin-marshall** [comment]
It would probably be best if we added [gulp-notify](https://www.npmjs.com/package/gulp-notify) for Sass & JS error handling. It will give you error notifications through your OS's notification system. I can add it in when I get some time.

**Comment by colin-marshall** [comment]
@jimlongo56 does the new error notification system I implemented help?

**Comment by jimlongo56** [comment]
@colin-marshall (sorry for the delay) Hey these new notifications are fantastic. On Mac OS X 10.11 they slide in on the top right as banners. Can't miss them now.  Thanks.

![screen shot 2016-01-02 at 9 49 28 pm](https://cloud.githubusercontent.com/assets/6787988/12077068/495b0770-b19b-11e5-8b49-be01090f9364.png)
![screen shot 2016-01-02 at 9 49 15 pm](https://cloud.githubusercontent.com/assets/6787988/12077069/4d830280-b19b-11e5-950b-7861ccd48d6b.png)

**Comment by colin-marshall** [comment]
@jimlongo56 great!
