### ISSUE TITLE
Errors on installation

### ISSUE THREAD

**Issue by nerdythor** [olefredrik/FoundationPress#665]
I'm using the newest version of Node.js and upon an npm install of FoundationPress I've gotten a couple of weird errors. I'm installing on a testbed localhost in Windows.

This is my first time with Foundation and as a result I'm sure this is a PEBCAK situation but I'd appreciate any pointers y'all could give.

Here's the debug log

[log.txt](https://github.com/olefredrik/FoundationPress/files/75172/log.txt)

**Comment by drivenfaroff** [comment]
Same issues here (running Windows 10). Part of it is because of #664 and I'm guessing the Node version you are running as well.

>This project requires Node.js v4.x.x to be installed on your machine. Please be aware that you may encounter problems with the installation if you are using v5.1.0 with all the latest features.

**Comment by nerdythor** [comment]
Alright, I went through so far and I've been able to resolve the majority of errors I was getting initially. I added Python, the correct version of jsnode, etc. and added them all the the correct Path enviroment.

However now my issue is that the MSbuild 14.0 is absolutely refusing to install the program.

**Comment by olefredrik** [comment]
Sorry for the late reply. Is this still an issue? I just installed a fresh copy of FoundationPress on Windows 10 with no issues. Which error messages do you get on ```npm install```?

**Comment by olefredrik** [comment]
Closing this issue due to lack of response. Feel free to re-open if there's still a problem.
