### ISSUE TITLE
Duplicate jQuery 

### ISSUE THREAD

**Issue by bharuma** [olefredrik/FoundationPress#669]
In the enqueue-script, we are loading the jQuery from Google CDN.

In the gulp file, we are packing jQuery again:
javascript: [
    'assets/components/jquery/dist/jquery.js',

Why is that jQuery is duplicated? Is this for local fall back?

Some of my jQuery code (dynamically loaded, but not through jquery ajax) do not load because of duplicate jquery loads (and I have to inactivate either from foundationpress.js or comment from CDN to make it work)

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/670

**Comment by colin-marshall** [comment]
@bharuma this was my fault. When I made the gulpfile for FP I used the paths in the gulpfile from the Foundation Zurb Template as a reference and it looks like I forgot to remove jQuery. Thanks for pointing out my error.
