### ISSUE TITLE
off-canvas positioning

### ISSUE THREAD

**Issue by RaMonkey** [olefredrik/FoundationPress#671]
I'm looking for a way to get the off-canvas menu coming in from left to right as was the default in FP 5.
It's now pushing the page down which I don't find very convenient.

TIA,

Ramon

**Comment by RaMonkey** [comment]
Bump!

Anyone who knows how to get the canvas menu from the side instead of the top?

The mobile menu I mean!
The new way it's in default now is from top to bottom and covers everything beneath.

TIA,

RaMonkey

**Comment by colin-marshall** [comment]
From the Dashboard go to: `Appearance -> Customize -> Mobile Navigation Layout` and switch it to Off-Canvas and it will open form the side.

**Comment by RaMonkey** [comment]
Thank you very much again Colin :-)

I feel stupid for it being that simple but glad I know now.

**Comment by colin-marshall** [comment]
No problem! Please close this issue if it's fully resolved.
