### ISSUE TITLE
PostInstall issues 

### ISSUE THREAD

**Issue by vicpal25** [olefredrik/FoundationPress#672]
We started noticing jenkins errors when running the postinstall build of foundationpress:
```
foundationpress@5.5.2 postinstall /var/www/app
bower install && grunt build
[ERROR]: module.js:340
[ERROR]:     throw err;
[ERROR]:           ^
[ERROR]: Error: Cannot find module 'imurmurhash'
```
This was working as of two weeks ago. For now, we have commented out the postinstall. Suggestions?

**Comment by olefredrik** [comment]
What version of Node.js are you on? (Type ```node -v``` in your terminal to get your version number) 

You can try
```
rm -rf node_modules
npm install
```

**Comment by olefredrik** [comment]
Because of lack of response, I would assume that this is now resolved.
