### ISSUE TITLE
Bower install js compile errors

### ISSUE THREAD

**Issue by bradymwilliams** [olefredrik/FoundationPress#673]
We had a new install of WP with foundationpress and make some commits and changes from the current master. However, when trying to install the theme and move databases to another WP install, the Foundation off-canvas menu does not work.

I throws this error
```
Tried to initialize off-canvas on an element that already has a Foundation plugin.
```

Any help is appreciated.

**Comment by olefredrik** [comment]
Ok? What changes did you commit form the current master?

**Comment by BlackSheepWithMe** [comment]
Okay after some intensive digging after scrapping my build it appears the problem isnt with the migrations as it is with the bower installation somewhere. Upon installing a new bower component foundation compiles and tries to initialize twice or something? When I remove the `init-foundation.js` file the error goes away but so does the mobile nav. Any help is appreciated

**Comment by olefredrik** [comment]
Do you get any errors in console?

**Comment by russtache** [comment]
No console errors.

**Comment by BlackSheepWithMe** [comment]
I did not get any console errors, just the original warning in the browser console

**Comment by olefredrik** [comment]
Do you have a link to a test site where I can have a look at what's going on?
