### ISSUE TITLE
Mobile Menu not working correctly.

### ISSUE THREAD

**Issue by FDfranklin** [olefredrik/FoundationPress#675]
Hello,

I'm having an issue with the mobile menu.

When I press the hamburger icon the menu comes on canvas, when I click on a menu item it just moves off canvas without taking me to the next page. I've tested this in browser and on my iPhone 6.

When on the computer in Chrome if I double click a menu item it will take me to the page but not on a single click.

It's almost as the first click is telling the menu to go off canvas and isn't registering I'm clicking the link.

Any ideas what could be causing this?

Thanks

**Comment by FDfranklin** [comment]
Here's a crappy gif of my issue. The last attempt was a double click.

![Image of Yaktocat](http://i.imgur.com/5GRUdAg.gif)

**Comment by LukePettway** [comment]
Check your markup, whenever I've had this issue, its because a <div> wasn't closed correctly and as a result the overlay was going overtop of the off-canvas menu. Double-click works because when it is closing the overlay goes away and you are getting through just in time.

**Comment by olefredrik** [comment]
@FDfranklin : Which version of FP are you using? It should work as expected. Have you made any significant changes in the markup or navigation walkers?

**Comment by FDfranklin** [comment]
How do I check what version I'm on?

I have not made any significant changes.

**Comment by LukePettway** [comment]
@FDfranklin check in your style.css in your theme folder, it will look like this:

```css

/*
Theme Name:         FoundationPress
Theme URI:          http://foundationpress.olefredrik.com
Github Theme URI:   https://github.com/olefredrik/FoundationPress
Description:        FoundationPress is a WordPress starter theme based on Foundation 6 by Zurb
Version:            2.3.0
Author:             Ole Fredrik Lie
Author URI:         http://olefredrik.com/

License:            MIT License
License URI:        http://www.opensource.org/licenses/mit-license.php
*/

```

**Comment by olefredrik** [comment]
I have verified that this works as expected (in the latest version of FP). Your problem is possibly related to a ```<div>``` that is not closed.
