### ISSUE TITLE
Default Topbar

### ISSUE THREAD

**Issue by arielnoname** [olefredrik/FoundationPress#677]
Hello,

I have this question: Why does FoundationPress comes with a modified version of the Top Bar? I'm finding kind of difficult to apply my own styles to it because I want to start from scratch.

Thanks for the awesome theme again man

EDIT: This is the first project using Foundation 6, started like 3 hours ago.. It's all very different now and I'm learning this again. Now the Topbar doesn't have all those nice variables to make it pretty. But then, the question remains.

**Comment by olefredrik** [comment]
Hi, 

The topbar has been rewritten and broken down into smaller parts as part of the upgrade to the Foundation 6.

These links may be helpful:
http://foundation.zurb.com/sites/docs/top-bar.html
https://zurb.com/university/lessons/how-to-re-create-top-bar-with-foundation-6
http://foundation.zurb.com/forum/posts/36228-foundation-6-topbar-like-f5

Cheers,
Ole Fredrik
