### ISSUE TITLE
Plans for using SASS?

### ISSUE THREAD

**Issue by Hobbit78** [olefredrik/FoundationPress#678]
Hi there,

Not really an issue but more an idea/question.
Are there any plans to change over to sass instead of scss in the smacss-directory?

Thanks in advance!

Love the work!

**Comment by colin-marshall** [comment]
Zurb Foundation uses SCSS, so it makes sense that FoundationPress uses SCSS. Also, for what I can tell, SCSS syntax is much more widely used in comparison to Sass.

What directory are you talking about?

**Comment by Hobbit78** [comment]
Hi Colin,

I haven't really thought about that and I think you're right about that scss is more common than sass.
Mostly I just import the necessary files into my sass files, but this method I can still use. It was just a thought.

I was talking about the directories where the scss files are stored in the assets folder. The method you use is called smacss. It's just a way to keep the sass files organized well, like Base, Layout, Modules etc.

Anyway, thanks for your clear answer and keep up the good work.

Cheers!
