### ISSUE TITLE
gulpfile javascript build

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#680]
@colin-marshall could you look at the gulp.task('javascript', function() 

Even if I comment out all the assets in PATHS{ javascript:[] } and rebuild the file the resulting foundation.js shows no changes.

**Comment by colin-marshall** [comment]
Anytime you make changes to the gulpfile you have to stop and restart the gulp task for them to take effect. Did you do this after commenting out the paths?

**Comment by jimlongo56** [comment]
I didn't have watch running.  I just ran build.

**Comment by colin-marshall** [comment]
@jimlongo56 I have solved the issue.

When I made the gulpfile I did some testing and thought I didn't need to have a clean task that deletes the files before it rebuilds them. I think I only tested it with the SCSS though and not the JS, and it looks like foundation.js definitely needs to be deleted before it gets built. Check out the PR above if you need this fixed before it gets merged.

**Comment by jimlongo56** [comment]
Thanks @colin-marshall that seems to have fixed that.

**Comment by colin-marshall** [comment]
Yup! Would you mind reopening this issue until the PR is merged? Thanks!
