### ISSUE TITLE
Off canvas menu won't open/reveal left

### ISSUE THREAD

**Issue by adibbz** [olefredrik/FoundationPress#682]
I have set the mobile menu to Offcanvas through the Appearance > Customize menu and nothing happens. It attempts to reveal the topbar but with no menu. It doesn't slide right and open the offcanvas menu. 

I ran into a similar issue with previous version of FP and was able to fix by toggling the Topbar and Offcanvas options but no luck this time. 

I pulled down FP on 1/6/16 and am developing locally.

**Comment by bujordan** [comment]
I'm also seeing the same issue. Pulled down on 1/19.

**Comment by olefredrik** [comment]
Hmm. Strange as it works as expected here. Do you get any errors in your console?
