### ISSUE TITLE
Old project with grunt: not able to make some change

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#683]
Hello.
I have to make some change on an old project (FoundationPress with grunt).
grunt
Loading "sass.js" tasks...ERROR
>> Error: `/Volumes/Dev Studio12/www/LeSaint/dev/wp-content/themes/LeSaintZurbPress/node_modules/node-sass/bin/darwin-x64-v8-4.6/binding.node` is missing. Try reinstalling `node-sass`?

Seems there is a problem with sass but bower update do not change anything... I tried 'npm install node-sass' without success...
In the meantime, I use Codekit to compile the CSS but I really prefer grunt or Gulp...
Any idea?

**Comment by dantahoua** [comment]
Am I the online who change old project sometime? I can't find a solution for now, same problem with another project...
Is there a way to change it to gulp or to run bower without error?

**Comment by dantahoua** [comment]
So for the now the only solution I found after trying to install without success node-sass is to switch to grunt-contrib-sass...

**Comment by adzay** [comment]
I have the same issue. I have also been looking for an answer.

**Comment by olefredrik** [comment]
Compatibility with versioning of node dependencies & npm seems to be a persistent problem. See the README.md file included with your version of FP and check which version of Node.js is supported. You can [upgrade / downgrade your version of node.js with Homebrew](http://www.wiredatom.com/blog/2015/03/30/downgrade-node-js-to-a-specific-version-using-homebrew/) . If this does not work, I'm afraid I can not help here.

**Comment by hawbsl** [comment]
Ole I'm looking at my README.md file and can't see anything telling which version of node.js to use. This is all I have, I think:

```
**Okay, so you'll need to have the following items installed before continuing.**

  * [Node.js](http://nodejs.org)
  * [Grunt](http://gruntjs.com/): Run `[sudo] npm install -g grunt-cli`
  * [Bower](http://bower.io): Run `[sudo] npm install -g bower`

## Quickstart

```
