### ISSUE TITLE
Can't find topbar breakpoint in settings.scss

### ISSUE THREAD

**Issue by rachelchorney** [olefredrik/FoundationPress#684]
I am trying to change the topbar breakpoint so the mobile topbar displays at medium screens and smaller and I can't figure out how using the settings. My settings scss file doesn't have a setting for it.

**Comment by nevernotsean** [comment]
Top Bar breakpoints are now part of a new plugin for Foundation 6. See here:
http://foundation.zurb.com/sites/docs/responsive-navigation.html

**Comment by rachelchorney** [comment]
Thank you!
