### ISSUE TITLE
library/navigation.php

### ISSUE THREAD

**Issue by rachelchorney** [olefredrik/FoundationPress#685]
Is it okay to edit the library/navigation.php file or is there a better way to adjust the breakpoints for the navigation?

**Comment by colin-marshall** [comment]
Seems like something that could be accomplished using only CSS.

**Comment by olefredrik** [comment]
You're right. I removed the inline visibility classes from navigation.php and added breakpoint mixins for navigation in _navigation.scss 

https://github.com/olefredrik/FoundationPress/pull/698

**Comment by anthonywjackson** [comment]
Struggling to make the top bar and title bar breakpoint to behave as expected. Latest fresh FoundationPress install shows both .vertical and .dropdown menus on medium and up. On small, the title bar appears with hamburger menu link, but when clicked nothing happens. 

Commenting out `.main-navigation {
  @include show-for(medium);
}` from _navigation.scss gets the hamburger link to work on small, but doesn't fix both mobile and desktop menus showing on medium and up.

Ideally there's a simple way to choose the breakpoint for the mobile menu. I wonder if I'm missing something obvious.
