### ISSUE TITLE
Missing semicolon in SCSS produces a segmentation fault.

### ISSUE THREAD

**Issue by JayyWalker** [olefredrik/FoundationPress#686]
I had gulp watch running fine until I missed out a semi colon. It took about 2 hours for me to realise this as I thought the segmentation fault was an issue with npm and not one my scss files. Is there a way to fix this? Maybe a scan that debugs the files to prevent so much development time being wasted?

**Comment by colin-marshall** [comment]
Did you receive any errors in the console or through gulp-notify?

**Comment by JayyWalker** [comment]
@colin-marshall I received it through the console. Gulp notify isn't installed...maybe I should install gulp-notify?

**Comment by colin-marshall** [comment]
Gulp-notify was added to FoundationPress about 3 weeks ago. Copy/overwrite your `gulpfle.js` and `package.json` with the latest versions:

https://github.com/olefredrik/FoundationPress/blob/master/gulpfile.js
https://github.com/olefredrik/FoundationPress/blob/master/package.json

Then run `npm install`, and you should be good to go.
