### ISSUE TITLE
media breakpoints

### ISSUE THREAD

**Issue by silviaball** [olefredrik/FoundationPress#688]
Hi, I'm new in foundation press.
I try to insert $medium-down: "#{$screen} and (max-width:#{upper-bound($medium-range)})"; in my _settings.scss file like the guide http://foundation.zurb.com/sites/docs/v/5.5.3/media-queries.html but it doesn't work. In my css file I see  @media only screen and (max-width: upper-bound(40.063em, 64em)) { 
That 's not right because there is  upper-bound and not the value in em. Why this? Is upper-bound function not defined in Foundation press?

**Comment by colin-marshall** [comment]
What version of FoundationPress are you using? The latest versions of FoundationPress use Foundation 6 and you linked the Foundation 5.5.3 docs. Try here: [Foundation for Sites 6 Media Queries](http://foundation.zurb.com/sites/docs/media-queries.html).

**Comment by silviaball** [comment]
Thanks

2016-01-21 20:53 GMT+01:00 Colin Marshall <notifications@github.com>:

> What version of FoundationPress are you using? The latest versions of
> FoundationPress use Foundation 6 and you linked the Foundation 5.5.3 docs.
> Try here: Foundation for Sites 6 Media Queries
> <http://foundation.zurb.com/sites/docs/media-queries.html>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olefredrik/FoundationPress/issues/688#issuecomment-173689700>
> .
>



-- 
Silvia Ballardin | Web Developer
Thehouseofmouse

Via Brentanella, 54 31023 Resana - TV
T +39 0423 1958300
F +39 0423 738075
