### ISSUE TITLE
Run Watch/Build Issues

### ISSUE THREAD

**Issue by moseke** [olefredrik/FoundationPress#690]
Having some issues getting up and running:

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/Users/1163442/.node/bin/npm" "run" "watch"
npm ERR! node v4.2.5
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.3.0 watch: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.3.0 watch script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.
[npm-debug.txt](https://github.com/olefredrik/FoundationPress/files/99383/npm-debug.txt)

**Comment by colin-marshall** [comment]
Did you get errors when you ran `npm install`?

**Comment by moseke** [comment]
Even though I started fresh with Node today it did not install npm. I stripped it and started over and seem to be running just fine. Thanks for triggering that line of problem-solving.
