### ISSUE TITLE
[Shortcodes] [Buttons]

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#694]
@josh-rathke I was driving through Lakeside on my way to Whitefish a couple weeks ago and it reminded me of the shortcodes we were working on. Let's make a separate issue for each shortcode so we can keep everything organized and help move things forward. Any update on when we can make some progress on this?

Thanks!
Colin

**Comment by dantahoua** [comment]
Hey guys! I was looking for some shortcode "Foundation 6 ready" and I just found that: http://inti.waqastudios.com/ or https://github.com/waqastudios/inti-foundation
You should throw an eye on it, very well made, the guy is good! And the shortcode are perfect! :)

**Comment by josh-rathke** [comment]
I have been super busy lately, sorry. I'll try to take a peek at it this
weekend.

Next time you're in Lakeside give me a shout and we'll grab a cup of coffee
or something. Even better, a Beer at the Tamarack.

-Josh

Josh Rathke
I.T. Director & Web Developer, YWAM Montana | Lakeside
p: (406) 844-2221 m: (765) 637-5847 a: 501 Blacktail Rd. Lakeside MT, 59922
s: www.ywammontana.org e: josh.rathke@ywammontana.org

**Comment by josh-rathke** [comment]
@colin-marshall & @olefredrik I haven't forgotten about this, or abandoned it for that matter. I am working on a project that I think would benefit greatly from having this in it. It was built using one of the last versions of FoundationPress before it was upgraded to 6 (facepalm)....But anyways, I am going to try and get it up to par with the current build and go from there.

Sorry about being absent lately. Ever since the Holidays things have been super busy around here.

**Comment by colin-marshall** [comment]
@josh-rathke no worries buddy. It's open source, you get to it when you can!

I would definitely be down to meet you for a beer next time I head north. Always wanted to try that Tamarack because I have heard it is better and has a different menu than the one in Missoula, which is pretty solid in my opinion.

**Comment by nitrokevin** [comment]
Hi just wondered if anyone has any updates on shortcodes, is there anything to test out?

**Comment by olefredrik** [comment]
Hi guys. I checked out the Foundation parent theme that @dantahoua mentioned. Looks like a pretty decent theme with shortcode functionality built right in.

@joshrathke @colin-marshall If you still have an interest making shortcodes for FoundationPress, it might be worth taking a look at [this](https://github.com/waqastudios/inti-foundation/tree/master/framework/shortcodes). As I see it, there is no need to reinvent the wheel.

**Comment by olefredrik** [comment]
As it's been a year and a half since this issue was opened and there has not been any progress yet (no blame), I think it's fair to close this :)
