### ISSUE TITLE
npm run package do not minify js

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#695]
Hello.
Don't you think it would be better if "npm run package" create a "production" package?
Actually when we create a package, the js is not minified.
If I do "npm run production" the js is minified but I don't have any package...

**Comment by colin-marshall** [comment]
I agree that it would be better the way you suggest. In the meantime, you can run `gulp package --production` and you should get minified files.

**Comment by dantahoua** [comment]
Thanks Colin, but I already tried "npm run package --production" and the foundation.js is not minified... ;)
I tried different combination of command but cannot achieve the desired result. (I'm not that good with npm,gulp, but I learn fast!).

**Comment by colin-marshall** [comment]
The command you tried is different from the one I told you to use.  Try the one I suggested.

**Comment by dantahoua** [comment]
Oh yeah, sorry! I add to install gulp globally to be able to run the "gulp" command and yes it's working. Thanks.

**Comment by dantahoua** [comment]
Thanks! :)
