### ISSUE TITLE
Reveal does not display properly on a page with right sidebar layout

### ISSUE THREAD

**Issue by jkaliski** [olefredrik/FoundationPress#696]
Hi Ole Frederik. I am having trouble adding a modal window into a post with 'sidebar on the right' layout. 
As you see on the image attached, on mobile layout the modal somehow lands on the bottom of the page by default:
![screen shot 2016-01-28 at 15 41 49](https://cloud.githubusercontent.com/assets/6241598/12647491/c266b864-c5d5-11e5-9542-725e8055560a.png)

While on desktop it is displayed somewhere under the vertical middle.
![screen shot 2016-01-28 at 15 41 30](https://cloud.githubusercontent.com/assets/6241598/12647500/ca7f1744-c5d5-11e5-924c-cb253938f3cd.png)

I tested the same code on fullwidth layout page template, no problems there. 

Any ideas would be highly appreciated. Thanks!

**Comment by olefredrik** [comment]
Tested reveal on a single post with a right sidebar layout. Here is the result. Looks good to me?

![reveal](https://cloud.githubusercontent.com/assets/1080017/13669377/5ae2ac16-e6c3-11e5-80ce-7f1c39f02b2f.png)

**Comment by jkaliski** [comment]
Appreciate that you looked on that. It looks very good to me too. I have no idea what is messing up modals position on my install. Couldn’t spot the issue with the Web Inspector either. I have a fresh install on the theme now, it solved the issue.

Many thanks.
