### ISSUE TITLE
Noob question regarding fonts and how to set them up

### ISSUE THREAD

**Issue by andreaarcher** [olefredrik/FoundationPress#702]
How do you add/install fonts? 
my client sent over a mish-mash of eto, svg, ttf and .less files and I can't for the life of me figure out where to put them and how to call...

thanks in advance

**Comment by FlatspinZA** [comment]
You reference your font file in the header.php file. 

For instance, referencing a Google font, put this line between your `<head>` tags in header.php:

`<link href='https://fonts.googleapis.com/css?family=Raleway:800,600' rel='stylesheet' type='text/css'>`

Then change $body-font-family in _settings.scss so: `$body-font-family: 'Raleway', sans-serif;`

So, now you have a custom font you need to use - I'm pretty sure you'd put it in your theme_directory/assets/fonts folder

There's an excellent article <a href="http://tympanus.net/codrops/css_reference/font-face/">here</a> on using your own custom fonts.
