### ISSUE TITLE
Fonts issues.

### ISSUE THREAD

**Issue by pranay5289** [olefredrik/FoundationPress#703]
Hey Folks,

I have used this theme for my new website. and i have also added the @fontface code on my style sheet but it seems to me that the font is not applying to my site where ever i want too. I am trying to solve this issue but didn't find any solution instead of using plugins that are available for in WordPress for google fonts.
Please suggest me the possible solution for how to install our fonts on this theme and how to use them in our website.

Thank in Advance.

**Comment by olefredrik** [comment]
If you're using Google Fonts, you have three different options for including the webfonts to your site. [Here you'll find the step-by-step instructions](https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Open+Sans) by Google.

**Comment by pranay5289** [comment]
ohh yeah i found it before anyways thanks :) ..!!
