### ISSUE TITLE
how to style wordpress footer widgets

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#706]
I've used a shortcode to place a form in the footer widget in wordpress, the form is getting "large-4 columns widget widget_text" class applied to it automatically 
How can I change the large-4, I'm not sure where this is being defined?

**Comment by chuckn246** [comment]
If you haven't figured it out yet, check /library/widget-areas.php.

**Comment by nitrokevin** [comment]
Thank you yes this is what I was after

**Comment by wakatoyee** [comment]
How about the content area? Have you figured it out?

**Comment by chuckn246** [comment]
Could you be a little more specific?

On the full with template or sidebar template or??

Probably wouldn't hurt to open a new issue either so more people can see it and/or benefit from it.

**Comment by phylaxis** [comment]
I'm having an odd issue with this that is similar, but unrelated. I have added 4 widgets to the footer widget area and they are all being defined as `large-4`, but in the CSS `large-4`is being set to `width: 33.33333%;`, it should be '25%'. Anyone know why this would be happening?
