### ISSUE TITLE
Misc changes to consider

### ISSUE THREAD

**Issue by Aetles** [olefredrik/FoundationPress#708]
In my (now heavily modified) fork of FoundationPress I have a branch were I kept some changes that could be brought back to FoundationPress if it is something others like, before I started to made more sever changes for my own need. 

I'm not gonna create a bunch of PR:s unless there is a real demand for it, because a lot of the changes is more personal preference that necessary change. Instead I'm listing them here and you can decide if this is something for FoundationPress. (Stuff like moving files and renaming folder could create confusions for other users, for example.)

Most of these changes are self-explanatory, I think, but further motivation/explanation for these changes are in some of the commit descriptions. 

- Remove "precomposed" from Apple touch icons
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/46efa37a7a462a1112f0fbda2bd1b02279986ca0

- Use @package for theme name, not @subpackage
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/aff2c2dbf01277891033290e1c7c46c1b81a18d7

- Omit the closing PHP tag at the end of files
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/2d3ebc951d94f0c7ac1b85038b69584ad53014ae

- Use bloginfo charset instead of hard coded utf-8
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/82a16139795cb3e877555e3b883fc59c8b89ce8b

- Rename page template folder to "page-templates"
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/b490f9992648b46f5e0afa563d52662528be96fb

- Rename template parts folder to "template-parts"
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/bd37bd024ec26ebb3d62f045a6c6cf1e53d0aa02

- Add trailing commas to gulpfile.js
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/53616439b069c4188298f96b8b80efdc176e1a48

- Move template parts to template-parts folder
https://github.com/Adagio-design/Adagio-Foundation-Starter/commit/bdab6e8c5490a21969b0ec094b4aace0ff9dd955

**Comment by olefredrik** [comment]
@Aetles : All of the changes you listed above makes sense to me. If you could create pull requests, I will gladly merge your changes into the master branch.

**Comment by Aetles** [comment]
I have busy week but I'll give it a try this weekend! (Actually never made a PR before, so I'm not promising anything :smile: )

**Comment by colin-marshall** [comment]
@Aetles I put in the pull request for you. Your post made it very easy for me to merge in all your commits so you will get all the credit. Thanks for helping out!

PR: #717

**Comment by Aetles** [comment]
Oh, nice! Thanks!

**Comment by olefredrik** [comment]
Merged https://github.com/olefredrik/FoundationPress/pull/717
