### ISSUE TITLE
Off canvas mobile menu issue

### ISSUE THREAD

**Issue by cotswold** [olefredrik/FoundationPress#709]
I've created a main menu and see there are 2 positions available, top right and mobile so I've assigned it to top right. Now when I make the browser window small the hamburger icon appears and the menu disappears from top-right as you'd expect however if you click the hamburger icon nothing happens.

I thought it might just be that I need to create another menu and assign to mobile position so did that but now the second menu displays under the top right menu in a list. If I make the browser smaller both menus disappear but the hamburger still doesn't work. I've checked the console and am not getting any error notices.

![screen shot 2016-02-05 at 14 27 56](https://cloud.githubusercontent.com/assets/2691387/12848966/cdb49304-cc14-11e5-93f4-15f3df60e9e7.jpg)

I'd be very grateful if anybody knows why it isn't working? I have the latest files installed.

Could it be related to the file path problems? In order to get the npm gulp install/build to work without errors I had to change the gulpfile.js paths from `assets/components` to `bower_components`

**Comment by mlangone** [comment]
Have you tried this? 
https://github.com/olefredrik/FoundationPress/issues/639#issuecomment-179549818

**Comment by cotswold** [comment]
That worked thanks! I had been trying to set it up in the admin area without realising the mobile menu setting is in customizer

**Comment by colin-marshall** [comment]
@cotswold most likely those are file permission problems you were having, not file path problems. `assets/components` is the path for bower which is set in `.bowerrc`.  You should sort out the errors instead of changing all the paths to `bower_components`. What errors were you experiencing during `npm install` and `npm run build`?

If it's a permissions issue, see:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by olefredrik** [comment]
Just discovered that a few errors with the topbar was introduced in my latest navigation changes. Should be fixed now #714 .

**Comment by FlatspinZA** [comment]
I can confirm that the issue with the menu title is now fixed.
