### ISSUE TITLE
Reveal Modal

### ISSUE THREAD

**Issue by amenity** [olefredrik/FoundationPress#712]
I noticed that Reveal Modal is not in the Kitchen Sink examples — should it be implemented separately? Using the [Foundation syntax for modals](http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html) is not working out of the box.

**Comment by olefredrik** [comment]
Hi @amenity ,

What version of FoundationPress are you using? The latest version is based on Foundation 6. The link you're referring to is pointing to the Foundation 5 docs. If you use the syntax as described [in the Foundation 6 docs](http://foundation.zurb.com/sites/docs/reveal.html), it should work as expected. 

I [just updated the Kitchen Sink template](https://github.com/olefredrik/FoundationPress/pull/713) with a working example of the reveal modal. The [demo site](https://foundationpress.olefredrik.com/kitchen-sink) is updated as well.

Please let me know if this don't work for you.

**Comment by amenity** [comment]
@olefredrik Aha! You're right.  Thanks so much, and for the super-speedy template update.

**Comment by olefredrik** [comment]
:+1:
