### ISSUE TITLE
Modify topbar to accordion menu

### ISSUE THREAD

**Issue by dioogbento** [olefredrik/FoundationPress#715]
Hello,
I've been kind of stuck trying to figure out how to solve a design issue. Hope anyone could give a hint.
I would like to use the menu included in the header but move it to what would be a left side bar (I don't think I could make use of a menu in the sidebar widgets because it doesn't allow me to configure its layout or responsive behavior, am I right?).

So, may I and how could I modify the topbar into a vertical accordion menu on the left side of any page?

Thanks in advance.

**Comment by FragaGeddon** [comment]
In the header.php file look `<div class="top-bar-right">` and just remove right from the class.

**Comment by dioogbento** [comment]
@FragaGeddon I'm sorry if I didn't make myself very clear… I think I could do something like that, but then I would have to add a .row class to .off-canvas-content and some columns to header and .container, to show them "side by side". Am I correct? And I'm not sure if that is good practice…

**Comment by olefredrik** [comment]
This issue is related to this feature request https://github.com/olefredrik/FoundationPress/issues/715

**Comment by dioogbento** [comment]
Hi @olefredrik Yes it's related. Thanks for the reference.

In the meanwhile I took a different approach:
Registered a new menu for the sidebar and called it in sidebar.php

sidebar.php:
```
foundationpress_side_bar_nav();
```

navigation.php:
```
register_nav_menus(array(
	'top-bar-r'  => 'Right Top Bar',
	'mobile-nav' => 'Mobile',
	'side-bar-nav' => 'Side Bar',
));


/**
 * Desktop navigation - side bar
 *
 * @link http://codex.wordpress.org/Function_Reference/wp_nav_menu
 */
if ( ! function_exists( 'foundationpress_side_bar_nav' ) ) {
	function foundationpress_side_bar_nav() {
		wp_nav_menu( array(
			'container'      => false,
			'menu_class'     => 'vertical menu',
			'items_wrap'     => '<ul id="%1$s" class="%2$s desktop-menu" data-accordion-menu>%3$s</ul>',
			'theme_location' => 'side-bar-nav',
			'depth'          => 3,
			'fallback_cb'    => false,
			'walker'         => new Foundationpress_Side_Bar_Walker(),
		));
	}
}
```
