### ISSUE TITLE
New menu

### ISSUE THREAD

**Issue by msacchetti** [olefredrik/FoundationPress#716]
I am trying to register a new nav menu, doing what I always do.. copy and paste 

`if ( ! function_exists( 'foundationpress_top_bar_r' ) ) {
	function foundationpress_top_bar_r() {
		wp_nav_menu( array(
			'container'      => false,
			'menu_class'     => 'dropdown menu',
			'items_wrap'     => '<ul id="%1$s" class="%2$s show-for-medium" data-dropdown-menu>%3$s</ul>',
			'theme_location' => 'top-bar-r',
			'depth'          => 3,
			'fallback_cb'    => false,
			'walker'         => new Foundationpress_Top_Bar_Walker(),
		));
	}
}`

and change all the function calls/names to something unique. the menu is showing up properly in the backend, but calling the function in the front end wont show the menu. 

I could have sworn ive done this with foundationpress on almost every site ive built.. did anything change? ive checked for typos 10 times. 

Thanks

**Comment by colin-marshall** [comment]
Does wp_debug show any errors?

**Comment by msacchetti** [comment]
After trying everything else, i changed 'depth' => 1, instead of 3, and it showed up. No idea why, consider this a fluke or closed. Thanks Colin
