### ISSUE TITLE
Error messages always displayed when using Abide validation

### ISSUE THREAD

**Issue by phylaxis** [olefredrik/FoundationPress#719]
When building a form within the Foundation Press theme and using Abide validation there seems to be an issue where the `error` text is always displayed. This should load hidden and only appear when the error is triggered. Below is a simple example. The text in the `<small class="error">` element should not be displayed on load, but for some reason it is.

```
<form data-abide id="signupform" action="<?php echo wp_registration_url(); ?>" method="post">
<label for="email"><?php _e( 'Email', 'tmo-accounts' ); ?> <strong>*</strong>
     <input type="text" name="email" id="email" required pattern="email" />
</label>
<small class="error">A valid email address is required.</small>  

<p><input type="submit" name="submit" class="button-primary register-button" value="<?php _e( 'Register', 'tmo-accounts' ); ?>"/></p>
</form>
```

**Comment by olefredrik** [comment]
Try changing ``<small class="error">`` to ``<small class="form-error">``

I've recently added an [Abide demo](https://foundationpress.olefredrik.com/kitchen-sink#abide) to the kichen sink template.

Please let me know if this helps.

**Comment by phylaxis** [comment]
Thanks. Guess the issue was I was still using the 'old' Foundation 5 markup.
