### ISSUE TITLE
Offcanvas menu not working

### ISSUE THREAD

**Issue by MarineLB** [olefredrik/FoundationPress#720]
Hi, i'm using the latest version of FoundationPress, i noticed that in header.php this line of code called the mobile menu  : 
`<?php if ( ! get_theme_mod( 'wpt_mobile_menu_layout' ) || get_theme_mod( 'wpt_mobile_menu_layout' ) == 'topbar' ) : ?>
					<?php get_template_part( 'parts/mobile-top-bar' ); ?>
				<?php endif; ?>`
so i tried to replace top-bar by off-canvas (as the off-canvas.php exists) 
It does show a menu, but it definitely does not work like an offcanvas menu..
please help ?

**Comment by olefredrik** [comment]
Hi, @MarineLB !

Did you set the mobile menu to be displayed as an offcanvas menu in the customizer?

![customizer](https://cloud.githubusercontent.com/assets/1080017/12917995/eade055c-cf3c-11e5-9676-ed21e7f2e8e8.png)

**Comment by MarineLB** [comment]
ohhh i was looking for this setting ! 
i did just make the change, however it still doesn't appear !

**Comment by olefredrik** [comment]
Did you check the mobile option in Appearance -> Menus in wp-admin?

![menu-settings](https://cloud.githubusercontent.com/assets/1080017/12918096/83abca58-cf3d-11e5-9230-b1a7814f93f6.png)

**Comment by MarineLB** [comment]
Yep, it's checked.
I noticed something : the off-canvas menu does show in the chrome devtools, however it's hidden on the left (maybe some js is not being loaded ?) and its z-index was too low (9 worked) 
Still : there is no top bar with the burger icon at all

**Comment by olefredrik** [comment]
Sounds like something weird has happened. If you roll back the changes you just did in the .php files, what errors do you get in the devtools console (chrome)?

**Comment by MarineLB** [comment]
There was no particular errors in the console ! (I returned the header.php to its previous condition)

**Comment by olefredrik** [comment]
Hmm. I just pulled the latest master branch to my local dev install, did an ```npm run build``` and fired it up on localhost. The offcanvas is functioning as expected here, so it's quite difficult to troubleshoot as I'm unable to reproduce the error.

**Comment by MarineLB** [comment]
i actually might not have the latest version (it's older than 2 days ago). i'll try to add the changes and see if it works ! 
thanks for your help !

**Comment by MarineLB** [comment]
Well i've updated all the changes related to the topbar issue, but i still don't get the hamburger icon

here's how it looks like : 
<img width="1280" alt="capture d ecran 2016-02-09 a 15 34 57" src="https://cloud.githubusercontent.com/assets/17142863/12919122/df28b3a0-cf42-11e5-9cad-4f368a87cc5b.png">

**Comment by olefredrik** [comment]
Both off-canvas and hamburger icon works on a fresh install. Unfortunately I have not the ability to debug on a remote dev environment.
