### ISSUE TITLE
Adjusting breakpoints topbar in FP6

### ISSUE THREAD

**Issue by RaMonkey** [olefredrik/FoundationPress#726]
Hi I'm trying to show the hamburger menu at all resolutions.

However, I can't find a way to control the breakpoints ;-/

**Comment by RaMonkey** [comment]
Perhaps this isn't the right place to ask for this type of thing, but would really help me out knowing how to achieve this.

TIA 

Ramon

**Comment by olefredrik** [comment]
Hi @RaMonkey ,

The value of ```data-responsive-toggle``` should be the ID of the menu you're toggling.

By default, the title bar will be visible on small screens, and the Menu hides. At the medium breakpoint, the title bar disappears, and the menu is always visible. This breakpoint can be changed with the ```data-hide-for``` attribute in HTML, or the hideFor setting in JavaScript.

So in header.php you could modify line 36 to 
```
<div class="title-bar" data-responsive-toggle="site-navigation" data-hide-for="xxlarge">
```

or possibly create a new insanely large breakpoint in ```_settings.scss``` and use that instead. There should be ```data-show-for="all"``` setting on this component, but there isn't.

[More info can be found in the Foundation docs](http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-toggle)

**Comment by RaMonkey** [comment]
Thank you very much Ole.

**Comment by swthate** [comment]
What if you need a custom breakpoint at an oddball figure, like 855px, that doesn't fit nicely with the pre-existent ones made by Zurb?
