### ISSUE TITLE
Adding logo in center of Nav Bar

### ISSUE THREAD

**Issue by kevinman1234** [olefredrik/FoundationPress#730]
Im a little new at this. How would i go about adding a logo in the center of a navigation Bar.

Menu | Price | Logo | About | Contact Us

**Comment by colin-marshall** [comment]
I updated the building block for a centered logo with F6 here:
http://zurb.com/building-blocks/centered-top-bar-with-logo

**Comment by kevinman1234** [comment]
Thank you very much, however is there a way to do this using php so that i can change the navigation names in wordpress, while at the same time have logo in center?

**Comment by colin-marshall** [comment]
You would just have to alter the top-bar in header.php to be like the building block.

**Comment by kevinman1234** [comment]
omg lol thank youvery much,  sorry so new at this
