### ISSUE TITLE
npm WARN package.json foundationpress@5.5.1 No license field.

### ISSUE THREAD

**Issue by ableslayer** [olefredrik/FoundationPress#734]
I have updated my node.js and everything so that I can run the new FoundationPress 6 on a different project. Now that I'm back here on my old project which still uses Foundation 5, I can't run anything.

I can't "watch" and change my scss files. It's ok if I don't update this to Foundation 6 but I just want to change something to the theme (sass file).

Before, I'm running `foundation watch` and it watches my sass files. Now every time I do that it says: **Error: missing script: start**

**I tried npm install and it says**:
npm WARN package.json foundationpress@5.5.1 No license field.

**npm run watch and it says**:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12

tried: `npm rebuild node-sass` which I used on my other old project that worked and here it says:
Error: Cannot find module 

What can I do to make this old project working again?

**Comment by colin-marshall** [comment]
The warning about the license field you can ignore, thats not the issue. 

Try deleting your node_modules folder and running npm install. 

It could be that you need to be on an older version of node for this. Look into nvm-windows and install an older version of node like 0.12 or 0.10 if the previous suggestion doesn't work.

**Comment by ableslayer** [comment]
Deleting and npm install didn't work. Too sad... I have lots of projects that uses FoundationPress 5

I'm going to install nvm-windows. Not sure if this is really worth it or just add my additional css to the minified foundation.css.

But let me try this first.

thanks!

**Comment by colin-marshall** [comment]
A user in issue #722 says that they switch between Node 0.10.33 for FP 1.x projects and Node 4.2.6 for FP 2.x projects.

**Comment by olefredrik** [comment]
Was your problem solved, @ableslayer ?

**Comment by ableslayer** [comment]
@olefredrik - I'm having trouble insalling the nvm for windows. Currently I just added the css to foundation.css which is kinda childish.

 I got to try again. But I know what to do now and close this issue. 

Thanks!
