### ISSUE TITLE
Clean Install Problem

### ISSUE THREAD

**Issue by fatbuddha-design** [olefredrik/FoundationPress#737]
Hello
I have now tried two separate clean installs of Foundation Press following the instructions on the Github page, ie clone, npm install, npm run watch, but in both cases I have the following error :-

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@1.3.14
3 info using node@v0.10.22
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
6 info prewatch foundationpress@2.4.0
7 info watch foundationpress@2.4.0
8 verbose unsafe-perm in lifecycle true
9 info foundationpress@2.4.0 Failed to exec watch script
10 error foundationpress@2.4.0 watch: `gulp`
10 error Exit status 8
11 error Failed at the foundationpress@2.4.0 watch script.
11 error This is most likely a problem with the foundationpress package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     gulp
11 error You can get their info via:
11 error     npm owner ls foundationpress
11 error There is likely additional logging output above.
12 error System Windows_NT 6.2.9200
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
14 error cwd C:\Users\Will\Documents\Web Design\Wordpress\FoundationPress\Two
15 error node -v v0.10.22
16 error npm -v 1.3.14
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

How can I overcome this please?

**Comment by wakatoyee** [comment]
Hello do you have a clean installation using `npm install`? I just tried an experimental installation. I installed [nodejs 4.x.x](https://nodejs.org/dist/v4.3.1/node-v4.3.1-x86.msi) (I still choose 32-bit version of nodejs) on x64-bit platform windows 7.. My `node -v` is 4.3.1 and `npm -v` is 2.14.12. 

I ran into problems as well. First I didn't have [git](https://git-for-windows.github.io/) and I needed to make sure the PATH is working and I verified it using `git` on cmd prompt and to verify it must show git help. Next, I need to run `npm install -g bower` and `npm install -g gulp`. Now `npm install` and `npm run watch` works fine. I hope this helps.

**Comment by colin-marshall** [comment]
@fatbuddha-design your version of Node is too old for FoundationPress 2.x.

https://github.com/olefredrik/FoundationPress#requirements
> This project requires **Node.js v4.x.x** to be installed on your machine. Please be aware that you may encounter problems with the installation if you are using v5.1.0 with all the latest features.

**Comment by wishe** [comment]
I found that i needed to use an older version of Node on FoundationPress(Foundation 5) projects and the newer 4.x.x on the new FoundationPress(Foundation 6). I got around this issue by installing nvm(https://github.com/creationix/nvm). With nvm you can jump from version to version when you need to. Hope this helps!

**Comment by olefredrik** [comment]
What @colin-marshall and @wishe said.
