### ISSUE TITLE
Block Grid Not Working

### ISSUE THREAD

**Issue by adibbz** [olefredrik/FoundationPress#738]
I've added a menu to my page template like so:

<?php wp_nav_menu( array('menu' => 'Services', 'menu_class' => 'small-block-grid-3') ); ?>

The block grid class does not seem to do anything however. they all just sit in an unordered list. This happened even when I hardcoded a list with the block grid class. 

I tried digging around but it seems like the block grid is being imported so I don't think it is that. Any ideas?

**Comment by colin-marshall** [comment]
Are you on FoundationPress 2? If so, you are using Foundation 6 which changed the block grid to use different classes.

http://foundation.zurb.com/sites/docs/grid.html#block-grids

**Comment by adibbz** [comment]
Ahh, that links was very helpful. Thank you. 

I am on Foundation 6 so that's why  'small-block-grid-3' wasn't working. 

thanks!
