### ISSUE TITLE
Flexbox grid?

### ISSUE THREAD

**Issue by roborracle** [olefredrik/FoundationPress#741]
Is there something I can do do enable the flexbox grid? I desperately need a vertical centering solution and my understanding is that Foundation 6 has some new classes that utilize the flexbox grid and enable vertical centering. I've looked in the settings file for the flexbox rule, but it's not there, unless I'm just missing it.

Can we make use of this in FoundationPress?

http://foundation.zurb.com/sites/docs/flexbox.html#enabling-flexbox-mode

**Comment by olefredrik** [comment]
Hi @roborracle , 

We have an open [pull request](https://github.com/olefredrik/FoundationPress/pull/740/files) including the update to Foundation 6.2. This update has [several improvements](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2#flexbox-mode) to the flexbox mode.

We just need to fix a few issues before merging the update into the master branch. Hang on :) If you want to upgrade yourself, you can follow this [upgrade guide](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2).

Cheers,
Ole Fredrik

**Comment by olefredrik** [comment]
FoundationPress [is now updated](https://github.com/olefredrik/FoundationPress/pull/742) with the latest features from Foundation 6.2. 

[Here is a guide](http://foundation.zurb.com/sites/docs/flexbox.html#enabling-flexbox-mode) on how to enable flexbox mode.

**Comment by roborracle** [comment]
HI @olefredrik - thanks for this. I'm not sure I'm following you on the upgrade - what do I need to do to upgrade here? Forgive my ignorance - long day :)

**Comment by olefredrik** [comment]
Depends on your workflow, really. If you're starting a new project, it's as easy as cloning the repository followed by ```npm install```. If you're familiar with git and working on an existing project and, you could simply run ```git pull origin master``` to pull the latest changes, followed by ```npm install```.

**Comment by roborracle** [comment]
Thanks again for the response. I'm familiar with git, but not a master by any measure. Originally, we had a conflict with the git repo in FoundationPress and the repo we're using for our overall development project that live on Bitbucket, so it looks like I removed git repo in FoundationPress without consideration of being able to pull upgrades/updates later. Obviously at this point, not my greatest moment. 

There is no git repo in our instance FoundationPress as it stands. We've got a LOT of stuff done in FP and we definitely do not want to lose any of it, but we also really need this flexbox piece to save our sanity with these vertical alignment issues. Can you recommend a solution to be able to pull and/or merge with our current project?

**Comment by olefredrik** [comment]
You could create a new upgrade-branch ```git checkout -b upgrade``` and manually add the file changes required to update to Foundation 6.2. https://github.com/olefredrik/FoundationPress/pull/742/files

Alternatively you could [add the FoundationPress repo as a remote](https://help.github.com/articles/adding-a-remote/), and pull in the latest changes from the master branch. If you've made a ton of changes in your project, you will most likely get a few merge conflicts that you will have to deal with. But as long as you're creating a new branch before doing this, there is no risk, as I see it.
