### ISSUE TITLE
Npm installation stop working...

### ISSUE THREAD

**Issue by mrxmath** [olefredrik/FoundationPress#744]
Hi,
I tried to reset my theme, by deleting the folder and cloning again, but now when i tried to install, the npm package give me a lot of erros... and i can't install anymore

Paespedros-iMac:themes mateusoliveira$ ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/zurb/motion-ui.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.129]: errno=Connection refused

npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
 
> bufferutil@1.2.1 install /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
 
> utf-8-validate@1.2.1 install /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> fsevents@1.0.8 install /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
 
> phantomjs@1.9.19 install /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/32/m1ggqzvs1hx0t5rbd1h_xwrc0000gv/T/phantomjs/phantomjs-1.9.8-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/32/m1ggqzvs1hx0t5rbd1h_xwrc0000gv/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1456957820152/phantomjs-1.9.8-macosx -> /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs
 
> spawn-sync@1.0.15 postinstall /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

 
> node-sass@3.4.2 install /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node
 
> node-sass@3.4.2 postinstall /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
 
> bufferutil@1.2.1 install /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> utf-8-validate@1.2.1 install /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/
> foundationpress@2.5.0 postinstall /Users/mateusoliveira/sites/maquina-solo-2016/wp-content/themes/FoundationPress
> bower install && gulp build

bower cached        git://github.com/zurb/motion-ui.git#1.2.2
bower validate      1.2.2 against git://github.com/zurb/motion-ui.git#~1.2.0
bower cached        git://github.com/zurb/foundation-sites.git#6.2.0
bower validate      6.2.0 against git://github.com/zurb/foundation-sites.git#~6.2.0
bower cached        git://github.com/FortAwesome/Font-Awesome.git#4.5.0
bower validate      4.5.0 against git://github.com/FortAwesome/Font-Awesome.git#~4.5.0
bower cached        git://github.com/jquery/jquery-dist.git#2.2.1
bower validate      2.2.1 against git://github.com/jquery/jquery-dist.git#~2.2.0
bower cached        git://github.com/ten1seven/what-input.git#1.1.4
bower validate      1.1.4 against git://github.com/ten1seven/what-input.git#~1.1.2
bower install       motion-ui#1.2.2
bower install       fontawesome#4.5.0
bower install       jquery#2.2.1
bower install       foundation-sites#6.2.0
bower install       what-input#1.1.4

**Comment by colin-marshall** [comment]
Try running this command: `git config --global url."https://".insteadOf git://`
