### ISSUE TITLE
gulp file errors, FP 2.5, npm run watch, Windows 7 x64

### ISSUE THREAD

**Issue by mhair** [olefredrik/FoundationPress#748]
I don't know if the errors I'm seeing after upgrading are due to the gulpfile, or due to more insane headaches with using node/npm on windows with node-gyp depencencies. On "npm run watch". Starting at clean:javascript

ReferenceError: del is not defined.

Further down, I get....
Error in plugin run-sequence

Same for npm run build.

So I have TONs of headaches getting Windoze Visual C++ compiler set up properly, much of encountered when I was using the Zurb Foundation 6 template (panini stack). It never stopped complaining of errors, but was able to "watch" in that environment. Was also able to get Foundationpress 2.3 watch running. But now that I've upgraded, I find the gulp errors above. 

Thinking it was just more of the same problem as before that was not completely solved, I started down that path again with node-gyp [documentation ](https://www.npmjs.com/package/node-gyp) talking about the ultimate alchemy for success on Windows. As I had previously installed Visual Studio 2015 Community instead of 2013 per a different article, but now seeing that only 2013 is recommended, I went down that path. Another day wasted, and I'm still no closer to having a workable node stack. It DOES work sometimes, just not with certain dependencies, generally having to do with the C++ compiler. It's enough to make a dev want to jump ship to Macintosh. If you're interested in the mother of all troubleshooting threads, look [here](https://github.com/nodejs/node-gyp/issues/629). Even this did not solve my problem, and tons of articles later, I'm in the same spot.

So hoping that it is not my configuration, but rather a true gulpfile error, I'm appealing here for any clues as to what is going on.

Thanks.

**Comment by olefredrik** [comment]
Whoa. I did not even realize developers on Windows was bound to have Visual Studio installed. That makes no sense to me. As far as I know, there is no error in the gulp file. It works as expected on Mac and Linux. It also works well on other Windows installations. So there is probably something wrong with the configuration on your development environment. I'm sorry I can not be of help here.
