### ISSUE TITLE
Git Ignores Files Inside FoundationPress Theme Folder.

### ISSUE THREAD

**Issue by drivenfaroff** [olefredrik/FoundationPress#750]
**How can this bug be reproduced?**

1. Followed Quickstart install
2. Went to theme folder and noticed almost all of the files were being ignored.

**What did you expect to happen?**
To be able to use git to upload the theme folder.

**What happened instead?**
Files are being ignored. Git did put the theme folder up but nothing else inside of it. I removed the .gitignore files and they are still being ignored. Also tried installing in several different places to see if it was something else but end result was the same. Issue is not the same with other themes (see screenshot, red means the file is being ignored).

Any thoughts let me know.

<img width="1364" alt="screen shot 2016-03-04 at 8 54 08 am" src="https://cloud.githubusercontent.com/assets/1910216/13530401/cf059c0c-e1e6-11e5-9f5b-21336888d6db.png">

**Comment by olefredrik** [comment]
Whoa. It makes no sense that the files in red should be ignored by git. The only thing I can think of is that your theme is located under a folder that might be under source control with a separate .gitignore file? 

Can you navigate to the FoundationPress folder and type:
```git status```

That should return the following message:
```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

Try making a change in README.md and save the file
```git status```  should now return the following message:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md
```

Let's try that first. If your working directory is clean with nothing to commit after editing the README.md file, let's try to 

```
rm -rf .git
rm -rf .gitignore
git init
```

**Comment by olefredrik** [comment]
I have files marked with red in my terminal as well. That does not mean they're ignored by git. The only thing that gets ignored by git is the files and folders in ```.gitignore```.

![screen shot 2016-03-08 at 14 09 49](https://cloud.githubusercontent.com/assets/1080017/13602547/80c43518-e537-11e5-9cfa-ca9fc279b850.png)

**Comment by drivenfaroff** [comment]
I did get the files added with the second part that you said.

They were still red after that just like yours. I'll ignore that part going forward.

Thanks!
