### ISSUE TITLE
FoundationPress Grid

### ISSUE THREAD

**Issue by wjdennen** [olefredrik/FoundationPress#751]
Please excuse the basic question: 

With FoundationPress 2.0.0 and later, Foundation 6+ is used. 

It seems as though the Grid is no longer used for layout of pages in these recent versions of FoundationPress? I'd expect to see grid classes on this, but instead I see more custom S/CSS being used for layout.

Is the Grid no longer used for basic layout in FoundationPress? or, more likely, what am I missing?

**Comment by olefredrik** [comment]
The grid is certainly in use. But instead of adding the layout classes in markup, we use a more semantic approach. You can see details about building layout semantic in [Foundation docs](http://foundation.zurb.com/sites/docs/grid.html#building-semantically).

**Comment by wjdennen** [comment]
Thanks @olefredrik. I figured that out after I submitted this issue -- sorry about that.

**Comment by olefredrik** [comment]
Hey, no problem :)
