### ISSUE TITLE
Homepage replicate across all pages

### ISSUE THREAD

**Issue by fingomarketing** [olefredrik/FoundationPress#755]
On our site all pages are the same copying the homepage but with different URL’s – the URL rewrite’s don’t seem to work.
 
We have disabled all plugins, updated Wordpress and eliminated hosting issues and .htaccess. If you swap to other themes it is fine. We have also simplified our site by removing the code in the header, footer and templates but the homepage still displays on all pages.
 
We have found various other articles referencing using wp_reset_query but these are already in place.
 
On the permalinks setting it works with plain ?p=123 so have set it to that but none of the other options work.

**Comment by olefredrik** [comment]
Are all your pages set to use the front template? 

![page-attributes](https://cloud.githubusercontent.com/assets/1080017/13570067/4e49c07e-e46c-11e5-847e-65c1d5a8c4ae.png)

If yes, try using a different template (e.g the default template).

**Comment by fingomarketing** [comment]
They are all using different templates

**Comment by olefredrik** [comment]
Can you try downloading a fresh install and see if your problem persists?

**Comment by fingomarketing** [comment]
The error was in functions.php
commenting out the line add_filter( 'rewrite_rules_array', 'disable_embeds_rewrites' ); fixed it
many hours wasted on this

**Comment by colin-marshall** [comment]
@fingomarketing I'm sorry you wasted many hours but that line of code isn't even in FoundationPress.

**Comment by olefredrik** [comment]
@fingomarketing : I also wasted time on an error that was not caused by FoundationPress. Which is just fine. No problem. But please do not pretend it's my fault that you have spent hours debugging your own code.

**Comment by fingomarketing** [comment]
Thanks olefredrik wasn't saying it was your fault I was posting my solution in case others had a similar issue. Thanks for your help and the quick response.
