### ISSUE TITLE
Fresh install changes to _settings.scss not cascading consistently

### ISSUE THREAD

**Issue by timothabgreen** [olefredrik/FoundationPress#760]
**How can this bug be reproduced?**

1. Fresh SASS install - Clone the repository and install with npm
2. Change $secondary-color in _settings.scss
![screen shot 2016-03-08 at 16 57 42](https://cloud.githubusercontent.com/assets/17704022/13608978/ee0bd240-e54e-11e5-8f1b-40e8761eb653.png)
3. Add a button to home page and set class to secondary
`<a href="#" class="button secondary">A Button</a>`

**What did you expect to happen?**
Button background color change to new color set above

**What happened instead?**
Default #777 color remains. Check Console 
![screen shot 2016-03-08 at 17 00 08](https://cloud.githubusercontent.com/assets/17704022/13609035/4210f5e6-e54f-11e5-95e9-4204fb5851e3.png)

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/761
