### ISSUE TITLE
bower components _global overriding scss/global/_setting

### ISSUE THREAD

**Issue by cucocreative** [olefredrik/FoundationPress#762]
I have just move from using 1.6 to 2.5.1 and use CodeKit to compile the the css on a Mac running 10.10.5.

I don't know what I am doing wrong but compared to 1.6, the bower components seems to override the the my custom settings. For example if I change the colour for $secondary-color in the file assets/scss/global/settings once it is compiled the colour is equal to what was defined in one of the files within assets/components/foundation-files/scss/...

**Comment by dantahoua** [comment]
Interesting, I just discovered the same problem but I do not use codekit, just regular npm...
In assets/scss/global/_setting.scss I changed $primary-color: red; BUT the color color shown in the website still is the default foundation one...

**Comment by dantahoua** [comment]
Update: If I change the order in foundation.scss, putting the '@import "global/settings";' after the '@import '../components/foundation-sites/scss/foundation';'
it works, wich in a way make sense I think. What I don't understand is why it has been working before!!! I made two website with new FoundationPress  and it was working!

**Comment by olefredrik** [comment]
Hi guys. 

This issue was fixed earlier today. Here is the pull request https://github.com/olefredrik/FoundationPress/pull/761 . 

You can either pull the latest master branch or simply check out the updated [_settings.scss](https://github.com/olefredrik/FoundationPress/pull/761/files) where the new foundation-palette mixin has been introduced.

Cheers,
Ole Fredrik

**Comment by dantahoua** [comment]
And you know what Ole, I saw it in my mail earlier!!! Holy s@$t !! Ah ah, I must pay more attention to the latest pull! :)

**Comment by olefredrik** [comment]
The reason it was working before, is that the Foundation team introduced the new foundation palette in the 6.2 update. You can find more details [here](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2#color-palette) if interested.
