### ISSUE TITLE
Sass Mixins with FoundationPress

### ISSUE THREAD

**Issue by photonomad** [olefredrik/FoundationPress#765]
First, I apologize if this is the wrong place to ask this question.

I'm really stumped and just need to know how to add/include/import/use bourbon (or any mixin library) with FoundationPress. Should I install the library (bourbon, compass, etc.) via npm and then edit the gulpfile.js? If so, how? If not, where can I find some clear instructions on how to add mixins so that they can be used and won't produce sass errors during npm run watch?

**Comment by EricRihlmann** [comment]
## Step 1
Add Bourbon dependecny to `bower.json`
```javascript
{
  "name": "foundationpress",
  "main": [
    "assets/stylesheets/foundation.css",
    "assets/javascript/foundation.js"
  ],
  "ignore": [],
  "dependencies": {
    "foundation-sites": "~6.2.0",
    "motion-ui" : "~1.2.0",
    "fontawesome": "~4.5.0",
    "bourbon": "~4.2.6"
  }
}

```

## Step 2
Add Bourbon Sass partial to `assets/scss/foundation.scss` after "My custom styles" comment at line 78
```scss
// Bourbon - (http://bourbon.io/) 
@import "../components/bourbon/app/assets/stylesheets/bourbon";
```

## Step 3
Instruct npm to install Bourbon via Bower dependency from step 1.
```bash
$ npm install
```

## Done!

**Comment by photonomad** [comment]
Eric, thank you SO MUCH!!

I had a little problem with Step 3 because I didn't realize that I needed to run: "npm install bourbon" inside the assets/components/ directory.  (I had been running it in the main FoundationPress directory, which put bourbon in the node_modules folder).  Once I fixed my mistake there, bourbon is working perfectly!

I really appreciate the time you took to spell it out for me! :)

**Comment by EricRihlmann** [comment]
No problem! 

What version of FoundationPress are you running? You shouldn't have to move any files.

**Comment by photonomad** [comment]
Oh my. Thanks for following up. I'm still new to using npm, etc.  Even though I _thought_ I was following your instructions, in my haste, I was actually completely ignoring what you said. Ack! 

I _thought _ I had to install bourbon with `npm install bourbon` at some point.   Now, I'm finally seeing the light! npm installs the dependencies listed in the bower.json file (which is what you say clearly in Step 3). Finally, I think I'm starting to get how all this works. Thanks again for you help!
