### ISSUE TITLE
WordPress Site Icon

### ISSUE THREAD

**Issue by drivenfaroff** [olefredrik/FoundationPress#766]
Feature request to add `wp_site_icon` to `header.php`

```
<?php 
    if (has_site_icon()) {
        wp_site_icon();
    } else { ?>
    <link rel="icon" href="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/icons/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="144x144" href="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/icons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/icons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/icons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" href="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/icons/apple-touch-icon.png">
<?php } ?>
```

Not sure if there is a reason this hasn't been added yet but would be a nice include with fallback if an icon isn't added through the customizer.

**Comment by Aetles** [comment]
Is this needed anymore? With the removal of all site icons in https://github.com/olefredrik/FoundationPress/commit/ca760c3eb220e90b7169eeae75e8c263c1aa3e79 it is supposed to be handled by WordPress core. Do you really need `wp_site_icon()` then?

**Comment by drivenfaroff** [comment]
If wp_site_icon() fires in wp_head() like it looks like it does here: https://github.com/WordPress/WordPress/blob/9fb5c540bb7888faec05670bd70a93e0593dcfb1/wp-includes/default-filters.php#L239 then I would think it wouldn't be needed.

**Comment by Aetles** [comment]
Yeah, and looking at the default themes header.php (like [Twenty Fifteen](https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfifteen/header.php) and [Twenty Fourteen](https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfourteen/header.php)) I only see `wp_head()` calls, so I think it's safe to say we don't need `wp_site_icon()`.
