### ISSUE TITLE
Significance of this return after running "watch"?

### ISSUE THREAD

**Issue by squidzink** [olefredrik/FoundationPress#775]
Copy the following snippet into your website, just before the closing </body> tag
`<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.11.1.js'><\/script>".replace("HOST", location.hostname));
//]]></script>`

I'm not sure what this means or if it's necessary or how it affects my MAMP set up which runs off port localhost:8888

**Comment by colin-marshall** [comment]
This shows up because you have not set the URL to your local server in `gulpfile.js`. In your case, you would do this: 
```js
// Enter URL of your local server here
// Example: 'http://localwebsite.dev'
var URL = 'http://localhost:8888';
```

This will get BrowserSync working with your local server. It's not mandatory though.

**Comment by squidzink** [comment]
Thanks @colin-marshall. I did make that setting but as the actual domain I have entered in Mamp for that particular site rather than localhost: It is working properly now. Thank you for the clarification.
