### ISSUE TITLE
Missing modules when running npm run build or npm install

### ISSUE THREAD

**Issue by tylerfoulkes** [olefredrik/FoundationPress#780]
Hi,
I am working on a foundation press project and I am trying to get it all setup and working. I have cloned the preexisting repository howoever every time I run pretty much any npm command I get the following output:

> foundationpress@2.3.0 build /path/to/foundation/project
> gulp build

module.js:327
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/path/to/foundation/project/node_modules/gulp-load-plugins/node_modules/findup-sync/lib/findup-sync.js:15:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.3.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.3.0 build script 'gulp build'.
npm ERR! This is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/foundation/project/npm-debug.log

I have uninstalled nodeJS completely and reinstalled it again. It seems that I must have large dependency missing because every time I try to install the module that it says its missing it just complains about another module missing. Im a bit new to these package managers but aren't supposed to take care of all the dependencies?

- Tyler

**Comment by colin-marshall** [comment]
Do you get errors when you run `npm install`?

**Comment by tylerfoulkes** [comment]
@colin-marshall
Ya, npm install throws this error.

**Comment by colin-marshall** [comment]
The error in the original post is from running `npm run build`. I want to see the error from `npm install`

Please do the following:
`rm -rf node_modules`
`npm install`
provide the contents of that error message

Thanks.

**Comment by colin-marshall** [comment]
@tylerfoulkes did you figure it out?

**Comment by tylerfoulkes** [comment]
Yes that worked perfect, thank you! Sorry I didn't respond earlier.

**Comment by colin-marshall** [comment]
No worries! Just making sure you got it sorted out. Feel free to close the issue if it's resolved. Thanks!

**Comment by clementcrownrise** [comment]
@colin-marshall , I am having the same error, I am using a windows 8 system, but it is as if the command  rm -rf node_modules is not recorgnized on windows.

**Comment by venkatavinash** [comment]
@clementcrownrise , rm -rf is linux command to remove the directory i.e., node_modules in this case. You can try deleting node_modules and do "npm install"  again. Hope it works!

**Comment by oranb83** [comment]
if it doesn't work it could be a linking problem like I had. Try to uninstall npm and install it again, it should fix the problem.

**Comment by Desdichado** [comment]
In windows you could probably use rmdir /s node_modules  instead of rm -rf node_modules.

**Comment by imsantosh** [comment]
i am facing same problem . i also uninstall and then install it ,but it is not working 
getting below error:

module.js:428
    throw err;
    ^

**Comment by chegior** [comment]
Hi, I'm getting the same error on WINDOWS 10,

C:\>node C:\Users\chegi\Documents\00 Soft Project\Test1.js
module.js:471
    throw err;
    ^
 I tried to run the **npm install**

and I got:

C:\>npm install
npm WARN enoent ENOENT: no such file or directory, open 'C:\package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path C:\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, mkdir 'C:\node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path C:\npm-debug.log.3072103967
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\npm-debug.log.3072103967'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\npm-debug.log.3072103967'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\npm-debug.log.3072103967' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>

Any suggestion how to fix this one, or If removing the modules may help, Thanks!!!

**Comment by Aravin** [comment]
I am also getting same error!

**Comment by yugensoft** [comment]
Firstly, npm on windows is just horrible. I know your pain.
Secondly, it's telling you what to do: `npm ERR! Please try running this command again as root/Administrator`
Open the cmd.exe with right click -> run as administrator

**Comment by geekycatholic** [comment]
having the same problem here.

**Comment by artigarg** [comment]
at npm install i did not get any error but after running on command promt i am geeting an error.

C:\Users\Lenovo\Desktop\sample website with node.js>node pcnmserver.js
module.js:471
    throw err;
    ^
Error: Cannot find module 'C:\Users\Lenovo\Desktop\sample website with node.js\pcnmserver.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by Katharsas** [comment]
Same error after a fresh install of node, npm and node-sass on Win 10:
```
[INFO] Running 'npm install --color=false' in C:\Users\---src\main\frontend
[ERROR] npm WARN prefer global node-gyp@3.6.2 sho`uld be installed with -g
[INFO] 
[INFO] > node-sass@4.5.3 install C:\Users\---\src\main\frontend\node_modules\node-sass
[INFO] > node scripts/install.js
[INFO] 
[ERROR] module.js:341
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'extend'
[ERROR]     at Function.Module._resolveFilename (module.js:339:15)
[ERROR]     at Function.Module._load (module.js:290:25)
[ERROR]     at Module.require (module.js:367:17)
[ERROR]     at require (internal/module.js:20:19)
[ERROR]     at Object.<anonymous> (C:\Users\---\src\main\frontend\node_modules\request\index.js:17:29)
[ERROR]     at Module._compile (module.js:413:34)
[ERROR]     at Object.Module._extensions..js (module.js:422:10)
[ERROR]     at Module.load (module.js:357:32)
[ERROR]     at Function.Module._load (module.js:314:12)
[ERROR]     at Module.require (module.js:367:17)
[ERROR] npm WARN frontend No description
[ERROR] npm WARN frontend No repository field.
[ERROR] npm WARN frontend No license field.
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-sass@4.5.3 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\---\AppData\Roaming\npm-cache\_logs\2017-08-08T11_02_46_858Z-debug.log
```

**Comment by zhangshichuan** [comment]
@colin-marshall  thx

**Comment by dnorton94** [comment]
@artigarg did you troubleshoot this issue 

I get a similar problem...

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>node app.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\app.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

C:\WINDOWS\system32>rimraf node_modules

C:\WINDOWS\system32>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

up to date in 0.284s

C:\WINDOWS\system32>node app.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\app.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

C:\WINDOWS\system32>

**Comment by colin-marshall** [comment]
@dnorton94 are you even using FoundationPress? You don't build FoundationPress with `node app.js` which makes me think you using a completely different Node app.

Regardless, I think you are probably in the wrong directory if you are trying to run a Node app from the `C:\WINDOWS\system32` directory. You need to be in the directory `app.js` is in.

**Comment by zhangshichuan** [comment]
@clementcrownrise Directly open the installed folder (node_modules). Right-click to remove it

**Comment by FlatspinZA** [comment]
BTW, chaps, for those of you who don't use Linux/Mac, just so you know - Windows has a huge problem with the deep file system created in node_modules & will very often refuse to remove the entire directory, even from PowerShell using Administrative privileges. 

One solution is "Unlocker", but then people who aren't paying attention install other unnecessary applications on their PC, and the other irritation is that it often requires a system reboot to perform the operation.

In Windows 10, fortunately, we can install 'Windows Subsystem for Linux' via 'Control Panel >> Programs & Features >> Turn Windows Features On or Off'. 

There is a tutorial on installation here: https://msdn.microsoft.com/en-us/commandline/wsl/install-win10, and afterwards users can then perform native Linux commands on their Windows folders using Bash from the Command Prompt, eliminating the need for pesky workarounds to delete files Windows battles with.

**Comment by Jay991** [comment]
Hey guys, I'm on mac OS High Seirra and I'm trying to install solidity but i'm getting the below response. I tried runnig the command as sudo - same response. I also tried running    ` rm -rf node_modules `     `  npm install`   Also did not work. 

Here is the response I have been getting: 

     ~ $sudo npm install -g solc
     Password:
     module.js:538
         throw err;
         ^

     Error: Cannot find module '../lib/utils/unsupported.js'
         at Function.Module._resolveFilename (module.js:536:15)
         at Function.Module._load (module.js:466:25)
         at Module.require (module.js:579:17)
         at require (internal/module.js:11:18)
         at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
         at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
         at Module._compile (module.js:635:30)
         at Object.Module._extensions..js (module.js:646:10)
         at Module.load (module.js:554:32)
         at tryModuleLoad (module.js:497:12)
```

**Comment by colin-marshall** [comment]
@Jay991 are you using FoundationPress?

**Comment by Jay991** [comment]
I just moved to a new environment all worked fine - Thanks ! :)

-- 
Jihad Rizk

On December 6, 2017 at 8:53:32 PM, Colin Marshall (notifications@github.com)
wrote:

@Jay991 <https://github.com/jay991> are you using FoundationPress?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/olefredrik/FoundationPress/issues/780#issuecomment-349738264>,
or mute the thread

**Comment by ramjanbd** [comment]
i just run this code
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest

**Comment by imsagarj** [comment]
module.js:538
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\codebase\calendercode1.1.0\server_side\controller\api\auth\auth.js:5:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\codebase\calendercode1.1.0\route.js:7:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

plz give the solution for this ... I reinstall all npm package still this problem happens

**Comment by udaysaikumar1919** [comment]
I  getting this error, I didn't know how to figure it out
module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/udaysaikumar/connection'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by khelmrab** [comment]
i run build kibana 
i update npm version 3.x  to  4.6.1 working for me 
the latest version 5.x don't work

**Comment by colin-marshall** [comment]
@khelmrab @udaysaikumar1919 please see:
https://github.com/olefredrik/FoundationPress/issues/780#issuecomment-353163676

**Comment by avsingh999** [comment]
I think  should install only LTS version of node

**Comment by anookeen** [comment]
![image](https://user-images.githubusercontent.com/20276300/35485191-c798390c-0453-11e8-9c50-62a33633378f.png)
I am getting this error. Help please.

**Comment by GauravSinghPawar** [comment]
I am getting this error while Altering table in database.....

C:\Users\Gaurav\Node.js>node demo_alterTable.js
module.js:540
throw err;
^

Error: Cannot find module 'C:\Users\Gaurav\Node.js\demo_alterTable.js'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Function.Module.runMain (module.js:684:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:608:3

---------------------------------------------Source Code------------------------
////filename- demo_alterTable.js
var mysql = require('mysql');

var con = mysql.createConnection({
host: "localhost",
user: "root",
password: "",
database: "nodejs"
});

con.connect(function(err) {
if (err) throw err;
console.log("Connected!");
var sql = "ALTER TABLE customers ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY";
con.query(sql, function (err, result) {
if (err) throw err;
console.log("Table altered");
});
});

**Comment by colin-marshall** [comment]
This issue keeps getting responses from people that aren't using FoundationPress, so I'm going to lock conversation since we can't help you with issues that aren't related FoundationPress.

There is one solution in this thread that seems to have helped a lot of people (delete `node_modules` and reinstall), so I'll leave it here to make sure it is seen:

```
rm -rf node_modules
npm install
```

If you are using FoundationPress and still have this issue, feel free to open a new one. For the rest of you, https://github.com/npm/npm is a better place to get help on the issue if the above solution does not work.
