### ISSUE TITLE
_settings.scss and custom CSS

### ISSUE THREAD

**Issue by wjdennen** [olefredrik/FoundationPress#781]
Could you clarify which files we're allow/supposed to edit?

Is it ok to edit _settings.scss, or should we make a copy and include it?

What about custom CSS? 

I've included another SCSS file, but I am finding I have to use !important to over-ride some default styles, and I'd like to avoid that.

thanks.

**Comment by colin-marshall** [comment]
It's ok to edit `assets/scss/global/_settings.scss`.

Include your other SCSS file at the bottom of `assets/scss/foundation.scss` and you should not have to use `!important`.

**Comment by colin-marshall** [comment]
@wjdennen I'm going to assume this is resolved. Feel free to reopen if you still are having issues. Thanks!
