### ISSUE TITLE
Strange character ( ` ) appearing in site text - this theme only

### ISSUE THREAD

**Issue by dberz** [olefredrik/FoundationPress#782]
I'm seeing apostrophes replace spaces all across my site text content -- and I think it's FoundationPress related. 

These characters do not appear when I enabled the Wordpress "twenty sixteen" theme.  My host (wpenegine) suggested I contact my theme's developer.  I suppose that is "us" here... 

Thank you all in advance for your thoughts.

--

See attached two screenshots of the same content, one in my custom FoundationPress theme, the other in Twenty Sixteen.

FoundationPress
![image](https://cloud.githubusercontent.com/assets/5471790/14082672/517f443e-f4df-11e5-8858-d2d3ffefd1d5.png)

Twenty Sixteen
![image](https://cloud.githubusercontent.com/assets/5471790/14082694/6fd09f78-f4df-11e5-8760-a02a929f76b5.png)

--

I'll also copy in the text as pulled from different views - in case the characters appear in the core DB or Admin.

site HTML (https://parsleyhealth.com/about/
``
This kind of care is normally $10,000 and up at a high- end concierge doctor. We make it affordable with our monthly membership.

Your team is trained in using proven natural options like food, lifestyle changes and supplements, alongside the most cutting-edge science and in-depth testing, from your bacteria to your hormones to your genes, so that you can avoid unnecessary medications.
``

WP Admin
``
This kind of care is normally $10,000 and up at a high- end concierge doctor. We make it affordable with our monthly membership.

Your team is trained in using proven natural options like food, lifestyle changes and supplements, alongside the most cutting-edge science and in-depth testing, from your bacteria to your hormones to your genes, so that you can avoid unnecessary medications.
``

PHPMyAdmin
``
This kind of care is normally $10,000 and up at a high- end concierge doctor. We make it affordable with our monthly membership.

Your team is trained in using proven natural options like food, lifestyle changes and supplements, alongside the most cutting-edge science and in-depth testing, from your bacteria to your hormones to your genes, so that you can avoid unnecessary medications.
<p style="text-align: center;">[efsbutton style="" size="" color_class="" align="left" type="link" target="false" title="Learn More About Membership" link="https://parsleyhealth.com/medicine/"]</p>
``

**Comment by olefredrik** [comment]
Hi @dberz, site in Chrome and inspected the text. It seems like there is a ```&nbsp;``` added after each comma.

<img width="1090" alt="nbsp" src="https://cloud.githubusercontent.com/assets/1080017/14083298/2715606c-f515-11e5-80d7-52d964c86957.png">

This is kind of strange, as it does not occur on a fresh FoundationPress install. Anyway, a ```nbsp;``` should be rendered as a blank space, not an apostrophe.

Are you using any plugins such as a third-party WYWIWYG-editor? If you inspect a paragraph on your site after switching to a different theme, do you still get ```nbsp;```'s after commas?

**Comment by dberz** [comment]
Thanks @olefredrik.  

Yes, the &nbsp; is present even when I've enabled the Twenty Sixteen theme:

``
Your team is trained in using proven natural options like food, lifestyle changes&nbsp;and supplements, alongside the most cutting-edge science and in-depth testing,&nbsp;from your bacteria to your hormones to your genes, so that you can avoid&nbsp;unnecessary medications.
``

--

I believe I'm using the standard WYSIWYG editor.  

Regarding plugins, I'm using the '[Easy Foundation Shortcode](https://wordpress.org/plugins/easy-foundation-shortcodes/)' plugin and a few others.  

Attaching the full list here for reference:
![image](https://cloud.githubusercontent.com/assets/5471790/14083930/3c91b3f2-f4e6-11e5-90e9-14b766218397.png)

--

I need to find a live example, but I believe this issue also appears within non-Wordpress straight theme HTML text.  So I'm not sure if it's an issue with the wordpress content / WYSIWYG :(

**Comment by FlatspinZA** [comment]
Well, there's your answer, especially if the error occurs when using another theme - it's not FoundationPress related, at all. Try your addons

**Comment by FragaGeddon** [comment]
I copied and pasted your text into a page and it was both fine in the visual editor and the text editor.
If you have copied from let's say a word document, or some other type, right click to paste and select 'Paste as plain text' or CTRL+SHIFT+V.

**Comment by dberz** [comment]
@FlatspinZA this error ONLY appears in Foundation Press, NOT other themes.

@FragaGeddon the text entry is done directly in the WP visual editor, and is not copied and pasted.  Very confusing why some spaces are rendered correctly and others as ``&nbsp;``.  Other users have also entered text that appears this way, so I don't think it's a local machine (keyboard?) related issue.

All very confusing.  And surprising that the theme renders the ``&nbsp;`` as a `` ` `` in any case.

**Comment by colin-marshall** [comment]
@dberz did you try to disable all plugins and see if the problem remains?

Also, possibly unrelated but worth noting, you mentioned that you are using the Easy Foundation Shortcode plugin. If you are using FoundationPress 2.0 or greater then you have Foundation 6. Easy Foundation Shortcodes is for Foundation 4/5. Some components may work but the syntax on a lot of them changed in v6 so a lot of the shortcodes will not work. Make sure that plugin is also not including Foundation's js.

**Comment by dberz** [comment]
@colin-marshall thanks for the suggestion.  This issue happens even with all plugins disabled.  And I'm aware of the version issues / limitations with the Easy Foundation Shortcodes plugin and definitely excited for the new project you're working on.  These short codes are pretty essential to getting full value out of FoundationPress as it allows non-technical users to create basic, super valuable layouts like columns (works from 5>6), accordions (does not work in 6), etc.

Re. my situation, I still see two issues here:

1. Creation of ``&nbsp;`` characters in the site content.  Almost certainly NOT a foundationpress issue, but highly bizarre.
2. Display of ``&nbsp;`` characters as `` ` `` in the front end.  Likely a FoundationPress issue.

**Comment by colin-marshall** [comment]
@dberz do you still get the problem if you?:
- Fresh clone of FoundationPress into a new directory in the themes folder
- Run `npm install`
- Switch to the fresh FoundationPress theme you just created

**Comment by colin-marshall** [comment]
@dberz I believe the problem is your font. I changed the font to Arial in the inspector in Chrome and the backticks went away.

**Comment by dberz** [comment]
@colin-marshall holy smokes!  I think you're right.  Thanks for spotting that!
