### ISSUE TITLE
Search by author of post?

### ISSUE THREAD

**Issue by tylerfoulkes** [olefredrik/FoundationPress#785]
I am wondering if I can add functionality to the search tool included in FoundationPress and make it so that it searches by both name of posts and name of authors of posts?

Any help would be greatly appreciated!

**Comment by Eccola** [comment]
@tylerfoulkes , native WordPress search functionality is quite primitive. 
You could try: https://wordpress.org/plugins/relevanssi/

**Comment by colin-marshall** [comment]
@tylerfoulkes I'm doing a little cleanup of open issues and am going to close this one. Feel free to reopen it if you still need help or would like to discuss it further. Thanks!
