### ISSUE TITLE
Paragraph Font Size in _settings.scss

### ISSUE THREAD

**Issue by damacs** [olefredrik/FoundationPress#786]
Probably a very stupid question, but how can I change the paragraph font size to 14px (default 16px)? Thanks.

**Comment by Eccola** [comment]
@damacs , see /assets/components/foundation-sites/scss/typography/_base.scss

**Comment by dberz** [comment]
@damacs I'm not sure I would recommend editing the SCSS within the components/foundation-sites directory.  

Is there a way to bump up the base paragraph size within /assets/scss/ directory?

/assets/scss/global/settings.scss has a $global-font-size property, but I find that is a coarse grain way of bumping up font sizes.  

My body text font face is small, so I'm also looking for an efficient way of bumping up all body text, but not other fonts.

**Comment by Eccola** [comment]
@dberz, I was just quickly pointing out the source of paragraph font-size. I wouldn't suggest editing this file either, but to read: http://foundation.zurb.com/sites/docs/global.html#font-sizing

Also, knowing the paragraph inherits the font-size, could we just use our custom styles to change it to whatever we wish, depending on the context?

**Comment by Eccola** [comment]
@damacs @dberz  Any further thoughts on this?  Did you resolve your font-size issues? Please share!

**Comment by zoomwebstudio** [comment]
O mvvx'"11)68)(6) bcddoob,

Le 30 août 2016 17:26, "Ole Fredrik Lie" <notifications@github.com> a
écrit :
