### ISSUE TITLE
NPM Error When Using "npm install"

### ISSUE THREAD

**Issue by Radizzt** [olefredrik/FoundationPress#790]
I'm trying to install FoundationPress with a fresh Wordpress and I'm getting an error everytime I try: `npm install`

This is the result:

> creative-mac-1s-mac-pro:FoundationPress MAC1$ npm install
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN engine gulp-autoprefixer@3.1.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine postcss@5.0.19: wanted: {"node":">=0.12"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine postcss@5.0.19: wanted: {"node":">=0.12"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
 
> spawn-sync@1.0.15 postinstall /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

> Installing native dependencies (this may take up to a minute)
> npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
> npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
> npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})

> phantomjs@1.9.20 install /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs
> node install.js

> PhantomJS not found on PATH
> Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
> Saving to /var/folders/_h/1bc6ypq56c57w_7sd_qrv57c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
> Receiving...
> \ [=========================---------------] 62%-
> Received 9187K total.
> Extracting zip contents
> Removing /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom
> Copying extracted folder /var/folders/_h/1bc6ypq56c57w_7sd_qrv57c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1460483741886/phantomjs-1.9.8-macosx -> /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom
> Writing location.js file
> Done. Phantomjs binary available at /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs

-
> fsevents@1.0.11 install /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

> [fsevents] Success: "/Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v11-darwin-x64/fse.node" is installed via remote

> node-sass@3.4.2 install /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

> Binary downloaded and installed at /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.4.2 postinstall /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

> ` /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
>  testing binary.
> Binary is fine; exiting.
> npm ERR! EEXIST, open '/Users/MAC1/.npm/b9740b98-C1-npm-lodash-3-10-1-package-tgz.lock'
> File exists: /Users/MAC1/.npm/b9740b98-C1-npm-lodash-3-10-1-package-tgz.lock
> Move it away, and try again. 
> 
> npm ERR! System Darwin 14.3.0
> npm ERR! command "node" "/usr/local/bin/npm" "install"
> npm ERR! cwd /Users/MAC1/Documents/Richard/Genesis/wp-content/themes/FoundationPress
> npm ERR! node -v v0.10.32
> npm ERR! npm -v 1.4.28
> npm ERR! path /Users/MAC1/.npm/b9740b98-C1-npm-lodash-3-10-1-package-tgz.lock
> npm ERR! code EEXIST
> npm ERR! errno 47
> npm ERR! not ok code 0

I check for the file and it doesn't exist. If i `npm install` again afterward there's not more error, but I'm missing folders - specificially the assets/components folder.

Thanks,
Richard

**Comment by jgierer12** [comment]
Have you tried doing what it suggested?
>`File exists: /Users/MAC1/.npm/b9740b98-C1-npm-lodash-3-10-1-package-tgz.lock`
>`Move it away, and try again.`

**Comment by Radizzt** [comment]
I tried, but the file doesn't exist. When I went in looking for it.

**Comment by jgierer12** [comment]
sorry, I commented before reading through your whole post

**Comment by Radizzt** [comment]
O haha, No problem.

**Comment by EricRihlmann** [comment]
It's because you are using node `0.10.32`. FoundationPress requires at least version `4.x.x`. I recommend using [nvm (node version manager)](https://github.com/creationix/nvm) to easily install/change what version of node you are using.

**Comment by Radizzt** [comment]
O Great, didn't realize my node was so out of date.

Thanks!
