### ISSUE TITLE
How to apply styles for different screen sizes

### ISSUE THREAD

**Issue by tylerfoulkes** [olefredrik/FoundationPress#791]
I have a custom .scss file and I am wondering how I can apply certain styles to elements on different screen sizes? For instance I have social icons on both my mobile and desktop views but I want the icons to be slightly smaller on the mobile view.

Any help would be greatly appreciated!

**Comment by Eccola** [comment]
@tylerfoulkes , this is purely Foundation related. See: http://foundation.zurb.com/sites/docs/media-queries.html
