### ISSUE TITLE
Npm run / build 'clean' javascript error - Gulp/Node/Windows 7 Dependencies

### ISSUE THREAD

**Issue by mhair** [olefredrik/FoundationPress#792]
**How can this bug be reproduced?**
1. Bower Update to get the latest 6.2.1
2. npm run watch or npm run build
3. 'clean' errored after / Error in plugin 'run-sequence' / An error occured in task 'Clean:javascript'.

**What did you expect to happen?**
Normal watch

I've had zero success on Windows 7 with each 'upgrade' of Foundation 6.x. I thought it was specific to Zurb Advanced Template, but still unable to get normal build/watch in Foundationpress 2.6.1. I've tried it both with node 4.4.2 and 5.1. I've tried it with Gulp 4.0 Alpha 2 and Gulp 3.9.1. I've deleted node-modules and dumped npm cache more times than I can say. I'm just having ZERO success with the Node/NPM/Gulp stack. The previous FoundationPress 1.7.2 using grunt? No problem.

So the obvious conclusion to me anyway, is that likely all of the problems I've been having with Foundation 6.X have to do with the Gulp/Node workflow on Windows 7, and possibly elsewhere. So unless someone here can help me to continue with 6.X by final squashing these problems, I'm afraid I'm doomed to remain on Foundation 5.5x and Foundationpress 1.72 which uses it. I believe that is the latest on 5.x. I've noted that @colin-marshall has been very helpful in not only developing the more advanced features, but in helping people to debug the build process. Perhaps you can help me too, but whatever happens, I hope it is mercifully short as I'm pressed up against the wall due to the amount of time this has already taken and I'm forced to move forth on the previous assets. That said, I'll do what I can in my spare time to try to continue to try to resolve this. I've sort of given up on the Foundation for sites repository in terms of reporting issues. I've not really received any serious efforts to help resolve my situation, and I must admit, it's a sticky one to address from afar since it could be so many things. Very disappointing over all as I was very excited about Foundation 6.X and wanting to pursue this project using it. But it just goes to show how much project dependencies matter. I guess one other option is to save my current version of the project in hopes of getting a prepros workflow, but so far I've had difficulties with it as well. Not sure if that is because it has the same dependencies on the backend or not. I'm pretty sure it uses Node on the backend which Windows has many issues with. But at least the grunt workflow seems to be working.

**What happened instead?**

npm-debug.log below
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\mhair.ICS\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.8.6
3 info using node@v5.10.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle foundationpress@2.6.1~prewatch: foundationpress@2.6.1
6 silly lifecycle foundationpress@2.6.1~prewatch: no script for prewatch, continuing
7 info lifecycle foundationpress@2.6.1~watch: foundationpress@2.6.1
8 verbose lifecycle foundationpress@2.6.1~watch: unsafe-perm in lifecycle true
9 verbose lifecycle foundationpress@2.6.1~watch: PATH: C:\Users\mhair.ICS\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpress\node_modules.bin;C:\Program Files\nodejs;%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Ruby21\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft\Web Platform Installer\;%appdata%\npm;ProgramFiles%\nodejs;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\MSbuild\12.0\Bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\xampplite\php\ext;C:\xampplite\php\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\SmartGit\git\bin;C:\Program Files (x86)\SmartGit\git\cmd;C:\xampplite\php;C:\xampplite\mysql\bin;c:\wp-cli;C:\Python27\python.exe;C:\Program Files (x86)\MSbuild\12.0\Bin;C:\xampplite\php\ext;C:\Users\mhair.ICS\AppData\Roaming\npm
10 verbose lifecycle foundationpress@2.6.1~watch: CWD: C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpress
11 silly lifecycle foundationpress@2.6.1~watch: Args: [ '/d /s /c', 'gulp' ]
12 silly lifecycle foundationpress@2.6.1~watch: Returned: code: 1  signal: null
13 info lifecycle foundationpress@2.6.1~watch: Failed to exec watch script
14 verbose stack Error: foundationpress@2.6.1 watch: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\mhair.ICS\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\mhair.ICS\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid foundationpress@2.6.1
16 verbose cwd C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpress
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\mhair.ICS\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "watch"
19 error node v5.10.1
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error foundationpress@2.6.1 watch: `gulp`
22 error Exit status 1
23 error Failed at the foundationpress@2.6.1 watch script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the foundationpress package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs foundationpress
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls foundationpress
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by snetts** [comment]
@mhair hey, did you manage to sort out the problem on Windows 7 coz I am using the latest version of everything, Foundation, FoundationPress and Node but nothing. I am getting the same error.

**Comment by cesasol** [comment]
This project only runs with node 4 to 5.9.

**Comment by olefredrik** [comment]
Not able to recreate issue when using the recommended version of [Node](https://nodejs.org/en/) (currently 6.11.1)
