### ISSUE TITLE
can't upload on external save via SFTP

### ISSUE THREAD

**Issue by andreaarcher** [olefredrik/FoundationPress#794]
Hello,
on my most recent install of FP my "monitor file: upload on external save" doesn't work in SFTP (sublime plugin). It used to be that when I saved a linked css file the main one would compile and upload automatically. Now on my new build that has stopped working. In my sublime directory I see foundation.css and foundation.css.map slide in and out which seems to suggest that they are being closed and reopened- this doesn't happen on any of my earlier installs. I think that the closing is stopping the monitoring so it's not being saved after compilation. Does anyone know if there is a setting somewhere to fix this?

Thanks in advance

Andi

**Comment by shawnnaquin** [comment]
same issue.

**Comment by andreaarcher** [comment]
@shawnnaquin -- if you figure this out please hit me up...

**Comment by shawnnaquin** [comment]
so its because of the clean css and clean JS tasks. 

```
gulp.task('clean:css', function() {
  return del([
      'assets/stylesheets/foundation.css',
      'assets/stylesheets/foundation.css.map'
    ]);
});
```

since the file is being deleted SFTP sees it as a new file and not an edited and currently monitored file. 

I ended up using the gulp.watch task and gulp-sftp to reupload the file on create.

```
gulp.task('watch-scss', function() {
  sequence(['clean:css', 'sass'], 'sftp-css');
});
```

**Comment by andreaarcher** [comment]
Perfect, that worked! Thanks
