### ISSUE TITLE
Error trying to compile foundation.scss

### ISSUE THREAD

**Issue by noxxviii** [olefredrik/FoundationPress#796]
**How can this bug be reproduced?**

1. Install Prepros/Or Install SASS and Node 4.4.3 LTS on a MacBook Pro (El Capitan)
2. Try to compile foundation.scss via Prepros/Or open Terminal cd <theme location> -> run npm install -> run npm build
3. Get Error

**What did you expect to happen?**

No error

**What happened instead?**

I get this Error Message 

```
gulp-notify: [Sass Error] assets/scss/global/_settings.scss
Error: File to import not found or unreadable: ../../components/foundation-sites/scss/util/util
       Parent style sheet: /Users/akira/Desktop/FoundationPress-master/assets/scss/global/_settings.scss
        on line 43 of assets/scss/global/_settings.scss
>> @import '../../components/foundation-sites/scss/util/util';
```
  
Tested it on two MacBooks independently and am really Stuck, I don't know if it's an error with Foundationpress or possibly my fault.

**Comment by olefredrik** [comment]
What version of node are you using? You can type ```node -v``` in your terminal to reveal your version number. Which errors did you get when running ```npm install``` ?

**Comment by noxxviii** [comment]
I get no Errors when using `npm install` and `node -v` says `2.15.1` and thanks for the quick response

**Comment by colin-marshall** [comment]
Does the `assets/components/foundation-sites` directory exist?

**Comment by colin-marshall** [comment]
Does the `assets/components/foundation-sites` directory exist?

**Comment by colin-marshall** [comment]
Also is 2.15.1 the npm version or the node version?

**Comment by noxxviii** [comment]
Sorry about the confusement:  

`node -v` is `v4.4.3`
`npm -v` is `2.15.1`

after trying over and over it does work at last with the Terminal but Prepos still exits with errors, but I can't recreate the Error using the Terminal anymore nor do I know why it occured, the named directory did exist (and was readable/writable).

**Comment by mikemontes** [comment]
I'm showing the same error as noxxviii. I'm not sure what is wrong. I have followed tutorials and all with no luck.

**Comment by mikemontes** [comment]
error scss/global/_settings.scss (Line 43: File to import not found or unreadable: ../../components/foundation-sites/scss/util/util.

**Comment by colin-marshall** [comment]
@mikemontes does the directory `assets/components/foundation-sites` exist?

**Comment by mikemontes** [comment]
It didn't.

I fixed it however using the node.js install process instead of the team tree house tutorial. This is what I used if anyone runs into the same issue. https://foundationpress.olefredrik.com/posts/tutorials/foundationpress-for-beginners

**Comment by colin-marshall** [comment]
Ahhh I see. Can you link me to the FoundationPress Treehouse tutorial you were using? I am guessing it was older and used v1.

If you want to use the older version to follow along, you can do the following:

```sh
git clone -b foundation-5 https://github.com/olefredrik/FoundationPress.git
```

**Comment by anthonyabraira** [comment]
@noxxviii / I found that my HomeBrew had updated my node software to version 7.x.x which is already known to cause issues. Therefore did a downgrade to 4.4.2 following these steps:

https://www.abeautifulsite.net/how-to-upgrade-or-downgrade-nodejs-using-npm

```
sudo npm cache clean -f
sudo npm install -g n
sudo n 4.4.2
```
