### ISSUE TITLE
Working with an "old" FoundationPress

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#800]
Not really an issue but sometimes you have to change something on an older website made with FoundationPress. And sometimes, one thing (juste change two thing in the CSS) that should take 5 minutes take 1h and more because it's difficult to update old SCSS when your system has upgraded (node, bower, grunt,etc).
Maybe it would be great to find a solution to avoid that!

Just in case, I openend an old theme (FoundationPress 5.5.0, one that was working with 'grunt build'), and I got the 
'Loading "sass.js" tasks...ERROR
>> Error: Module did not self-register.' error.

What I did for this one is upgrading node-sass with 'npm i node-sass@latest --save' and grunt-sass with 'npm i grunt-sass@latest --save'. Seems to work so far now.

**Comment by colin-marshall** [comment]
As far as Node/npm goes, I would recommend using NVM (Node Version Manager). You can have multiple versions of Node on your system and switch between them. You could have one version setup to work with Foundation 5 projects and another to work with Foundation 6 projects. You can even put an `.nvmrc` file in each project's root directory that will automatically switch to the correct version of Node when you are inside that project's directory in terminal.

**Comment by dantahoua** [comment]
Thanks Colin, I have to give it a try. Thanks a lot!

**Comment by dantahoua** [comment]
I finally found the good version to use with NVM and with try and try until I find the good version. Work like a charm once you find the good npm version to use! Thanks.

**Comment by colin-marshall** [comment]
@dantahoua glad you got it working! Please share the versions of node/npm that you found worked well with F5/6 as other users may find that info helpful. Thanks!

**Comment by drivenfaroff** [comment]
I've had luck doing the following. However there could be issues if you changed stuff in the package.json file along the way.

1. Backup the following in the shoremaster theme folder.
node_modules
package.json
Replace package.json file with this one from Git: https://github.com/olefredrik/FoundationPress/blob/foundation-5/package.json
Remove the node_modules folder
This command does it from the command line “rm -rf node_modules/“
Run “npm install”

**Comment by dantahoua** [comment]
I add to install the 0.9 version. Maybe it would need another version for a more recent project...

**Comment by wishe** [comment]
I had some similar issues before i started using nvm. The versions of npm that i use are 0.10.37 for F5 and 4.2.3 for F6. Those seems to run well!
