### ISSUE TITLE
using xlarge and xxlarge causes warnings

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#801]
I have activated the xxlarge breakpoint in the settings and I'm now getting the following warnings when ever I update a file

WARNING: breakpoint(): the media query "xxlarge only" cannot be used because xxlarge is the largest breakpoint.
    on line 56 of assets/components/foundation-sites/scss/util/_breakpoint.scss
    from line 130 of assets/components/foundation-sites/scss/util/_breakpoint.scss
    from line 54 of assets/components/foundation-sites/scss/components/_visibility.scss
    from line 82 of assets/components/foundation-sites/scss/components/_visibility.scss
    from line 32 of stdin

WARNING: breakpoint(): the media query "xxlarge down" cannot be used because xxlarge is the largest breakpoint.
    on line 56 of assets/components/foundation-sites/scss/util/_breakpoint.scss
    from line 130 of assets/components/foundation-sites/scss/util/_breakpoint.scss
    from line 71 of assets/components/foundation-sites/scss/components/_top-bar.scss
    from line 61 of stdin

**Comment by Aetles** [comment]
Don't you think this is rather [an issue with Foundation](https://github.com/zurb/foundation-sites/issues/7979)? It seems like [it is already fixed](https://github.com/zurb/foundation-sites/commit/8252c2ba8f2703a377dc0cf594aa5a2e3ab2ad7a) since 6.2.0. (But since Foundation 6.2.0 was buggy it could be better to stay on 6.1.x for other reasons, even though 6.2.1 fixed some of the issues.)

**Comment by nitrokevin** [comment]
Hi Aetles, thanks for the link, yeah that looks like the same issue, but I'm on 6.2.1 and still getting the warnings, not a major problem if it doesn't cause any real issues

**Comment by Leland** [comment]
As a point of reference, I'm using both xlarge and xxlarge successfully on my build.

You simply have to update the `$breakpoint-classes` in _settings.scss to include the two breakpoints. Final code should look like:

`$breakpoint-classes: (small medium large xlarge xxlarge);`
