### ISSUE TITLE
Toggle search box not working on desktop view

### ISSUE THREAD

**Issue by tylerfoulkes** [olefredrik/FoundationPress#802]
I am working on a website that has a set of social icons in the header, one of the icons is a search icon. When you click it the search box toggles down and you can search something. Something happened (Im not quite sure what) but now the search box only toggles on mobile view and when it toggles, it toggles the navigation as well, why doesn't it toggle on desktop view? and why is it linked to the navigation toggle on mobile view?

Any help would be greatly appreciated!

**Comment by colin-marshall** [comment]
Please provide the php for these social icons in your header.

**Comment by tylerfoulkes** [comment]
'''php
<div class="title-bar" data-responsive-toggle="site-navigation">
      <div class="title-bar-title">
            <button class="menu-icon" type="button" data-toggle="offCanvas"></button>
            <center>
                  <a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><img src="<?php echo     get_template_directory_uri();?>/assets/images/site/exponent-logo.png" width="60%"></a>
            </center>
	    <?php get_template_part( 'parts/header', 'icon-box' ); ?>
	</div>
</div>
'''

**Comment by tylerfoulkes** [comment]
```php
<div class="title-bar" data-responsive-toggle="site-navigation">
    <div class="title-bar-title">
        <button class="menu-icon" type="button" data-toggle="mobile-menu"></button>
        <center>
            <a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><img src="<?php echo get_template_directory_uri();?>/assets/images/site/exponent-logo.png" width="60%"></a>
        </center>
        <?php get_template_part( 'parts/header', 'icon-box' ); ?>
    </div>
</div>
```
The above code runs for mobile view however when I press the search icon it toggles both the navigation and the search box and when I remove this line of code:
```php
<?php get_template_part( 'parts/header', 'icon-box' ); ?>
```
The desktop view code runs as it should and the search box toggles but obviously the icons no longer show up on mobile view. I think Ive pin pointed it to be something wrong with the data-toggle tag being used for both navigation and search so on desktop view data toggle doesn't work at all because the data-toggle tag only works on mobile view.

**Comment by colin-marshall** [comment]
@tylerfoulkes I tried to email you through the "Contact Me" link on your website but I got a message back that it didn't go through for some reason. Shoot me an [email](mailto:colin.michael.marshall@gmail.com) so I can resend the message to you. Thanks!

**Comment by colin-marshall** [comment]
Closing this... resolved via email with @tylerfoulkes
