### ISSUE TITLE
Scss import failing

### ISSUE THREAD

**Issue by StlthyLee** [olefredrik/FoundationPress#804]
I've just updated my foundationpress theme to use the latest version and have found that when I run `npm run watch`  I'm getting the following SASS error 

`[13:56:56] gulp-notify: [Sass Error] assets/scss/global/_settings.scss
Error: File to import not found or unreadable: ../../components/foundation-sites/scss/util/util
       Parent style sheet: /Users/lee/code/blog/wp-content/themes/stlthy_wptheme/assets/scss/global/_settings.scss
        on line 43 of assets/scss/global/_settings.scss
 @import '../../components/foundation-sites/scss/util/util';`

I've had a look in both my theme and in foundationpress master and it is correct this file does not exist. Is there a reason for this?

Update:
This seems to be the case for any file found in the /components/foundation-sites location. is there a directory missing or were these meant to be removed during my merge? (I didn't get any conflicts in these areas)

**Comment by StealthyGecko** [comment]
I think I've figured out what the issue is, but will update when I know for sure

**Comment by StealthyGecko** [comment]
I have indeed figured out this issue, it turned out that npm install  was failing silently it was only when I ran`bower install && gulp build` that the causes of the errors became apparent.

However I now have a different issue when I run `npm run watch` I'm not seeing any styling whatsoever in the browser :/

**Comment by StealthyGecko** [comment]
I've just tried a completely clean install of FoundationPress following the instructions on the Readme again  and I'm getting exactly the same results here is a screenshot of how it looks.  

<img width="1919" alt="screen shot 2016-04-28 at 13 43 21" src="https://cloud.githubusercontent.com/assets/36741/14886154/3922c89a-0d47-11e6-9ff4-6286ca70e460.png">

 This is getting pretty frustrating now I wanted to upgrade my theme as I noticed it was behind master but at present I can't do anything, until now I have loved using FoundationPress any help would be appreciated

**Comment by olefredrik** [comment]
Do you get any errors when running ```npm install```?

**Comment by StealthyGecko** [comment]
Hi @olefredrik 

No I don't

Here is the output:

`npm install                                                                                                                                                                                     130 ↵
|
> foundationpress@2.6.1 postinstall /Users/lee/code/blog/wp-content/themes/FoundationPress
> bower install && gulp build

[13:53:59] Using gulpfile ~/code/blog/wp-content/themes/FoundationPress/gulpfile.js
[13:53:59] Starting 'clean'...
[13:53:59] Starting 'clean:javascript'...
[13:53:59] Starting 'clean:css'...
[13:53:59] Finished 'clean:javascript' after 9.81 ms
[13:53:59] Finished 'clean:css' after 7.24 ms
[13:53:59] Finished 'clean' after 12 ms
[13:53:59] Starting 'build'...
[13:53:59] Starting 'copy'...
[13:53:59] Finished 'copy' after 85 ms
[13:53:59] Starting 'sass'...
[13:53:59] Starting 'javascript'...
[13:54:00] Starting 'lint'...
[13:54:02] Finished 'lint' after 2.1 s
[13:54:02] Finished 'sass' after 2.8 s
[13:54:03] Finished 'javascript' after 4.19 s
[13:54:03] Finished 'build' after 4.62 s`

**Comment by StealthyGecko** [comment]
I've just tried installing the latest version on my second laptop and ended up with the same results. I'm really struggling to get the latest version of this working

**Comment by colin-marshall** [comment]
@StealthyGecko can you please elaborate on what you did to update the theme to the latest version?

**Comment by StealthyGecko** [comment]
@colin-marshall thats the thing this isn't updating the theme anymore. I moved out my old theme and tried to install a fresh copy of FoundationPress and this is what happens. My plan was to get the new version of the theme working and then copy across any of my own styling etc. but so far I can't even get the basic theme to work

**Comment by StealthyGecko** [comment]
@olefredrik / @colin-marshall So in the hope it may help find the route cause of this issue I thought I would start from scratch (again) so that I could post the full output from running `npm install`
[output.txt](https://github.com/olefredrik/FoundationPress/files/242152/output.txt)

I noticed that there are a few warnings about deprecated packages and as such I am looking at fixing those but other than that I'm not sure what would cause this

**Comment by colin-marshall** [comment]
Those warnings shouldn't be an issue. Have you tried uninstalling and reinstalling Gulp globally? What version of Node are you running? Run npm cache clean and rm -rf node_modules before running npm install again.

**Comment by colin-marshall** [comment]
@StealthyGecko anything new to report?

**Comment by StealthyGecko** [comment]
@colin-marshall unfortunately I haven't been able to make time to work on this particular project for a few days but as soon as I do I'll update you.

**Comment by LukePettway** [comment]
I've been seeing similar issues lately, on a few developers in the agency that shares an office space with us. More often than not, it looked like they needed to update their Node/NPM versions, reinstall everything, and it all started working. Not sure if that helps or not.

**Comment by cbessee** [comment]
@StlthyLee Is it possible you're missing the .bowerrc file that tells bower to install components at assets/components/? That would explain why you're getting file not found errors but no errors on bower install.

**Comment by mattmcgiv** [comment]
Running `npm update` and then (from the FoundationPress root directory): `bower install && gulp build` has fixed this issue for me.

After running those two commands, `npm run build` seems to have worked perfectly compiling my SCSS into CSS, whereas before I just had the "broken" styles as shown in the above screenshot from @StlthyLee
