### ISSUE TITLE
FoundationPress installation via npm failed

### ISSUE THREAD

**Issue by shoaibik** [olefredrik/FoundationPress#805]
When installing FoudationPress via npm failed with message, 

```
this.processing = new Promise(function (resolve, reject) {
ReferenceError: Promise is not defined
```
I am using Ubuntu 14.04 LTS , npm 1.3.10 and node v0.10.25

Detailed message is attached.
[log.txt](https://github.com/olefredrik/FoundationPress/files/241834/log.txt)

**Comment by colin-marshall** [comment]
You need to be running Node v4+ for FoundationPress

**Comment by shoaibik** [comment]
Thank you, after Installing latest node, it worked.
