### ISSUE TITLE
Logged in to my WP install via Browser Sync

### ISSUE THREAD

**Issue by jkaliski** [olefredrik/FoundationPress#806]
I set up a MAMP server on my local machine with the address localhost:8888.

Because I installed FoundationPress and used gulp Browser Sync for live view I accidentally logged in to my WP through localhost:3000. I wonder if I should be worried about any changes in my database in case I updated something on my website.

**Comment by colin-marshall** [comment]
You are fine. The WordPress server is still the same, BrowserSync just uses localhost as a proxy for the MAMP server. 

The only downside to logging in to the WP Dashboard through localhost is that the dashboard will reload when changes are detected. After BrowserSync starts and opens a new tab for localhost, I always login to the dashboard in a separate tab through the original local server url (mywebsite.dev for example) so the dashboard doesn't refresh with the rest of the site.

**Comment by jkaliski** [comment]
Glad to hear that Colin, thank you for your help!
