### ISSUE TITLE
Active dropdown always showing.

### ISSUE THREAD

**Issue by bseehafer** [olefredrik/FoundationPress#814]
I've got an issue related to a recent question but using FP5. I have an issue where in a section that navigation is marked as active, a user cannot navigate up and down through the page via the submenu without it being stuck open all the time and won't auto-close. If you hover over the other menu items, those will open and close as expected but the active section has an issue. 

I tried using jquery to automatically show and hide the menu but for some reason the solution doesn't work in Chrome on Windows (works fine on a Mac) and FF both Mac and PC. IE the solution works fine but I've switched out so many different functions trying to get it to work (toggle, addClass, toggleClass, etc.) and all work just the same, the menu hides and then shows again as it should on the browsers that it works in and then fails to reappear in the ones that are giving me an issue.

This is one version of the jquery function that works:
$(document).ready(function() {
    $('.top-bar-section li.active:not(.has-form) a:not(.button)').click(function() { 
        $("li.active ul.sub-menu.dropdown").css("display", "none");
    });
    $('.top-bar-section li.active:not(.has-form) a:not(.button)').hover(function() {
        if($("li.active ul.sub-menu.dropdown").css("display", "none")){
           $("li.active ul.sub-menu.dropdown").css("display", "block");
        }
    });
})

And this is a page from the site to illustrate: http://development.maclynutility.com/littlefriends/childrens-services 

If you navigate through that section of the site the active menu will stick in the above browsers, I need it to autoclose and am running out of options on how to do that. I apologize if this might not be the correct way to go about this but I'm in the 11th hour on this and it's got me up against a wall. I do appreciate any help anyone can provide, thank you very much.

**Comment by olefredrik** [comment]
FP5 is no longer supported.
