### ISSUE TITLE
NPM run production not working with node.js 6.1.0 (Solved)

### ISSUE THREAD

**Issue by oshovah** [olefredrik/FoundationPress#815]
**How can this bug be reproduced?**

1. npm run production

[17:23:32] Finished 'lint' after 924 ms
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /Users/gott/Sites/plainTemplate/wp-content/themes/plainTemplate/node_modules/clean-css/lib/utils/input-source-map-tracker.js:191:56
    at Array.forEach (native)
    at trackContentSources (/Users/gott/Sites/plainTemplate/wp-content/themes/plainTemplate/node_modules/clean-css/lib/utils/input-source-map-tracker.js:188:20)
    at InputSourceMapStore.trackLoaded (/Users/gott/Sites/plainTemplate/wp-content/themes/plainTemplate/node_modules/clean-css/lib/utils/input-source-map-tracker.js:255:3)
    at fromString (/Users/gott/Sites/plainTemplate/wp-content/themes/plainTemplate/node_modules/clean-css/lib/utils/input-source-map-tracker.js:32:8)
    at InputSourceMapStore.track (/Users/gott/Sites/plainTemplate/wp-content/the

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "run" "production"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! plaintemplate@1.0.0 production: `gulp --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plaintemplate@1.0.0 production script 'gulp --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the plaintemplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs plaintemplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls plaintemplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gott/Sites/plainTemplate/wp-content/themes/plainTemplate/npm-debug.log

any ideas?

**Comment by colin-marshall** [comment]
If you had `npm run production` working on a previous version of node, I would install Node Version Manager and rollback to that version. I have found that having the most recent version of Node installed to be troublesome. I usually stick back a couple releases. I've been running 5.1.1 for awhile on my laptop and have 5.5 running on my desktop. Both work great with FoundationPress for me.

**Comment by oshovah** [comment]
Thanks Colin Marshall
Node 5.5.0 Works! I totaly forgott that you can't trust a release version.
