### ISSUE TITLE
$foundation-palette: Not compiling

### ISSUE THREAD

**Issue by peterbaio** [olefredrik/FoundationPress#816]
I've exhausted my research on why this is happening.  When I comment this variable out, $breakpoints does not compile.  Any help?

Syntax error: Invalid CSS after "  primary": expected ")", was ": #2199e8,"
        on line 52 of /Applications/MAMP/htdocs/sinfitWebsite/wp-content/themes/sinfit/assets/scss/global/_settings.scss
        from line 11 of /Applications/MAMP/htdocs/sinfitWebsite/wp-content/themes/sinfit/assets/scss/foundation.scss

$foundation-palette: (
  primary: #2199e8,
  secondary: #777,
  success: #3adb76,
  warning: #ffae00,
  alert: #ec5840,
);

**Comment by colin-marshall** [comment]
@peterbaio your question is not clear. Are you commenting out `$breakpoints` or `$foundation-palette`? And why are you commenting it out?

**Comment by peterbaio** [comment]
Hi Colin,

I was just testing to see if there was an issue with $foundation-palette that's why I commented it out.  The issue seems to be how the variable is written out cause $breakpoints is written out the same way.

**Comment by fredconv** [comment]
Hi 

I ve got thte same problem here

I ve just installed the theme, didn't change anything, try to compile but i get this error: 
"parse error: failed at `$foundation-palette: (`.../wp-content/themes/FoundationPress-master/assets/scss/global/_settings.scss on line 51"

and in the _settings.scss 

$global-font-size: 100%;
$global-width: rem-calc(1200);
$global-lineheight: 1.5;
$foundation-palette: (
  primary: #2199e8,
  secondary: #777,
  success: #3adb76,
  warning: #ffae00,
  alert: #ec5840,
);
$light-gray: #e6e6e6;
$medium-gray: #cacaca;
$dark-gray: #8a8a8a;
$black: #0a0a0a;
$white: #fefefe;
$body-background: $white;
$body-font-color: $black;
$body-font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;
$body-antialiased: true;
$global-margin: 1rem;
$global-padding: 1rem;
$global-weight-normal: normal;
$global-weight-bold: bold;
$global-radius: 0;
$global-text-direction: ltr;
$global-flexbox: false;
$print-transparent-backgrounds: true;

@include add-foundation-colors;
..................................
...
...



same as above, if i remove the variable, another variable written the same way (list of value) , i got a parse error. 

I ve tried it with wp-scss auto compiler, and the npm watch also TT_TT 



Thanks for your help

**Comment by olefredrik** [comment]
Unable to recreate issue on latest version of FoundationPress.
