### ISSUE TITLE
Maybe add node version somewhere at first install?

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#819]
Not really an issue but more of a suggestion... Maybe it would be a good idea to write somewhere the node version used when installing a theme? So if we come back to that theme one year later, we know which version to choose with NVM... I see a lot of issue coming from npm version, it would at least remove those one ;)
Just an idea, what do you think?

**Comment by colin-marshall** [comment]
`.nvmrc` exists for this reason. You add a `.nvmrc` file with a node version to the root of a project and it will switch to that version when you enter the project directory through the terminal. Documenting the use of NVM and how to setup the `.nvmrc` file is what I would suggest.
