### ISSUE TITLE
Post Nav/Pagination Not Showing

### ISSUE THREAD

**Issue by robertrhu** [olefredrik/FoundationPress#820]
As always, thank you so much for FoundationPress. Its my favorite!

For some reason I am unable to get next and previous pagination navigation to appear on the bottom of my single-*.php pages. This usually works out of the box but not working for me this time. Previous and next links don't appear on my posts.

I haven't changed anything in the functions.php pagination function.

Here's what I've using in my single-*.php files...

```
//CODE I'M USING ON MY SINGLE PAGES

<?php /* Display navigation to next/previous pages when applicable */ ?>
        <?php if ( function_exists( 'foundationpress_pagination' ) ) { foundationpress_pagination(); } else if ( is_paged() ) { ?>
            <nav id="post-nav">
                <div class="post-previous"><?php next_posts_link( __( '&larr; Older posts', 'foundationpress' ) ); ?></div>
                <div class="post-next"><?php previous_posts_link( __( 'Newer posts &rarr;', 'foundationpress' ) ); ?></div>
            </nav>
        <?php } ?>
```

**Comment by joewellmade** [comment]
Hi, I also can't get the pagination to work on single.php.

**Comment by Eccola** [comment]
Hello folks, there seems to be slight confusion what kind of navigation should appear and where.

The `single.php` is equipped with `wp_link_pages` function:
https://codex.wordpress.org/Function_Reference/wp_link_pages

I agree `single.php` should contain `previous_post_link` and `next_post_link` function:
https://codex.wordpress.org/Function_Reference/previous_post_link
https://codex.wordpress.org/Function_Reference/next_post_link

The snippet @robertrhu suggests is meant to be used only on archive templates.

**Comment by joewellmade** [comment]
Thanks Eccola, here's my template code, do you know why it's not showing?
`<?php
/**
 * The template for displaying all single posts and attachments
 *
 * @package FoundationPress
 * @since FoundationPress 1.0.0
 */

get_header(); ?>

<div id="single-post" role="main">

	<div class="row">
		<div class="large-6 large-offset-3 columns post-box">
			<?php do_action( 'foundationpress_before_content' ); ?>
			<?php if ( have_posts() ) : ?>
			<?php while ( have_posts() ) : the_post(); ?>
				<article <?php post_class('main-content') ?> id="post-<?php the_ID(); ?>">
					<header>
						<h1 class="entry-title"><?php the_title(); ?></h1>
						<?php foundationpress_entry_meta(); ?>
					</header>
					<?php do_action( 'foundationpress_post_before_entry_content' ); ?>
					<div class="entry-content">

					<?php
						if ( has_post_thumbnail() ) :
							the_post_thumbnail('large');
						endif;
					?>

					<?php the_content(); ?>
					</div>
					
					<footer>
						<?php wp_link_pages( array('before' => '<nav id="page-nav"><p>' . __( 'Pages:', 'foundationpress' ), 'after' => '</p></nav>' ) ); ?>
						<p><?php the_tags(); ?></p>
					</footer>
					
				</article>
				
				
			<?php endwhile;?>
			

			<?php else : ?>
				<p><?php _e('Sorry, no posts matched your criteria.'); ?></p>
			<?php endif; ?>

			

			<?php do_action( 'foundationpress_after_content' ); ?>
		</div>
	</div>

</div>
<?php get_footer();`

**Comment by joewellmade** [comment]
Hi Eccola, here's my template code, do you know why I can't get pagination to show here?

`<div id="single-post" role="main">

	<div class="row">
		<div class="large-6 large-offset-3 columns post-box">
			<?php do_action( 'foundationpress_before_content' ); ?>
			<?php if ( have_posts() ) : ?>
			<?php while ( have_posts() ) : the_post(); ?>
				<article <?php post_class('main-content') ?> id="post-<?php the_ID(); ?>">
					<header>
						<h1 class="entry-title"><?php the_title(); ?></h1>
						<?php foundationpress_entry_meta(); ?>
					</header>
					<?php do_action( 'foundationpress_post_before_entry_content' ); ?>
					<div class="entry-content">

					<?php
						if ( has_post_thumbnail() ) :
							the_post_thumbnail('large');
						endif;
					?>

					<?php the_content(); ?>
					</div>
					
					<footer>
						<?php wp_link_pages( array('before' => '<nav id="page-nav"><p>' . __( 'Pages:', 'foundationpress' ), 'after' => '</p></nav>' ) ); ?>
						<p><?php the_tags(); ?></p>
					</footer>
					
				</article>
				
				
			<?php endwhile;?>
			

			<?php else : ?>
				<p><?php _e('Sorry, no posts matched your criteria.'); ?></p>
			<?php endif; ?>

			

			<?php do_action( 'foundationpress_after_content' ); ?>
		</div>
	</div>

</div>`

**Comment by Eccola** [comment]
@joewellmade, what FP version you are using?

Try paginating your single post content, like:

```
Post Page 1 Content

<!--nextpage-->

Post Page 2 Content

<!--nextpage-->

Post Page 3 Content

```

**Comment by joewellmade** [comment]
Thanks Eccola, I'm using the latest version, I've got it working now by adding: 
`<?php previous_post_link(); ?>    <?php next_post_link(); ?>`

I'm not sure how to add this to a custom post type single.php page however. I've got a single page template called single-monkey_business.php and need to apply pagination to that now.

**Comment by joewellmade** [comment]
Thanks, much appreciated, I have it working now.

**Comment by colin-marshall** [comment]
@Eccola you think we should add the `previous_post_link()` & the `next_post_link()` to FoundationPress on `single.php`? I'm all for adding it, if others think so too.

Anybody else have an opinion on adding this? @olefredrik @Aetles?

**Comment by olefredrik** [comment]
I'd say yes.

**Comment by Aetles** [comment]
Isn't that what [the_post_navigation()](https://developer.wordpress.org/reference/functions/the_post_navigation/) does? It's already in `single.php`. Or am I misunderstanding the questing here?

(Whenever I am in doubt I usually check what Underscores are doing and they are using `the_post_navigation()` in their [single.php](https://github.com/Automattic/_s/blob/master/single.php) and no sign of `previous_post_link()` or `next_post_link()`.)

**Comment by colin-marshall** [comment]
@Aetles thank you, that is correct. I only read this thread and should have looked at the theme first. 

@robertrhu is `<?php the_post_navigation(); ?>`  present in your `single-*.php`?

**Comment by Eccola** [comment]
@colin-marshall ,  see: https://github.com/olefredrik/FoundationPress/pull/839
