### ISSUE TITLE
Mobile Menu Accordion Menu - Expand "active" submenu parent automatically

### ISSUE THREAD

**Issue by photonomad** [olefredrik/FoundationPress#822]
Is there a way to make menu-items with the "active" and "is-accordion-submenu-parent" classes automatically be expanded when the page loads?

It would be more convenient for viewers if the active menu item in the vertical accordion menu would just be open by default, but I can't figure out where or how to edit the code to make this happen. 

Thanks in advance for any suggestions!

**Comment by AdamChlan** [comment]
See if this helps you out:

http://foundation.zurb.com/forum/posts/21440-accordion-expand-all-on-load <http://foundation.zurb.com/forum/posts/21440-accordion-expand-all-on-load>

**Comment by photonomad** [comment]
Thanks for suggesting that link! I tried it, but unfortunately it does not work for me (using Foundation 6).

Your suggestion did lead me to reread F6 info on Accordion Menus:
http://foundation.zurb.com/sites/docs/accordion.html

I edited line 46 of navigation.php to the following:
`'items_wrap'     => '<ul id="%1$s" class="%2$s" data-accordion-menu data-multi-expand="true">%3$s</ul>',`

The **data-multi-expand="true"** is now showing up in my code, but it seems to have no effect.

![image](https://cloud.githubusercontent.com/assets/1000126/15408572/82b44f3e-1dd6-11e6-8a2e-f310870f6fc6.png)

**Comment by photonomad** [comment]
Actually, I guess data-multi-expand="true" doesn't open all the items. It just allows more than one item to be open at a time.

And, Accordion Menu is different from just an Accordion.

So, it looks like I need to utilize this somewhere:
$('#element').foundation('down', $target);

Having trouble figuring out how to use it.

**Comment by photonomad** [comment]
Thanks @AdamChlan - though, I think the solution in that thread is not compatible with Foundation 6.

This is the solution I found that works with the Foundation 6 Accordion Menu:

$(window).load(function() { 
$(".active a").trigger('click');
});

**Comment by thomasfrobieter** [comment]
"To have a sub-menu already open when the page loads, add the class .is-active to that sub-menu."

**Comment by AlexLaforge** [comment]
If you need to do it manually, you can use this code (tested with Foundation 6.4.3) :
`$('.menu.vertical.accordion-menu[data-accordion-menu] .is-submenu-item.is-accordion-submenu-item > a.current').parents().find('.is-accordion-submenu-parent > a').trigger('click');`
