### ISSUE TITLE
Autoprefixer missing -webkit prefixes

### ISSUE THREAD

**Issue by PixelbarEupen** [olefredrik/FoundationPress#826]
I recently discovered that the autoprefixer is configured to skip -webkit prefixes. Most of all browser doesn't need them anymore but the android devices are still using the -webkit prefix.  (See http://caniuse.com/#search=transform ).

In the gulpfile, the autoprefixer is configured like this:
var COMPATIBILITY = ['last 2 versions', 'ie >= 9'];

This skips the -webkit prefix. when I change it to:
var COMPATIBILITY = ['last 3 versions', 'ie >= 9'];

With the first setting, even the off-canvas was not working on my test devices (Android 4.4.2). After changing it to the second setting, everything works fine on all my android devices.

It is confusing that I just discovered this issue the very first time on a recent project. Plenty of other older projects were fine with this setting.

Even when I check the "official" Foundation-CSS file, everything is prefixed with -webkit.

Can someone report similar problems with the autoprefixer and if yes i think that the gulpfile should be modified to include -webkit prefixes as long as android still need them. Or could this be a new issue due to a recent update of the autoprefixer?

Thanks

**Comment by beesmart** [comment]
@PixelbarEupen 

Yes this exact issue is happening to me as well. I raised an issue (now closed) concerning this before finding that you've already got here first!

You're right in that -webkit- seems to have stopped appearing, though -moz- is still there. I created a few sites - perhaps a month ago - and they all retain the -webkit- prefix. This affects Safari browsers mainly (the latest builds as well) and the usage of the offcanvas menu. I'll have to try you version adjustment above to see if that also restores functionality to the menu in Safari.
