### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by Snaphaan** [olefredrik/FoundationPress#827]
Windows 8
Latest node.js

Error message at the start when installing foundationpress. Did run a number of commands before this to try and solve a npm install issue with JointWP.

npm config set registry http://registry.npmjs.org/
npm config get proxy
npm config rm proxy
npm config rm https-proxy

Didn't fix anything really but foundationpress is working now. Dunno if these errors are anything to worry about:

```
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node release >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in tree.
npm WARN optional dep failed, continueing fsevents@1.0.12
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
```

**Comment by olefredrik** [comment]
Hi. These are warnings, not errors. No need to worry as long as FoundationPress is working and you're able to run the ```npm run build``` and ```npm run watch``` commands.
