### ISSUE TITLE
no styles

### ISSUE THREAD

**Issue by czokalapik** [olefredrik/FoundationPress#830]
I have no idea how SCSS works and i think my provider won't let me install compiler, so i'm missing CSS files:

/assets/stylesheets/foundation.css?ver=2.6.1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/assets/javascript/foundation.js?ver=2.6.1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/stylesheets/foundation.css?ver=2.6.1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by colin-marshall** [comment]
Are you able to run `npm install`?

**Comment by tomhermans** [comment]
Follow the quickstart, run that locally and then upload/deploy to your server (node_modules can be excluded)

**Comment by czokalapik** [comment]
i'm not able to run npm install:
`-bash: npm: command not found`
Plus i have no experience with using commands :/
I don't even know how to run such thing locally, usually i simply downloaded FoundationPress, uploaded it to FTP and installed theme.

**Comment by FlatspinZA** [comment]
1. You need to install Node.js (use the appropriate installer for your environment - https://nodejs.org/en/download/).NPM is included in the install. (Node Package Manager)
2. I used Ruby Installer to get my environment right (http://rubyinstaller.org/downloads/) - for using Foundation gem, etc. 
3. Install MiniGW, for libsass, the SASS compiler (http://www.mingw.org/), if on Windows, alternately check for a compiler that works on your OS.
4. Install Git - https://git-scm.com/downloads
5. Now you need a local web server (MAMP, LAMP, XAMP - whatever - I am using Microsoft Web Matrix (Web Server for idiots)).

To install MySQL & PHP locally, just install WordPress from the App Gallery on WebMatrix - you can delete this project once you have installed the fake WordPress site (files & content).

Now copy the WordPress installation files (dowloaded from WordPress & unzipped) into the working directory of your local project, and 'open folder' with WebMatrix pointing to the root of your project - this will install PHP dependencies. 

Use the command line to navigate to your project root folder - then it's "your_project_name/wp-content/themes"....follow the instructions for downloading the FoundationPress package, and installing it as per the 'Quickstart' instructions. 

Once installed you need to run "NPM run watch" (for the SASS compiler to work) from the theme folder of your new project "your_project_name/wp-content/themes/FoundationPress"

There are quite a few things to learn, but once you have learnt them, you won't look back, and developing locally will be a breeze.

**Comment by czokalapik** [comment]
I ended up installing webmatrix and stopped on totally empty App Gallery without any idea what to do next. Last try was to copy missing files from https://foundationpress.olefredrik.com/, but all the icons were squares, so no use. So back to bootstrap.

**Comment by olefredrik** [comment]
@czokalapik : If you read the [requirements](https://github.com/olefredrik/FoundationPress#requirements) and follow the [quickstart](https://github.com/olefredrik/FoundationPress#quickstart), you should be up and running in minutes. If you have no interest of using the required dependencies (npm and gulp), I would recommend using a different starter-theme.
