### ISSUE TITLE
Advice on Excessively Large File Size?

### ISSUE THREAD

**Issue by moseke** [olefredrik/FoundationPress#831]
Not exactly a bug, but I am looking for some advice and feed-back.

Is anyone else concerned or experiencing problems with the size of the current version of this theme? Compressed my file size is 53.3MB compared to the 34.7MB from previous versions, and 13MB for a fresh Foundation 6 install. 

What safe things can I do to thin this out for production? What files can I ditch when not in dev?

Thanks for the help!

**Comment by dantahoua** [comment]
You have to run npm run package... It will generate a zip file containing the theme with only the files you need. The size will depend on the images you use in assets and javascript you use. My theme usually end up around 5~6Mo!!!

**Comment by moseke** [comment]
@dantahoua Thank you so much for responding, going to back through and reading the official documentation I can see that we've been skipping a big step. I tried npm run package, but it doesn't output a zip for me. Is there something else that I need to be doing here?

**Comment by dantahoua** [comment]
Sorry, the right command is "npm run production"... :)

**Comment by moseke** [comment]
@dantahoua — Sorry for dragging this out... I tried `npm run production` after your first comment, and inserted the script that it output and then it just watches. 

Is there an API or Documentation for this that I could be consulting? Do I need to change one of these JSON files? I'm so lost right now. 😧

**Comment by dantahoua** [comment]
You do not have to change anything or edit any file for it to work... After doing npm run production, you're supposed to have a new folder in your theme in which you have the package...

**Comment by moseke** [comment]
OH MY GOD! It was in there the whole time and I just didn't see it. You are a saint @dantahoua!
