### ISSUE TITLE
Colin's centered menu with logo (zurb building block)

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#834]
**How can this bug be reproduced?**
Unable to get the menu items to position to the centre of the screen
http://zurb.com/building-blocks/centered-top-bar-with-logo

**What happened instead?**

I can only get the 2 menus to line up with the edge of my grid, unlike the demo which starts from the logo in the centre

**Please List the Following:**
OS X El Cap
* Node version (node -v) [Node v4+ is required] : 6.2
* Foundation version (bower list) : FoundationPress 6.2.2

I have just used the code "as is" on the zurb site but instead of the menu items starting at the centre and growing out, mine are starting from the edge of the screen and growing in, I have added
 class="top-bar column row" to contain to the grid but its still working outside in.

Also changing the variable $logo-padding: $logo-width - 32px;  is having no effect at all

![screen shot 2016-06-13 at 16 37 23](https://cloud.githubusercontent.com/assets/16405648/16013401/2db4abce-3185-11e6-98cb-3ed5dd0fffad.png)

**Comment by colin-marshall** [comment]
I haven't tried it with FoundationPress, and this Building Block was made with an older version of Foundation (either 6.0.x or 6.1.x). Did you try recreating it with just Foundation in 6.2.2?

**Comment by nitrokevin** [comment]
Not had a chance to test this yet, but I will do. Thanks
