### ISSUE TITLE
Blog pagination issue w/ woocommerce - links shift from /blog to /store pages

### ISSUE THREAD

**Issue by dberz** [olefredrik/FoundationPress#836]
You can see this here:

- https://parsleyhealth.com/blog/ the footer pagination links correctly link to blog pages.
- https://parsleyhealth.com/blog/page/2 and beyond, the blog pagination now links to my woocommerce **store**, ex. https://parsleyhealth.com/store/page/3/

I have not adjusted the FoundationPress index.php pagination code from the default:

````
			<?php /* Display navigation to next/previous pages when applicable */ ?>
			<?php if ( function_exists( 'foundationpress_pagination' ) ) { foundationpress_pagination(); } else if ( is_paged() ) { ?>
				<nav id="post-nav">
					<div class="post-previous"><?php next_posts_link( __( '&larr; Older posts', 'foundationpress' ) ); ?></div>
					<div class="post-next"><?php previous_posts_link( __( 'Newer posts &rarr;', 'foundationpress' ) ); ?></div>
				</nav>
			<?php } ?>
````

Would like to keep the blog post pagination links to blog pages, and the store page links to store pages.  

Any thoughts are appreciated!

**Comment by Eccola** [comment]
@dberz, did you get this?
`index.php` is a basic archive template. You can filter its output using `pre_get_posts` hook:
https://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts

Or, you could create a custom loop template for your blog entries, using `wp_query` arguments:
`$args = array( 'post_type' => 'post' );`
https://codex.wordpress.org/Class_Reference/WP_Query

**Comment by dberz** [comment]
@Eccola thank you!  I will investigate this.  

I'm surprised that customization is needed as FoundationPress supports woocommerce products & blog posts.  I would think the pagination links would work out of the box.

**Comment by colin-marshall** [comment]
@deberz I agree this should work out of the box. Will try to have a look in the future at this.

**Comment by dberz** [comment]
Thanks @colin-marshall and team.  You guys do a great job on this project!

One note per @Eccola's suggestion above: I was able to set a post_type specific loop within index.php, but FoundationPress seems to lose that post_type requirement on page two of the search results.  (ex. https://parsleyhealth.com/blog/page/2).   Is the loop for pages past pages 2-_n_ controlled somewhere else?

My page 1 correctly displays all pages as 'posts', only on page 2 does this jump to 'products'.

**Comment by colin-marshall** [comment]
@dberz I'm trying to reproduce locally. Could you please provide me with screenshots of `Settings -> Reading` and `Settings -> Permalinks`? Also, do you have a repo of your theme I could take a look at?

Thanks!

**Comment by dberz** [comment]
Thank you @colin-marshall.  Settings > Permalinks screenshot attached below. 

Happy to share my bitbucket repo with you privately.   

![screencapture-parsleyhealth-com-wp-admin-options-permalink-php-1467311569596](https://cloud.githubusercontent.com/assets/5471790/16499701/8fe8d1f6-3ecf-11e6-9c7b-0cffa77b6d05.png)

**Comment by colin-marshall** [comment]
@dberz thanks! Can I also please get a screenshot of the **Reading** settings?

**Comment by dberz** [comment]
Attached!

![image](https://cloud.githubusercontent.com/assets/5471790/16504921/7b001e34-3ee8-11e6-8a56-b43d205c4a22.png)

**Comment by dberz** [comment]
Update: this issue has resolved itself after I deactivated all plugins and reactivated them.  

Cause is unknown, but perhaps a caching layer or my 'autoptimize' plugin was part of the problem.
