### ISSUE TITLE
..

### ISSUE THREAD

**Issue by cabukater** [olefredrik/FoundationPress#837]
**How can this bug be reproduced?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**

**What happened instead?**

**Please List the Following:**
* OS & version:
* Node version (node -v) [Node v4+ is required] :
* Foundation version (bower list) :

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by colin-marshall** [comment]
@cabukater do you actually have an issue or was this a mistake? Closing for now, feel free to reopen it with info of an issue if one exists.
