### ISSUE TITLE
Theme Check Errors - Should I Be Worried?

### ISSUE THREAD

**Issue by David-Else** [olefredrik/FoundationPress#840]
Hello,

I am checking this theme out, and using https://wordpress.org/plugins/theme-check/ I get the following errors that concern me. I am a newb at this, should i be concerned by these errors? I don't want problems down the line... thanks!

PS Thanks for all your free work, I do appreciate it!

REQUIRED: Text Domain: is missing from your style.css header.
REQUIRED: .screen-reader-text css class is needed in your theme css. See See: the Codex for an example implementation.
REQUIRED: .gallery-caption css class is needed in your theme css.
REQUIRED: .bypostauthor css class is needed in your theme css.

WARNING: Found wp_deregister_script in enqueue-scripts.php. Themes must not deregister core scripts.

Line 19: wp_deregister_script( 'jquery' );

WARNING: Found a translation function that is missing a text-domain. Function _e, with the arguments 'Your comment is awaiting moderation.'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'FP Small'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'FP Medium'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'FP Large'
REQUIRED: You are not allowed to hide the admin bar.
REQUIRED: The theme doesn't have comment pagination code in it. Use paginate_comments_links() or the_comments_navigation or the_comments_pagination or next_comments_link() and previous_comments_link() to add comment pagination.
REQUIRED: No content width has been defined. Example:

if ( ! isset( $content_width ) ) $content_width = 900;

REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.
REQUIRED: Could not find comment_form. See: comment_form

 <?php comment_form(); ?>

RECOMMENDED: No reference to add_theme_support( "custom-header", $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
RECOMMENDED: Could not find the file readme.txt in the theme. Please see Theme_Documentation for more information.
RECOMMENDED: Tags: is either empty or missing in style.css header.

**Comment by LukePettway** [comment]
Are you planning on putting the them up on the WordPress Theme Market or anywhere else whether for free or not?

**Comment by Learn-Digital-Audio** [comment]
I am currently evaluating blank wordpress themes to use as the basis for creating custom themes for clients for a new business. I am totally new to theme development and just putting my 'toes in the water'.

I tried theme checker on another theme from the official wordpress site, and it did throw a few mild errors, but FoundationPress seems to have a few that seem more serious, for example:

"REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed."

Security is massively important. As i am a beginner at theme development and plan to put in a huge amount of work to learn, I would like to be certain I am starting off with a blank theme with no problems.

Thanks for the reply Luke, while i have your ear, perhaps you could tell me if you make a child theme while working on foundationpress? How am I meant to upgrade to a new core version, maybe best practice is to not touch the core files, but it seems Themes\FoundationPress\assets\scss\global.scss is meant to be edited directly? THANKS!

**Comment by LukePettway** [comment]
@Learn-Digital-Audio FoundationPress itself is a boilerplate meant to be directly built upon. I have never personally child-themed it as I have never had a need to but I am sure there are people who have. 

As far as the theme warnings, some of those might be good for Issues if they aren't already listed. Some of those might be intentional but someone like @olefredrik can speak more to that.  A couple of them such as text-domain in the style.css file are very simple to implement, so they shouldn't be much of an issue to resolve.

**Comment by olefredrik** [comment]
I don't consider any of the "required" changes or "warnings" as critical, to be honest. If any of you guys want to fix it to make it compliant with the theme check, I'm always open for reviewing pull requests.
