### ISSUE TITLE
Only a portion of styles from _front.scss are compiling.

### ISSUE THREAD

**Issue by jarrydfillmore** [olefredrik/FoundationPress#846]
**How can this bug be reproduced?**

1. See the _front.scss code
2. Only a portion of it is being compiled
3. Result? Full styles aren't being compiled and ultimately loaded

**What did you expect to happen?**
For all the styles to be loaded and my website to display properly

**What happened instead?**
Not all the styles were loaded

**Please List the Following:**
* OS & version: Mac - OS X Yosemite
* Node version (node -v) [Node v4+ is required] : v4.4.1
* Foundation version (bower list) : Not sure

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.

http://codepen.io/jdfillmore/pen/wWgyBM

**Summary**

I'm using the _front.scss file to style my site. Only some of the styles from _front.scss are being compiled out. Gulp is giving no errors when compiling.

Image of exactly what's going on:
![untitled-1](https://cloud.githubusercontent.com/assets/15603061/16357039/2e52911c-3ab9-11e6-885d-2cfac4580f28.jpg)

**Comment by olefredrik** [comment]
Hmm. I would expect gulp to throw an error if there was something wrong in your _front.scss file. Does the Chrome Devtools display any of the styles you're missing if you inspect the element?

**Comment by jarrydfillmore** [comment]
@olefredrik I know right?

Doesn't look like it, see the screenshot below:
![screen](https://cloud.githubusercontent.com/assets/15603061/16357780/a1009f88-3acd-11e6-8562-6508a6689f1c.jpg)

**Comment by LukePettway** [comment]
If you lint your CSS, are any errors present, what about your HTML?

**Comment by jarrydfillmore** [comment]
@LukePettway @olefredrik I ended up splitting up the scss files, and it worked. No idea why but it's working now!
