### ISSUE TITLE
How can I get the mobile menu to be on tablet devices as well?

### ISSUE THREAD

**Issue by jarrydfillmore** [olefredrik/FoundationPress#847]
**How can this bug be reproduced?**

1. Trying to get the moblile menu to be present on tablet devices
2. Tried, can't get it to work
3. Need the help!

**What did you expect to happen?**

For the mobile menu to be present on tablet devices, as well as on mobile.

**What happened instead?**

The opposite!

**Please List the Following:**
* OS & version: OS X Yosemite
* Node version (node -v) [Node v4+ is required] : Node v4.4.1
* Foundation version (bower list) : Not sure

**Comment by colin-marshall** [comment]
Try this:
- Open `/assets/scss/modules/_navigation.scss`
- Change the word `medium` to `large` on lines 4 & 8

https://github.com/olefredrik/FoundationPress/blob/master/assets/scss/modules/_navigation.scss#L4
https://github.com/olefredrik/FoundationPress/blob/master/assets/scss/modules/_navigation.scss#L8

**Comment by colin-marshall** [comment]
@jarrydfillmore I'm going to close this issue. If my response didn't solve your problem, feel free to reopen the issue. Thanks!
