### ISSUE TITLE
Is FP compatible with the WP Theme Directory guidelines?

### ISSUE THREAD

**Issue by gmmedia** [olefredrik/FoundationPress#849]
Hello,
I like to share my themes in the WP theme directory.

Somebody already tried to submit a FoundationPress theme there?

thank you
Jochen

**Comment by derweili** [comment]
I haven't tried yet. But there are some points I kown which do not match the guidelines.

For example:
- most cleanup functions (plugin Territory)
- Minification of styles and scripts is not allowed unless original files are included. ([Don't know if scss counts as original css files](https://make.wordpress.org/themes/handbook/review/recommended/css-preprocessors/))

It is definitely possible to modify FoundationPress to match all the guidelines.

You can find the guidelines here:
https://make.wordpress.org/themes/handbook/review/

**Comment by gmmedia** [comment]
To remove the cleanup functions and only add not-minified css files would be the easiest stepp.

Maybe anybody else here tried that before?
