### ISSUE TITLE
WP built-in post tags

### ISSUE THREAD

**Issue by AlexanderMars** [olefredrik/FoundationPress#851]
WP built-in posts tags doesn't work properly with FoundationPress theme. 
1. Creating tags in POSTS / tags menu.
2. Assigning tags to some new or existing posts - edit or create new post (enable "tags" in screen option of post)
3. Clicking on any tag on a live website and it will be redirected to the right page but without a correct content according to the clicked tag. It should contain all posts with that tag inside of it.
For example page dev2.hvvmg.com/page/100 
clicking "fitness"
redirecting to dev2.hvvmg.com/tag/fitness-2 (content is doctors list which is not relevant to that tag)
- OS & version: Windows 8
- Foundation version (bower list) : 5.4.3

**Comment by colin-marshall** [comment]
@AlexanderMars I did some testing and Tags appear to work as they should in the current version of FoundationPress. I'm going to close this issue, but if you are still having problems with it feel free to reopen.
