### ISSUE TITLE
Current steps to create offcanvas menu on the right? Removed from Customizer?

### ISSUE THREAD

**Issue by adambundy** [olefredrik/FoundationPress#852]
Sorry if this isnt the appropriate place to post this, but I've seen mention of a customizer option for 'offcanvas menu position (L/R)' and it seems to have been removed. Where has this been moved or what is the recommended method now for moving the offcanvas menu to the right?

**Comment by urbankid** [comment]
Hi @adambundy,
you can update the file /template-parts/mobile-off-canvas.php from

`<nav class="off-canvas position-left" id="mobile-menu" data-off-canvas data-position="left" role="navigation">`

to `<nav class="off-canvas position-right" id="mobile-menu" data-off-canvas data-position="right" role="navigation">`
