### ISSUE TITLE
Browser Sync expects different task handle in Gulpfile

### ISSUE THREAD

**Issue by svinqvmraka** [olefredrik/FoundationPress#860]
**How can this bug be reproduced?**

1. Enter address of the local site in gulpfile.js:16
2. run ```gulp browsersync```

**What did you expect to happen?**
Successfull browser sync  watch.

**What happened instead?**
```
[10:46:29] Task 'browsersync' is not in your gulpfile
[10:46:29] Please check the documentation for proper gulpfile formatting
```

**Please List the Following:**
* OS & version: Archlinux
* Node version (node -v) [Node v4+ is required] :  ```v6.3.0```
* Foundation version (bower list) : ```foundation-sites#6.2.3```

Changing the task handle in gulpfile.js:88 from ```browser-sync``` to ```browsersync```  ~~fixes the issue for me.~~ makes the browsersync task run successfully except it doesn't reload the site on file save. Not sure if that's the same issue.

**Comment by colin-marshall** [comment]
@svinqvmraka the browser-sync task is not meant to be run by itself. The only command you need to run is `gulp` or `npm run watch` which does the same thing.
