### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by joewellmade** [olefredrik/FoundationPress#861]
Hi, I'm having problems installing npm. Is anyone else having problems. Screenshot attached.

Thanks,
Joe
<img width="730" alt="screen shot 2016-07-25 at 14 22 58" src="https://cloud.githubusercontent.com/assets/1428597/17102886/8640241c-5273-11e6-9c3a-90c3648af742.png">

**Comment by joewellmade** [comment]
It seems I have to use 'sudo' to run anything and there is still an error:

'Error: File to import not found or unreadable: ../../components/foundation-sites/scss/util/util
       Parent style sheet: /Applications/MAMP/htdocs/cuttest/wp-content/themes/FoundationPress/assets/scss/global/_settings.scss
        on line 43 of assets/scss/global/_settings.scss
>> @import '../../components/foundation-sites/scss/util/util';'

**Comment by LukePettway** [comment]
What version of Node/NPM are you running?

**Comment by joewellmade** [comment]
Thanks Luke, here's the version info:

node -v
v4.4.4

npm -v
2.15.1

**Comment by LukePettway** [comment]
So the first thing I would do is fix NPM permissions:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

Then I would remove the node_modules folder completely. Try npm install after that.

**Comment by joewellmade** [comment]
Amazing, thanks Luke, I changed the permissions and that's fixed it!
