### ISSUE TITLE
Layout glitch

### ISSUE THREAD

**Issue by joewellmade** [olefredrik/FoundationPress#863]
Hi, I have a problem with a live site now that the client is adding content, I can't seem to replicate it  on my local copy. I have fixed it previously by asking them not to select more than one category per post, however something else seems to be throwing it off now. Also they want to be able to select more than one category also.

Here's a link to the page where it's happening: http://www.ludicology.com/2016/07/14/developing-playwork-projects/

There is a margin around the entire page. The page should look more like this page (without the navigation dropping down and the weird margins) http://www.ludicology.com/

Any help would be gratefully appreciated. 

Joe

**Comment by ducth201** [comment]
The body has a 40px padding because it has the classname "advice".

**Comment by joewellmade** [comment]
Oh man, can't believe I couldn't see that! Thank you.
