### ISSUE TITLE
Error during npm run build

### ISSUE THREAD

**Issue by bobofactory** [olefredrik/FoundationPress#866]
This is the error msg I encountered when i tried to get the final deliverable with npm run build. Would anyone kindly advise what's wrong with it? Thank you.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart foundation-emails-template@1.0.0
6 info start foundation-emails-template@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info foundation-emails-template@1.0.0 Failed to exec start script
9 verbose stack Error: foundation-emails-template@1.0.0 start: `gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid foundation-emails-template@1.0.0
11 verbose cwd /Users/Bo/garble-test-4
12 error Darwin 15.2.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error foundation-emails-template@1.0.0 start: `gulp`
17 error Exit status 1
18 error Failed at the foundation-emails-template@1.0.0 start script 'gulp'.
18 error This is most likely a problem with the foundation-emails-template package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs foundation-emails-template
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls foundation-emails-template
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by colin-marshall** [comment]
@bobofactory does this have anything to do with FoundationPress? Your error log shows you were trying to install foundation-emails-template 1.0.0 which is completely different.

**Comment by olefredrik** [comment]
what he said :arrow_up:
