### ISSUE TITLE
SSL with FoundationPress

### ISSUE THREAD

**Issue by jkaliski** [olefredrik/FoundationPress#868]
Does anybody know how to modify functions.php of this theme in order to securely load image files?
I get an error message that the theme is loading .png .jpg .svg files insecurely and therefore I cannot use my SSL. Thanks for helping.

**Comment by Eccola** [comment]
@jkaliski , this is not FoundationPress related issue. 
You could try something like: https://wordpress.org/plugins/ssl-insecure-content-fixer/

**Comment by olefredrik** [comment]
@jkaliski : If your site is set up to use https, you can enable the protocol relative theme assets function, by commenting out [line 51 in functions.php](https://github.com/olefredrik/FoundationPress/blob/master/functions.php#L51) 

``require_once( 'library/protocol-relative-theme-assets.php' ); ``

**Comment by jkaliski** [comment]
Thanks for helping me sorting it out!

**Comment by olefredrik** [comment]
No problem :)

**Comment by anthonyabraira** [comment]
I tried what was suggested here but I am find that my issue arises from browser sync not updating during code edits. I have updated the gulp file by providing:

```
// Enter URL of your local server here
// Example: 'http://localwebsite.dev'
var URL = ''; // SSL Support
// var PORT = 443;
```

to 

```
// Enter URL of your local server here
// Example: 'http://localwebsite.dev'
var URL = 'https://var.dev.com'; // SSL Support
var PORT = 443;
```

I also edited the gulpfile.js — 

```
// Browsersync task
gulp.task('browser-sync', ['build'], function() {

  var files = [
            '**/*.php',
            'assets/images/**/*.{png,jpg,gif}',
          ];

  browserSync.init(files, {
    // Proxy address
    proxy: URL,
    	 https: true, // SSL Support

    // Port #
    	port: 443
  });
});

```

to 

```
// Browsersync task
gulp.task('browser-sync', ['build'], function() {

  var files = [
            '**/*.php',
            'assets/images/**/*.{png,jpg,gif}',
          ];

  browserSync.init(files, {
    // Proxy address
    proxy: URL,
    	 https: true, // SSL Support

    // Port #
    	// port: 443
  });
});

```

The browser then started refreshing but nothing was changing despite the updates to the code. I also got these errors in my console:

`Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “var.dev.com” which could put your confidential information at risk.`

Could really use some feedback on the required settings to get this working.
