### ISSUE TITLE
is_single returns true for attachment page (navigation.php)

### ISSUE THREAD

**Issue by mrsWeasel** [olefredrik/FoundationPress#871]
Just added an image gallery with the option to link to attachment page. When I clicked the image link, these are the error messages i got in debug mode:

Notice: Undefined offset: 0 in .../navigation.php.
Notice: Trying to get property of non-object in .../navigation.php.

The problem seems to be the conditional block in foundationpress_breadcrumb function. Quick fix (although I'm sure there are better ones) that seemed to work was to make sure that attachment page does not return true for is_single:

``` php
if ( is_single() && ! is_attachment() ) {
// echo the stuff
}
```

OS & version: MacOS 10.8.5
Node version: 5.0.0
Foundation version (bower list) : 6.2.0

PS I'm a total newbie with Github so apologies if this didn't go 100% by the book :)

**Comment by colin-marshall** [comment]
@mrsWeasel thanks for pointing this out. Would you like to submit a pull request with the bugfix? I can walk you through it.

**Comment by mrsWeasel** [comment]
@colin-marshall sure I'd love to! How should we go about this?
