### ISSUE TITLE
Caret-down or down arrow not showing when navigation has submenus

### ISSUE THREAD

**Issue by labanino** [olefredrik/FoundationPress#873]
Not sure if it is an issue but the thing is that foundation by default shows the **down arrow** when there is a **submenu**. So, I pasted the navigation's code generated by Wordpress in jsfiddle and it shows the arrow. Question, I know many people doesn't like this arrow so, did change something on the css of js for the arrow not to show? Thanks.

**Comment by dantahoua** [comment]
It is removed in the _navigation.scss file. You can edit this file to your taste.
`.dropdown.menu:first-child >
    li.is-dropdown-submenu-parent >
    a::after {
        display: none;
    }`

**Comment by labanino** [comment]
What's up with :first-child? Anyways, thank you very much @dantahoua !
