### ISSUE TITLE
JS error in Safari

### ISSUE THREAD

**Issue by Cobbalobb** [olefredrik/FoundationPress#874]
Hi, 

I've got a site using  v2.6.1 and i'm getting the following error in JS:
`[Error] SyntaxError: Unexpected token ')'
	(anonymous function) (foundation.js:1079)`

Line 1079 is:
` $(window).on('resize.zf.mediaquery', () => {`

I use FoundationPress a lot and have never had this problem before, I have sites on v2.1.0 and v2.3.0 so i'm wondering if it's just a bug in this version?

If so what's the easiest way for me to update my theme version, while keeping all of my custom work?

The error can be seen on any page at https://bigstartassemblies.org

Thanks,
James

**Comment by olefredrik** [comment]
Hi @Cobbalobb , 

Did you make any changes to your gulpfile.js? 

The [foundation.util.mediaQuery.js](resize.zf.mediaquery) needs to be included after the [foundation.core.js](https://github.com/olefredrik/FoundationPress/blob/master/gulpfile.js#L37).

Do you get any errors when running `npm run build` ?

**Comment by Cobbalobb** [comment]
Hi @olefredrik 

Thanks for the reply.

No changes to the gulpfile.js, that bit in question looks like:
`    'assets/components/foundation-sites/js/foundation.core.js',
    'assets/components/foundation-sites/js/foundation.util.*.js',`

So that seems ok?

npm run build runs fine, the only thing of question is:
`(node:15147) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.`

Thanks,
James

**Comment by olefredrik** [comment]
I found this [similar issue](http://foundation.zurb.com/forum/posts/39633-onresizezfmediaquery----syntaxerror-unexpected-token-). 

What does your package.json file look like? If you're on a recent version of FP, Babel  Core / preset / plugins should be listed under devDependencies. Can you check your node_modules folder and look for the babel folders there? If they're not there, try `npm install`.

**Comment by Cobbalobb** [comment]
Babel is in the package.json and in my node_modules folder. 

I think I found the fix though, it was to do with babel. I've added the following to package.json and it seems to have done the trick:
`"babel": {
    "presets": ["es2015"],
    "compact": true
  }`

Thanks for your help and continued support of the framework, I use it a load!

**Comment by ScottyZA** [comment]
Had the same bug issue and @Cobbalobb solution solved it. Should we not add this to the repo?
