### ISSUE TITLE
node.js 

### ISSUE THREAD

**Issue by kareeem2910** [olefredrik/FoundationPress#882]
hi there 
i'm using windows 10 and i just started to learn about node.js.
when i trying to open a file contains js code from CMD  i got this error 
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\Dell\Desktop\node\index01'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

 **i have already followed some solutions like "npm install"
but i got this** 

npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Program Files\nodejs\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Program Files\nodejs\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Program Files\nodejs\npm-debug.log.3153271373
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\npm-debug.log.3153271373'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\npm-debug.log.3153271373']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\Program Files\nodejs\npm-debug.log.3153271373' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

**Comment by olefredrik** [comment]
Which version of Node.js did you install? Did you install GCC (like described [here](https://github.com/olefredrik/FoundationPress#requirements))? 

And did you follow this quickstart ?

```
$ cd my-wordpress-folder/wp-content/themes/
$ git clone https://github.com/olefredrik/FoundationPress.git
$ cd FoundationPress
$ npm install
```

**Comment by olefredrik** [comment]
Because of lack of response, I assume you fixed it. Feel free to reopen if you are still struggling.
