### ISSUE TITLE
Drop Down Menu Vertical Class can't be removed

### ISSUE THREAD

**Issue by steamfunk1** [olefredrik/FoundationPress#888]
I am trying to remove the vertical menu class from the drop down menu from the menu-walkers.php but even when i remove it, the class is still applied. why is that?

**Comment by derweili** [comment]
Which menu do you mean.
Do you want to remove the vertical class from the mobile nav? 
If so, you have to go to the [ FoundationPress/library/navigation.php ](https://github.com/olefredrik/FoundationPress/blob/master/library/navigation.php) and remove it on line 48

**Comment by steamfunk1** [comment]
hey @derweili I would like to remove the vertical class from the desktop top-bar-right nav menu submenu.

**Comment by derweili** [comment]
This is because they are added by [Responsive Navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html) Javascript.
You can remove the "data-dropdown-menu" attribute from the "items_wrap" value inside the "foundationpress_top_bar_r" function.

But this will break you layout.

**Comment by steamfunk1** [comment]
Hey @derweili thanks i appreciate it, I just removed the vertical class in the library/menu-walkers.php  `$output .= "\n$indent<ul class=\"dropdown menu vertical \" data-toggle>\n";` then i added `data-vertical-class="NewClass"` to the navigation.php `'items_wrap'     => '<ul id="%1$s" class="%2$s desktop-menu" data-dropdown-menu data-vertical-class="horizontal">%3$s</ul>',` Incase anyone else was wondering.
