### ISSUE TITLE
"Unexpected character '`'" running npm run production or package

### ISSUE THREAD

**Issue by roby94** [olefredrik/FoundationPress#898]
Hi,

Running npm run production or npm run package, i get the following error: 

gulp-notify: [Uglify JS Error] /Applications/MAMP/htdocs/SiteName/wp-content/themes/MyTheme/assets/javascript/custom/foundation.js: Unexpected character '`'.

Is almost a clean installation, i've worked only on php and scss files, nothing in javascript.
The strange thing is that if i run npm run watch works.

How can i fix it? Tell me if you need other datails.
Thank you!

**Comment by roby94** [comment]
Fixed id crating .babelrc file with:
```javascript
{
  "presets": ["es2015"]
}
```

**Comment by brandudno** [comment]
Hello, 

I am having the same issue, where can I find the .babelrc file that needs to updated?

**Comment by roby94** [comment]
Hi @brandudno, you need to create it, if not exists, in the root of your theme.

**Comment by brandudno** [comment]
I managed to sort by doing a clean install and moving my template files. Thanks for replying, anyway!
