### ISSUE TITLE
npm run watch fails

### ISSUE THREAD

**Issue by brianr001** [olefredrik/FoundationPress#899]
I have installed the theme and was able to do "npm install" and "npm run build" seem to work without problem (although there were some warnings in the npm install sequence).

"npm run watch" fails with the following log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info prewatch foundationpress@2.7.1
6 info watch foundationpress@2.7.1
7 verbose unsafe-perm in lifecycle true
8 info foundationpress@2.7.1 Failed to exec watch script
9 verbose stack Error: foundationpress@2.7.1 watch: `gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid foundationpress@2.7.1
11 verbose cwd /home/brian/Dev/x2017/public/wp-content/themes/x2017
12 error Linux 4.4.0-38-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error foundationpress@2.7.1 watch: `gulp`
17 error Exit status 1
18 error Failed at the foundationpress@2.7.1 watch script 'gulp'.
18 error This is most likely a problem with the foundationpress package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs foundationpress
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls foundationpress
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

* OS & version: Ubuntu 14 running in vagrant.
* Node version (node -v) [Node v4+ is required] : 4.6.0
* Foundation version (bower list) : 6.2.0

**Comment by uptownstudios** [comment]
This may be an issue with Browser Sync. I ran into this as well and checked around and found this issue on another Github page: https://github.com/BrowserSync/browser-sync/issues/224

That page led me to this Stackoverflow answer that worked beautifully for me: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

No more errors when running npm run watch.

**Comment by brianr001** [comment]
Outstanding. That did the trick, thanks for pointing that out.
