### ISSUE TITLE
jQuery error from 'source' folder

### ISSUE THREAD

**Issue by ymcheung** [olefredrik/FoundationPress#910]
**How can this bug be reproduced?**
1. Activate certain plugins.
2. Open Console in Chrome.
3. Some errors by js file located in the 'source' folder that only could be seen in Chrome's Dev Tool.

Please refer to the screen:
![error from source folder](https://dl.dropboxusercontent.com/u/45932/2016-10-25%2011.01.40.jpg)

The console error came from "stickyfooter.js" located in /source folder. 
However, the folder doesn't actually exist.
I corrected that error from stickyfooter.js in "assets/javascript/custom" folder, but "/source/stickyfooter.js" remained the same.

Also, as shown in the error message, "$" is an error.
In some cases, there is another error message:
foundation.core.js:189TypeError: Cannot read property 'getBoundingClientRect' of undefined

From a plugin's author, he said that it's because **there is no jQuery.noConflict(); at theme side**.

**What did you expect to happen?**
No more error messages from "/source" folder and use jQuery.noConflict();

**Please List the Following:**
- OS & version: OSX 10.12 / Windows 10 / Chrome
- Node version (node -v) [Node v4+ is required] : 4.5.0
- Foundation version (bower list) : 6.2.2

Thank you!

**Comment by EricRihlmann** [comment]
What are the certain plugins that you have activated? I'm not seeing this error on a clean install with no changes to the theme.

**Comment by ymcheung** [comment]
I deactivated Foundation's Reveal and replaced it with other modal script, and the errors are gone.
So I headed to report to Zurb.

I thought it was caused by source maps and didn't know how to remove them.

Thank you!
