### ISSUE TITLE
.active class applied to .main-menu li when using custom relative URLs in Menus

### ISSUE THREAD

**Issue by dylanmcleod** [olefredrik/FoundationPress#914]
I am building a one page site, however there a couple of separate pages (eg Posts page, Archives, 404 etc) that I need to link back to the Home page, not an anchor on that particular page. When using a relative URL with the anchor link, the .main-menu li has an .active class applied to it.

**How can this bug be reproduced?**
1. Step one
   Create a custom relative link in Menus eg.  /#style-anchor
2. Step two
   Save Menu

**What did you expect to happen?**
As expected the link behaves as normal, scrolling to it's respective anchor tag on the homepage, and when on a separate page, links back to the anchor on the homepage

**What happened instead?**
However, when using a relative URL with the anchor link, the .main-menu li has an .active class applied to it.

**Please List the Following:**
- OS & version: Mac OS El Capitan 10.11.6
- Node version (node -v) [Node v4+ is required] : v5.1.1
- Foundation version (bower list) : 6.2

**Include Test Case** (if applicable):  
http://bossy2.dylanmcleod.net.au/

I've tried removing all custom JS and deactivating plugins.

![active-class-being-applied](https://cloud.githubusercontent.com/assets/8255466/19834424/58f888e2-9eb2-11e6-81b8-50cdf2ee60df.jpg)

**Comment by linuxbastard** [comment]
Might be related to #933

**Comment by olefredrik** [comment]
https://github.com/olefredrik/FoundationPress/pull/1032
