### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by kamov** [olefredrik/FoundationPress#915]
When I run "npm run build" I get below error:

from debug file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundationpress@2.7.1~prebuild: foundationpress@2.7.1
6 silly lifecycle foundationpress@2.7.1~prebuild: no script for prebuild, continuing
7 info lifecycle foundationpress@2.7.1~build: foundationpress@2.7.1
8 verbose lifecycle foundationpress@2.7.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle foundationpress@2.7.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Applications/MAMP/htdocs/iwv/wp-content/themes/FoundationPress/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kamov/phalcontools
10 verbose lifecycle foundationpress@2.7.1~build: CWD: /Applications/MAMP/htdocs/iwv/wp-content/themes/FoundationPress
11 silly lifecycle foundationpress@2.7.1~build: Args: [ '-c', 'gulp build' ]
12 silly lifecycle foundationpress@2.7.1~build: Returned: code: 1  signal: null
13 info lifecycle foundationpress@2.7.1~build: Failed to exec build script
14 verbose stack Error: foundationpress@2.7.1 build: `gulp build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid foundationpress@2.7.1
16 verbose cwd /Applications/MAMP/htdocs/iwv/wp-content/themes/FoundationPress
17 error Darwin 14.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error foundationpress@2.7.1 build: `gulp build`
22 error Exit status 1
23 error Failed at the foundationpress@2.7.1 build script 'gulp build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the foundationpress package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs foundationpress
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls foundationpress
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by colin-marshall** [comment]
@kamov do you get more specific errors when you run `gulp build`?

**Comment by snetts** [comment]
I am having a problem installing using npm install on a Windows machine. I am getting the error as shown in my npm-debug log attached.

What is the problem? And can I possibly build a new theme based on FoundationPress without going through the node installation process?

Am new to this so please take it easy on me.

Thanks.

[npm-debug.txt](https://github.com/olefredrik/FoundationPress/files/580077/npm-debug.txt)

**Comment by olefredrik** [comment]
@kamov : Can you please try deleting your node_modules folder, then run `npm install` and paste see if you get any errors on install? I'm running on the same version of node and npm as you (on a mac), and I get no errors at all on a fresh install.

**Comment by snetts** [comment]
Thanks it worked great @olefredrik
