### ISSUE TITLE
Is FoundationPress Updated?

### ISSUE THREAD

**Issue by jaimevelasquez** [olefredrik/FoundationPress#916]
Hi,
I just want to ask if this foundationpress ( https://github.com/olefredrik/FoundationPress ) is updated? like on Foundation 6.2? cause i want to enable the flexbox mode,

I already read this tutorial http://foundation.zurb.com/sites/docs/flexbox.html#enabling-flexbox-mode 

but it still not enable. I'm thinking maybe its not updated.

**Comment by Leland** [comment]
Yup: see [Bower file](https://github.com/olefredrik/FoundationPress/blob/master/bower.json#L9).

It's running the most recent version of Foundation.

**Comment by elicohenator** [comment]
@olefredrik should be marked as closed
