### ISSUE TITLE
FoundationPress generator

### ISSUE THREAD

**Issue by colinduwe** [olefredrik/FoundationPress#919]
I love FoundationPress. However, when I use it to create a fully customized theme for Acme Inc. I would like my finished product to avoid functions prefixed with 'foundationpress_' and strings translated with 'foundationpress'.

Would there be interest in a generator like the one for [Components](https://github.com/Automattic/components.underscores.me/blob/master/inc/components-generator.php) to generate a custom-named FoundationPress download with appropriate attribution and so forth. If there's interest I'm happy to take a stab at it.

**Comment by olefredrik** [comment]
Hi @colinduwe , 

Like the idea. If you have time, please go ahead. Looking forward to see it 👍

**Comment by colinduwe** [comment]
That Components generator is some snazzy code. Here's a rough cut just taking their components generator theme and modifying it to generate a custom FP theme [FoundationPress Generator](http://fpgenerator.colinduwe.com/)

It surely needs more thorough code review of the output to ensure I didn't goof anything. I'll also repackage it as a plugin rather than a theme so its easier to integrate into your existing site.

Code is [Here](https://github.com/colinduwe/components.underscores.me)

**Comment by colinduwe** [comment]
Here it is repackaged as a plugin [FoundationPress Generator](https://github.com/colinduwe/foundationpress-generator).

Here it is in use on [a site running FoundationPress](http://fpgenerator.colinduwe.com/).

It needs some people to download some custom themes and review the output. I've been through it a bunch and I think its pretty close.

**Comment by Eccola** [comment]
Hi @colinduwe , your generator works really nice!

After unzipping and uploading the theme to remote server, I only had to chmod the directory permissions to 755, otherwise everything is perfectly functional.

**Comment by olefredrik** [comment]
Nice @colinduwe 👍
