### ISSUE TITLE
Copy task: Motion UI and What Input

### ISSUE THREAD

**Issue by emaia** [olefredrik/FoundationPress#922]
Hi guys!

I have a question about the copy task in the gulpfile.js (v2.8.0). 
In the file we have this:

```
// Copy task
gulp.task('copy', function() {

  // Motion UI
  var motionUi = gulp.src('assets/components/motion-ui/**/*.*')
    .pipe($.flatten())
    .pipe(gulp.dest('assets/javascript/vendor/motion-ui'));

  // What Input
  var whatInput = gulp.src('assets/components/what-input/**/*.*')
      .pipe($.flatten())
      .pipe(gulp.dest('assets/javascript/vendor/what-input'));

```

With this all the Motion UI and What Input files are placed in the javascript/vendor folder (including scss, css, md, json...) but the js files of both components are already included in javascript/foundation.js by Uglify task.

Is there any purpose for this in the copy job?
Thanks

**Comment by populationtwo** [comment]
I was wondering the same thing.

I second that. I think that task is unnecessary since the theme doesn't enqueue the script from `assets/javascript/vendor`. I searched the packaged file and couldn't fine any instances of `assets/javascript/vendor` used in the theme.

**Comment by olefredrik** [comment]
Technical debt. Thanks to @emaia for pointing it out. And thanks to @populationtwo for the pull request.
