### ISSUE TITLE
Foundation.js 

### ISSUE THREAD

**Issue by 15emedoctor** [olefredrik/FoundationPress#923]
On the site http://dev.nephilimk.com/
No Foundation.js is not working The image are not showing up on the header for exemple. The stciky menu is not working.

**Comment by olefredrik** [comment]
Open the console in Chrome devtools and you'll find that there are errors in your custom javascript that prevents the page from rendering properly. Fix this, and you should be good to go. 

![nephilimk](https://cloud.githubusercontent.com/assets/1080017/21425271/6caae730-c848-11e6-8d1d-8c60ce6a2194.png)
