### ISSUE TITLE
"Active" class no longer being applied to Topbar link on active page

### ISSUE THREAD

**Issue by joshtipton28** [olefredrik/FoundationPress#933]
**How can this bug be reproduced?**

1. Step one: Create a new site using Foundationpress
2. Step two: Create a few pages and add them to a menu in the topbar
3. Step three: Inspect nav links to see if an "active" class is being applied

**What did you expect to happen?**
A class of "active" to be added to the nav link corresponding to the current page.

**What happened instead?**
The class is not there. The CSS styling is still in navigation.scss though.

**Please List the Following:**
* OS & version: Windows 10
* Node version (node -v) [Node v4+ is required] : 6.9.2
* Foundation version (bower list) : 6.3.0

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by linuxbastard** [comment]
Here are the classes on a page link that come up when that page menu item is clicked:

`menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-<page-id> current_page_item`

We have a function in foundation.php, starting at line 80, that is supposed to add the `active` class, but it seems to not be functioning. Looking into this, but please have some more patience. It's Monday where I am and I've got an hour before duty calls. :cry:

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/1032
