### ISSUE TITLE
Error: 'libsass' bindings not found. Try reinstalling 'node-sass'?

### ISSUE THREAD

**Issue by FlakCannon** [olefredrik/FoundationPress#936]
After updating node (4.1.1) and npm (6.9.4) I am getting the same error. I have tried removing and installing node_modules with the above new package.json, clearing npm cache and still no joy. First of all I noticed you were missing the "scripts" from package.json but after adding still this error:

Error: 'libsass' bindings not found. Try reinstalling 'node-sass'?

I have tried reinstalling node-sass and rebuilding to no avail. Any ideas?

Error says to tell you this fails on my system: grunt build

I am on windows and using FoundationPress 5.5.1

Attached is the npm-debug.log
[npm-debug.txt](https://github.com/olefredrik/FoundationPress/files/721258/npm-debug.txt)

**Comment by FlakCannon** [comment]
Hello again, can anyone point me in a direction?

**Comment by olefredrik** [comment]
Try ``npm rebuild node-sass`` . This should do the trick after updating node and npm.
