### ISSUE TITLE
How do I support the built in WP Gallery in Foundationpress

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#937]
**How can this bug be reproduced?**

1. Create Gallery in Wordpress Media
2. Gallery displays in columns in the content editor
3. Gallery displays as a list of images in the published page

**Please List the Following:**
* OS & version: Mac 10.12.1
* Node version (node -v) [Node v4+ is required] :  6.2
* Foundation version (bower list) : 6.3

I can create image galleries using ACF gallery plugin, but if I try to use the built in WP gallery so I can include a gallery easily in the content editor I'm not sure how to add support for this in foundationpress

**Comment by walkerdigital** [comment]
+1

**Comment by walkerdigital** [comment]
I added a partial called _gallery.css in /assets/scss/components with:

```
.gallery
 {
  border: 1px solid #FF9900;
  
  @include breakpoint(small) {
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  @include breakpoint(medium) {
    flex-direction: row;
  }

  .gallery-item {

    @include breakpoint(small) {
      width: 100%;
      img { width: 100%; }
    }

    @include breakpoint(medium) {
      width: 32%;
    }

    div {
      padding: 1rem;
    }

  }
}
```

Then I included the import in foundation.scss

`@import "components/gallery";`

This seemed to do the job for me.  This is a copy of the cards example scss.

**Comment by nitrokevin** [comment]
Thanks I'll give this a go

**Comment by nitrokevin** [comment]
That worked thank you.

I don't suppose there is any way to get the inbuilt gallery to use interchange instead of selecting the image size
