### ISSUE TITLE
Cannot get Foundation equalizer working

### ISSUE THREAD

**Issue by zitrusblau** [olefredrik/FoundationPress#94]
Hi all,

does anyone have a solution for this issue?
I cannot get the equalizer working by using Foundation 5.3.3 with FoundationPress Theme for WordPress.

``` HTML
<div class="row" data-equalizer">
<div class="small-6 large-4 columns">
<div class="panel radius" data-equalizer-watchstyle="height: inherit;">
...
</div>
</div>
<div class="small-6 large-4 columns">
<div class="panel radius" data-equalizer-watch style="height: inherit;">
...
</div>
</div>
<div class="small-6 large-4 columns">
<div class="panel radius" data-equalizer-watch style="height: inherit;">
...
</div>
</div>
<div class="small-6 large-4 columns">
<div class="panel radius" data-equalizer-watch style="height: inherit;">
...
</div>
</div>
<div class="small-6 large-4 columns">
<div class="panel radius" data-equalizer-watch style="height: inherit;">
...
</div>
</div>
<div class="small-6 large-4 columns">
<div class="panel radius" data-equalizer-watch style="height: inherit;">
...
</div>
</div>
</div>
```

So, the scripts are working but all of the equal panel get an inherit height. What is the problem? I cannot find out, cause there is no error message to check this.

Actually I cannot send a link, cause I've only an instance on my localhost yet.

**Comment by musicgabser** [comment]
Hm, that all doesn't work for me, are they new developments? I would need it to equalize post previews....

**Comment by zitrusblau** [comment]
you could use an alternative height matching script instead:
http://brm.io/jquery-match-height/

**Comment by mariapaz** [comment]
The problem is that the columns are stacked as opposed of being in independent 12 columns rows.

You need to add this and it works!
$(document).foundation({
  equalizer : {
    // Specify if Equalizer should make elements equal height once they become stacked.
    equalize_on_stack: true
  }
});

http://stackoverflow.com/a/27724183

**Comment by adamski-g** [comment]
@mariapaz, thanks! was scratching my head with that one. Works perfectly.
