### ISSUE TITLE
Sass Error

### ISSUE THREAD

**Issue by bisonbrah** [olefredrik/FoundationPress#942]
**How can this bug be reproduced?**

1. Step one -> git clone https://github.com/olefredrik/FoundationPress.git
2. Step two -> Run 'sudo npm install'
3. Step three -> Run 'npm run build OR npm run watch' = gulp-notify: [Sass Error] assets/scss/global/_settings.scss
Error: File to import not found or unreadable: ../../components/foundation-sites/scss/util/util
Parent style sheet: =/domain/app/public/wp-content/themes/FoundationPress/assets/scss/global/_settings.scss
        on line 44 of assets/scss/global/_settings.scss

**What did you expect to happen?**

Gulp would work and generate the style.css for theme to work

**What happened instead?**

Error listed above; no SCSS is being converted to CSS for theme to render..

**Please List the Following:**
* OS & version: Mac OSX Sierra v10.12.13
* Node version (node -v) [Node v4+ is required] : Node v 6.9.2
* Foundation version (bower list) :

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.
* [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
* [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by olefredrik** [comment]
Did you get any errors on npm install?

**Comment by bisonbrah** [comment]
No errors; just 'npm WARN deprecated':

`npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

npm WARN lifecycle foundationpress@2.9.0~postinstall: cannot run in wd %s %s (wd=%s) foundationpress@2.9.0 bower install && gulp build /Users/bisonbrah/Local Sites/fsorthoperio-com/app/public/wp-content/themes/FoundationPress
foundationpress@2.9.0 /Users/bisonbrah/Local Sites/fsorthoperio-com/app/public/wp-content/themes/FoundationPress`

**Comment by anthonyabraira** [comment]
Same thing happening here +1

**Comment by drewpyd85** [comment]
same issue here following

**Comment by dantahoua** [comment]
Did you try with other node version, just to see if it's the node version the problem? Also I see you do "sudo" npm install... I never use sudo with npm... Just installed two time this week without problem...
Usually problems comes from node version, since I use nvm, I always found a way out a problem! ;)

**Comment by drewpyd85** [comment]
yes, I'm sorry my mistake...

I'm using a brand new computer that came with NODE.js pre-installed with version 7.2 (from IT dept.)

After downgrading to 6.9.5 it works as it did before. THANK YOU!

**Comment by tpkemme** [comment]
_`npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0.`_

This is the issue.  If you're using node v.7.0 or up, every dependency in this project needs to use graceful-fs v4.0 or up.  From what I can tell there are 4 or 5 node modules that are still relying on graceful-fs v3.0 and below

**Comment by lcarlhart** [comment]
Hello, I am having trouble figuring out how to turn on flexbox?? I made this change:
`$global-flexbox: true;`
on the _settings.scss. . . but I am a little unaware of how to use the mixins ect.

Thank you for your help!

**Comment by dantahoua** [comment]
You need to un-comment "@include foundation-flex-classes;" AND "@include foundation-flex-grid;"
AND comment "@include foundation-grid;" and "@include foundation-float-classes;"
in assets/scss/foundation.scss

**Comment by lcarlhart** [comment]
Thank you for sending! Very helpful.
