### ISSUE TITLE
How many of you are using Flexbox flex grid?

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#943]
Not an issue, I'm just really curious if there is some of you who use the Flex grid in Foundation?

I made my first project with Flex grid enable last week... It was... Interesting.
I probably need to adapt (after so many years of working with Float). I found some minor bugs (like the img ratio if your img is a direct descendant of a float container) and some strange behavior (probably because of my "novice" level in Flex).

**Comment by colinduwe** [comment]
I'm a recent convert. So much less work for vertical centering, equal height children, justify with space between, etc.

**Comment by nitrokevin** [comment]
I haven't used it yet because I'm worried about browser support, interested to know if this is causing issues for anyone or not?

**Comment by yourdesigncoza** [comment]
Hi,

THX for everyone's efforts, Yes I use flexbox, but it does "break" if
implemented in SASS, so I use a standalone css file just when needed :::


Thank You
John

- - - - - - - - -

Web: http://yourdesign.co.za
Twitter: yourdesigncoza
Mobile:  +27 79 177 1970

**Comment by dantahoua** [comment]
Other issue I found: the "collapse" class is not working with flex-grid...

**Comment by Leland** [comment]
Just started using it. SO nice. A lot of the stupid quirks of CSS positioning are made easy through it.

**Comment by colinduwe** [comment]
Has anyone else noticed issues with Flexbox grid modifier classes not inheriting the expected style. For example if you add 'align-center' to a row it doesn't inherit 'align-content: center' I haven't run this down to submit as its own issue. It may be my theme is behind the FP head and this has already been addressed. I may also have not correctly switched from standard grid to flex in sass.

**Comment by cesasol** [comment]
I use flexbox for almost every proyect I work with
