### ISSUE TITLE
dropdown menu not working

### ISSUE THREAD

**Issue by vbislife04mb** [olefredrik/FoundationPress#948]
Just did a brand new install of foundation press and the dropdown menus are not working. 
http://omahahls.com/dataworkstemp/

**Comment by olefredrik** [comment]
You have a 404 error on foundation.js. This file needs to load correctly for stuff to work as expected.

<img width="879" alt="screen shot 2017-03-06 at 5 12 42 pm" src="https://cloud.githubusercontent.com/assets/1080017/23618279/260864c4-0290-11e7-869a-74ee3fac4783.png">

**Comment by yourdesigncoza** [comment]
Hi,

You're not loading .js

**Comment by vbislife04mb** [comment]
I knew it was something simple! thanks Michael!! Can you tell me where that should be called in?

**Comment by conorbarclay** [comment]
It looks like it is being enqueued. Make sure the file actually exists on your server, though.

**Comment by vbislife04mb** [comment]
thanks all

**Comment by youriwims** [comment]
Hi, I know this is a super old issue, but how did you put the dropdown menu into your template? I'm a complete newb to FoundationPress, but know Foundation and am having some issues. I've registered my nav and created it in wp-admin, but I'm still not getting the dropdown--mine still looks like the default top bar. Let me know if you can help, I'd really appreciate it.


> Just did a brand new install of foundation press and the dropdown menus are not working.
> http://omahahls.com/dataworkstemp/
