### ISSUE TITLE
img_unautop is greedy

### ISSUE THREAD

**Issue by swinggraphics** [olefredrik/FoundationPress#95]
Had to comment out the `img_unautop` function in cleanup.php because it adds figure tags inappropriately, replacing a `<p>` tag with `<figure>` that is nowhere near an img, then closing it somewhere far down the page. My brain is too foggy to troubleshoot the regex right now, but I'll post again if I figure it out.

**Comment by stirlingsohn** [comment]
we also had to take it out because it removes all css classes from images inside the_content().

**Comment by DavidBruchmann** [comment]
The best is to keep the wrap in that function out, then the function is really only doing what the name says and it keeps simple.

function img_unautop($pee) {
    $pee = preg_replace('/<p>\\s*?(<a .*?><img.*?><\\/a>|<img.*?>)?\\s*<\\/p>/s', '$1', $pee);
    return $pee;
}

Additionally I'd remove the regex-part perhaps for removing the p around linked images as links are inline-elements that should be wrapped usually.

function img_unautop($pee) {
    $pee = preg_replace('/<p>\\s*?(<img.*?>)?\\s*<\\/p>/s', '$1', $pee);
    return $pee;
}

**Comment by olefredrik** [comment]
The img_unautop function was removed in https://github.com/olefredrik/FoundationPress/commit/bcd2505f6b8e3f1b17c9e3cdffc7f65eb17ab48f#diff-1565ad18be73929a637f7cc08011590cL198
