### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by spinfly** [olefredrik/FoundationPress#952]
Trying to use the Social Media WordPress plugin...

https://wordpress.org/plugins/ultimate-social-media-plus/

...with the latest version of FoundationPress, but when the plugin is activated, I get...

`Uncaught TypeError: $ is not a function at foundation.js:10140
`

…in the console from my compiled foundation.js file. This is an issue with the Joyride demo code, and it seems like it's the first time a $ is used, so it might be some sort of namespace issue.

I asked the plugin developer...

https://wordpress.org/support/topic/uncaught-typeerror-is-not-a-function-3/

...but he says to notify the theme developer.

Using Mac OS X 10.12.3 with Node v6.10.0. Here's my bower list:

```
bower check-new     Checking for new versions of the project dependencies...
foundationpress /wp-content/themes/FoundationPress
├── fontawesome#4.5.0 (latest is 4.7.0)
├─┬ foundation-sites#6.3.1
│ ├── jquery#2.2.4 (3.1.1 available)
│ └── what-input#4.0.6 (latest is 4.1.1)
└─┬ motion-ui#1.2.2
  └── jquery#2.2.4 (latest is 3.1.1)
```

**Comment by EricRihlmann** [comment]
@spinfly can you close this out?

**Comment by spinfly** [comment]
Much obliged!
