### ISSUE TITLE
Update Travis CI Build Checks

### ISSUE THREAD

**Issue by EricRihlmann** [olefredrik/FoundationPress#959]
Now with WP recommending PHP 7 or greater as the minimum requirements, is it really necessary to run a build job all the way back to PHP 5.2 and WP 4.1?

**My Recommendation**
- Add PHP 7.1 _(if initial build fails, switch to allowed failure until resolved)_
- Add PHP 7.0
- Change PHP 5.6 from allowing to fail to required to pass
- Remove anything older than PHP 5.6 _(those versions are not even supported by PHP anymore)_

Any thoughts?

**Comment by olefredrik** [comment]
Totally agree. Fixed https://github.com/olefredrik/FoundationPress/pull/960

**Comment by EricRihlmann** [comment]
Cool. Although, it looks like PHP 5.6 was removed and PHP 7.1 was added twice — once as being required and again as allowed to fail. Since PHP 7.1 is passing, we should do away with the allowed to fail test. How about getting PHP 5.6 back in there? _(still supported by PHP and probably the most popular version)_  Also, instead of checking against WP versions 4.1, 4.2, how about just checking against the current version (already doing that) and the previous two versions — 4.5 and 4.6?
