### ISSUE TITLE
Setting Top Bar colors ( topbar-link-bg-active ) is not working

### ISSUE THREAD

**Issue by ghost** [olefredrik/FoundationPress#96]
The variable **topbar-link-bg-active** that I've changed in the file __settings.scss_ has the right value, the problem is that the style is being overwritten.

Looks like there are two selectors, one with _media query_ and other one _without media query_. The ones _without media query_ overwrites the right one.

That's what I see in Firebug (grey color overwrites pink color):
![topbar-link-bg-active](https://cloud.githubusercontent.com/assets/2210134/4000067/80f8a5a8-2956-11e4-873d-9f14fdab2a30.jpg)

Someone could try this, just modify the variable **topbar-link-bg-active**?

Thanks.

**Comment by swthate** [comment]
I apologize for the post necromancy, seeing as this is nearly a year old. However, I was having this exact problem, and fought it all yesterday afternoon. With a fresh mind this morning, I discovered my own $topbar-link-bg-active variable was being overwriten by scss/site/_topbar.scss.

In that file, the same css snippet from _structure.scss was found.

This probably isn't much of an issue any more, but I just wanted to mention this in case there is anyone else who may be as lost/frustrated as I was yesterday!

Thanks for all the hard work, Ole. Skol!
