### ISSUE TITLE
_settings.scss and _foundation.scss importing non-existent files

### ISSUE THREAD

**Issue by ronanfernandes** [olefredrik/FoundationPress#966]
I´ve just installed FoundationPress via npm.
Then, tried to run the gulp tasks 'npm run build', unfortunatelly, had no success.
Sass just can't compile.
In '/assets/scss/foundation.scss' there are **too many** broken links. For instance, it calls:
*@import '../components/foundation-sites/scss/foundation';* (this file isn´t in the package!)

Also _settings.scss have too many broken links. In the first non commented line we have one:
@import '../../components/foundation-sites/scss/util/util';

There are also use of non-declared variables and mixins: $primary-color, @fontawesome, and so on.

All those imports of non-existent files prevent Gulp/Sass from achieving the goal of combine the files.

Am I missing anything?
I tried to copy Foundation files (the framework, not FoundationPress) into 2 different folders inside FoundationPress, but there are still broken imports inside _settings.scss.
What do I need to do?

**Comment by wishe** [comment]
Sounds like you may have forgotten to run `npm install` to install all the dependencies. There are some instructions in the readme of this repo on how to get started.

**Comment by iLama** [comment]
@wishe I can confirm that `npm install` doesn't fix this problem.

**Comment by ronanfernandes** [comment]
What I did: 
Mannually copied the Foundation framework into a subfolder of FoundationPress and changed files to include the files in the new paths I created.
Works, but ugly solution.
