### ISSUE TITLE
Dropdown menu issue

### ISSUE THREAD

**Issue by jdm1971** [olefredrik/FoundationPress#969]
Hi - I'm trying to use a dropdown menu on a site I'm working on http://iplumb.co/

When you go to the homepage and hover over Bathrooms no dropdown occurs - BUT go to any other page & then hover over Bathrooms and the dropdown works as it should.

Any idea why this isn't working correctly on the homepage please?

Would really appreciate some help. 

Thank you. John.

**Comment by wishe** [comment]
Seems to be working fine from here. I am on latest version of Chrome. Did you just fix it or is it maybe a problem on your end with some browser caching ?

**Comment by jdm1971** [comment]
Thanks for taking a look. I've tried it on latest chrome, Firefox and iPad too. Problem still exists and cache cleared. Are you definitely doing this - go to iplumb.co - from that home page click bathrooms - it goes to the bathrooms page BUT if when you arrive on bathrooms or any other page and then click the bathrooms link suddenly the drop down works. Something quirky is happening, here at least.

**Comment by jdm1971** [comment]
Hi - Just to say I've reverted to not having a drop-down.
