### ISSUE TITLE
Duplicate search bar when widget search produces no results

### ISSUE THREAD

**Issue by LGT4** [olefredrik/FoundationPress#970]
See attached. The no results template has a search bar. It duplicates the right side bar search widget. Is there a need for the 2nd search bar in the no results template?

[Search Results for “something real” – FoundationPress.pdf](https://github.com/olefredrik/FoundationPress/files/894633/Search.Results.for.something.real.FoundationPress.pdf)

**Comment by linuxbastard** [comment]
You can modify it of course. If I'm not mistaken those are default sidebars widgets.

**Comment by olefredrik** [comment]
What he said ⬆️   Closing this as I don't consider it to be an issue.
