### ISSUE TITLE
responsive toggle menu stops working on 6.3.1

### ISSUE THREAD

**Issue by hardikdangar** [olefredrik/FoundationPress#973]
**How can this bug be reproduced?**

1. Download foundation WordPress theme and change version in bower.json of "foundation-sites": "6.3.0",
2. npm install
3. responsive toggle will work on mobiles.
4. in bower.json change "foundation-sites": "~6.3.0" which will update it to 6.3.1. responsive toggle will not work when in mobiles.

**Please List the Following:**
* OS & version: Linux ubuntu 16.04 chrome latest
* Node version (node -v) [Node v4+ is required] : v6.9.5
* Foundation version (bower list) : 6.3.1

**Comment by olefredrik** [comment]
I try to make the most of the Foundation core features as possible work in the version that the project is based on. As you have updated Foundation yourself, there is a lot of things that may have gone wrong along the way. The responsive toggle should be working fine in the current version.
