### ISSUE TITLE
foundation.css Loading in Visual Editor

### ISSUE THREAD

**Issue by moseke** [olefredrik/FoundationPress#976]
WP - 4.7.3
Node - 6.2.0
FoundationPress - 2.9.0

The visual editor is loading foundation.css. I've tracked it to this function (probably):
![screen shot 2017-04-12 at 8 11 04 am](https://cloud.githubusercontent.com/assets/5262718/24965328/931038c8-1f58-11e7-824c-67084a48bec0.png)

Any ideas on how to get this to stop?

**Comment by Eccola** [comment]
@moseke,
see: https://github.com/olefredrik/FoundationPress/blob/master/library/theme-support.php
line 41

**Comment by moseke** [comment]
Thank you @Eccola. I am relieved that this was an easy solution!
