### ISSUE TITLE
functions.php

### ISSUE THREAD

**Issue by dtlevin** [olefredrik/FoundationPress#981]
Not sure if this is a bug or not, but here is what happens.

1. Make a library/custom-functions.php file
2. Put an HTML comment in there 
3. Open the media library on your wordpress site and it won't load any images.

Mac OS 10.10.1
latest version of FoundationPress using Desktop Server
latest version of WordPress 4.7.4

**Comment by linuxbastard** [comment]
I'll try recreating your issue in a few hours when I get back up again, but do you have any log files or can you enable debug on WP to see if you get any error messages?

**Comment by dtlevin** [comment]
I'll try to recreate it and get you the logs this weekend.

**Comment by olefredrik** [comment]
@dtlevin : Did you manage to recreate this?

**Comment by olefredrik** [comment]
I close this because of lack of response. Please reopen if you're able to recreate and this is still an issue.
