### ISSUE TITLE
WooCommerce compatibility

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#982]
I tried posting to Gitter, but it looks fairly unused.

Has anyone used FoundationPress with WooCommerce?
What steps would you take to have it compatible?

**Comment by msacchetti** [comment]
#718 try this

**Comment by newtlabs** [comment]
The new lightbox/zoom feature in WooCommerce 3.0 is broken with FoundationPress.

**Comment by olefredrik** [comment]
Any luck, @jimlongo56 ?

**Comment by linuxbastard** [comment]
Current version of FoundationPress should work with woocommerce, including new WooCoomerce 3+ theme support for zooming and lightboxes. I have a fresh install of FoundationPress running with WooCommerece 3.1.1 and I just created a `woocomerce` folder inside my FP theme folder and edited the WC templates there.

**Comment by jimlongo56** [comment]
Although I haven't got around to working on this site yet, everything I've read says you should declare WooCommerce support to remove admin dashboard warnings

```
add_action( 'after_setup_theme', function() {
	add_theme_support( 'woocommerce' );
} );
```

Then create a woocommerce.php which is a modification of page.php - there are 2 methods mentioned in the WooCommerce docs.

More details here:
https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/?_ga=2.269299513.974104830.1502233497-894541166.1488137586

That seems like the bare minimum.  Then of course copy the template files from the plug-in to your theme and add foundation markup to them.

Let me know if you'd be interested in having this supported in a pull request.

**Comment by olefredrik** [comment]
@jimlongo56 

I'm not very familiar with WooCommerce as I haven't used in any projects. But I have realized that it is the biggest and best solution for e-commerce on the WordPress platform. 

If you want to improve the WooCommerce support in FoundationPress, that's awesome. I will be happy to review your pull request. :)

**Comment by newtlabs** [comment]
@olefredrik @jimlongo56

As @linuxbastard says I've also used FoundationPress with a few WooCommerce setups and it is fine. So the above should already be there and therefore there is no need for your PR...

Cheers!
