### ISSUE TITLE
anyone is using scrollmagic with FoundationPress

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#983]
**How can this bug be reproduced?**

Sorry this isn't a bug, just wondered if anyone has successfully managed to get scrollmagic working with foundationpress?

If so, any tips on installing and getting it going

I've tried bower install scrollmagic --save-dev
then adding the js to the gulp file but it isn't working for me

**Comment by Eccola** [comment]
@nitrokevin , 
did you run `npm run build` after adding to gulpfile?

**Comment by nitrokevin** [comment]
yes, and it looks like scroll magic is getting built, I'm probably doing the scroll magic coding wrong!
